### PR TITLE
ENH: Update remote module maintenance script

### LINKED ISSUE #682: `UpdateRemoteModules.sh` does not handle correctly commit hashes with trailing characters
### Description
[UpdateRemoteModules.sh](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/UpdateRemoteModules.sh) does not handle correctly commit hashes with trailing characters.

### Steps to Reproduce

Execute [UpdateRemoteModules.sh](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/UpdateRemoteModules.sh).

### Expected behavior

Pretending the `+`/`-` signs are shown by `git diff`:
```
- set(GIT_TAG 70a5a174a0ca0bebe00d6b1f817caacceef8cf35)
+ set(GIT_TAG 07f0e1622ca3eeed8b9c5b9665b066b785af86e8)
```

### Actual behavior

Current result on applying the script to [WikiExamples.remote.cmake](Modules/Remote/WikiExamples.remote.cmake) pretending the `+`/`-` signs are shown by `git diff`
```
- set(GIT_TAG 70a5a174a0ca0bebe00d6b1f817caacceef8cf35)
+ set(GIT_TAG 07f0e1622ca3eeed8b9c5b9665b066b785af86e8
```

### Reproducibility

100%

### Versions

`master`. Added in 8fdb4542f2203fddee463a02cbc14587ade2375c.

### Environment

Any.

### Additional Information

None.

### PR DESCRIPTION
**Pull request by maekclena**
Fixes #682 and #685.

This updated version of `UpdateRemoteModules.sh` uses more constraining parsing rules to avoid issues and removes version specific syntax to be more portable.

It also adds the option `-ongreen` to update only if the latest build was successful.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
May be the PR subject could be reformatted to *ENH: Update remote module maintenance script* so that it becomes clearer.

**Comment by dzenanz** [comment]
@maekclena Can you run the script and make a new PR with updated remotes?

**Comment by jhlegarreta** [comment]
I've just tested the PR and it works overall:
- **Nice output of the taken actions**. Could be improved by **grouping the updated vs. non-updated ones vs. those not update because they are failing** (thus avoiding the *(...) is already up to date* and *(...) was updated to latest commit*).  But this is not a show stopper. 
- We still have the tag issue with the remotes (i.e. `RTK` would be updated to the master commit), but I did not address that either and is closely related to the way remotes can be handled concerning versions (i.e. not an easy thing to be systematical), so for the time being, this is correct to me.
- Checked that the PR **does fix** #682. **Great**.
- **The ancient version was introducing some undesired CR/LFs** (my bad) to all files that were **later filtered by git** (ITK hooks may be) so as to avoid unnecessary commits. **The new version does not introduce them**. Which is **simply great**. Thanks @maekclena.

**Unfortunately I checked that**:
- The script updated the [ITKWikiExamples](https://github.com/InsightSoftwareConsortium/ITKWikiExamples) remote, which shows a **failing Azure Pipeline badge**, and I trust it is failing. The script updated the remote anyway, though, so the CI check in the script seems not to be working correctly.

@maekclena whenever you find the time, could you have a look?

Note that all remote CIs will eventually be migrated to Azure Pipelines, if this is of any interest for having the `status` answer.

**Comment by jhlegarreta** [comment]
I've re-tested the script:
- The **output message now shows only the updated modules**. **Nice**.
- Looks like the **status is now taken into account**. **Great**.

Thanks @maekclena  !

However, there is still at least **one more thing that I've detected**: for remotes with upstream URLs in comment (e.g. [SmoothingRecursiveYvvGaussianFilter.remote.cmake](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Remote/SmoothingRecursiveYvvGaussianFilter.remote.cmake)), it looks like **the script takes the URL that first matches the regex, even if it lives on a commented line**. Thus, in the above case, instead of updating the commit hash from the [expected repository](https://github.com/InsightSoftwareConsortium/ITKSmoothingRecursiveYvvGaussianFilter), it will do so from the [upstream repository](https://github.com/Inria-Asclepios/SmoothingRecursiveYvvGaussianFilter), and it will be printed as such in the output:
```
Modules updated:
Inria-Asclepios/SmoothingRecursiveYvvGaussianFilter
```

The commit to which the remote module `cmake` file has been updated correspond's to the upstream latest, which, in this case, is well behind ISC's latest. Even if ISC's was behind (which may happen if the upstream has a merge commit from ISC), we'd like to stick to the appropriate repository (which may not necessarily be the upstream).

So I'd dare to say that the fix boils down to discarding the regex results that lie on a comment line.

**Comment by dzenanz** [comment]
> So I'd dare to say that the fix boils down to discarding the regex results that lie on a comment line.

Equally valid fix is to remove the commented lines, or put them later so they don't throw of this script.

**Comment by jhlegarreta** [comment]
@maekclena  Thanks ! Checked and now it is working as expected !!

:rocket: :tada: :fireworks: 

This is an awesome improvement !

**Comment by jhlegarreta** [comment]
I will merge when Windows and CDash builds are completed successfully.

**Pull request merged**
