### PR TITLE
ENH: Add numbers to the three `itkPyBufferMemoryLeakTest` print messages

### PR DESCRIPTION
**Pull request by N-Dekker**
Add numbers (1, 2, 3) to the print messages in itkPyBufferMemoryLeakTest,
to ease analysis of the output from a test failure.

### CODE REVIEW

**Comment by N-Dekker** [comment]
@dzenanz Could the `itkPyBufferMemoryLeakTest` failures possibly be introduced by pull request #2554 "BUG: add support for long long pixel types in PyBuffer", merged by cd36c640a0a918d914c7fe102748c1ca00fa074a ?

**Review by dzenanz — APPROVED** [review]
Incremental build didn't work for me, I needed to manually rebuild something to avoid a clean build.

While it is possible that did it, I see no reason why it would do that. This same test used to be flaky on Mac before, if I remember correctly.

**Comment by N-Dekker** [comment]
> While it is possible that PR did it, I see no reason why it would do that.

I don't know either. Would it matter that these `types` from itkPyBuffer and itkImageDuplicator have become out of sync, with PR  #2554 ?

https://github.com/InsightSoftwareConsortium/ITK/blob/cd36c640a0a918d914c7fe102748c1ca00fa074a/Modules/Bridge/NumPy/wrapping/itkPyBuffer.wrap#L5


https://github.com/InsightSoftwareConsortium/ITK/blob/cd36c640a0a918d914c7fe102748c1ca00fa074a/Modules/Core/Common/wrapping/itkImageDuplicator.wrap#L11-L13

**Review by hjmjohnson — APPROVED** [review]

**Comment by dzenanz** [comment]
Even if it does not fix the pyBuffer memory leak, ImageDuplicator should be wrapped with LL types. -> Done in #2584.

**Pull request merged**
