### PR TITLE
Gpu finite difference image error

### PR DESCRIPTION
**Pull request by seanm**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
hmmm, I must have done something wrong here. All I'm wanting to merge is 5cd5f1f0765c1a9001ec17ffde2c9bb2827df0d5

**Comment by gdevenyi** [comment]
@seanm You need to do a rebase/squash, or that can be done on merge

**Comment by dzenanz** [comment]
I manually merged it after rebasing.

**Comment by seanm** [comment]
Thanks! Saves me from figuring out the git incantations. :)

**Pull request closed without merging**
