### PR TITLE
clang-format lint and apply GitHub Actions

### LINKED ISSUE #1201: CI hook and pre-commit hook for clang-format
### Description
work on a CI hook to check / apply clang-format with the version Hans has proposed along with a pre-commit hook to check / apply the style check.

As discussed in #1191

### PR DESCRIPTION
**Pull request by thewtex**
Add GitHub Actions to:

- Provide a status check that checks that the current pull request conforms to ITK's Coding Style with clang-format.
- Apply `clang-format` to a PR when the *action:ApplyClangFormat* label is added. This will run `clang-format` on all commits on the branch and force-push the branch, then remove the label. This label should be applied by someone with write access to the PR, i.e. the author or repository maintainers.

While the local Git hook catches most style changes, this provides an additional check and a convenient way to apply style updates on demand.

Moreover, these GitHub Actions can easily be applied to other repositories on GitHub.

Closes #1201

### CODE REVIEW

**Comment by hjmjohnson** [comment]
I hope this works!  Nice.

**Comment by thewtex** [comment]
It worked during tests on my fork :-)

**Comment by hjmjohnson** [comment]
@thewtex The failing test seems completely unrelated.

**Comment by thewtex** [comment]
> Not sure if all GitHub Actions that are being put in place should be minimally documented, may be in the `CONTRIBUTING.md` file.

@jhlegarreta good idea -- added!

**Comment by jhlegarreta** [comment]
Looks good Matt. Thanks !

**Pull request merged**
