### PR TITLE
Vxl update 20191208

### PR DESCRIPTION
**Pull request by hjmjohnson**
Supersedes and closes #1479.

### CODE REVIEW

**Comment by dzenanz** [comment]
Test failures are unrelated.

**Comment by dzenanz** [comment]
Wait, a merge commit is missing for this.

**Comment by hjmjohnson** [comment]
@dzenanz If this passes, could we merge it right away, or should we wait for other PR's to complete?

**Comment by dzenanz** [comment]
I am OK with merging right away. But that will be about 5 hours from now, so it will not make it into this night's nightly.

**Comment by hjmjohnson** [comment]
The windows failure is new.  I won't be able to look into why windows is failing for a long while. ;(.

**Comment by seanm** [comment]
CC @seanm @vfonov 

So @hjmjohnson so if this can't go in yet, can we at least merge the fix to https://github.com/vxl/vxl/pull/729 ?

**Comment by hjmjohnson** [comment]
Python failures are unrelated:

```
AttributeError: module 'ITKConnectedComponents' has no attribute 'swig'
itkTestDriver: Process exited with return value: 1
```

**Comment by hjmjohnson** [comment]
@seanm I finally found time to track down the failure of the windows build.  I had made the static array in the test too big for windows to handle.  Reducing the size of the test buffer fixed the problem.

**Comment by seanm** [comment]
Sweet, thanks!

**Pull request merged**
