### PR TITLE
STYLE: Replace "the the" with "the" in comments

### PR DESCRIPTION
**Pull request by N-Dekker**
The word "the" often appears accidentally duplicated, both in regular and doxygen formatted comments.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
Slightly off-topic 😸: The The is actually one of my favorite bands of the eighties... and they are going on tour again!!!

**Review by dave3d — APPROVED** [review]

**Comment by dave3d** [comment]
My wife, who was born in Taiwan, is always asking what's the point of articles and grammar?  She thinks it's a waste of time, being a Taiwanese/Chinese speaker.

**Comment by dzenanz** [comment]
Being a Slavic speaker, I frequently swallow articles too. Less so recently, with AI spell checkers which let me know when I forget them 😄

**Comment by N-Dekker** [comment]
@dave3d @dzenanz Based on your comments, I'm now considering a pull request to just remove all `"the"`'s from the source tree, not just `"the the"` and `"the the the"`. 😸

**Pull request merged**
