### PR TITLE
ENH: Use https instead of http when https works

### PR DESCRIPTION
**Pull request by Leengit**
`https` is more tamper-resistant and more private so we use it instead of `http` when it is available.

We detect which URLs work with `https` using
```shell
cd git/ITK
find . -type f | \
    fgrep -v sed-commands | fgrep -v .git/ | fgrep -v ThirdParty | \
    tr \\n \\0 | xargs -0 egrep -o 'http://[-._A-Za-z0-9]+' | cut -d : -f 2- | sort | uniq | \
    while read url
        do curl --connect-timeout 60 --output /dev/null --silent --head --fail "https${url#http}" && \
           echo "-e 's#${url}#https${url#http}#g' \\"
    done > sed-commands
```

We edit the ITK repository files by appending the output of the above command (except for the very last trailing backslash) to the command
```shell
cd git/ITK
find . -type f | \
    fgrep -v sed-commands | fgrep -v .git/ | fgrep -v ThirdParty | \
    tr \\n \\0 | xargs -0 sed -i -r \
```

### CODE REVIEW

**Comment by Leengit** [comment]
Files that would be changed in this pull request but are not changed because they are failing unrelated ITK pre-commit checks are:
```text
Modules/Core/Common/include/VNLSparseLUSolverTraits.h
Modules/Core/Common/test/ClientTestLibraryA.h
Modules/Core/Common/test/ClientTestLibraryB.h
Modules/Core/Common/test/ClientTestLibraryC.h
Modules/Filtering/ImageIntensity/test/itkLogicTestSupport.h
Utilities/KWStyle/ITKHeader.h
Wrapping/Generators/Python/PyUtils/itkPyCommand.cxx
```

**Comment by Leengit** [comment]
The second commit, just pushed, checks in the changes to the 7 files list above that were previously rejected on KWStyle grounds.  I got my `git commit` to work for them by temporarily setting `git config hooks.KWStyle false`.

If you know the proper way to permanently add these files to an exceptions list, please speak up.

**Comment by Leengit** [comment]
I just used a force push to make the commit messages more informative.  Additionally, more URLs were converted to using `https`.

**Review by dzenanz — APPROVED** [review]
Looks good on a glance.

**Comment by Leengit** [comment]
I just added a third commit that catches a few changes from `http` to `https` that were missed with the first commit.  I have left these as separate commits for the moment to ease review.

**Comment by Leengit** [comment]
I just squashed the first and third commits.  This will also re-run the tests to see whether the error was spurious.

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
Please update `.git-blame-ignore-revs`

**Comment by Leengit** [comment]
> Please update `.git-blame-ignore-revs`

I'll do a follow up pull request for that, since I have had problems with commit hashes changing as a pull request is merged.

**Comment by jhlegarreta** [comment]
This should also be done in the ITKModuleTemplate, the ITK Examples, the ITK SW Guide, and eventually all remotes.

**Comment by jhlegarreta** [comment]
> This should also be done in the ITKModuleTemplate, the ITK Examples, the ITK SW Guide, eventually all remotes, and any other ITK-related repositories that have the same license notice (e.g. itk-wasm).

@tbirdso took the courage to do the remotes, and almost all of the rest as well 🏅 . Thanks so much Tom:
- [ ] Remotes
- [X] ITKModuleTemplate: https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/pull/129
- [X] ITK-SW Guide: https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/185
- [X] ITK Examples: https://github.com/InsightSoftwareConsortium/ITKSphinxExamples/pull/390
- [X] itk-wasm: https://github.com/InsightSoftwareConsortium/itk-wasm/pull/574

@Leengit It maybe worthwhile to put the commands to a script in the `Maintenance` folder so that it can be readily be used if needed.

**Comment by tbirdso** [comment]
Sure thing, was a good education for me on how to use the maintenance script for updating remotes. I will add the scripts I used for 1) bumping ITK in remote module CI to use the updated styling and 2) reformatting http -> https (from @Leengit ) to the `Maintenance` folder, as well as updates to the `ApplyScriptToRemotes.sh` script to reflect git/Github protocol updates.

**Pull request merged**
