### PR TITLE
ENH: wrap StreamingImageFilter for all the dimensions

### PR DESCRIPTION
**Pull request by dzenanz**
Needed for fixing the wrapping in https://github.com/InsightSoftwareConsortium/ITKBoneEnhancement/pull/20.

### CODE REVIEW

**Comment by dzenanz** [comment]
I was just looking at that documentation, because my local build was failing too.

**Comment by thewtex** [comment]
This error:

```
/Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/../ITK-2.7-macosx_x86_64/Wrapping/Typedefs/itkEigenToMeasureImageFilter.i:82: Warning 401: Nothing known about base class 'itk::StreamingImageFilter< itk::Image< itk::Vector< float,3 >,3 >,itk::Image< itk::Vector< float,3 >,3 > >'. Ignored.
/Users/Kitware/Dashboards/ITK/ITKPythonPackage/scripts/../ITK-2.7-macosx_x86_64/Wrapping/Typedefs/itkEigenToMeasureImageFilter.i:82: Warning 401: Maybe you forgot to instantiate 'itk::StreamingImageFilter< itk::Image< itk::Vector< float,3 >,3 >,itk::Image< itk::Vector< float,3 >,3 > >' using %template.
```

Indicates

```
itk_wrap_image_filter("${WRAP_ITK_SCALAR}" 2)
```

should be:

```
itk_wrap_image_filter("${WRAP_ITK_SCALAR};${WRAP_ITK_VECTOR_REAL}" 2)
```

**Comment by dzenanz** [comment]
I was getting a warning that `StreamingImageFilter` is unknown to wrapping.

**Comment by thewtex** [comment]
@dzenanz please see the comment above.

**Pull request closed without merging**
