### PR TITLE
COMP: remove try-compile for SSE2 detection

### PR DESCRIPTION
**Pull request by seanm**
Instead rely on various preprocessor macros to detect if SSE2 is available.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
LGTM

**Comment by seanm** [comment]
The Windows failure seems unrelated to this patch... anyone knows what's up with it?

**Comment by dzenanz** [comment]
From the log:
```text
Collecting requests
  Downloading requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting linkheader
  ERROR: HTTP error 502 while getting https://files.pythonhosted.org/packages/27/d4/eb1da743b2dc825e936ef1d9e04356b5701e3a9ea022c7aaffdf4f6b0594/LinkHeader-0.4.3.tar.gz#sha256=7fbbc35c0ba3fbbc530571db7e1c886e7db3d718b29b345848ac9686f21b50c3 (from https://pypi.org/simple/linkheader/)
ERROR: Could not install requirement linkheader from https://files.pythonhosted.org/packages/27/d4/eb1da743b2dc825e936ef1d9e04356b5701e3a9ea022c7aaffdf4f6b0594/LinkHeader-0.4.3.tar.gz#sha256=7fbbc35c0ba3fbbc530571db7e1c886e7db3d718b29b345848ac9686f21b50c3 (from githubrelease>=1.5.7->scikit-ci-addons) because of HTTP error 502 Server Error: Gateway Error for url: https://files.pythonhosted.org/packages/27/d4/eb1da743b2dc825e936ef1d9e04356b5701e3a9ea022c7aaffdf4f6b0594/LinkHeader-0.4.3.tar.gz for URL 
##[error]Cmd.exe exited with code '1'.
Finishing: Install dependencies
```
`files.pythonhosted.org` hickuped?

**Comment by blowekamp** [comment]
Thank you for the follow up 👍

**Comment by dzenanz** [comment]
I restarted the Windows tests.

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
