### PR TITLE
ENH: Pass through CMAKE_SH for Eigen3 external

### PR DESCRIPTION
**Pull request by muschellij2**
In `CMake/itkExternal_Eigen3.cmake`, multiple CMake args are passed, but `CMAKE_SH` should be as well, if defined.  This is necessary when using MinGW because otherwise will get an error depending on your PATH configuration: `sh.exe was found in your PATH`.  Thus, when building ITK, we pass `-DCMAKE_SH:bool=OFF`, but this then breaks on Eigen3.  Related to #66. 

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by phcerdan** [comment]
This CMAKE_SH  error doesn't seems new for MinGW: https://stackoverflow.com/questions/41333215/mingw-sh-exe-must-not-be-in-your-path

**Comment by muschellij2** [comment]
No definitely not, but I'm guessing the MinGW setup doesn't have multiple
SH (like one from git) in the path simultaneously, which causes this error.

Best,
John

**Comment by thewtex** [comment]
Warning on macOS is unrelated: https://open.cdash.org/viewBuildError.php?type=1&buildid=6454659

**Comment by thewtex** [comment]
Cleaning up commit history.

**Comment by thewtex** [comment]
Windows build warnings unrelated: https://open.cdash.org/viewBuildError.php?type=1&buildid=6482317

**Pull request merged**
