### PR TITLE
Release hdf5 universal binary

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@dzenanz @thewtex @hjmjohnson ok how about just this for the release branch then?

**Comment by dzenanz** [comment]
5.2 RC2 was tagged on Wednesday evening. So currently `master`==`release`. I will let Matt decide whether to bump version number as required in #2294 or use the minimal fix from this PR.

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
Thanks @seanm ! Let's wait merge #2294 with the bump CMake minimum required version until after 5.2.0 has been released.

**Comment by thewtex** [comment]
Also merged to `master`.

**Comment by seanm** [comment]
OK great, thanks.  I'll have a universal build submitting to cdash as of tonight then.

**Pull request merged**
