### PR TITLE
COMP: itktiff: Suppress C99 inline only on MSVC from VS 2013 and below - For Release Branch

### PR DESCRIPTION
**Pull request by blowekamp**
Extend the condition from commit 08bf6bec432 (COMP: Conditionalize insane "#define inline" in libtiff, 2013-10-07, v4.5rc01~139^2). Newer MSVC versions need it to avoid duplicating `__ucrt_int_to_float`.

Issue: #4820

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
@dyollb yes, this fix should be backported.

**Comment by dzenanz** [comment]
Related discussion: https://github.com/InsightSoftwareConsortium/ITKModuleTemplate/issues/167.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
@blowekamp thanks! I will merge into `release`, `master`.

**Comment by cookpa** [comment]
Hi @thewtex, is this PR going to be merged into master?

**Comment by dzenanz** [comment]
This PR/commit was not explicitly merged to `master`, but `release-5.4` branch was merged into `release`, and then `release` was merged into `master`. But this change does not exist in `master`, because PR #4961 made big changes to this file, removing the code in question.

**Comment by blowekamp** [comment]
> Hi @thewtex, is this PR going to be merged into master?

In short, ITK master now has libtiff version 4.7.0. Please let us know if there are any issues.

**Comment by cookpa** [comment]
Thanks @dzenanz @blowekamp, I'll try this out

**Comment by cookpa** [comment]
Update: ITK now builds on Windows for me. Thanks for these fixes!

**Pull request merged**
