### PR TITLE
COMP: Fixed issue #1821 by conditionalizing ITKGPUCommon_* per-OS

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@dzenanz @thewtex could you review?

I've tested on macOS, but not on Windows, I'm just going on @Neumann-A comments in #1821.

**Review by thewtex — APPROVED** [review]
@seanm thanks!!

**Comment by dzenanz** [comment]
I am trying it locally.

**Comment by dzenanz** [comment]
[Rebasing](https://github.com/dzenanz/ITK/commit/a4cb037c5f160846e2275f7fc278c32855d6e4f1) this on #3440 works, too.

**Pull request merged**
