### PR TITLE
COMP: Remove deprecated/removed std::binary_function

### PR DESCRIPTION
**Pull request by poelmanc**
std::binary_function was deprecated in C++11 and removed in C++17. It only added typedefs. Since they were unused, it compiles fine without them. When building code enabling the latest C++ standards, the prior code would not compile.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by poelmanc** [comment]
> Code looks good. Commit message needs and update:
> commit [ef4065e](https://github.com/InsightSoftwareConsortium/ITK/commit/ef4065ecb8bf7f3947246c69db2ce6f4a0f3e87e) cannot be merged; it must start with one of the following prefixes: BUG: , COMP: , DOC: , ENH: , PERF: , STYLE: .

Thanks for the quick reply. Sorry I failed to read the contributor rules until I got to the pull-request stage, so I put "COMP:" on my PR but not on the commit message.

I'm not sure how to amend a commit message once it's been pushed. This commit was super easy to I'm happy to close this pull request and open a new one with a "COMP:" commit message.

**Comment by dzenanz** [comment]
Do [an `--amend`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#revise-a-topic) followed by force-push (e.g. `--force-with-lease` parameter to `git push`).

**Comment by thewtex** [comment]
Fixing commit message format...

**Comment by thewtex** [comment]
macOS build warning is unrelated:

  https://open.cdash.org/viewBuildError.php?type=1&buildid=6482281

**Comment by thewtex** [comment]
@poelmanc thanks for contributing! :clap:

**Pull request merged**
