### PR TITLE
VNL 2021-02-15 (7edc7cd8)

### PR DESCRIPTION
**Pull request by thewtex**
Run the UpdateFromUpstream.sh script to extract upstream VNL
using the following shell commands.

$ git archive --prefix=upstream-vnl/ 7edc7cd8 -- 
      CMakeLists.txt
      config/cmake
      core/CMakeLists.txt
      core/testlib
      core/vnl
      core/vxl_config.h.in
      core/vxl_copyright.h
      core/vxl_version.h
      v3p/CMakeLists.txt
      v3p/netlib
      vcl
 | tar x
$ git shortlog --perl-regexp --author='^((?!Kitware Robot).*)$' --no-merges --abbrev=8 --format='%h %s' 85ae25b7..7edc7cd8

Drew Gilliam (1):
      40ccc0b8 vpgl_rational_camera additional ordering schema

Joseph Mundy (2):
      faa3fcf4 remove bad cams from match tree
      7edc7cd8 upgrade from WGS80 to WGS84

Matt McCormick (1):
      d1cd3d14 COMP: Instantiate vnl_fft_base for 5D data

Change-Id: Ia06010461c76d8388e6fbcd9ff25cda79fc1bff1

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
commit a4dc6cc adds bad whitespace including CR/LF line endings:

v3p/netlib/libf2c/comptry.bat:1: trailing whitespace.
+%1 %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/comptry.bat:2: trailing whitespace.
+if errorlevel 1 goto nolonglong⏎
v3p/netlib/libf2c/comptry.bat:3: trailing whitespace.
+exit 0⏎
v3p/netlib/libf2c/comptry.bat:4: trailing whitespace.
+:nolonglong⏎
v3p/netlib/libf2c/comptry.bat:5: trailing whitespace.
+%1 -DNO_LONG_LONG %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/scomptry.bat:1: trailing whitespace.
+%1 -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/scomptry.bat:2: trailing whitespace.
+if errorlevel 1 goto nolonglong⏎
v3p/netlib/libf2c/scomptry.bat:3: trailing whitespace.
+exit 0⏎
v3p/netlib/libf2c/scomptry.bat:4: trailing whitespace.
+:nolonglong⏎
v3p/netlib/libf2c/scomptry.bat:5: trailing whitespace.
+%1 -DNO_LONG_LONG -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎

**Comment by thewtex** [comment]
> v3p/netlib/libf2c/comptry.bat
> commit a4dc6cc adds bad whitespace including CR/LF line endings:

Odd because we have `*.bat -crlf` in our *.gitattributes. @bradking @mathstuf

**Review by hjmjohnson — APPROVED** [review]
LGTM adding the FFT recent changes.

**Comment by bradking** [comment]
> Odd because we have *.bat -crlf in our *.gitattributes. 

The bot is complaining about the import commit, whose tree object does not include the rest of ITK.  The import script may need to write the `.gitattributes` content itself to get it in the import commit.

**Comment by phcerdan** [comment]
I am curious why this VNL update seems fine, not touching unrelated files as past VNL and MetaIO updates did.

@bradking Could you please share your thoughts on this related issue : https://github.com/InsightSoftwareConsortium/ITK/issues/2314 ?

**Review by phcerdan — APPROVED** [review]

**Comment by bradking** [comment]
I'll look at converting `Modules/ThirdParty/VNL/UpdateFromUpstream.sh` to use `Utilities/Maintenance/update-third-party.bash`, which provides a hook to handle `.gitattributes`.

**Comment by bradking** [comment]
@thewtex I updated your branch to convert to the newer import script, add the `.gitattributes` file to the import to suppress whitespace checks, and then perform the actual update you did before.

**Comment by thewtex** [comment]
@bradking thank you!!

**Pull request merged**
