### PR TITLE
DOC: Moved wiki examples to sphinx examples part2

### PR DESCRIPTION
**Pull request by hjmjohnson**
Link to Sphinx based documentation instead of
outdated media wiki documentation
 - Moved wiki AdaptiveHistogramEqualizationImageFilter example
 - Moved wiki AntiAliasBinaryImageFilter example
 - Moved wiki Atan2ImageFilter example
 - Moved wiki BackwardDifferenceOperator example
 - Moved wiki BinaryBallStructuringElement example
 - Moved wiki BinaryDilateImageFilter examples
 - Moved wiki BinaryErodeImageFilter examples
 - Moved wiki BinomialBlurImageFilter example
 - Moved wiki CastImageFilter example
 - Moved wiki CheckerBoardImageFilter example
 - Moved wiki CreateAnother example
 - Moved wiki FixedArray example
 - Moved wiki GradientMagnitudeImageFilter example
 - Moved wiki GradientMagnitudeRecursiveGaussianImageFilter example
 - Moved wiki GradientRecursiveGaussianImageFilter example
 - Moved wiki GrayscaleDilateImageFilter example
 - Moved wiki GrayscaleErodeImageFilter example
 - Moved wiki Histogram example
 - Moved wiki LaplacianRecursiveGaussianImageFilter example
 - Moved wiki MedianImageFilter examples
 - Moved wiki MersenneTwisterRandomVariateGenerator example
 - Moved wiki NumericSeriesFileNames example
 - Moved wiki ObserveEvent example
 - Moved wiki OtsuMultipleThresholdsImageFilter example
 - Moved wiki PasteImageFilter example
 - Moved wiki PermuteAxesImageFilter example
 - Moved wiki QuadEdgeMeshNormalFilter example
 - Moved wiki QuadEdgeMeshParameterizationFilter example
 - Moved wiki ReadWrite example
 - Moved wiki RegionOfInterestImageFilter example
 - Moved wiki RescaleIntensityImageFilter example
 - Moved wiki ScalarToRGBColormapImageFilter example
 - Moved wiki ShapedNeighborhoodIterator example
 - Moved wiki SigmoidImageFilter example
 - Moved wiki SimpleFilterWatcher example
 - Moved wiki SmoothingRecursiveGaussianImageFilter example
 - Moved wiki SobelEdgeDetectionImageFilter example
 - Moved wiki ThresholdImageFilter example
 - Moved wiki TimeProbe example
 - Moved wiki VectorContainer example
 - Moved wiki WarpImageFilter example
 - Moved wiki WatershedImageFilter example

Co-authored-by: Mathew J. Seng <mathewseng@gmail.com>

## PR Checklist
- [X] Adds Documentation.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@dzenanz Do you know why the "CDash" analysis keeps failing?

**Comment by dzenanz** [comment]
I don't know why CDash never leaves "in progress" phase. @bradking or @fbudin69500 might know, and @thewtex should know (he should be back next week).

**Comment by fbudin69500** [comment]
I don't know. Hopefully @bradking or @thewtex will know.

**Comment by thewtex** [comment]
> CDash never leaves "in progress" phase. 

Once in a while, two status check event observers would do the initial CDash check creation at the same time, resulting in two CDash checks. I improved the [ITKGitHubCDashStatus App](https://github.com/InsightSoftwareConsortium/ITKGitHubCDashStatus) so this should not happen any more. If it does, let me know.

**Pull request merged**
