### PR TITLE
DOC: Add `Pixi`-managed build status badge to README file

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add `Pixi`-managed build status badge to README file. A single badge is added since the OS configurations are part of a job matrix.

Add an additional column to distinguish Azure pipelines and GHA builds.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Notes:
- Cannot get a badge per matrix configuration.
- Should we remove the GHA macOS ARM64 workfow given that the `pixi`-managed builds are testing it?

**Comment by thewtex** [comment]
@jhlegarreta thanks!

This is what I see:

image

However, currently, the Pixi GitHub Actions configuration only runs C++ build/test.

Since the Pixi build uses the conda-forge toolchain, we can keep the GHA macOS ARM64 to have more toolchain coverage.

**Comment by jhlegarreta** [comment]
:+1: thanks Matt, yes that was what I intended to display. Removed the badge from the Python column.

**Review by hjmjohnson — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
:100: thanks @jhlegarreta !

**Pull request merged**
