### PR TITLE
Update kwsys

### PR DESCRIPTION
**Pull request by seanm**
Update to newest kwsys, notably to fix bug with Apple Silicon.

### CODE REVIEW

**Comment by seanm** [comment]
@bradking @thewtex I'm confused why there should be conflicts.  Does ITK alter kwsys without going via upstream kwsys?

**Comment by bradking** [comment]
@seanm I think you based on a very old version of the `release` branch.  The conflict is with a more recent update of KWSys.

**Comment by seanm** [comment]
As always, git is my nemesis. :)

So I tried the following:

`git checkout --track origin/release` to get my own local `release` branch, I think.

then 

```
git fetch upstream
git checkout release
git merge upstream/release
git push
```

Now it seems my fork's release is even with upstream.

Then I did:

```
git checkout -b update-kwsys-2021-02-10 origin/release
Modules/ThirdParty/KWSys/UpdateFromUpstream.sh
```

but now this fails with:

```
...
Resolving deltas: 100% (4770/4770), done.
++ '[' -n 2e004cc7547d3db156bed436e36bf34e6b4dd999 ']'
++ git worktree add /Users/sean/external/ITK/work/extract 2e004cc7547d3db156bed436e36bf34e6b4dd999
Preparing worktree (detached HEAD 2e004cc754)
fatal: 'add' is a missing but already registered worktree;
use '/Users/sean/external/ITK/work/extract -f' to override, or 'prune' or 'remove' to clear
+ rm -rf /Users/sean/external/ITK/work
```

**Comment by bradking** [comment]
There is a bug in the `UpdateFromUpstream.sh` script that breaks when running it more than once in a given work tree.  Run `rm -rf .git/worktrees/extract` to clean up after the first run.

**Comment by bradking** [comment]
I opened #2291 to update the third-party import script for that problem.

**Comment by seanm** [comment]
Oh!  It didn't occur to me that I'd done nothing wrong! :)

Wasn't sure how to fix this PR, so just created https://github.com/InsightSoftwareConsortium/ITK/pull/2292

**Pull request closed without merging**
