### PR TITLE
DOC: Fixed SetThrehsold typo in Canny doc.

### PR DESCRIPTION
**Pull request by dave3d**
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
This runs into:
```log
CMake Warning (dev) at /usr/local/share/cmake-3.24/Modules/ExternalProject.cmake:3071 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is not set.
```
e3d6c94eb962ce8bbe4de2d83a1289dfa5cb6921 should have taken care of this. Is your PR based off of current master?

**Comment by dave3d** [comment]
Oops, I wasn't based off the current master.

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
Nice catch, Dave, but isn't the entire comment obsolete?

```
   * TODO:  Document in the ITKv4 migration guide that
   * the SetThreshold member function was removed from
   * the CannyEdgeDetectionImageFilter, and that both
   * UpperThreshold and LowerThreshold need to be set.
   * To get the same results as with the SetThreshold method
   * change "myfilter->SetThrehsold" to "myfilter->SetUpperThreshold",
   * change "myfilter->SetThreshold" to "myfilter->SetUpperThreshold",
   * and add "myfilter->SetLowerThreshold(GetUpperThreshold()/2.0)"
```
It's just a TODO item about the the ITKv4 migration guide, right?

**Comment by dave3d** [comment]
> Nice catch, Dave, but isn't the entire comment obsolete?
> 
> ```
>    * TODO:  Document in the ITKv4 migration guide that
>    * the SetThreshold member function was removed from
>    * the CannyEdgeDetectionImageFilter, and that both
>    * UpperThreshold and LowerThreshold need to be set.
>    * To get the same results as with the SetThreshold method
>    * change "myfilter->SetThrehsold" to "myfilter->SetUpperThreshold",
>    * change "myfilter->SetThreshold" to "myfilter->SetUpperThreshold",
>    * and add "myfilter->SetLowerThreshold(GetUpperThreshold()/2.0)"
> ```
> 
> It's just a TODO item about the ITKv4 migration guide, right?
> 
> It appear that the typo was introduced 12 years ago, with commit [df54d1b](https://github.com/InsightSoftwareConsortium/ITK/commit/df54d1bb59eb9e3b832c614f3c931b704d8da4d0) and included with ITK v4.0a01:
> 
> https://github.com/InsightSoftwareConsortium/ITK/blob/df54d1bb59eb9e3b832c614f3c931b704d8da4d0/Code/BasicFilters/itkCannyEdgeDetectionImageFilter.h#L182-L188
> 
> I think I'd rather see the entire TODO item being removed by now.
> 
> My two cents, Niels

Maybe?  I don't know the code.  I just saw the misspelling and it irked me. :)

**Comment by N-Dekker** [comment]
@hjmjohnson @dzenanz Do you agree that the entire `TODO` comment section is obsolete now? It appears to be a hint for the ITKv4 migration guide, for users, migrating from ITK 3 to ITK 4. Hans, maybe you know, because you originally added the text! df54d1bb59eb9e3b832c614f3c931b704d8da4d0

**Comment by dzenanz** [comment]
I agree that the entire TODO is now moot, and should be replaced just by a simple docstring about `UpperThreshold`.

**Comment by hjmjohnson** [comment]
Superceeded by #3584 Thanks @dave3d for bringing our attention to this comment.

**Pull request closed without merging**
