### PR TITLE
COMP: Changed conditional include of emmintrin.h to use __SSE2__

### PR DESCRIPTION
**Pull request by seanm**
For compatability with Universal Binaries on macOS, change how #include <emmintrin.h> is done to test against __SSE2__.

Using a trycompile to check if #include <emmintrin.h> compiles doesn't work for UBs becuase the check will only be done for the native architecture, not both architectures (where indeed there would be the opposite answer).

Other parts of the codebase are already doing it this way, so it must work on other platforms too.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
Ah, thanks to all for your git help, this PR now has just the 1 commit as expected!

**Review by dzenanz — APPROVED** [review]

**Comment by seanm** [comment]
OK, this new incantation I've tried on just about every compiler on godbolt, and I think should work.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
Thanks @seanm !

**Comment by thewtex** [comment]
Merging for ITK 5.2rc03.

**Comment by blowekamp** [comment]
Please create an issue to remote the  ITK_HAVE_EMMINTRIN_H try compile now that it is not used.

**Comment by seanm** [comment]
@blowekamp https://github.com/InsightSoftwareConsortium/ITK/pull/2369

**Pull request merged**
