### PR TITLE
ENH: Add VTKPolyDataMeshIO GTest tests, testing lossless write and read

### PR DESCRIPTION
**Pull request by N-Dekker**
Added `VTKPolyDataMeshIO` GoogleTest, having the following unit tests:

 - LosslessWriteAndReadOfPoints
 - SupportWriteAndReadOfNaNCoordValues

### CODE REVIEW

**Comment by N-Dekker** [comment]
The proposed tests write some .vtk files to the current directory (in order to read them back, afterwards). Is it OK for these tests to just leave those little .vtk files there, or should they be removed by the tests themselves, at the end?

**Comment by dzenanz** [comment]
It would probably be best if we passed in the path to a temporary directory and wrote the files there. Passing a temp path from CMakeLists.txt file should be easy.

**Comment by N-Dekker** [comment]
> It would probably be best if we passed in the path to a temporary directory and wrote the files there. Passing a temp path from CMakeLists.txt file should be easy.

Thanks @dzenanz. It isn't entirely obvious to me how to do it via CMake. Could the temporary directory be specified with the proposed CreateGoogleTestDriver, call? It now just says:

    CreateGoogleTestDriver(ITKIOMeshVTK "${ITKIOMeshVTK-Test_LIBRARIES}" "${ITKIOMeshVTKGTests}")

Currently, the vtk files created by these tests appear locally at the build tree, on my Windows system, at `<build>\ITK\Modules\IO\MeshVTK\test\`. So I don't think it will bother people. So we could also leave it the way it is right now. What do you think?

**Review by dzenanz — COMMENTED** [review]
I meant use `${ITK_TEST_OUTPUT_DIR}` as an argument to the test executable, but I now realize that this is GTest, nor a regular test. Having the temporary files in the build folder are fine by me.

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
