### PR TITLE
ENH: Preserving information about auto-flipped negative steps in metadata

### PR DESCRIPTION
**Pull request by vfonov**
We need information weather the image was flipped to compensate for the negative steps.
This fix can also help resolve the issues menioned in https://github.com/InsightSoftwareConsortium/ITK/commit/7501479a970694b0dd4a8c4bbf7cbcc033fe059c

## PR Checklist

- [ ] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] :no_entry_sign: Adds the License notice to new files.
- [ ] :no_entry_sign: Adds Python wrapping.
- [ ] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [ ] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by vfonov** [comment]
CC @seanm

**Comment by blowekamp** [comment]
Would just storing the original spacing in the MetaDataDictionary as an Array, be more useful and easyier? These string tags seems a little cumbersome to manage.

**Comment by seanm** [comment]
@vfonov I think I agree with @blowekamp. If we change your patch to just store the original spacing, then apps like ours can consult it to know if ITK flipped things.  Since ITK also flips `direction`, maybe we should store the original of that too.

**Comment by seanm** [comment]
@blowekamp what do you think of @vfonov 's newest patch? It LGTM.

**Comment by vfonov** [comment]
Oops, I think my last commit didn't include needed changes

**Comment by blowekamp** [comment]
That looks a lot simpler and easier to use! Thanks!

couple more questions:
- should something similar  also be added to the ImageSeries reader?
- Do you see an easy way to add a little test?

**Pull request merged**
