### PR TITLE
STYLE: Remove doxygen.config.in (superseded by DoxygenConfig.cmake)

### PR DESCRIPTION
**Pull request by N-Dekker**
The use of doxygen.config has been replaced by DoxygenConfig.cmake, with pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3311 commit a96d03fb5f4a4bb470516aa623dbc9b4aaaa6e4f
"COMP: Use modern doxygen_add_docs for BUILD_DOCUMENTAITON", Hans Johnson (@hjmjohnson), March 18, 2022

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Change looks good. Question: Does it affect the doc build process? 😄

**Comment by thewtex** [comment]
@N-Dekker did you confirm that the doxygen build succeeds?

**Comment by N-Dekker** [comment]
> did you confirm that the doxygen build succeeds?

@thewtex I did not try it out locally, but I searched exhaustively for "doxygen.config" in the source tree, and only found it in comments, like:

     # The DoxygenConfig.cmake is a replacement for configuring a doxygen.config.in file

https://github.com/InsightSoftwareConsortium/ITK/blob/e3189492ce6858035b68a2b89e4a4d2f1d4041ad/Utilities/Doxygen/CMakeLists.txt#L171
 
Before commit a96d03fb5f4a4bb470516aa623dbc9b4aaaa6e4f (March, 2022), Utilities/Doxygen/CMakeLists.txt still configured doxygen.config.in, by doing:

    configure_file(${ITK_SOURCE_DIR}/Utilities/Doxygen/doxygen.config.in
                   ${ITK_BINARY_DIR}/Utilities/Doxygen/doxygen.config)

That statement was removed by commit a96d03fb5f4a4bb470516aa623dbc9b4aaaa6e4f (March, 2022).

@hjmjohnson Can you confirm that "doxygen.config.in" is no longer necessary, now that we have DoxygenConfig.cmake?

**Comment by thewtex** [comment]
@N-Dekker it needs to be tested before merging. I will start a local build.

**Pull request merged**
