### PR TITLE
BUG: fixed memory leaks in MINC IO

### PR DESCRIPTION
**Pull request by issakomi**
MINC IO does not free allocations before throwing an exception sometimes,
s. discussion https://github.com/InsightSoftwareConsortium/ITK/pull/3529

https://open.cdash.org/viewDynamicAnalysis.php?buildid=8097352

(reviewed _writing_ an image).

### CODE REVIEW

**Comment by issakomi** [comment]
Don't know why 'Label PR' test fails, maybe something _github_ internal?

**Comment by issakomi** [comment]
Have changed a little to avoid repeating code and tested exit points (to avoid double free, etc).

**Review by jhlegarreta — APPROVED** [review]
Thanks for doing this @issakomi. Have not tested but looks good.

Maybe, following for comment in the related issue:
> I have done trivial test, without using itkIOTestHelper.h, just read MHA and write MNC to wrong path, the leaks are there. If the path is correct -- there are no problems, 

Adding a test such as the one you did would be convenient.

**Comment by gdevenyi** [comment]
@vfonov

**Comment by issakomi** [comment]
> > I have done trivial test, without using itkIOTestHelper.h, just read MHA and write MNC to wrong path, the leaks are there. If the path is correct -- there are no problems,
> 
> Adding a test such as the one you did would be convenient.

it is really very simple [test](https://drive.google.com/file/d/1y8EcexH4ijOQ5-j0zIavvkNDKlumlJcJ/view?usp=sharing), to try `valgrind --leak-check=full ./test` without ITK's testing subsystem, already merged new ITK tests with intentional wrong path (which discovered [leaks](https://open.cdash.org/viewDynamicAnalysis.php?buildid=8097352)) are doing the same. Maybe later more tests could be done to trigger exceptions and increase coverage, e.g. 4D image.

**Review by dzenanz — APPROVED** [review]

**Comment by vfonov** [comment]
> @vfonov

Looks ok

**Pull request merged**
