### PR TITLE
BUG: MinPriorityQueueElementWrapper constructor needs ZeroValue()

### PR DESCRIPTION
**Pull request by Leengit**
For some types, 0 won't do in the constructor. Instead we need, e.g., NumericTraits<TElement>::ZeroValue(). This will help Seg3D to compile.

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
Thanks, Lee!

**Review by dzenanz — APPROVED** [review]
MacOS failure was due to Azure downtime.

**Comment by Leengit** [comment]
Index<2>::ZeroValue() was needed and didn't work in some configurations.  Trying the default constructor for Index<2> instead.

**Comment by dzenanz** [comment]
This patch allows Seg3D to compile for me.

**Review by dzenanz — APPROVED** [review]
To be squashed before merging

**Pull request merged**
