### PR TITLE
ENH: PoolMultiThreader uses one less thread

### PR DESCRIPTION
**Pull request by dzenanz**
There is one work unit passed through the queue now,
as work unit 0 is executed in current thread.

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
```
The following tests FAILED:
	2345 - itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest (SEGFAULT)
```

**Comment by hjmjohnson** [comment]
@dzenanz I'm just curious if this may be running out of memory on the CI nodes.

**Comment by dzenanz** [comment]
Doubtful. itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest uses around 200MB of RAM.

**Comment by blowekamp** [comment]
I'm suspicious is my be something related to the new docker image used on CircleCI.

**Comment by dzenanz** [comment]
The test failure is unrelated to this patch.

**Pull request merged**
