### PR TITLE
BUG: Do not assert module swig attribute for init_docstring

### LINKED ISSUE #2064: Python Wrapping: UnaryFunctorImageFilter issue when building with RTK
### Description

Python wrapping is not working with recent commits to ITK master as UnaryFunctorImageFilter (and maybe others) is missing(?).  I encountered this when compiling with `ITK_WRAP_PYTHON=ON` and `Module_RTK=ON` but as this is an ITK Filter I suspect that this is not an RTK dependent issue.
Maybe this is more relevant to @SimonRit and RTK?
The build itself compiles without errors but the wrapping is incomplete (see example below).

### Steps to Reproduce

Clone current master, Build Release with `ITK_WRAP_PYTHON=ON` and `Module_RTK=ON` using MSVC or ninja.
Open python shell and execute commands given below.

### Expected behavior
```
import itk
itk.Image
<itkTemplate itk::Image>

from itk import RTK as rtk
rtk.Image
<itkTemplate itk::Image>

itk.UnaryFunctorImageFilter
<itkTemplate itk::UnaryFunctorImageFilter>
```
### Actual behavior

```
import itk
itk.Image

<itkTemplate itk::Image>

from itk import RTK as rtk
rtk.Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 101, in LoadModule
    LoadModule(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 101, in LoadModule
    LoadModule(dep, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 215, in LoadModule
    init_function()
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\itkVectorRescaleIntensityImageFilterPython.py", line 791, in unary_functor_image_filter_init_docstring
    if isinstance(itk.UnaryFunctorImageFilter, itkTemplate.itkTemplate):
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 70, in LoadModule
    assert hasattr(this_module, "swig")
AssertionError

itk.UnaryFunctorImageFilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkLazy.py", line 56, in __getattribute__
    itkBase.LoadModule(module, namespace)
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itkBase.py", line 70, in LoadModule
    assert hasattr(this_module, "swig")
AssertionError
```

### Reproducibility

100%

### Versions

ITK 5.1.1 master
but ITKConfig.cmake actually uses
```
set(ITK_VERSION_MAJOR "5")
set(ITK_VERSION_MINOR "2")
set(ITK_VERSION_PATCH "0")
```

### Environment

CMake 3.17.5
VS2019, v16.7.6 or ninja v1.10.1
Python 3.8.3 from Anaconda3 (2020.07)
Windows 10

### Additional Information

I suspect one of the recent commits to be the issue as I tried some of the older ones and saw that [at least everything works up to this commit](https://github.com/InsightSoftwareConsortium/ITK/commit/4c0982ddec474b1701d695839c78c7e888659ef4). Maybe even some of the following commits work but I didn't have time to check all of them.
As I don't know what actually went wrong I do not what I am looking for.

For the builds mentioned above I used ninja but MSVC behaves similar, just takes way longer to build everything.
I also tried to set `Module_RTK_GIT_TAG=master` as I thought RTK may be the culprit but this does not change anything.

### PR DESCRIPTION
**Pull request by thewtex**
Following up on
https://github.com/InsightSoftwareConsortium/ITK/commit/183cb1db67c5dbd30a25f279f913a4d2da5ea0b6
an `assert hasattr(this_module, "swig")` was added, but is true for most
classes, but this assertion causes issues when calling
`*init_docstring()` in the module. Replace the assert with a
condition.

Also, simplify the namespace `swig` initialization further on.

Closes #2064

### CODE REVIEW

**Comment by MrTzschr** [comment]
@thewtex Thanks for this suggestions. Unfortunately this does not solve the issue:
```
itk.UnaryFunctorImageFilter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ITK\bin-master\Wrapping\Generators\Python\itk\support\itkLazy.py", line 82, in __getattribute__
    value = namespace[attr]
KeyError: 'UnaryFunctorImageFilter'
```
Looking a bit closer at the issue I saw that the `namespace` dictionary is more or less empty and only contains `{'swig': {}}`, 
so i think `itkBase.itk_load_swig_module(module, namespace)` at line 78 in `itkLazy.py` fails.

**Comment by SimonRit** [comment]
Thanks @thewtex for looking into it and @MrTzschr for the test. I confirm it doesn't solve the issue. You can actually easily test it from the packages available [here](https://github.com/SimonRit/RTK/actions/runs/482408583) after modification of `itkBase.py`.

**Comment by thewtex** [comment]
@MrTzschr @SimonRit thanks for testing.

I added an additional commit. Does this work for you?

**Comment by MrTzschr** [comment]
@thewtex That additional commit did the trick, now it works for me. Thank you so much for fixing this!
I get the expected output:
```
>>> import itk
>>> itk.Image
<itkTemplate itk::Image>
>>> itk.UnaryFunctorImageFilter
<itkTemplate itk::UnaryFunctorImageFilter>
```

@SimonRit This also fixes my issues with RTK:
```
>>> from itk import RTK as rtk
>>> rtk.Image
<itkTemplate itk::Image>
```
Probably just some module which is loading the same filter from ITK that triggered this, sorry for the false alarm.

**Review by SimonRit — APPROVED** [review]
I approve it since it solves #2064. I'm really glad you solved it before it was in an official release. I'll check that the RTK CI packages work as expected once ITK 5.2rc02 is released.

**Pull request merged**
