### PR TITLE
Replace zlib by zlib-ng

### PR DESCRIPTION
**Pull request by dzenanz**
Some PRs in zlib-ng need to be merged, namely, https://github.com/zlib-ng/zlib-ng/pull/1043 and https://github.com/zlib-ng/zlib-ng/pull/1042. Preferably also https://github.com/zlib-ng/zlib-ng/pull/1040 or https://github.com/zlib-ng/zlib-ng/pull/1041. Until then, we will use `develop` branch in my fork.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Thanks for picking this up @dzenanz. This is well beyond my ability to do right now, but I'll be watching closely for education.

**Comment by dzenanz** [comment]
This works for me. I updated the description with current state. It would be good if someone else tried this to confirm it works as expected.

**Comment by dzenanz** [comment]
I haven't tested installation yet.

**Comment by dzenanz** [comment]
I cleaned up the history. Testing the installation is still TODO.

**Comment by dzenanz** [comment]
Only a minor change was needed to fix installation (the latest commit). Now waiting for upstream to merge my patches.

**Comment by thewtex** [comment]
Since we are using CMake, the *Makefile.in* files should be removed from the import.

Why is CircleCI failing?

Can we add the name mangling patches to our branch?

**Comment by dzenanz** [comment]
> Makefile.in files should be removed from the import

Will do.

> Why is CircleCI failing?

`/usr/bin/ld: cannot open linker script file /.../ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib.map: No such file or directory` - I will add this file too. I don't know why only CircleCI needs it.

> Can we add the name mangling patches to our branch?

This is currently in my fork. We could go with this while waiting for some variant of the patches to be merged. But that risks the patch to be reject on philosophical/maintenance burden grounds, thus forcing us to keep our own set of patches which will need to be occasionally rebased with probable conflicts..

**Comment by thewtex** [comment]
> We could go with this while waiting for some variant of the patches to be merged. But that risks the patch to be reject on philosophical/maintenance burden grounds, thus forcing us to keep our own set of patches which will need to be occasionally rebased with probable conflicts.

Hopefully it will be merged upstream. Or, a different approach could be used upstream, and we will switch to that if it serves the need. But if we need to keep our own set of patches for the name mangling, then that is what we will have to do.

**Review by thewtex — APPROVED** [review]
🚀  well done @dzenanz @gdevenyi !

**Comment by gdevenyi** [comment]
>  well done @dzenanz @gdevenyi !

Thanks but @dzenanz definitely did all the hard work. I'm gonna carefully study these changes to learn a bit more CMAKE.

**Comment by thewtex** [comment]
@dzenanz we are getting the error:

```
CMake Error: File /Users/runner/work/1/s/Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib_name_mangling.h.empty does not exist.
CMake Error at Modules/ThirdParty/ZLIB/src/itkzlib-ng/CMakeLists.txt:1064 (configure_file):
  configure_file Problem configuring file
```

**Comment by dzenanz** [comment]
The last [force-push](https://github.com/InsightSoftwareConsortium/ITK/compare/88d53ff79a87143f4f533469770f3b8123ef125c..d149ddffd9f886844094c14d40768bc376ba9422) takes care of that. ITK.macOS.Python "was cancelled". I will clean up this PR so it can be merged today.

**Review by thewtex — APPROVED** [review]

**Comment by aaron-bray** [comment]
I still seem to be getting this itkzlib-ng not found on the latest master on windows

**Comment by aaron-bray** [comment]
Hang on, maybe my cmake did not refresh something after pull...

**Comment by aaron-bray** [comment]
Yeah, note to self, When MSVC asks you to reload, and you click ok, but then it says, sorry can't do that in the process of a build. Close MSVC and reopen it

Nothing to see here
Thanks for your time

**Comment by dzenanz** [comment]
Doesn't it give the option to stop the build in order to reload?

**Pull request merged**
