### PR TITLE
ENH: Support `ttype` parameter for numpy<->ITK conversions

### LINKED ISSUE #1348: Add ttype keyword parameter for NumPy conversion functions
Similar to the [functional ITK Python filter interfaces](https://itkpythonpackage.readthedocs.io/en/latest/Quick_start_guide.html#basic-examples), support passing a `ttype` keyword argument to the ITK NumPy interface functions. The will enable explicit specification of the type desired. For example:

```
ImageType = itk.Image[itk.RGBPixel[itk.UC], 3]
itk_image = itk.image_from_array(np_image, ttype=(ImageType,))
```

@hina-shah

### PR DESCRIPTION
**Pull request by Leengit**
Resolves #1348 by adding `ttype` keyword parameter to the functions `_GetArrayFromImage`, `GetArrayFromImage`, `array_from_image`, `GetArrayViewFromImage`, `array_view_from_image`, `_GetImageFromArray`, `GetImageFromArray`, `image_from_array`, `GetImageViewFromArray`, `image_view_from_array`, `_GetArrayFromVnlObject`, `GetArrayFromVnlVector`, `array_from_vnl_vector`, `GetArrayViewFromVnlVector`, `GetArrayFromVnlMatrix`, `GetArrayViewFromVnlMatrix`, `array_from_vnl_matrix`, `_GetVnlObjectFromArray`, `GetVnlVectorFromArray`, `vnl_vector_from_array`, `GetVnlMatrixFromArray`, and `vnl_matrix_from_array`.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
LGTM

**Comment by Leengit** [comment]
My manual merge with master missed something, which I just fixed with the latest force-push.

**Comment by Leengit** [comment]
The test was failing due the incorrect assumption that whatever the original, non-`ttype`-based code produced under Linux would be the same type under MacOS.  I have just pushed a change to the test that has the `ttype`-based code request whatever type was produced by the  non-`ttype` code, and then checks that the output from the `ttype`-based code is as was requested.

**Review by thewtex — COMMENTED** [review]
Do we need to force a tuple here? It is more consistent with the filter argument type, but it is simpler and more convenient avoid constructing a tuple. Can we support both?

**Comment by Leengit** [comment]
> Do we need to force a tuple here? It is more consistent with the filter argument type, but it is simpler and more convenient avoid constructing a tuple. Can we support both?

With 7a6522396a13b8e068f733ec7dd6c50d05dd0e8f, just pushed, any of these should work:
```python
ttype=itk.Image[itk.F,2]
ttype=(itk.Image[itk.F,2],)
ttype=[itk.Image[itk.F,2]]
```

**Comment by Leengit** [comment]
Force-pushed 00e6785a6a9248ff64faa2aaa501e25543aceea6 to squash the commits.

**Review by thewtex — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
