### PR TITLE
DOC: Add repobeats stats to README, contributing docs

### PR DESCRIPTION
**Pull request by thewtex**
Demonstrate community activity and motivate involvement.

Add to the README and ReadTheDocs Contributing index.

### CODE REVIEW

**Review by hjmjohnson — APPROVED** [review]
I think this looks good to me. Hopefully, it will motivate new users and contribute.

**Comment by jhlegarreta** [comment]
Sorry for being late; is there a way that these point to some repobeats/ITK website instead of pointing to the image file? i.e. clicking on the image simply opens the image in another tab.

**Comment by N-Dekker** [comment]
Looks really cool! Indeed, the effect of clicking  on the image it a bit disappointing, though, as Jon (@jhlegarreta) remarked. And I'm missing any stats of involvement by means of code reviewing. I think code reviewers deserve to be in the spotlight as well  😃

**Comment by thewtex** [comment]
@jhlegarreta @N-Dekker I added a link to the GitHub Pulse demonstrate that we are an active community in https://github.com/InsightSoftwareConsortium/ITK/pull/5089

**Pull request merged**
