### PR TITLE
Hdf5 universal long double

### PR DESCRIPTION
**Pull request by seanm**
@thewtex @dzenanz do you know what git thing I'm screwing up that I see 38 commits in this PR instead of just the 1 expected?  And how do I fix it?

### CODE REVIEW

**Comment by blowekamp** [comment]
It looks like you local master has diverted from the origin.

**Comment by seanm** [comment]
Could be, but things look in-sync to me:

```
leprechaun:ITK sean$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

leprechaun:ITK sean$ git push
Everything up-to-date

leprechaun:ITK sean$ git pull
Already up to date.
```

**Comment by dzenanz** [comment]
What does `git pull upstream/master` do?

**Comment by seanm** [comment]
```
leprechaun:ITK sean$ git pull upstream/master
fatal: 'upstream/master' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

leprechaun:ITK sean$ git remote -v
origin	https://github.com/seanm/ITK.git (fetch)
origin	git@github.com:seanm/ITK.git (push)
upstream	https://github.com/InsightSoftwareConsortium/ITK.git (fetch)
upstream	https://github.com/InsightSoftwareConsortium/ITK.git (push)

leprechaun:ITK sean$ git branch -vv
  hdf5-universal-long-double cae6629caa [origin/master: ahead 1] COMP: cherrypicked HDF5 upstream changes for macOS universal binary support
* master                     9b26b5deba [origin/master] Merge remote-tracking branch 'upstream/master'
```

**Comment by dzenanz** [comment]
I just cleanly rebased your branch on top of current master. Your branch had a long history with multiple merges with the master.

**Review by dzenanz — APPROVED** [review]

**Comment by seanm** [comment]
Thanks. Though I worry this will happen to me every time... I have another patch coming, so we'll see...

**Comment by thewtex** [comment]
> Your branch is up to date with 'origin/master'.

When git says this, it is only relative to the last time a `fetch` / `pull` occurred -- if the remote repository has advanced, it could not be out of date.

> git pull upstream/master

We want `git pull upstream master`.

**Review by thewtex — APPROVED** [review]
Thanks for the contribution, @seanm !

**Comment by dzenanz** [comment]
I usually use TortoiseGit, so my command line git-fu is rusty.

**Comment by seanm** [comment]
>We want git pull upstream master.

OK, that certainly did something!  It gave conflict after conflict, in files that I really don't think I've ever touched, but I think I've got them all resolved.  Now my status is:

```
$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 13 and 37 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)
```

I'm hesitant that I want `git pull` as it suggests since I just did `git pull upstream master`...

**Comment by dzenanz** [comment]
You don't need any further rebasing for this PR.

**Comment by seanm** [comment]
I know, it's my local master branch I'm trying to fix up though.

**Comment by blowekamp** [comment]
> I know, it's my local master branch I'm trying to fix up though.

The most explicit command includes specifying only doing a fast forward merge:
```
git pull upstream master --ff-only
```

Frankly my repository are rather inconsistent these days with upstream/origin and master/main being common, so I am finding myself being explicit more frequently.

**Comment by Leengit** [comment]
> I know, it's my local master branch I'm trying to fix up though.

When you are in between pull requests, and if the main code repository is known as `upstream` according to `git remote -v` then you can get your master back in sync with 
```shell
git checkout master && git fetch upstream && git reset --hard upstream/master
```
If you want to update your personal fork as well, and if it is called `origin` according to `git remote -v` then you follow those with:
```shell
git push origin +master
```

**Pull request merged**
