### PR TITLE
ENH: enabling itkResampleImageTest2Streaming tests

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

### CODE REVIEW

**Comment by thewtex** [comment]
Rebasing on `master`...

**Comment by dzenanz** [comment]
All the errors seem to be related to slow/unstable network at Kitware earlier today. Force-pushing to trigger a rebuild.

**Comment by dzenanz** [comment]
The most likely explanation: the interpolators now had bigger region to work with, so some values at the edges of the streamed regions changed slightly. But I did not dig deep.

**Comment by romangrothausmann** [comment]
Hm, this I find odd because the reference images were created without employing streaming (to ensure that the streaming results are identical to the ones without streaming).
Did you use streaming for the creation of the new ones?

**Comment by dzenanz** [comment]
You are right. A==B and C==D, which means that streaming and non-streaming versions are the same. The differences came from somewhere else. I did not investigate from where.

**Pull request merged**
