### PR TITLE
COMP: added override keyword on a dtor

### PR DESCRIPTION
**Pull request by seanm**
I have a patch pending for upstream HDF5 too.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
Fine, thanks @seanm  For ITK, we did clang-tidy [modernize-use-override](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-override.html), which meant that whenever `override` was added, the `virtual` keyword would be removed from that member function declaration. Did you consider removing `virtual` in this case as well?

**Comment by seanm** [comment]
>Did you consider removing virtual in this case as well?

That is not the HDF5 convention.

**Review by thewtex — APPROVED** [review]

**Comment by N-Dekker** [comment]
> > Did you consider removing virtual in this case as well?
> 
> That is not the HDF5 convention.

OK, I see. Thanks!

**Review by N-Dekker — APPROVED** [review]
Thanks Sean! I would suggest a more specific commit subject line (as long as the 72 chars limit allows us), for example: 

    COMP: Add override specifier to the HDF5 `H5Location` destructor

But it's OK to me anyway.

**Pull request merged**
