### PR TITLE
ENH: Improve itkEuclideanDistancePointMetric coverage.

### PR DESCRIPTION
**Pull request by hjmjohnson**
Exercise basic object methods.

Exercise all Set/Get macros.

Refactor the test to accept input parameters to test all possible
conditions.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This is **not ready to be merged**: it should be rebased on master (e.g. `typedef`s around), and as said in the follow-up it required more work. So let's leave it unmerged, and I'll have a look as time permits. Thanks.

**Comment by jhlegarreta** [comment]
@hjmjohnson I've seen that you worked on this. Thanks. I just did a few more changes (used `typename` for the template arguments and used `std::stoi`) and rebased on master.

Let's merge it for keeping things moving forward, and some time in the future, when I am in a position to come back to the code coverage issues, I'll check the necessary additions to do.

**Comment by hjmjohnson** [comment]
@jhlegarreta Merging based on your comment.

**Comment by jhlegarreta** [comment]
Thanks @hjmjohnson. Moving forward !

**Comment by jhlegarreta** [comment]
Not seeing the CIs right now or where they were failing/how [InsightSoftwareConsortium/ITKExamples/#149](https://github.com/InsightSoftwareConsortium/ITKExamples/pull/149) would fix them, but thanks @thewtex .

I guess clang formatting will need to be applied as well.

**Comment by dzenanz** [comment]
It looks like this PR was merged a year ago. https://github.com/InsightSoftwareConsortium/ITKExamples/pull/149 adds an example, and does not attempt to fix anything. If you wanted to make follow-up improvements to this, a new PR is in order. Or am I misunderstanding something?

**Comment by jhlegarreta** [comment]
Sorry @dzenanz. My bad. Since it was being cross-ref'ed and given that I did not pay due attention to the status (`merged` vs. `open`), it looks like I was confused.

**Pull request merged**
