### PR TITLE
COMP: added vcl compiler detection for GCC 10.x

### PR DESCRIPTION
**Pull request by nolden**
Change-Id: Ie2ad7c15a9166aa553c92a1075f7e6cc7aa05155

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by nolden** [comment]
All unit tests on gcc 10.1.1 (Fedora 32) passed.

**Comment by dzenanz** [comment]
This is 4.13 branch. Probably that's why most CI tests failed due to infrastructure incompatibility.

**Comment by dzenanz** [comment]
@thewtex @blowekamp can either of you double-check and merge?

**Comment by nolden** [comment]
Thanks for the quick help!

**Comment by gdevenyi** [comment]
Any there any other commits on 4.13 to justify another release, or should I just cherry pick this commit for my project?

**Comment by dzenanz** [comment]
Yes, there was quite a number of commits since Feb 28th 2019 (4.13.2 release). As [4.13.3](https://github.com/InsightSoftwareConsortium/ITK/milestone/8) is now past its planned due date, it would be good if @thewtex pitched in with updated plans about it.

**Comment by dzenanz** [comment]
But it will likely wait for 5.1.0 announcement, and that is hung up on updating the remote modules to work with it?

**Comment by thewtex** [comment]
4.13.3 is planned for mid-June.

**Pull request merged**
