### PR TITLE
BUG: Fix GitHub community template syntax errors.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix GitHub community template syntax errors.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Let's see if this makes the trick.

I found some valuable examples here to enlighten the way:
https://github.com/PowerShell/PowerShell/tree/master/.github/ISSUE_TEMPLATE
https://github.com/PowerShell/PowerShell/issues/new/choose

A few comments:
- I removed the title. I finally understood what it means, and I think it is better to leave it blank to force users to fill it (although I ignore whether it can be left blank). But I'm open to suggestions.
- The quotes are not necessary in our case/for the strings were are using ([ref here](https://yaml.org/spec/1.2/spec.html#id2786942)). 
- Looking at the PowerShell repository we could add some more templates. I'm open to suggestions.
 - I am in two minds about changing the filenames to be all lower case. Any preferences?

Thanks.

**Comment by jhlegarreta** [comment]
**Not sure what's wrong with the PR template**. This PR does not modify the template, and thus no change is expected. 

Did a few tests in a mock private repository concerning the PR template (changed the case in case the PR template, in contrast to the issue templates, is case sensitive; removed the white
space at the beginning of the file) without finding the cause, though.

However, **the issue templates should be working with the changes introduced in this PR** according to the tests I did in the same private, mock repository.

A **feature** I found is that **enclosing the guidelines in the** `<!-- -->` **markup makes them visible only at the time the issue is being opened**, but not once they are open. So I think that is an improvement that is worthwhile. May be in another PR.

Also **I guess the PR template is only used when opening one from the web interface**, and not the command line. Not sure anything can be done about it.

Suggestions are welcome.

**Comment by jhlegarreta** [comment]
CDash failure looks like a false positive ?

**Comment by thewtex** [comment]
> * Looking at the PowerShell repository we could add some more templates. I'm open to suggestions.

The first two are nice. We could could have one that corresponds to each `type:XYZ` label...

> * I am in two minds about changing the filenames to be all lower case. Any preferences?

LESS SHOUTING sounds good to me :-).

**Comment by jhlegarreta** [comment]
Thanks for the review @thewtex !

The issue templates are working :tada: .

In a subsequent PR I will
- Change the case.
- Enclose the guidelines in `<!-- -->` so that they are only visible at the time the user writes the issue/PR.

And I will add a few more templates on a separate PR. Some may not fit well into a template. Will think about it/propose something.

Still two issues ahead:
- The PR template is still not being displayed. I run out of ideas to look at.
- Using the git alias to open the PR will not display the template. May be we can use the GitHub API to query and get it displayed?

**Comment by thewtex** [comment]
@jhlegarreta awesome!

Maybe the PR template is only used when files for the PR are edited through the web interface?

**Comment by jhlegarreta** [comment]
👍 

> Maybe the PR template is only used when files for the PR are edited through the web interface?

I'd dare to say that that will be the case unless we do dome fancy stuff to use the GitHub queries/API to get the PR templates when using our aliases to open a PR. Not sure it is even possible. We may want to have a look at it at a later time.

**Pull request merged**
