### PR TITLE
STYLE: Change some declarations to use trailing return type

### PR DESCRIPTION
**Pull request by dzenanz**
This fixes some of the compile errors on VS2017.
They were introduced around the time C++17 was enabled. The first error message was:

```log
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): error C2244: 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector': unable to match function definition to an existing declaration
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(473): note: see declaration of 'itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: definition
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(const itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::IndexType &) const'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: existing declarations
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(const itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::IndexType &) const'
m:\dashboard\itk\modules\numerics\statistics\include\itkHistogram.hxx(474): note: 'const Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::MeasurementVectorType &itk::Statistics::Histogram<TMeasurement,TFrequencyContainer>::GetMeasurementVector(Histogram<TMeasurement,TFrequencyContainer>::Sample<itk::Array<TValue>>::InstanceIdentifier) const'
```

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by N-Dekker** [comment]
Thanks @dzenanz, for doing a follow-up to PR #2780 commit c54ad6715a68570f9db14f002c239ec7ea06383d

Did you do same the regular expression as in c54ad6715a68570f9db14f002c239ec7ea06383d ?

    Find what: ^typename (\w+<.+>::)(.+)\r\n\1(.+)\r\n{\r\n
    Replace with: auto\r\n$1$3 -> $2\r\n{\r\n
    Filter: itk*.hxx
    [v] Match case
    (*) Regular expression

Honestly I don't really understand why theses errors reappear now, as I thought they were solved by PR #2780.

**Comment by N-Dekker** [comment]
> They were introduced around the time C++17 was enabled

Thanks but that was already 3 weeks ago, with pull request #3969 commit 513507e4c70172d5431563f89dc77c6bae1ad5b1 How frequently is VS2017 still being tested? And is there a reason to assume that the compile errors are related to enabling C++17?

**Comment by dzenanz** [comment]
No regex, I went by compiler error messages. VS2017 is tested nightly, and the errors started appearing on April 1st. I looked at the log and that was about time we flipped the switch on C++17, and you did a first round of refactoring. I did not narrow it down to a specific commit, though.

**Review by N-Dekker — APPROVED** [review]
I'm sorry that pull request #2780 appeared incomplete. For the sake of completeness, could you please rerun the regex, to ensure that no cases are forgotten this time? I think Core\Common\include\itkResourceProbe.hxx could still be included with this commit.

Approved anyway.

**Comment by N-Dekker** [comment]
Locally tested: those VS2017 compile errors do indeed appear with pull request #3969 commit 513507e4c70172d5431563f89dc77c6bae1ad5b1, the upgrade to C++17 😢 

Nevertheless it's just fine to use trailing return types in the cases addressed by your PR. It is also in accordance with the ITKSoftwareGuide:
- https://github.com/InsightSoftwareConsortium/ITKSoftwareGuide/pull/162

**Comment by N-Dekker** [comment]
OK, let's merge this one. The remaining use cases for trailing return types can always be addressed afterwards. Thanks @dzenanz

**Comment by dzenanz** [comment]
Follow-up in #4026.

**Pull request merged**
