### PR TITLE
STYLE: Install MINC's cmake files to lib/cmake

### PR DESCRIPTION
**Pull request by zbeekman**
- Install MINC's cmake files (`itkLIBMINCConfig.cmake` and
   `UseitkLIBMINC.cmake` into `lib/cmake` not `lib/`
 - This patch is required to get ITK accepted into the Homebrew package manager
 - See also https://github.com/Homebrew/homebrew-core/pull/39138

## PR Checklist
- [ ] [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] Adds the License notice to new files.
- [ ] Adds Python wrapping.
- [ ] Adds tests and baseline comparison (quantitative).
- [ ] [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by thewtex** [comment]
@zbeekman thanks for the contribution and for packaging ITK in Homebrew.

Please consider creating a pull request on the upstream [libminc](https://github.com/BIC-MNI/libminc) repository. Typically, we merge there first, then do a subtree merge into ITK.

CC: @vfonov @gdevenyi @iMichka

**Comment by zbeekman** [comment]
I was about to PR upstream, but it looks like @vfonov beat me to working on it, so I'll leave it alone.

**Comment by zbeekman** [comment]
@thewtex: It looks like upstream is patching MINC. Should I close this PR under the assumption that it will be included in the next MINC/ITK release? Please let me know how you think we should proceed.

**Comment by thewtex** [comment]
@vfonov can `develop-homebrew-style` be merged into `develop`? @zbeekman we will then pull in your changes from libminc and this PR can be closed.

**Comment by zbeekman** [comment]
LMK if you're minting a new release of ITK anytime soon. I'm going ahead and green-lighting the Homebrew PR but, so long as the MINC patch makes it into the next release, we'll need to remove the patch we're currently applying in Homebrew.

**Comment by zbeekman** [comment]
xref: https://github.com/Homebrew/homebrew-core/pull/39138

**Comment by thewtex** [comment]
Thanks, @zbeekman .

This has been merged into ITK `master`, and it will be in ITK 5.0 RC 2 (to be released within the week).

**Comment by zbeekman** [comment]
Great, thanks!

**Pull request closed without merging**
