### PR TITLE
COMP: Fix warning in PointSetToPointSetMetricv4

### PR DESCRIPTION
**Pull request by dyollb**
change index type to SizeValueType in functor for ParallelizeArray
also change start/end index type to SizeValueType.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed), itkEuclideanDistancePointSetMetricRegistrationTest.cxx is sufficient to reproduce issue
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
The commit needs to have `COMP: ` prefix. Prefixes are not necessary for GitHub pull requests (and are frequently absent for multi-commit PRs). Can you update and force push?

**Comment by dyollb** [comment]
> The commit needs to have `COMP: ` prefix. Prefixes are not necessary for GitHub pull requests (and are frequently absent for multi-commit PRs). Can you update and force push?

@dzenanz Sorry. How do I "Please rewrite commits to fix the errors listed above"? I made the changes directly via browser in the github code editor.

**Comment by dzenanz** [comment]
There are a couple alignment issues (using GitHub UI bypasses commit hook which applies the code style). Details [here](https://github.com/InsightSoftwareConsortium/ITK/pull/1820/checks?check_run_id=671050644) (also accessible via details link in the above list of checks).

**Comment by dyollb** [comment]
*action:ApplyClangFormat*

**Comment by dzenanz** [comment]
Unfortunately, this does not work for PRs from forks, only from branches in the main repo.

**Comment by dyollb** [comment]
@dzenanz will this be merged into the 5.1 release? thanks

**Comment by dzenanz** [comment]
You could make a new PR into the `release` branch, with this same patch. As 5.1.0 is already tagged, it would go into 5.1.1, sometime in the future.

**Comment by thewtex** [comment]
This has been merged into the `release` branch for inclusion in 5.1.1.

**Pull request merged**
