### PR TITLE
ENH: Enable HDF5_ENABLE_THREADSAFE

### PR DESCRIPTION
**Pull request by blowekamp**
This may improve concurrent reading in python.

https://docs.hdfgroup.org/hdf5/v1_12/_m_t.html

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Is any performance hit expected from turning this on?

**Comment by blowekamp** [comment]
> Is any performance hit expected from turning this on?

Reading the linked documentation this option added a mutex lock for global variables, and per-thread error reporting. Adding a mutex lock should not have any measurable impact for ITK's usage of HDF5 for IO.

**Review by thewtex — APPROVED** [review]
👍 🚀

**Comment by dzenanz** [comment]
@blowekamp is this ready for merging?

**Pull request merged**
