### PR TITLE
Update vnl

### PR DESCRIPTION
**Pull request by phcerdan**

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]

**Comment by dzenanz** [comment]
I think this broke the installed version of ITK. I am now running into below error when compiling [Seg3D](https://github.com/dzenanz/Seg3D/tree/itk5migration) at 386b258.

M:\Dev\Seg3D-vs19sb\Externals\Install\ITK_external\include\ITK-5.2\itkVector.h(23,10): fatal error C1083: Cannot open include file: 'vnl/vnl_vector_ref.h': No such file or directory (compiling source file M:\Dev\Seg3D\src\Core\DataBlock\ITKImageData.cc)

**Comment by phcerdan** [comment]
This is an upstream problem, introduced by a recent refactor of CMake functions. Reported: https://github.com/vxl/vxl/issues/801

**Comment by phcerdan** [comment]
Should we wait for upstream to revert/fix this, or do we fix it in ITK? The commit `master~4` of vnl works fine.

**Comment by dzenanz** [comment]
> Should we wait for upstream

I don't know how long it will take. Maybe propose a PR which updates to `master~4`? And if they are fast enough, update to the fixed commit?

**Comment by phcerdan** [comment]
Solved upstream, PR incoming.

**Pull request merged**
