### PR TITLE
ENH: Add probot-stale GitHub bot configuration

### PR DESCRIPTION
**Pull request by thewtex**
This is the configuration for the probot-stale GitHub App:

  https://probot.github.io/apps/stale/

that automatically close stale Issues and Pull Requests that tend to accumulate during a project.

### CODE REVIEW

**Comment by phcerdan** [comment]
I agree with @jhlegarreta, the automatic comment after a period of inactivity is great, but closing issues and PR's seems like too much. Not strongly opinionated against it though.

**Comment by hjmjohnson** [comment]
I respectfully (but completely) disagree with @jhlegarreta & @phcerdan :).  

- Keeping the most important tasks front and center is really important.
- long lists of stale/inactive issues/tasks consume an inordinate amount of resources (resources spent trying to ignore outdated items).
- The items can be re-opened and commented on.  In order to keep an item open for a complete year only requires a single stake owner to add "Still important" comment once every 3 months.  If no stakeholder is willing to write a single word in an issue or pull request every 3 months, then it is highly likely that the effort of filtering out that task/PR during other duties exceeds the likelihood of the task getting completed.

This is my 2 cents, but projects that are good at identifying what is currently relevant and prioritizing those items often perform better.

**Comment by dzenanz** [comment]
I agree with Hans that inactive things should be close if no one is even willing to comment infrequently. And we can find a list of items closed due to being stale by filtering by label.

**Comment by phcerdan** [comment]
That makes sense @hjmjohnson. Although, there are some issues that go to a different category. They do not require immediate action but maybe deal with structural or more long term changes, some are open, unsolved questions. Commenting on those is usually unnecessary, nothing new to be added, but the issue hasn't disappeared or staled. I see there are flags: `pinned`, `security` in the example, that can be used to not close these.

Getting an issue closed just because it has been ignored, or no more time has been put into it... The issue is still there. I guess it depends on the workflow of the maintainers, and what they consider an issue. Is an issue something that has to be taken care of? Or can an issue be a conversation or tracking about some topic? You are the maintainers receiving the PR's, you decide the workflow!!

**Comment by thewtex** [comment]
I also do not like closing issues that are actually outstanding, but I can understand the value of removing clutter and prioritizing. As I understand it, the bot should add a `status:Backlog` label, so we know why an issue is closed, and we can still filter and search for these issues. Let's try it, and see how it goes. Maybe Marie Kondo will feature our GitHub repository in one of her books someday :jp: :sparkle: :joy:

**Pull request merged**
