### PR TITLE
Parallelize ContourExtractor2DImageFilter

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
This now always fails test 5. Maybe you could take over @Leengit?

**Comment by Leengit** [comment]
I've ironed out all the bugs but one.  The handy `ConstantBoundaryCondition` functionality sets a default value for pixels outside of the _image_, but that's not what we need.  We want to be able to set a default value for pixels outside the  _region_ being processed.  I'll work on that soon.  If you want to take a look ... see 0da296e69f33bef8f9e1aabdafb489e496f1ef05,

**Comment by Leengit** [comment]
@dzenanz would you be willing to take another turn at this?  The code checked into 9fc6864b592db672463f7c407c0ace8d25d33c7f is pretty close to done, but I see two issues.

1. We are copying the input region to be its own image even in the case that it already is all of its image.  (Look for '!!!' in itkContourExtractor2DImageFilter.hxx, lines 304-314)  I suspect that there is an easy way to check for this condition, but I don't know it.
2. The iterator loop for the `ConstShapedNeighborhoodIterator<InputImageType, BoundaryConditionType> it` skips its last element -- it processes exactly 19 of its 5×4 cases.  What's going on with that?  (Look for '!!!' in itkContourExtractor2DImageFilter.hxx.)  In another thread, @thewtex asks whether we could instead use `ShapedImageNeighborhoodRange` -- I haven't looked at that.

**Comment by dzenanz** [comment]
I could take a turn at this, but probably not this week due to work on another project.

**Comment by Leengit** [comment]
I have submitted a competing pull request (#2384) for a number of reasons explained there.  Ultimately we'll want to merge only one of these pull requests, but in the meantime we can cherry pick from each other, etc.

**Comment by dzenanz** [comment]
Closing in favor of #2384.

**Pull request closed without merging**
