### PR TITLE
BUG: Fix reference counts for HDF5 DataSet assignment operator

### PR DESCRIPTION
**Pull request by Leengit**
Address Issue #2288.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Is this a change from upstream? If not, please submit it upstream, too.

**Comment by Leengit** [comment]
> Is this a change from upstream? If not, please submit it upstream, too.

I will submit it upstream next, though I will first wait for the all clear from CDash and reviewers here.

**Comment by Leengit** [comment]
The [CDash](https://open.cdash.org/index.php?project=Insight&begin=2021-03-22&end=2022-03-21&filtercount=1&showfilters=1&field1=revision&compare1=63&value1=179b01e0aa69241a3443217ea271a3b1477c6d04)board is green.  I have submitted Pull Request https://github.com/HDFGroup/hdf5/pull/503 to the upstream source.

**Comment by Leengit** [comment]
The upstream source uses different clang formatting.  I have updated this pull request to match the upstream formatting.

**Review by thewtex — APPROVED** [review]
Nice @Leengit !

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
