### PR TITLE
MetaIO 2024-07-03 (d269b397)

### PR DESCRIPTION
**Pull request by dzenanz**
Code extracted from:

    https://github.com/Kitware/MetaIO.git

at commit d269b3972910919ad22f2b179a13c189b176deef (master).

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by aylward — APPROVED** [review]
LGTM!

**Review by thewtex — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]

**Comment by dzenanz** [comment]
I now notice this PR wasn't merged via merge commit, messing up update script's logic for future updates. @bradking what is the best way to fix it?

**Comment by bradking** [comment]
If you still have the original PR branch, merge it to `master` by hand.  It shouldn't bring any changes, but should put history structure in a state that works for future updates.

**Comment by dzenanz** [comment]
If I do that, then run the update script, the script picks up the wrong commit as base:
Screenshot 2024-07-15 11 02 37

**Comment by dzenanz** [comment]
I think that highlighted commit is the correct one to use as the base for an update. Maybe that is so because there were no changes to MetaIO since?

**Comment by bradking** [comment]
We need the committer date on your original branch to be newer than the squashed commit.  I manufactured that history locally and pushed a merge to `master` that should fix this.

**Comment by dzenanz** [comment]
Thank you, that worked. I created a new PR with a minor update: #4778.

**Pull request merged**
