### PR TITLE
ENH: Move Discrete Gaussian, Hessian ImageFunction's out of Review

### PR DESCRIPTION
**Pull request by thewtex**
Mature at this point.

These need to go into the ITKImageIntensity module instead of
ITKImageFunction because of their dependency on
itk::RescaleIntensityImageFilter.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
Looks like these ImageFunction's have been in Review for more than 13 years already, right? Is there a specific reason to move them out of Review right now?

**Comment by dzenanz** [comment]
We would like to completely eliminate `Review` module, by putting its contents into appropriate other modules. We decided to do it incrementally, as people had time and enthusiasm for it. And this is another step on that path.

**Comment by N-Dekker** [comment]
> We would like to completely eliminate `Review` module, by putting its contents into appropriate other modules. We decided to do it incrementally, as people had time and enthusiasm for it. And this is another step on that path.

Ah, thanks for explaining @dzenanz! So then, should they still be reviewed anyway? Could it be that some of them are obsolete now, and may just be removed?

**Comment by dzenanz** [comment]
The typical behavior was to turn on review module, because it had many frequently used classes. By now, we have moved most of them to proper places, and perhaps removed some. We probably should not remove any more, but part of moving the class to appropriate place is evaluating whether it is needed, and if unclear, cross-link the possibly redundant classes via "See also" in the documentation. Ideally, also add/improve testing when doing the move.

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
