### PR TITLE
STYLE: Add missing `<< indent` insertions to `PrintSelf` implementations

### PR DESCRIPTION
**Pull request by N-Dekker**
`PrintSelf` should usually produce an indentation for each data member.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
@dzenanz That's the way it was originally intended, right? Inserting an `insert` for each printed member, right?

**Comment by dzenanz** [comment]
Inserting an `indent` 😄

**Comment by N-Dekker** [comment]
> Inserting an `indent` 😄

Well, you know what I mean, for each member, the _intention_ was an _insertion_ of an _indentation_, right?

**Comment by dzenanz** [comment]
You wrote
> Inserting an insert

instead of `Inserting an indent`. But yes, I agree, what you propose in this PR is what was intended.

**Comment by N-Dekker** [comment]
> You wrote
> 
> > Inserting an insert
> 
> instead of `Inserting an indent`.

Fixed! 😸

**Comment by N-Dekker** [comment]
This is just a "STYLE" PR (rather than "BUG"), right? Obviously the PR is likely to affect (_correct_, I would say) the user output.

**Review by dzenanz — APPROVED** [review]

**Comment by jhlegarreta** [comment]
> This is just a "STYLE" PR (rather than "BUG"), right? Obviously the PR is likely to affect (correct, I would say) the user output.

Definitely `STYLE`. It does not fix any runtime crash or incorrect result.

Thanks for doing this @N-Dekker. Merging.

**Review by jhlegarreta — APPROVED** [review]

**Pull request merged**
