### PR TITLE
STYLE: Move `DCMTK` test baselines to `IO` folder

### PR DESCRIPTION
**Pull request by jhlegarreta**
Move `DCMTK` test baselines to the module's `Baseline` folder to improve
the organization and scope, and in order to reduce clutter at the
`Testing` folder level.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
There is no consistent criterion for some modules (i.e. having their input and baseline data in their specific folder vs. the general baseline folder), so let me know if it is preferable for the baselines to dwell in a folder within the module.

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
Generally, it is preferrable to have the inputs and baselines in the module folder. This improved organization makes things easier to find and move content when required.

**Comment by jhlegarreta** [comment]
> Generally, it is preferrable to have the inputs and baselines in the module folder. This improved organization makes things easier to find and move content when required.

:+1: done in 60a30e9.

**Review by thewtex — APPROVED** [review]
Thanks @jhlegarreta !

**Pull request merged**
