### PR TITLE
ENH: Add Azure Pipelines script for nightly code coverage

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
@thewtex  If you are in favor of this, please create a new build which uses this file, and give it a manual test against "refs/557/head". Then we can resolve the differences with the local azure.cmake and dasboard/azure.cmake, and merge that and test again.

**Comment by blowekamp** [comment]
Here is the test build I did:
https://dev.azure.com/SimpleITK-DevOps/SimpleITK/_build/results?buildId=276

**Comment by thewtex** [comment]
@blowekamp This is great! :champagne: 

Here's the build:

  https://dev.azure.com/itkrobotcoverage/ITKCoverage/_build/results?buildId=3&view=logs

Could you please push the `AddAzureNightlyCoverage` to the *InsightSoftwareConsortium/ITK* repository to facilitate testing? It would not find `refs/557/head` or `refs/pulls/557/head`.

**Comment by blowekamp** [comment]
Update patch, created patch for dashboard branch. Should be good to go.

**Comment by blowekamp** [comment]
I have push the branch to the `InsightSoftwareConsortium/ITK` repo as requested.

**Comment by blowekamp** [comment]
You can also try a manual build with "refs/pull/557/head"

**Comment by thewtex** [comment]
Queued!

 https://dev.azure.com/itkrobotcoverage/ITKCoverage/_build/results?buildId=4

**Comment by blowekamp** [comment]
That looks like it was successful.

**Comment by blowekamp** [comment]
@thewtex This patch looks good to merge to get coverage back on our dashboard with the proper azure pipelines configuration done.

**Comment by thewtex** [comment]
@blowekamp nice!

Since we will have a difficult time keeping nightly builds online, could it be enabled for `master` and `release*` merges?

**Comment by blowekamp** [comment]
Yes that would work.

This could be part of a separate pipeline configuration with the "batch" option which does more aggressing testing, that what is done for every merge/pr. This would imply renaming the configuration file to something like "AzurePipelinesBatch.yml". This is at least my line of thinking with SimpleITK now.

**Comment by blowekamp** [comment]
@thewtex I think this is ready do go.

**Pull request merged**
