### PR TITLE
DOC: fix MutexLock-related broken links in the migration guide

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Review by jamesobutler — APPROVED** [review]

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
@dzenanz in the future, please capitalize the subject line per our style guidelines, i.e. *fix* -> *Fix*. This is important for changelog generation.

**Comment by dzenanz** [comment]
I will try to remember it.

**Comment by jamesobutler** [comment]
I think you could use something like https://github.com/marketplace/commitcheck here in the repo. Slicer uses it as it is a regexp search of the commit message.

**Comment by thewtex** [comment]
@jamesobutler cool! Do you know what regex Slicer uses?

**Comment by jamesobutler** [comment]
Unfortunately I do not. I think it is configured through a page on CommitCheck's domain rather than a public facing config file. @jcfr was the one who I remember modified it once for Slicer so he should know.

Of course there might be another GitHub app that could enforce the same type thing with a public facing config that would be easier to change.

**Comment by jcfr** [comment]
To integrate with GitHub,  we use commit check. Here is the configuration:

image

and is currently enabled for this repos:

image

On the workstation side, the check is implemented here:

https://github.com/Slicer/Slicer/blob/be10a167f70d7f574173ad42ca3a99d24ca32f3d/commit-msg#L73-L115

**Comment by jcfr** [comment]
We could probably update the regex from :

```
(BUG|COMP|DOC|ENH|PERF|STYLE)\: \w+
```

to 

```
(BUG|COMP|DOC|ENH|PERF|STYLE)\: [A-Z]\w+
```

**Pull request merged**
