### PR TITLE
STYLE: Replace `new` by C++14 `std::make_unique`

### PR DESCRIPTION
**Pull request by N-Dekker**
According to Clang-Tidy `modernize-make-unique`:
https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-unique.html

C++ Core Guidelines, March 11, 2021, R.23: Use make_unique() to make unique_ptrs
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rr-make_unique

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]
Very Nice!

**Comment by N-Dekker** [comment]
Honestly, even though I mentioned Clang-Tidy `modernize-make-unique`, I mostly did the code changes manually. Clang-Tidy Visual Studio integration didn't work very smoothly today, on my laptop 🤔 I tried both Clang Power Tools (https://clangpowertools.com) and the Visual Studio "Code Analysis" Clang-Tidy option (https://docs.microsoft.com/en-us/cpp/code-quality/clang-tidy?view=msvc-160)

**Comment by N-Dekker** [comment]
itkPyBufferMemoryLeakTest keeps failing, on ITK.macOS.Python (Azure.Mac-1622805395877): https://open.cdash.org/viewTest.php?onlyfailed&buildid=7266522 That's unrelated to the C++14 upgrade, right?

**Comment by hjmjohnson** [comment]
@N-Dekker  I hope so.  It's failing on all the PR's recently clogging up the system.

**Pull request merged**
