### PR TITLE
COMP: Fix DCMTK unused CMake variable warning

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
Do you get annoyed by Mac file format warning when compiling with DCMTK enabled?

**Comment by blowekamp** [comment]
I don't believe I have enchanted the "Mac file format warning". I was just addressing this warning:
https://open.cdash.org/viewBuildError.php?type=1&buildid=6275919

**Comment by dzenanz** [comment]
The error message looks like this:
_In project ITKIODCMTKHeaderTest1, file C:\Dev\ITK-2019\Modules\ThirdParty\DCMTK\ITKDCMTK_ExtProject-build\config\include\dcmtk\config\arith.h, line 1: Warning C4335: Mac file format detected: please convert the source file to either DOS or UNIX format_

**Comment by blowekamp** [comment]
@dzenanz What compiler are you using to get that message?

Looks like a format/encoding issue that should be address upstream in DCMTK.

**Comment by dzenanz** [comment]
This happens with VS 2019. I suspect that we need a newer version of DCMTK. I bet that this annoying warning has been addressed meanwhile.

**Pull request merged**
