### PR TITLE
Add Python wrapping for PhasedArray3DSpecialCoordinatesImage

### PR DESCRIPTION
**Pull request by dzenanz**
This is essentially a migration of https://github.com/KitwareMedical/ITKUltrasound/pull/232 from Ultrasound remote module to here. It involved some non-trivial reorganization. It is also a prettified version of #4099.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5

### CODE REVIEW

**Review by tbirdso — APPROVED** [review]
Looks great!

**Review by thewtex — APPROVED** [review]
@dzenanz awesome!!

Could you please check a build of ITKPythonPackage, adjusting the repository and hash here:

https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/dc6a18600233ac69a8f42b7489e4edf6a5d8883a/CMakeLists.txt#L90-L93

before merging to ensure that there are not any build errors or wrapping warnings. The package has other wrapping options enabled, and this is a good check for the type combinations enabled here.

@tbirdso ITK 5.4rc01 has been tagged, I am resolving a few wrapping issues. This will be included in 5.3rc02.

**Comment by dzenanz** [comment]
Following the Windows section of [wheel building instructions](https://github.com/InsightSoftwareConsortium/ITK/blob/v5.4rc01/Documentation/Maintenance/Release.md#generate-release-itk-python-wheels), I invoked building via `C:\P\IPP>C:\Python310-x64\python.exe ./scripts/windows_build_wheels.py  --py-envs 310-x64 --no-cleanup 1> ../build2.log 2>&1`, for the two tags, before and after the changes here (build logs below).

As far as I can tell, these changes did not introduce new errors or warnings. As even the first build did not finish without errors, I am not absolutely certain. Taking a closer look at the logs, there are reassuring entries related to phased array, the last one of which is:
```log
-- Installing: C:/P/IPP/_skbuild/win-amd64-3.10/cmake-install/.//itk/itkPhasedArray3DSpecialCoordinatesImagePython.py
```
Full build logs:
[before.log](https://github.com/InsightSoftwareConsortium/ITK/files/12028889/build.log)
[after.log](https://github.com/InsightSoftwareConsortium/ITK/files/12028890/build2.log)

I think we can merge this.

**Comment by dzenanz** [comment]
I am building once more locally, I will merge if all goes well.

**Pull request merged**
