### PR TITLE
ENH: Update to newer third-party update script from CMake

### PR DESCRIPTION
**Pull request by bradking**
Use the CMake `Utilities/Scripts/update-third-party.bash` as of commit
`693f4c70ff`.  Manually preserve ITK's change from commit 5dccc2207e
(BUG: Do not gpg sign third party updates, 2018-11-19, `v5.0b02~82^2~1`).

### CODE REVIEW

**Comment by bradking** [comment]
@thewtex this needs to be merged to both `release` and `master`.  It's needed to make third-party updates easier.  See the trouble encountered in #2290 for an example.

**Comment by seanm** [comment]
Thanks for the fix!

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
@bradking thanks!

Merging to `master` now -- we will release 5.2 RC 2 over the next few days, and I will update `release` at that time.

**Comment by dzenanz** [comment]
This was merged into `release` branch, as that was the target of the PR. I will merge it into master too.

**Pull request merged**
