### PR TITLE
ENH: add a convenience function WriteImage

### PR DESCRIPTION
**Pull request by dzenanz**
Inspired by #2102 and https://github.com/dzenanz/ITKMorphologicalContourInterpolation/commit/a9ac128f57078cb7c71d1abacd1ce8fce02f1c96.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Review by hjmjohnson — APPROVED** [review]

**Comment by blowekamp** [comment]
Please consider placing these procedural methods into a sub-namespace of itk.

Also consider just using the std::string methods. C strings can implicitly be converted to std::string.  So the raw C ptr is just for  efficiency (?), but this a convince function for code that should not be time critical, so the burden of the extra methods out ways the potential enhancement.

**Comment by N-Dekker** [comment]
It seems to me that the `const char *` overloads aren't necessary, as @blowekamp said.

**Comment by dzenanz** [comment]
Good point Brad! I will also wait for review from Niels. Hans merged it too fast.

**Comment by N-Dekker** [comment]
> So the raw C ptr is just for efficiency (?), but this a convince function for code that should not be time critical, so the burden of the extra methods out ways the potential enhancement.

I agree. By the way, if the performance penalty of creating an `std::string` would be a serious problem (not in this case, I think) C++17 introduces `std::string_view`, which is more lightweight than `std::string`. That's for later, possibly...  😃

**Comment by N-Dekker** [comment]
> Please consider placing these procedural methods into a sub-namespace of itk.

Of course, that is why I originally proposed defining the function as a static member function of `ImageFileWriter<>`. https://github.com/InsightSoftwareConsortium/ITK/pull/2102 So that it wouldn't look like a function without a home 😺  But I'm not really opposed to having it as a free function at `itk` namespace level, if that's what you want. I have to say it is quite convenient to have it at `itk` namespace.

**Comment by hjmjohnson** [comment]
> Good point Brad! I will also wait for a review from Niels. Hans merged it too fast.

Sorry,  I'm just trying to keep the forward momentum.  This topic had many discussions and I thought it represented a good step forward.  

BTW:  I agree with the proposed changes to drop `const char *`.  The std::string_view would be a great candidate for macro.

```
# a macro to take advantage of newer C++ standards when available
#if C++17 
   using ITK_STRING_VIEW=std::string_view
#else
   using ITK_STRING_VIEW=std::string
#endif
```

**Comment by N-Dekker** [comment]
Technically I wouldn't think that an overload for non-const `TImage *` should be necessary, when there is already an overload for `const TImage *`.  Did you encounter any case where the non-const `TImage *` overload appeared necessary?

**Comment by N-Dekker** [comment]
It looks like the `const SmartPointer<const TImage>` overloads may also be removed, as the compiler may deduce the constness of `TImage` automatically for the `SmartPointer<TImage>` overload. (For example, `TImage` could be deduced to `const itk::Image<int>`.)

**Comment by dzenanz** [comment]
Without non-const overloads there are compile errors:
```text
4>itkImageRandomIteratorTest2.cxx
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkImageRandomIteratorTest2.cxx(85): error C2672: 'itk::WriteImage': no matching overloaded function found
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkImageRandomIteratorTest2.cxx(85): error C2784: 'void itk::WriteImage(const itk::SmartPointer<const TImage>,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const itk::SmartPointer<const TImage>' from 'itk::SmartPointer<itk::Image<PixelType,2>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(260): note: see declaration of 'itk::WriteImage'
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkImageRandomIteratorTest2.cxx(85): error C2784: 'void itk::WriteImage(const TImage *,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const TImage *' from 'itk::SmartPointer<itk::Image<PixelType,2>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(249): note: see declaration of 'itk::WriteImage'
4>itkSymmetricSecondRankTensorImageReadTest.cxx
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageReadTest.cxx(87): error C2672: 'itk::WriteImage': no matching overloaded function found
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageReadTest.cxx(87): error C2784: 'void itk::WriteImage(const itk::SmartPointer<const TImage>,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const itk::SmartPointer<const TImage>' from 'itk::SmartPointer<itk::Image<MatrixPixelType,3>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(260): note: see declaration of 'itk::WriteImage'
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageReadTest.cxx(87): error C2784: 'void itk::WriteImage(const TImage *,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const TImage *' from 'itk::SmartPointer<itk::Image<MatrixPixelType,3>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(249): note: see declaration of 'itk::WriteImage'
4>itkSymmetricSecondRankTensorImageWriteReadTest.cxx
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageWriteReadTest.cxx(72): error C2672: 'itk::WriteImage': no matching overloaded function found
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageWriteReadTest.cxx(72): error C2784: 'void itk::WriteImage(const itk::SmartPointer<const TImage>,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const itk::SmartPointer<const TImage>' from 'itk::SmartPointer<itk::Image<TensorPixelType,2>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(260): note: see declaration of 'itk::WriteImage'
4>C:\Dev\ITK-git\Modules\Core\Common\test\itkSymmetricSecondRankTensorImageWriteReadTest.cxx(72): error C2784: 'void itk::WriteImage(const TImage *,const itk::ITK_STRING_VIEW &,bool)': could not deduce template argument for 'const TImage *' from 'itk::SmartPointer<itk::Image<TensorPixelType,2>>'
4>c:\dev\itk-git\modules\io\imagebase\include\itkImageFileWriter.h(249): note: see declaration of 'itk::WriteImage'
```

**Comment by N-Dekker** [comment]
Is `itk::ITK_STRING_VIEW` already there? How is it defined?

**Pull request merged**
