### PR TITLE
ENH: Add `itk::GrayscaleGrindPeakImageFilter` class test

### PR DESCRIPTION
**Pull request by jhlegarreta**
Add `itk::GrayscaleGrindPeakImageFilter` class test.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not sure if the output image is meaningful. Maybe someone more familiar with the filter can chime in and comment. Thanks.

**Review by dzenanz — APPROVED** [review]
The [result](https://data.kitware.com/api/v1/file/hashsum/sha512/fa7eb2b24ade1f2f29348858d65146a0864f60903810ce2a330776b4f74ef29fa62a4d390ba7b1116a60e954462f3e46ae316b389903ab3438240e73272ab548/download) looks plausible, even if weird.

**Comment by dzenanz** [comment]
I also think that somebody more familiar with grayscale morphology should look.

**Comment by blowekamp** [comment]
> I also think that somebody more familiar with grayscale morphology should look.

The output looks correct to me. The correctness can be verified: for any threshold [N, max] all connected components are connected to the image boundary. I checked this visually with Fiji.

**Comment by jhlegarreta** [comment]
@blowekamp thanks for checking ! :100:.

**Pull request merged**
