### PR TITLE
COMP: seems all use of kwiml is no longer actually needed, removed it.

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by seanm** [comment]
@hjmjohnson @dzenanz @thewtex I didn't yet `git rm` all of kwiml, but seems we can...

**Review by dzenanz — APPROVED** [review]

**Comment by seanm** [comment]
Oh, I didn't mean for this to be merged so fast...

So I guess you concur that nothing needs kwiml?  Is that surprising or not?  I guess I can just delete the folder in ThirdParty too then?

**Comment by dzenanz** [comment]
I don't remember hearing of KWIML before this, so I assume nothing needs it 😄

**Comment by dzenanz** [comment]
Maybe if was needed before we could rely on C++11. But now we require C++14, so I guess try deleting it and if nothing breaks we will know we don't need it 😄

**Comment by seanm** [comment]
@dzenanz see https://github.com/InsightSoftwareConsortium/ITK/pull/2982

**Pull request merged**
