### PR TITLE
WIP: Move default [con/de]strutor to .h (part 2)

### PR DESCRIPTION
**Pull request by hjmjohnson**
Use C++11 = default in .h file rather than
definition in .hxx.

This work is a continuation of work started in Core/Common
subdirectory, but now is applied to all the non-third party
directories

Co-authored-by: Mathew J Seng <mathew-seng@uiowa.edu>

### CODE REVIEW

**Comment by thewtex** [comment]
CI found some issues.

**Comment by hjmjohnson** [comment]
@thewtex Thanks. I'm struggling to replicate this error.   I do not see it on my Mac or Linux builds.  It feels like a compiler error for some specific compiler version.  

I'm slowly rolling back small changes to identify the source of the problem.

**Comment by dzenanz** [comment]
I tested this PR on my Mac, and it was clean.

```bash
zukic-mini:ITK-rwd dzenan$ cmake --version
cmake version 3.10.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
zukic-mini:ITK-rwd dzenan$ clang --version
Apple LLVM version 10.0.0 (clang-1000.11.45.5)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
zukic-mini:ITK-rwd dzenan$ ninja --version
1.8.2
```

**Comment by hjmjohnson** [comment]
@dzenanz The failure is now on the windows build.  There are 96 new warnings, but I have been having difficulty in making an environment that replicates those warnings.

**Comment by dzenanz** [comment]
I can reproduce these warnings. I will look into it over the next days.

**Comment by hjmjohnson** [comment]
@dzenanz Thank you!  That is a huge relief.

**Comment by dzenanz** [comment]
I looked at this [post](https://discourse.itk.org/t/extern-templates-to-reduce-build-time/1105/2?u=dzenanz), but it did not help me come up with a better [solution](https://stackoverflow.com/questions/44160467/warning-c4661no-suitable-definition-provided-for-explicit-template-instantiatio) than disabling the warning. We might want to tackle #543 at some point before releasing ITKv5.

**Comment by blowekamp** [comment]
I thought that destructors where best defined in compiled implementation files due to polymorphism and multiple instance of the symbols issues.

**Comment by dzenanz** [comment]
I don't know why the warning doesn't occur in [`TransformIOBase`](https://discourse.itk.org/t/extern-templates-to-reduce-build-time/1105/2?u=dzenanz), but does in `ObjectToObjectOptimizerBase`. Anyway, suppressing the warning was the best thing I came up with.

**Comment by hjmjohnson** [comment]
@dzenanz Thanks for looking into this.  This "trivial change" has turned into a bit more of an issue than I originally thought.  I'd like to spend a little time breaking this issue into the "parts that work as expected" and the much smaller "part that introduced an error".

Hopefully, if we isolate the small bit of code that is causing issues, we can better see what is going on.

**Comment by blowekamp** [comment]
@Hans Please consider also breaking out the changes which removed the destructors from the compiled cxx files. In addition to my vague mentioned symbols issue there is also the potential in increase object files size, library sizes and increase demands on compilation with the duplicated code from the header decloration.

**Comment by maekclena** [comment]
I had one error while compiling this branch on macOS:
```
itkTransformFileWriterSpecializations.cxx:42:3: error:
definition of explicitly defaulted destructor
```
The error is that the destructor is already implemented as default in the header so it cannot be redefined elsewhere.
Once I deleted the destructor in the cxx and was able to compile without issues.

**Comment by dzenanz** [comment]
@hjmjohnson can you revive this PR? It would be a waste not to push this through!

**Comment by dzenanz** [comment]
Or did you split off a subset of this into another PR?

**Comment by hjmjohnson** [comment]
@dzenanz  I did split off a subset of this.  I'd like the rest of this to work as well, but I need to prioritize my time right now.

**Comment by blowekamp** [comment]
Moving the default constructors to be inlined for templated classes is a good thing.

However, for compiled classes, especially the "core" its classes such as itk:Object, itk::DataObject etc., there is a downside of more bloated code and compiled libraries. Additionally, there are some platform dependent polymorphism issues which can occur with shared libraries and inlined destructors due to duplicated symbols.

**Comment by hjmjohnson** [comment]
The remaining parts of this PR should *NOT* be committed based on observations by Brad Lowekamp.

"Moving the default constructors to be inlined for templated classes is a good thing.

However, for compiled classes, especially the "core" its classes such as itk:Object, itk::DataObject etc., there is a downside of more bloated code and compiled libraries. Additionally, there are some platform dependent polymorphism issues which can occur with shared libraries and inlined destructors due to duplicated symbols. For these cases it is not clear to me what is the advantage of this approach."

**Pull request closed without merging**
