### PR TITLE
ENH: Testing update from github.com/vxl/vxl

### PR DESCRIPTION
**Pull request by Leengit**
This pull request is for testing whether Pull Request https://github.com/vxl/vxl/pull/829/ will break ITK.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Comment by Leengit** [comment]
The code changes for this pull request are the same as the underlying pull request https://github.com/vxl/vxl/pull/829.  (However, the breakdown into commits is different. Does that matter?)  Do we mark this as ready for review, ..., and then merge it into ITK directly?

Or is there some other way that this should be done?  Will the merging of https://github.com/vxl/vxl/pull/829 into vxl initiate a process that will ultimately lead to merging into ITK?

**Comment by Leengit** [comment]
Pull Request https://github.com/vxl/vxl/pull/829 has been merged into vxl, so I am marking the present pull request as ready for review for ITK.

**Comment by Leengit** [comment]
I just force-pushed to mirror other changes that were made to the vxl repository.

**Comment by dzenanz** [comment]
This is usually updated by running [UpdateFromUpstream](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/VNL/UpdateFromUpstream.sh) script.

**Comment by Leengit** [comment]
> This is usually updated by running [UpdateFromUpstream](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/VNL/UpdateFromUpstream.sh) script.

I replaced my edits with the use of that script, and have force-pushed.

**Review by dzenanz — APPROVED** [review]

**Comment by Leengit** [comment]
I just re-ran `Modules/ThirdParty/VNL/UpdateFromUpstream.sh` using the current master branch and force-pushed.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
