### PR TITLE
WIP: Deprecate OrientImageFilter

### PR DESCRIPTION
**Pull request by blowekamp**
The anatomical direction enums used by this class are the oposite of the DICOM specification. Depricated to be replaced by the DICOMOrientImageFilter for consistent orientation notation.

Relates to #4788

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
Isn't `OrientImageFilter` a general class?  Why should it be tied to DICOM?

Looking at my own code, I see we use `OrientImageFilter` when reading MINC and NIfTI files too...

**Comment by issakomi** [comment]
> The anatomical direction enums used by this class are the oposite of the DICOM specification

Could you, please, send a link where 3-letter enums are defined in DICOM standard?

I think it is about terminology (`from` vs `to` notation), ITK space is the same as DICOM space.

RAI-codes are widely used, e.g. in MetaIO headers, in ITK-Snap, I use them too.
I know that Slicer uses LPS-terminology (but, AFAIK, works perfectly with actual orientation filter and enums) and in SimpleITK already exists [DICOMOrientImageFilter](https://simpleitk.org/doxygen/latest/html/classitk_1_1simple_1_1DICOMOrientImageFilter.html) with LPS notation.

MetaImage header:
meta

ITK-Snap:
snap

My app (I heavily use actual enum internally):
aliza

**Comment by gdevenyi** [comment]
Perhaps this is a side discussion but @issakomi I would argue that both those screenshots incorrectly describe what the orientation means.

I think it is far more clear to describe these orientations as describing the positive direction, i.e. RAS = +X+Y+Z, the direction of increasing coordinate (index) value is Right(X), Anterior(Y), Superior(Z)

http://www.grahamwideman.com/gw/brain/orientation/orientterms.htm

**Comment by seanm** [comment]
I have observed that some people understand RAI to mean the origin is at the right-anterior-inferior corner, and others understand it to mean that the axes point *towards* the right, anterior, and inferior.  :(

**Comment by issakomi** [comment]
> Perhaps this is a side discussion but @issakomi I would argue that both those screenshots incorrectly describe what the orientation means.

I didn't introduced these enums. It is breaking change. I am out of the discussion. Do whatever you want.

P.S. BTW, your MINC IO is completely brocken and loads with flipped axes.

**Comment by gdevenyi** [comment]
> > Perhaps this is a side discussion but @issakomi I would argue that both those screenshots incorrectly describe what the orientation means.
> 
> I didn't introduced these enums. It is breaking change. I am out of the discussion. Do whatever you want.
> 
> P.S. BTW, your MINC IO is completely brocken and loads with flipped axes.

Not mine. And I'm well aware: https://github.com/InsightSoftwareConsortium/ITK/pull/147

**Comment by issakomi** [comment]
> Not mine. And I'm well aware: #147

OK

**Comment by hjmjohnson** [comment]
The genesis of the OrientImageFilter was to assist with dealing with Analyze (pre-nifti) naming and orientation.  The publicly available documentation available was often fragmented and incomplete.  

I would prefer to keep this OrientImageFilter for historical reasons, and because some users still depend upon it.  Improving the documentation, and adding a documentation warning would be my preferred approach.  

I would also be supportive of minimizing the use of this class internal to ITK.

**Comment by blowekamp** [comment]
> I would prefer to keep this OrientImageFilter for historical reasons, and because some users still depend upon it. Improving the documentation, and adding a documentation warning would be my preferred approach.
> 
> I would also be supportive of minimizing the use of this class internal to ITK.

Please also see: PR #4791

The proposal to to replace it with the DICOMOrientImageFilter and the DICOMOrientation enums and keep legacy conversion from the SpatialOrientation enums to the DICOMOrientation class ( which has build it conversion between ITK direction matrix, enums, legacy enums, and strings (DICOM).

By moving the class to deprecated it allows users to migrate in the next 5+ years. And the tricky part of chasing the enums to the DICOM part has an even longer time period.

It is incredible confusing having documentation describing ITK as having DICOM compatible LPS coordinate systems, but the build in tools describe it as "RAI". I am hoping to use ITKv6 as an opportunity to improve the situation.

**Comment by issakomi** [comment]
> I think it is far more clear to describe these orientations as describing the positive direction, i.e. RAS = +X+Y+Z, the direction of increasing coordinate (index) value is Right(X), Anterior(Y), Superior(Z)

@gdevenyi Thanks. I have added actually both for the next release and there is (was) explanation "right. to left", etc.

o2

I am afraid v5 will be the last version I use, for a long time.

**Comment by seanm** [comment]
>The proposal to to replace it with the DICOMOrientImageFilter and the DICOMOrientation enums

I'm still not understanding what DICOM has to do with anything...

I've just read over itkOrientImageFilter.h and I don't see anything about DICOM.  It looks like a general structured grid reorientation class to me. Such a thing is useful. I use it in code that doesn't deal with DICOM files at all.

**Comment by blowekamp** [comment]
Unfortunately, this conversation has been split over 3 topics. Here issue #4788 and PR #4791. I am closing this PR, to help focus the conversation on issue #4788.

**Comment by dzenanz** [comment]
> I'm still not understanding what DICOM has to do with anything...

ITK used "origin" codes (RAI) instead of "to" codes (LPS). The "to" codes are used by DICOM standard, and are more widespread. To distinguish the "to" codes from "origin" codes, the "to" convention needs some name. In the other PR, Brad suggested that name be "DICOM", as in DICOMOrientation etc. Of course, orientation is general, and most medical image formats support orientation metadata, not just DICOM image format. Hopefully this explanation is helpful.

**Pull request closed without merging**
