### PR TITLE
ENH: Include DiffeomorphicDemonsRegistrationFilter wrapping

### PR DESCRIPTION
**Pull request by tbirdso**
ENH: Copied `DiffeomorphicDemonsRegistrationFilter.wrap` from Nonunit to PDEDeformable module so that it is built with ITK, and added Python test.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Assuming it builds without issue, it is probably better to move the file (delete it from the old location). In case someone searches later, two identical files would be confusing not knowing which one has effect and whether both are required.

**Review by dzenanz — CHANGES_REQUESTED** [review]
I meant to request changes 😄

**Comment by tbirdso** [comment]
Changes complete, I moved rather than copied the `.wrap` file from `Nonunit/Review` and confirmed the solution built without issues.

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
@dzenanz Should I have permissions to complete this PR (and others) when changes are approved and tests pass?

**Comment by dzenanz** [comment]
Yes, the author of a PR should be able to merge it (I prefer "rebase and merge") once the PR is approved by one of the maintainers and CI finishes with green status.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
