### PR TITLE
ENH: Switch to zlib-ng for modern maintained zlib codebase

### PR DESCRIPTION
**Pull request by gdevenyi**
See #416 

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by gdevenyi** [comment]
Todo:
- [ ] Modify how the Cmake is called to enable zlib-compat mode
- [ ] Cleanup the included files to be minimized
- [ ] Tests

**Comment by gdevenyi** [comment]
I think I've done the update properly. At this point the build fails at:
```
    152 In file included from /home/gdevenyi/scratch/itk-build/Modules/ThirdParty/ZLIB/src/itk_zlib.h:37,
    153                  from /home/gdevenyi/scratch/ITK/Modules/ThirdParty/NIFTI/src/nifti/znzlib/znzlib.h:60,
    154                  from /home/gdevenyi/scratch/ITK/Modules/ThirdParty/NIFTI/src/nifti/znzlib/znzlib.c:24:
    155 /home/gdevenyi/scratch/ITK/Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib.h:226:9: error: expected ‘;’ before ‘const’
    156   226 | Z_EXTERN const char * Z_EXPORT zlibVersion(void);
    157       |         ^~~~~~
```

So this may depend on https://github.com/InsightSoftwareConsortium/ITK/issues/1924 as it appears there's some bugs with NIFTI's usage of zlib?

**Review by dzenanz — COMMENTED** [review]
Good progress!

**Comment by dzenanz** [comment]
GDCM also fails to compile:
```text
[2371/5310] Building CXX object Modules/ThirdParty/GDCM/src/gdcm/Source/Common/CMakeFiles/gdcmCommon.dir/gdcmDeflateStream.cxx.o
FAILED: Modules/ThirdParty/GDCM/src/gdcm/Source/Common/CMakeFiles/gdcmCommon.dir/gdcmDeflateStream.cxx.o 
/usr/bin/c++  -IModules/ThirdParty/Expat/src/expat -I/home/vsts/work/1/s/Modules/ThirdParty/Expat/src/expat -IModules/ThirdParty/ZLIB/src -I/home/vsts/work/1/s/Modules/ThirdParty/ZLIB/src -I/home/vsts/work/1/s/Modules/ThirdParty/ZLIB/src/itkzlib-ng -IModules/ThirdParty/GDCM -IModules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/Common -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/MessageExchangeDefinition -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition -IModules/ThirdParty/GDCM/src/gdcm/Testing/Source/Data -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Testing/Source/Data -I/home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Utilities -mtune=generic -march=corei7 -Wall -Wcast-align -Wdisabled-optimization -Wextra -Wformat=2 -Winvalid-pch -Wno-format-nonliteral -Wpointer-arith -Wshadow -Wunused -Wwrite-strings -funit-at-a-time -Wno-strict-overflow -Wno-deprecated -Wno-invalid-offsetof -Woverloaded-virtual -Wstrict-null-sentinel  -w -fno-ipa-cp-clone -Os -DNDEBUG -fPIC -std=c++14 -MD -MT Modules/ThirdParty/GDCM/src/gdcm/Source/Common/CMakeFiles/gdcmCommon.dir/gdcmDeflateStream.cxx.o -MF Modules/ThirdParty/GDCM/src/gdcm/Source/Common/CMakeFiles/gdcmCommon.dir/gdcmDeflateStream.cxx.o.d -o Modules/ThirdParty/GDCM/src/gdcm/Source/Common/CMakeFiles/gdcmCommon.dir/gdcmDeflateStream.cxx.o -c /home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmDeflateStream.cxx
In file included from Modules/ThirdParty/ZLIB/src/itk_zlib.h:37:0,
                 from /home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Utilities/gdcm_zlib.h:22,
                 from /home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/Common/zipstreamimpl.h:65,
                 from /home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmDeflateStream.h:17,
                 from /home/vsts/work/1/s/Modules/ThirdParty/GDCM/src/gdcm/Source/Common/gdcmDeflateStream.cxx:14:
/home/vsts/work/1/s/Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib.h:226:1: error: 'Z_EXTERN' does not name a type; did you mean 'ZEXTERN'?
 Z_EXTERN const char * Z_EXPORT zlibVersion(void);
 ^~~~~~~~
 ZEXTERN
/home/vsts/work/1/s/Modules/ThirdParty/ZLIB/src/itkzlib-ng/zlib.h:256:1: error: 'Z_EXTERN' does not name a type; did you mean 'ZEXTERN'?
 Z_EXTERN int Z_EXPORT deflate(z_stream *strm, int flush);
```
Maybe you need to turn on some more backward compatibility options, in addition to `set(ZLIB_COMPAT ON)`?

**Comment by gdevenyi** [comment]
COMPAT is on, otherwise nothing would work :-) they have a whole new API otherwise

Historically there's a lot of "wrong" ways to use the zlib API that might be disallowed now. I'm gone camping now, I will return to this and Niftilib this weekend.

**Comment by gdevenyi** [comment]
Includes fixed.

Linked fails out now:
```
Consolidate compiler generated dependencies of target ITKCommon2TestDriver
[ 51%] Linking CXX executable ../../../../bin/ITKCommon2TestDriver
/usr/bin/ld: cannot find -litkzlib
collect2: error: ld returned 1 exit status
Modules/Core/Common/test/CMakeFiles/ITKCommon2TestDriver.dir/build.make:1388: recipe for target 'bin/ITKCommon2TestDriver' failed
make[2]: *** [bin/ITKCommon2TestDriver] Error 1
CMakeFiles/Makefile2:14507: recipe for target 'Modules/Core/Common/test/CMakeFiles/ITKCommon2TestDriver.dir/all' failed
make[1]: *** [Modules/Core/Common/test/CMakeFiles/ITKCommon2TestDriver.dir/all] Error 2
Makefile:165: recipe for target 'all' failed
make: *** [all] Error 2
```

Need to check if the renaming internally to itkzlib-ng has broken something (either because incomplete or something hard-coded)

**Comment by gdevenyi** [comment]
It looks like the integrated zlib has been running with a bunch of custom patches:
https://gitlab.kitware.com/third-party/zlib/-/compare/master...for%2Fitk-v1.2.11-2017-01-15-cacf7f1d

Will need to figure out which of these changes are needed now, or can be achieved in other ways, and maybe upstream some.

**Comment by thewtex** [comment]
@gdevenyi thanks so much for making this happen! :medal_sports: 

We will need to still apply the symbol name mangling on top of upstream. This is required to prevent symbol conflicts when a binary links both itk-zlib-ng and zlib-ng.

The CMake configuration ports likely need to be made on top of upstream, at least in some cases, so files are installed into the ITK module location, etc.

**Comment by dzenanz** [comment]
> symbol name mangling

It would make some sense to integrate this into upstream. Other projects could possibly benefit from this (at least VTK, probably some others too).

**Comment by gdevenyi** [comment]
> > symbol name mangling
> 
> It would make some sense to integrate this into upstream. Other projects could possibly benefit from this (at least VTK, probably some others too).

Ok, opened an issue here https://github.com/zlib-ng/zlib-ng/issues/1025, I'll see if I can figure out how to add it for review.

**Comment by dzenanz** [comment]
Closing in favor of #2708.

**Pull request closed without merging**
