### PR TITLE
BUG: Fix regression in PolygonSpatialObject::IsInsideInObjectSpace

### PR DESCRIPTION
**Pull request by dzenanz**
This is a slightly cleaned-up clone of #2422.

### CODE REVIEW

**Comment by dzenanz** [comment]
Force-push sets the intensity difference tolerance to zero (from default two) to make sure the test fails without the fix. If default inside value of 255 was used, this would not have been necessary. If someone doesn't mind making the change and regenerating the test baseline they are welcome to update my branch.

**Review by jhlegarreta — COMMENTED** [review]
Maybe the commit could be drawn from the `master` branch once it gets merged? (not sure how the sync is handled when it is required)

**Comment by dzenanz** [comment]
This commit merges cleanly into master, as PR #2454 shows.

**Review by jhlegarreta — APPROVED** [review]

**Comment by dzenanz** [comment]
The failures are unrelated. Merging.

**Pull request merged**
