### PR TITLE
STYLE: Miscellaneous comment cleanup

### PR DESCRIPTION
**Pull request by jhlegarreta**
- STYLE: Prefer double forward slashes for within-method body comments
- STYLE: Remove commented output stream messages
- STYLE: Remove unnecessary within-method body comments

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not intended to be comprehensive. I was having a look at these files for other reasons.

**Review by N-Dekker — APPROVED** [review]
Thanks Jon. Honestly I would rather have two commits: One that that converts from old C-style `/* ... */` to modern C++ style `// ...` and one that removes unnecessary comments. But no problem, approved 👍

**Comment by jhlegarreta** [comment]
> Thanks Jon. Honestly I would rather have two commits: One that that converts from old C-style /* ... */ to modern C++ style // ... and one that removes unnecessary comments. But no problem, approved 👍

Will see what I can do.

**Comment by jhlegarreta** [comment]
> Will see what I can do.

Done.

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
