### PR TITLE
ENH: itktiff: Update source tree layout to match upstream

### PR DESCRIPTION
**Pull request by bradking**
Re-import tiff 4.0.3 from upstream using our modern history structure.
Retain local edits made by ITK since 4.0.3 was imported previously.

Issue: #4953

### CODE REVIEW

**Comment by bradking** [comment]
Do: check

**Comment by bradking** [comment]
This needs to be merged to `master` without any rebasing or squashing.

**Comment by hjmjohnson** [comment]
@thewtex Should we move forward even though the ITK.Pixi-Cxx (windows-2022) is failing on all PRs?

**Comment by blowekamp** [comment]
I see the following build error:
/MANIFESTFILE:Modules\Core\TestKernel\src\CMakeFiles\itkTestDriver.dir/intermediate.manifest Modules\Core\TestKernel\src\CMakeFiles\itkTestDriver.dir/manifest.res" failed (exit code 1169) with the following output:
itktiff-6.0.lib(tif_luv.c.obj) : error LNK2005: __ucrt_int_to_float already defined in itktiff-6.0.lib(tif_aux.c.obj)

itktiff-6.0.lib(tif_color.c.obj) : error LNK2005: __ucrt_int_to_float already defined in itktiff-6.0.lib(tif_aux.c.obj)

**Comment by bradking** [comment]
@blowekamp I'm not able to reproduce that error on Windows, and CI is happy too.  Can you reproduce it in a fresh build tree?

**Comment by blowekamp** [comment]
> @thewtex Should we move forward even though the ITK.Pixi-Cxx (windows-2022) is failing on all PRs?

@thewtex Are the only configuration setting on the Pixi build here: https://github.com/InsightSoftwareConsortium/ITK/blob/master/pyproject.toml#L26-L34 

I don't see the job published to CDash, but the configuration is here:
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/11862520836/job/33062081900

I don't see anything particularly different about this build that might be causing this error.

**Comment by thewtex** [comment]
> @thewtex Should we move forward even though the ITK.Pixi-Cxx (windows-2022) is failing on all PRs?

It's not failing on all PR's. It has mostly been successfully passing:

https://github.com/InsightSoftwareConsortium/ITK/actions/workflows/pixi.yml?query=branch%3Amaster

It passed on this recent PR:

https://github.com/InsightSoftwareConsortium/ITK/actions/runs/11860511746/job/33055924587?pr=4956

**Comment by thewtex** [comment]
> Are the only configuration setting on the Pixi build here: https://github.com/InsightSoftwareConsortium/ITK/blob/master/pyproject.toml#L26-L34

These are the ITK configuration settings. Also worth noting is that it is using the [conda-forge `cxx-compiler` package, version 1.8.0](https://github.com/InsightSoftwareConsortium/ITK/blob/34e53a8c58a448f54ef35a4d12599c0d8e61b650/pixi.lock#L558).

**Comment by thewtex** [comment]
> @blowekamp I'm not able to reproduce that error on Windows, and CI is happy too. Can you reproduce it in a fresh build tree?

It's failing in CI, with fresh builds.

**Comment by thewtex** [comment]
A few Git bisects may helpful to find the underlying issue.

**Comment by bradking** [comment]
What is special about the ITK.Pixi Windows build that's different from the ITK.Windows build?  The only options I see in the logs are `-DCMAKE_BUILD_TYPE=RelWithDebInfo` and `-DBUILD_TESTING=ON`.  That works fine for me locally.

**Comment by blowekamp** [comment]
Nice Job tracking that down!

**Pull request merged**
