### PR TITLE
ENH: Python wrapping for v4 Optimizers

### PR DESCRIPTION
**Pull request by tbirdso**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
It is probably best to squash all these commit into one `ENH: ` commit.

**Comment by tbirdso** [comment]
@dzenanz  Should I squash commits on this branch or create a new PR?

**Comment by dzenanz** [comment]
Squash commits on this branch, then force-push.

**Review by thewtex — APPROVED** [review]
Well done! ⭐

**Review by dzenanz — APPROVED** [review]

**Comment by tbirdso** [comment]
The dashboard shows that [all tests passed but the ITK.Linux.Python build failed](https://dev.azure.com/itkrobotlinuxpython/ITK.Linux.Python/_build/results?buildId=3876&view=results). @thewtex @dzenanz do you have any insight into what to do here?

**Comment by dzenanz** [comment]
You can see the errors/warning on the [ITK dashboard](https://open.cdash.org/index.php?project=Insight). Search for builds containing `PR2259` in the build name. This is the relevant entry: https://open.cdash.org/viewBuildError.php?type=1&buildid=6994735

**Comment by tbirdso** [comment]
After updating LBFGSOptimizerBaseHelperv4 wrapping the branch is now ready to be merged. @dzenanz @thewtex

**Review by dzenanz — APPROVED** [review]
Adding Python wrapping for a class is frequently simple. But as you found out, not always :)

By incremental additions such as this, we will eventually achieve a complete Python wrapping of ITK.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
