### PR TITLE
ENH: Explicitly use Python 3.7 in Azure builds

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by thewtex** [comment]
I am guessing that the Azure machines installed Python 3.8, and `ninja` is only available for Python 3.7...

**Comment by hjmjohnson** [comment]
AH.  OK Thanks.

**Comment by hjmjohnson** [comment]
@thewtex FYI: mac failed.

**Comment by thewtex** [comment]
The macOS failure looks like an Azure hiccup -- I think it can be ignored.

I would like the other builds to finish so we verify that they work before merging.

**Comment by hjmjohnson** [comment]
@thewtex Other builds succeeded.  Can this be merged?

**Comment by hjmjohnson** [comment]
@thewtex @dzenanz This is holding up other patches.  Can it be merged yet?  

I need to rebase #555 and #547 on top of this to ensure that the windows builds work before merging.

**Comment by dzenanz** [comment]
The warnings are
```text
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so (found version "3.5.2") 
CMake Warning at Wrapping/Generators/Python/CMakeLists.txt:14 (message):
  Python executable ("3.7") and library ("3.5.2") version mismatch.
```
```text
-- Found PythonLibs: /usr/local/Frameworks/Python.framework/Versions/3.7/lib/libpython3.7m.dylib (found version "3.7.2") 
CMake Warning at Wrapping/Generators/Python/CMakeLists.txt:14 (message):
  Python executable ("3.7") and library ("3.7.2") version mismatch.
```
@thewtex should double check or fix before merging this.

**Comment by hjmjohnson** [comment]
All PR's are failing.  Is there any chance that the part of this patch that is needed for non-python build can be pushed forward?

Or can we move from ninja to make until this can be resolved?

**Comment by thewtex** [comment]
The warnings are a problem.... @jcfr is releasing wheels for Python 3.8 soon, which should fix our builds.

**Comment by hjmjohnson** [comment]
"soon" as in a few minutes, or "soon" as in the next few days?

**Comment by jcfr** [comment]
It is coming along, you can track progress at https://github.com/scikit-build/ninja-python-distributions/issues/20#issuecomment-468775762

**Comment by jcfr** [comment]
Generic plaform wheels that are ABI independent are now available, see https://pypi.org/project/ninja/1.9.0.post1/#files

**Pull request closed without merging**
