### PR TITLE
COMP: for compiling with perf enhancements

### PR DESCRIPTION
**Pull request by stnava**
This is what we needed for ANTs to build and link correctly.  @ntustison  FYI.   No urgency to merge.

### CODE REVIEW

**Comment by stnava** [comment]
@hjmjohnson fyi

**Comment by blowekamp** [comment]
Please find the following patch on Gerrit which addresses the annoying HDF5 warnings:
http://review.source.kitware.com/#/c/23783/

**Comment by blowekamp** [comment]
@stnava We are still using Gerrit for ITK. It looks like there are some important fixes here for ITK. Could you cherry-pick the relevant patches and create a patch on Gerrit?

**Comment by stnava** [comment]
yes - i will work on that - thanks for the hdf5 fixes.

brian

**Comment by thewtex** [comment]
These issues should be fixed in current ITK `master` :-)

**Pull request closed without merging**
