### PR TITLE
BUG: Fix `PythonVerifyGetOutputAPIConsistency` test on Windows

### LINKED ISSUE #3261: `PythonVerifyGetOutputAPIConsistency` failing on Windows
### Description

The `PythonVerifyGetOutputAPIConsistency` CDash test is failing in Windows Python CI. This may have been introduced by [https://github.com/InsightSoftwareConsortium/ITK/commit/c266651c33c2d57013fd0c32c126fa74dd51e6a6](https://github.com/InsightSoftwareConsortium/ITK/commit/c266651c33c2d57013fd0c32c126fa74dd51e6a6) and has been inconsistently observed in CI results.

### Steps to Reproduce

1. Build ITK Python wrappings
2. `ctest -C Release -R VerifyGetOutputAPIConsistency`

Or via Python terminal:
```py
>>> import itk
>>> from itk.support.base import load_factories
>>> load_factories('ImageIO')
>>> itk.force_load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\repos\ITK-build-unstable\Wrapping\Generators\Python\itk\support\init_helpers.py", line 116, in force_load
    getattr(itk, k)
  File "C:\repos\ITK-build-unstable\Wrapping\Generators\Python\itk\support\lazy.py", line 141, in __getattribute__
    value = namespace[attr]
KeyError: '_Num_base'
```

### Expected behavior

Force load succeeds

### Actual behavior

ITK fails to import `_Num_base` and other Windows-specific NumericTraits `std::` class wrappings

### Reproducibility

100%

### Versions

`main`

### Environment

Windows, Python 3.8

### Additional Information

Failure observed only when a `load_factories()` call is explicitly included before `force_load()`.

### PR DESCRIPTION
**Pull request by tbirdso**
#3156 introduced a Python mechanism for loading object factory overrides alongside modules at load time. `load_factories` is an implementation detail and may not be suitable to be called directly.

Issue #3261 exhibits an instance of this where a few templates such as `_Num_base` are not loaded correctly into the `itk` namespace when `load_factories` is called by the client program before other modules are loaded. Removing the `load_factories()` call and relying on `force_load()` to instead load in both modules and factories results in successful namespace population.

Resolves #3261.

## PR Checklist
- [x] Added test (or behavior not changed)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by tbirdso** [comment]
Note that this will address one of three test failures we are seeing in the ITK main branch, with the other two unrelated to factory changes: [CDash](https://open.cdash.org/viewTest.php?onlyfailed&buildid=7798279)

**Review by thewtex — APPROVED** [review]
Thanks for the CDash / CI attention @tbirdso !!

**Comment by tbirdso** [comment]
Checking `ITK.Linux` and `ITK.Windows` CI status shows that each check completed successfully but failed to POST results to Github due to "Internal Server Error". Perhaps more Github service issues today?

As all checks have passed I am moving forward with the merge.

**Comment by PranjalSahu** [comment]
Two checks failing on windows python for mesh serialization and pointset serialization.
Working on it.

**Comment by tbirdso** [comment]
@PranjalSahu I've also glanced through the serialization failures, they are due to inconsistencies in how we wrap `VectorContainer` across platforms and not directly due to any serialization issues. I've opened #3310 for discussion.

**Pull request merged**
