### PR TITLE
DOC: Spellcheck Filtering HXX and Video headers

### PR DESCRIPTION
**Pull request by dave3d**
Previously I fixed the spelling bugs in the ".h" files in Modules/Filtering.  Now I've gone through the ".hxx" header files.

Also I this PR fixes spelling bugs in the ".h" and ".hxx" files in Modules/Video.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by N-Dekker — APPROVED** [review]
Thanks, Dave!

**Comment by N-Dekker** [comment]
> Also I this PR fixes spelling bugs...

I this spelling bug as well 😸 And I would not call them "bugs" anyway. But no problem of course, thanks Dave!

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
Any clue about those kwrobot-v1 errors? Should they be fixed before merging this PR?

**Comment by dave3d** [comment]
> Any clue about those kwrobot-v1 errors? Should they be fixed before merging this PR?

I have no idea where that is coming from.  There's a SimpleITK PR that has the same type of error.

**Pull request merged**
