### PR TITLE
ENH: Download x86 clangformat on Darwin arm64

### PR DESCRIPTION
**Pull request by blowekamp**
Rosette 2 can be installed on OSX to enable emulation so that x86 executables can be run.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:+1: thanks @blowekamp

**Comment by blowekamp** [comment]
@dzenanz @thewtex I based this PR on the release branch. Think it should be merged into release too?

**Comment by thewtex** [comment]
@blowekamp yes, done!

**Comment by seanm** [comment]
Why test `CMAKE_HOST_SYSTEM_PROCESSOR` at all?

**Pull request merged**
