### PR TITLE
ENH: Add support for OPTIONAL_COMPONENTS

### PR DESCRIPTION
**Pull request by blowekamp**
Add support for find_package(ITK... OPTIONAL_COMPONENTS ITKModule).

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
I feel like this new feature should be documented elsewhere, too.

**Comment by dzenanz** [comment]
Software guide, release notes (when it is time for it) @thewtex. But both of these should come after this PR is merged.

**Comment by thewtex** [comment]
What is the behavior when an OPTIONAL_COMPONENT was not enabled?

**Comment by dzenanz** [comment]
I assume that the module was not liked to the project, but Brad can correct me if I am wrong.

**Comment by blowekamp** [comment]
> What is the behavior when an OPTIONAL_COMPONENT was not enabled?

Before if "OPTIONAL_COMPONENT" was then the component/itk module would be treated as required, and the find_package would fail.

When an optional component is requested but **not** enabled in the ITK build/install, then the ITK find package will still succeeds and the ITK_MODULES_ENABLED will not contain then missing component/itk module.

When an optional component is requested but **is** enabled in the ITK build/install, the the ITK find package succeeds and the ITK_MODULES_ENABLED contains the requested component/itk module. Along with the optional module CMAKE configuration being loaded.

A sample change in the SimpleITK configuration that this would enable is:

```
--if (GenericLabelInterpolator IN_LIST ITK_MODULES_ENABLED)
--  list(APPEND use_itk_modules GenericLabelInterpolator)
--endif()
--find_package(ITK COMPONENTS  REQUIRED ${use_itk_modules} )
++find_package(ITK REQUIRED COMPONENTS ${use_itk_modules} OPTIONAL_COMPONENTS GenericLabelInterpolator )
  
  add_library ( SimpleITKCommon ${SimpleITKCommonSource} ${SimpleITKAncillarySource} )
--sitk_target_use_itk (SimpleITKCommon PRIVATE ${use_itk_modules} )
++sitk_target_use_itk (SimpleITKCommon PRIVATE ${ITK_MODULES_REQUESTED} )
```

**Review by thewtex — APPROVED** [review]
Great!

**Pull request merged**
