### PR TITLE
STYLE: Replace `itk::NumericTraits<unsigned int>::OneValue()` with `1`

### PR DESCRIPTION
**Pull request by N-Dekker**
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/4460 commit 5d746cc0bc5efa6655580ee63c36cefde156a3c2
"STYLE: Replace `NumericTraits<unsigned int>::ZeroValue()` with `0U`"

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Does `1` vs `1u` make any difference?

**Comment by N-Dekker** [comment]
> Does `1` vs `1u` make any difference?

In practice, when you assign the value (`1` or `1u`) to a variable of a built-in type, it does not make a difference at all. So it's just a matter of style 😃

**Comment by blowekamp** [comment]
I am pretty sure at some point there was a compiler warning flag used that warned about conversions from int to unsigned int, and the draconian usage itk::NumericTraits was used to help determine where real conversion issues were occurring.

**Comment by N-Dekker** [comment]
itkOBJMeshIO.cxx does `m_NumberOfCellPixelComponents = 3` without `u` as well.

**Comment by N-Dekker** [comment]
If anyone insists on `1U`, that's OK to me as well, I can amend the commit if anyone wants to. I'm just _slightly_ in favor of `1`. Because of its simplicity 😃

**Comment by N-Dekker** [comment]
> I am pretty sure at some point there was a compiler warning flag used that warned about conversions from int to unsigned int, and the draconian usage itk::NumericTraits was used to help determine where real conversion issues were occurring.

Thanks for explaining, @blowekamp. Nowadays I think the main reason for using itk::NumericTraits would be to support pixel types in a generic way. Specifically, `itk::NumericTraits<PixelType>::OneValue()` returns `1` when the pixel type is int, while it returns `{1, 1, 1}` for an RGB pixel type.

**Comment by blowekamp** [comment]
> > I am pretty sure at some point there was a compiler warning flag used that warned about conversions from int to unsigned int, and the draconian usage itk::NumericTraits was used to help determine where real conversion issues were occurring.
> 
> Thanks for explaining, @blowekamp. Nowadays I think the main reason for using itk::NumericTraits would be to support pixel types in a generic way. Specifically, `itk::NumericTraits<PixelType>::OneValue()` returns `1` when the pixel type is `int`, while it returns `{1, 1, 1}` for an RGB pixel type.

The other case to consider is with itk::SizeType or std::std size type. The size of "long" and "long long" vary across systems and can change based on the word size for the architecture on some, but not other platforms.

**Comment by N-Dekker** [comment]
> > Nowadays I think the main reason for using itk::NumericTraits would be to support pixel types in a generic way. Specifically, `itk::NumericTraits<PixelType>::OneValue()` returns `1` when the pixel type is `int`, while it returns `{1, 1, 1}` for an RGB pixel type.
> 
> The other case to consider is with itk::SizeType or std::std size type. The size of "long" and "long long" vary across systems and can change based on the word size for the architecture on some, but not other platforms.

OK, but for a built-in integer type (or a typedef or _alias_ of a built-in integer type), `std::numeric_limits<T>` typically offers everything one may need. So in that case, I would prefer `std::numeric_limits<T>`, rather than `itk::NumericTraits<T>`.

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
