### PR TITLE
ENH: Adding VS2019 v142 AzurePipeline build

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
This PR is related to #1160 as it may be useful to test that PR on the v142 compiler in Release and or RelWithDebInfo configuration.

The configuration here is `Release` which I expect should not exhibit the bug referenced above.

It may be more useful to add additional VS builds to the `AzurePipelinesBatch.yml` so they get tested on merge, and don't hold up the CI of PRs. Comment welcome.

**Comment by dzenanz** [comment]
This looks ready to merge.

**Comment by blowekamp** [comment]
On the good side this demonstrate that VS2019 works in Release mode before the added flag.

Unfortunately, that change from Ninja to VS generator change the build time from ~2hrs to 3hrs, which is not acceptable for CI on PR. Perhaps adding '/MP' would help.

I will just move these build to the batch configuration.

**Comment by blowekamp** [comment]
I had a typo in the branch name, so a new PR has been created: #1169

**Pull request closed without merging**
