### PR TITLE
STYLE: Replace `std::bind` in ThreadPool::AddWork with lambda expression

### PR DESCRIPTION
**Pull request by N-Dekker**
Inspired by pull request https://github.com/SimpleITK/SimpleITK/pull/1994 commit https://github.com/SimpleITK/SimpleITK/commit/0dc078f88fbde2f773a9c09c4ad96f2d772725c6 "Use clang-tidy with modernize-avoid-bind", by Bradley Lowekamp (@blowekamp).

### CODE REVIEW

**Comment by dzenanz** [comment]
Let's see what CI says about this.

**Comment by N-Dekker** [comment]
@blowekamp What do you think? Do you like this PR?

FYI, Clang-Tidy (LLVM17.0.1) produced the following warning:

```
 ITK\Modules\Core\Common\include\itkThreadPool.h(92): warning: prefer a lambda to std::bind [modernize-avoid-bind]
   92 |       std::bind(std::forward<Function>(function), std::forward<Arguments>(arguments)...));
      |       ^

```

However, in this particular case, it wasn't able to fix the code. (Tidy-Fix didn't do it.) So I did it manually.

**Review by dzenanz — COMMENTED** [review]
I am fine with this as long as it works 😄

**Review by thewtex — APPROVED** [review]

**Comment by blowekamp** [comment]
Nicely done!

**Pull request merged**
