### PR TITLE
nifti 2023-09-11 (75180f77)

### PR DESCRIPTION
**Pull request by seanm**
Code extracted from:

    https://github.com/NIFTI-Imaging/nifti_clib.git

at commit 75180f776997bd161c5b231dfffb65e6385f5f93 (master).

### CODE REVIEW

**Review by dzenanz — CHANGES_REQUESTED** [review]
These updates should be done by running the appropriate update script, in this case https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/NIFTI/UpdateFromUpstream.sh. Do you mind doing that and force-pushing?

**Comment by seanm** [comment]
> These updates should be done by running the appropriate update script, in this case https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/NIFTI/UpdateFromUpstream.sh. Do you mind doing that and force-pushing?

That's how I generated this patch.  Does it seem otherwise?

**Comment by dzenanz** [comment]
It definitely seems otherwise. There should be at least two commits, update of nifti, and merge to master. Usually there is also a tag update commit. Your other PR, #4262, is a good example of that.

**Comment by dzenanz** [comment]
Closing in favor of #4269.

**Comment by seanm** [comment]
Weird. I swear I did the exact same here, but whatever. :)

**Pull request closed without merging**
