### PR TITLE
STYLE: Prefer Early Return

### PR DESCRIPTION
**Pull request by DVigneault**
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by DVigneault** [comment]
@dzenanz thanks for the review!

**Comment by DVigneault** [comment]
@dzenanz Thanks again for the review--let me know if there's anything else I should do to get this merged!

**Comment by dzenanz** [comment]
I was just giving people time to review it, as it came in on Friday.

**Comment by DVigneault** [comment]
@dzenanz No worries, and thanks!

**Pull request merged**
