### PR TITLE
ENH: Improve itk.imread error message when the input file doesn't exist

### LINKED ISSUE #3900: improve error message of `itk.imread` when the input file doesn't exist
### Description
`itk.imread` correctly raises an error when the input file doesn't exist,
but the error message is not very straightforward in some cases...

```py
Python 3.8.13 (default, Mar 28 2022, 06:16:26) 
[Clang 12.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import itk
>>> fixed_image = itk.imread("not_exist.nii.gz", itk.F)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/py38/lib/python3.8/site-packages/itk/support/extras.py", line 1275, in imread
    raise RuntimeError("No ImageIO is registered to handle the given file.")
RuntimeError: No ImageIO is registered to handle the given file.
```

### Expected behavior

error message could include a reason 'file doesn't exist', or raise `FileNotFoundError` instead

### Actual behavior

`RuntimeError: No ImageIO is registered to handle the given file.`

### Additional Information

itk 5.3.0

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #3900.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by dzenanz** [comment]
@thewtex I based this on `release` branch, in case we want to put it into the next patch release too.

**Comment by dzenanz** [comment]
@wyli does this fix #3900 for you?

**Review by tbirdso — APPROVED** [review]
Much clearer 👍

**Review by wyli — APPROVED** [review]
thanks @dzenanz!

**Review by jhlegarreta — APPROVED** [review]

**Pull request merged**
