### PR TITLE
COMP: Applied gtest PR 4025 to fix build with old clang

### PR DESCRIPTION
**Pull request by seanm**
From: https://github.com/google/googletest/pull/4025

### CODE REVIEW

**Comment by seanm** [comment]
@dzenanz

**Comment by dzenanz** [comment]
Would [updated GTest](https://github.com/InsightSoftwareConsortium/ITK/pull/3979) solve this issue for you?

**Comment by dzenanz** [comment]
#3979 was merged. Does that fix the problem for you? If not, please update this PR as it now has merge conflicts.

**Comment by hjmjohnson** [comment]
I do think this is superceeded by #3979 and can be closed.  @seanm  Thanks for poking this.  @dzenanz  Thanks for updating google test.

**Comment by seanm** [comment]
> #3979 was merged. Does that fix the problem for you?

We will see on cdash tomorrow...

**Comment by dzenanz** [comment]
If am reading the dashboard correctly, GTest compile failure is now gone.

**Comment by seanm** [comment]
> If am reading the dashboard correctly, GTest compile failure is now gone.

Only because it's much worse, it doesn't build at all:

https://open.cdash.org/build/8590216/configure

```
CMake Error at CMake/itkCompilerChecks.cmake:16 (message):
  Apple Clang 10.0.0 or later is required.
```

**Comment by dzenanz** [comment]
That is due to merging the PR which bumps required C++ version to 17 (from C++14). Maybe it is time to retire those builds?

**Pull request closed without merging**
