### PR TITLE
COMP: added missing HDF5 symbol mangling

### PR DESCRIPTION
**Pull request by seanm**
Building my own app against both vtk master and itk master results in link errors because both the libraries fail to mangle these 7 symbols.

### CODE REVIEW

**Review by N-Dekker — APPROVED** [review]
Thanks @seanm! Could it be that these HDF5 symbols were introduced with the upgrade from 1.10.7 to 1.12.1, pull request #2832 commit 621b4bd1617b3d56d6ba5ad749512d8a969b21f2 ?

Anyway, it's fine by me. 👍

**Review by hjmjohnson — APPROVED** [review]

**Comment by dzenanz** [comment]
All 7 of these symbols were removed by [PR2832](https://github.com/InsightSoftwareConsortium/ITK/pull/2832/commits/f21b8f9eaf7d6b703d168e40de1b286a4b511f4e#diff-ff21a10153dc41fdf05a04941f76a83d7a4b232d3049863f7db64f522d61e58fL482).

**Comment by seanm** [comment]
Yeah, it's hard to catch them all, because you really need to build all combinations of Debug + Release + Mac + UNIX + Window as some symbols exist only conditionally.

**Comment by hjmjohnson** [comment]
PR2832 generated a new set of mangled symbols from a blank slate. Perhaps we should merge the previous manglings with the new manglings (and also merge the VTK identified manglings too).  It probably does not hurt to have a superset of required manglings.

**Comment by seanm** [comment]
>It probably does not hurt to have a superset of required manglings.

Well, it sorta does, because it means you don't actually know how to generate the manglings from scratch and are declaring defeat. :)

**Pull request merged**
