### PR TITLE
ENH: Separate factory registration code to separate file

### PR DESCRIPTION
**Pull request by blowekamp**
Include cmake macros/functions to generate factory registration in
ITKConfig. This enable access to these method if UseITK.cmake is not
being used, which avoid directory wide properies being set.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
In commit message "This enable`s` access to these method if UseITK.cmake is not
being used, which avoid`s` directory wide proper`t`ies being set."

**Comment by blowekamp** [comment]
Ready for review. It would be good to get this in ITK for the next RC and release.

The added `itk_generate_factory_registration` is providing a good interface for SimpleITK to generate the factory registration managers as needed: SimpleITK/SimpleITK#1559

**Review by dzenanz — APPROVED** [review]
LGTM. @jcfr should review too.

**Review by tbirdso — APPROVED** [review]
LGTM (pending CI)

**Comment by blowekamp** [comment]
This PR is good to go IMHO. Please merge when ready...

**Review by hjmjohnson — APPROVED** [review]

**Comment by hjmjohnson** [comment]
@dzenanz in an ideal world,  I'd love @jcfr comments, but he will likely be overloaded when he returns, and it could be weeks before he has a chance to make this a priority.  I'd recommend making a good step forward with this PR, and we can revert later if @jcfr identifies a problem later.

I recommend we merge this now.

**Comment by blowekamp** [comment]
What is the release schedule? when will RC3 be tagged? This needs to be in before then?

**Comment by dzenanz** [comment]
I doubt RC3 will be tagged before Matt returns from vacation next week. I suggest we wait a day or two to give @lassoan a chance to review.

**Review by thewtex — APPROVED** [review]
@blowekamp thanks for working on this!

I am looking to tag RC 3 ASAP so merging now. @jcfr is in France, and he likely will not have time to test as mentioned, but we can still test it in other instances and follow up with improvements as needed.

**Comment by thewtex** [comment]
> I doubt RC3 will be tagged before Matt returns from vacation next week. 

Hopefully my vacation will involve getting a release candidate out, but we will see :-)

**Comment by dzenanz** [comment]
I guess this has broken remote modules, see e.g.: https://open.cdash.org/build/7678414/configure.

**Comment by blowekamp** [comment]
@dzenanz Is this building remote modules with ITK at the same time? There is no installation step performed on ITK here?

**Comment by dzenanz** [comment]
Correct. You can find the script(s) here: https://open.cdash.org/build/7678414/notes

**Comment by blowekamp** [comment]
See #3096 for follow up

**Pull request merged**
