### PR TITLE
DOC: Spell check remaining headers

### PR DESCRIPTION
**Pull request by dave3d**
Final spell checking pass of all the ".h", ".hxx", and ".py" files in ITK/Modules (excluding the ThirdParty sub-folder)

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dave3d** [comment]
The one spelling bug that I found that I didn't know how to fix was "oop" here:

https://github.com/InsightSoftwareConsortium/ITK/blob/c642a68a7572ea683c11e488bdab9f19a8c1dd37/Modules/IO/ImageBase/include/itkImageFileReader.hxx#L427

Any idea what's that comment supposed to say?

**Comment by dave3d** [comment]
> ```c++
> ```c++
> // we use std::copy_n here as it should be optimized to memcpy for
> // plain old data, but still is oop
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> I believe OOP = object oriented programming.
> The comment implies that proper copy constructors will be called if they exists.
> ```

OK, I'll add OOP to my dictionary then.

**Comment by dzenanz** [comment]
You could also expand that abbreviation, as someone else might not know what it stands for.

**Review by N-Dekker — APPROVED** [review]
Thanks again, Dave! 👍

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
