### PR TITLE
MINC update 20191003

### PR DESCRIPTION
**Pull request by vfonov**
* ENH: updated to the latest development branch of libminc

Incorporates changes for InsightSoftwareConsortium/ITK#1115 and BIC-MNI/libminc#94, BIC-MNI/libminc#96

### CODE REVIEW

**Comment by dzenanz** [comment]
It doesn't compile cleanly.

**Comment by vfonov** [comment]
hmm..  looks like it didn't pick up a new file...

**Comment by vfonov** [comment]
ping @seanm

**Comment by seanm** [comment]
LGTM

**Pull request merged**
