### PR TITLE
Gdcm update 2023 05 24

### PR DESCRIPTION
**Pull request by seanm**
Just sync from upstream.

### CODE REVIEW

**Comment by dzenanz** [comment]
@malaterre should we ignore these [ghostflow warnings](https://github.com/InsightSoftwareConsortium/ITK/pull/4053/checks?check_run_id=13743018210)? Or can they be fixed?

**Comment by seanm** [comment]
@dzenanz there were also warnings when I committed about some files sizes:

```
The path 'Modules/ThirdParty/GDCM/src/gdcm/Source/DataDictionary/privatedicts.xml' has size 1033 KiB, greater than allowed 1024 KiB.
The path 'Modules/ThirdParty/GDCM/src/gdcm/Source/InformationObjectDefinition/Part3.xml' has size 2282 KiB, greater than allowed 1024 KiB.
```

These messages don't make sense to me because the max size is already increased for those files in `Modules/ThirdParty/GDCM/src/gdcm/.gitattributes`

I had to commit bypassing hooks.

**Comment by seanm** [comment]
> To avoid that, max size should be increased in GDCM repository already

What I'm saying is: it already is: https://github.com/malaterre/GDCM/blob/master/.gitattributes

**Comment by dzenanz** [comment]
@bradking do you have an explanation for this?

**Comment by bradking** [comment]
I can't reproduce the local hook failure.  I created a branch from commit `6adfd15ab92` and ran `./Modules/ThirdParty/GDCM/UpdateFromUpstream.sh`.  It produced a merge commit with content identical to the branch here.

Note that the ghostflow check failure in this PR is unrelated.  The encoding error should probably be fixed in GDCM upstream first.

**Comment by seanm** [comment]
>I can't reproduce the local hook failure.

Weird. But I guess not a big deal. Like I said, I just bypassed the hook and committed manually. Maybe it only occurs with certain git versions or something...

**Comment by seanm** [comment]
Those non-ASCII characters are not present in GDCM master.  @malaterre maybe you need to cherry pick something into the release branch?

**Comment by dzenanz** [comment]
Let's give @malaterre a few more days to pitch in.

**Comment by seanm** [comment]
I believe those files with non-ASCII chars aren't really even used in ITK...

**Comment by dzenanz** [comment]
Hopefully, the next update will fix them.

**Comment by dzenanz** [comment]
PR #4061 is a follow-up update.

**Pull request merged**
