### PR TITLE
ENH: Increase coverage

### PR DESCRIPTION
**Pull request by jhlegarreta**
Improvements concerning testing and a few related enhancements:
- Fix an RTTI bug concerning a `Superclass` name.
- Remove a duplicate include file.
- Print all member variables in a number of classes.
- Use `itkBooleanMacro` to set the boolean ivar values to On/Off.
- Increase code coverage of a number of classes.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Follow-up of the latest comments in PR #2286:

- Commented the failing commands; will uncomment them in separate PRs once we are able to merge this.
- Removed the baseline comparison for the classes for which I have some concerns on the appropriateness of the used data in the test.

Will push these outstanding things and some others as time permits, but will allow myself some time. I might suggest some of them as GitHub issues so as not to have them as a blocking element on a PR, and given that I might not find the time to push them forward.

**Review by dzenanz — APPROVED** [review]
Code looks good, pending fixing of the two failing tests.

**Review by hjmjohnson — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
Thank you @jhlegarreta !

**Comment by jhlegarreta** [comment]
A short note related to this PR:

Thanks for all the patience. I'm well aware that I put quite of a burden on the CI derived from some oversights in the commits. I'm sorry for the noise.

I had noticed that the coverage increased noticeably (89.86% to 89.96%) between Feb, 15 and Feb, 16. It did not look like a hiccup since it was stable for a few days days. Not sure if it was intended or was a nice side effect of the commits merged between those days, but that was good news.

And finally, this PR, standing on the shoulders of all previous efforts, made it possible to break the 90% barrier for the `Aggregate Coverage` build, and make the `Code Coverage` be over 88%, also breaking into the +1300 threshold for files with complete coverage. The aggregate coverage has been stable around 90.09% for a few days now.

So great effort from the maintainers and the community to push towards a tool that is better tested. I remember Luis' call to the mailing list in 2014 to increase the coverage :-). I think he would be glad to know this.

**Pull request merged**
