### PR TITLE
WIP: DO NOT MERGE: ENH: Handle IPP/IOP/PixelSpacing for SC

### LINKED ISSUE #4109: GDCM ignores image geometry in secondary captures
### Description

Secondary capture images can optionally have ImageOrientationPatient and PixelSpacing fields, but GDCM currently forces the orientation to identity and looks for NominalScannedPixelSpacing instead of PixelSpacing, so otherwise valid images are loaded incorrectly.

There is more information in the discussion at this PR:

https://github.com/Slicer/Slicer/pull/7089

### Steps to Reproduce

The data available from the idc-open-data set on aws is the Visible Human Project male dataset converted to dicom by @dclunie.

You can get one file with this command:

`aws s3 cp --no-sign-request s3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/fbc89e1c-29c4-48cf-89fd-53b7c1dc1488.dcm .`

Or the whole dataset using this command (about 13 gigabytes).

`s5cmd --no-sign-request --endpoint-url https://s3.amazonaws.com cp 's3://idc-open-data/4aaf9181-fb6a-4a4c-bf49-d1eb9ed4a385/*' .`

### Expected behavior

The index to physical transform should be correctly populated.

### Actual behavior

The direction cosines are explicitly set of identity:

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx#L731-L740

The PixelSpacing is ignored, and the NominalScannedPixelSpacing is looked for, but is typically absent.

https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageHelper.cxx#L1265-L1273

### Reproducibility

Always

### Versions

Tested on current main branch,  but I suspect the code has been around for decades.

### Environment

Any

### Additional Information

I'll probably fix this, although it may not be a high priority if we fix https://github.com/InsightSoftwareConsortium/ITK/issues/4108 instead.

### PR DESCRIPTION
**Pull request by issakomi**
The PR is to run tests with changes in the upstream PR https://github.com/malaterre/GDCM/pull/158

Closes #4109

Replaces #4111

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for working on this 💯 

If possible, I suggest to include the following trailer in the commit:

```
Co-authored-by: Steve Pieper <pieper@isomics.com>
```

Thanks for considering 🙏

**Comment by issakomi** [comment]
> If possible, I suggest to include the following trailer in the commit:
> 
> ```
> Co-authored-by: Steve Pieper <pieper@isomics.com>
> ```

I have added `Co-authored-by` to the upstream PR https://github.com/malaterre/GDCM/pull/158
I am not sure that the PR will be accepted by GDCM, s. [post](https://github.com/Slicer/Slicer/pull/7089#issuecomment-1644002470).
This one was just to run the tests.
CC @pieper 

Screenshot 2023-07-20 at 17-06-37 ENH Handle IPP_IOP_PixelSpacing for SC by issakomi · Pull Request #158 · malaterre_GDCM

**Comment by jcfr** [comment]
> I have added Co-authored-by to the upstream PR 

Outstanding. :pray: 

> not sure that the PR will be accepted by GDCM

:crossed_fingers:

**Comment by pieper** [comment]
Thank you @issakomi - this looks like a much more complete solution.

**Comment by issakomi** [comment]
S. https://github.com/malaterre/GDCM/pull/158

**Pull request closed without merging**
