### PR TITLE
ENH: Conform to GitHub PR and issue template guidelines.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Conform to GitHub PR and issue template guidelines:
- Add the YAML front matter markup.
- Split the former `ISSUE_TEMPLATE.md` into a `BUG_REPORT.md` and a
  `FEATURE_REQUEST.md` template so that they better serve their purpose.
- Store the templates into their own, separate folders.

These changes should enable the templates be included in the community
profile checklist:
https://github.com/InsightSoftwareConsortium/ITK/community

References:
https://help.github.com/articles/about-issue-and-pull-request-templates/
https://help.github.com/articles/manually-creating-a-single-issue-template-for-your-repository/
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not sure how we will be able to test these before merging.

This comes after some discussions with the GitHub support team dating back to October 2018, and after they have updated the referred documentation.

The issue stemmed from the fact that I realized that our **CoC** and **Issue Template** were not being taken into account in the `Insights`/`Community` profile.

Let's see if this makes the trick. Cross-checking the documentation would be appreciated (e.g. looks weird that the YAML `:about:` is the only field requiring a colon before the word).

Thanks for your patience.

**Comment by jhlegarreta** [comment]
The errors reported by ITK.Linux Azure are unrelated:
```
The following tests FAILED:
	2058 - itkSPSAOptimizerTest (Failed)
```
with the following error:
```
etValue( 1.97733 -1.98178) = -9.99906
Solution        = (1.97726,-1.98181)
StateOfConvergence in last iteration: 5.65225e-06
NumberOfIterations: 58
Stop condition: SPSAOptimizer: Below tolerance. Tolerance is 1e-05
Test failed.
```

May be due to some numerical instabilities? Not sure when this started failing. Would need some time to investigate.

**Comment by thewtex** [comment]
> The errors reported by ITK.Linux Azure are unrelated: `itkSPSAOptimizerTest` fails

Yes, this is new to me -- let's keep an eye on it :eyeglasses: .

**Comment by jhlegarreta** [comment]
Thanks Matt.

Unfortunately, it looks like the PR did not solve the issue, even the contrary :worried: :
https://github.com/InsightSoftwareConsortium/ITK/community

No issue template is displayed now when trying to open one, while I'd have expected two templates to be available now:
https://github.com/InsightSoftwareConsortium/ITK/issues/new

I'll contact the GitHub support team.

**Pull request merged**
