### PR TITLE
Explicit libm linking for NrrdIO and libLBFGS.

### LINKED ISSUE #1841: Errors linking to libm when building with -Wl,--no-undefined
### Description

Building packages for openSUSE fails because of linking issues against libm. Specifically, the linker complains about missing reference to `sqrt` and other math functions when building the third-party module nrrdio and lbfgs. We probably hit this — while others may not — because the default compiler flags on openSUSE include `-Wl,--no-undefined` when linking; however, this indicates a real issue nonetheless.

We use the following patches to explicitly add `libm` to the linker:

```patch
--- insighttoolkit4-4.5.0.orig/Modules/ThirdParty/NrrdIO/src/NrrdIO/CMakeLists.txt
+++ insighttoolkit4-4.5.0/Modules/ThirdParty/NrrdIO/src/NrrdIO/CMakeLists.txt
@@ -64,7 +64,7 @@
 ADD_DEFINITIONS(-DTEEM_ZLIB=1)
 
 ADD_LIBRARY(ITKNrrdIO ${nrrdio_SRCS} )
-TARGET_LINK_LIBRARIES(ITKNrrdIO ${ITKZLIB_LIBRARIES})
+TARGET_LINK_LIBRARIES(ITKNrrdIO ${ITKZLIB_LIBRARIES} -lm)
 
 IF(ITK_LIBRARY_PROPERTIES)
   SET_TARGET_PROPERTIES(ITKNrrdIO PROPERTIES ${ITK_LIBRARY_PROPERTIES})
diff -ur InsightToolkit-4.13.2/Modules/ThirdParty/libLBFGS/src/CMakeLists.txt InsightToolkit-4.13.2_fix/Modules/ThirdParty/libLBFGS/src/CMakeLists.txt
--- InsightToolkit-4.13.2/Modules/ThirdParty/libLBFGS/src/CMakeLists.txt	2019-02-28 17:45:49.000000000 +0100
+++ InsightToolkit-4.13.2_fix/Modules/ThirdParty/libLBFGS/src/CMakeLists.txt	2019-07-02 16:05:59.161006477 +0200
@@ -17,6 +17,8 @@
 set(ITK3P_INSTALL_LIBRARY_DIR "${ITKLIBLBFGS_INSTALL_LIBRARY_DIR}")
 set(ITK3P_INSTALL_ARCHIVE_DIR "${ITKLIBLBFGS_INSTALL_ARCHIVE_DIR}")
 
+TARGET_LINK_LIBRARIES(itklbfgs -lm)
+
 INSTALL(TARGETS itklbfgs
   EXPORT ${ITK3P_INSTALL_EXPORT_NAME}
   RUNTIME DESTINATION ${ITK3P_INSTALL_RUNTIME_DIR} COMPONENT RuntimeLibraries
```

It would be great to have this accepted upstream, or if you have a better fix, that would be welcome too.

Tested against tagged version 5.1.0. 

Thanks!

### PR DESCRIPTION
**Pull request by badshah400**
Add libm to the list of libraries being linked against when building
third party libraries NrrdIO and libLBFGS. This prevents errors when
building with `-Wl,--no-undefined`. Fixes #1841.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by badshah400** [comment]
> Let's see how to compiles on Visual Studio.

If it doesn't — I have no idea about VS — we can wrap the libm linking inside `if(UNIX)` guards. Let me know if that will help.

**Comment by dzenanz** [comment]
All the tests ran successfully. There are some false positives in reporting, so it comes up red. Merging.

**Comment by thewtex** [comment]
@badshah400 thanks for contribution! :1st_place_medal:

**Comment by dzenanz** [comment]
It does cause warning in some situations:
```text
[3071/6042] Building CXX object Modules\Filtering\AnisotropicSmoothing\test\CMakeFiles\ITKAnisotropicSmoothingTestDriver.dir\itkCurvatureAnisotropicDiffusionImageFilterTest.cxx.obj
[3072/6042] Building CXX object Modules\Filtering\AnisotropicSmoothing\tes
        LINK : warning LNK4044: unrecognized option '/lm'; ignored
[3078/6042] Building CXX object Modules\Core\SpatialObjects\src\CMakeFiles\ITKSpatialObjects.dir\itkContourSpatialObject.cxx.obj
[3079/6042] Building CXX object Modules\Core\SpatialObjects\src\CMakeFiles\ITKSpatialObjects.dir\itkSpatialObjectFactoryBase.c
        LINK : warning LNK4044: unrecognized option '/lm'; ignored
[3140/6042] Building CXX object Modules\Filtering\BiasCorrection\test\CMakeFiles\ITKBiasCorrectionTestDriver.dir\ITKBiasCorrectionTestDriver.cxx.obj
[3141/6042] Building CXX object Modules\Filtering\BiasCorrection\test\CMakeFiles\ITKBiasCorrectionTestDriv
        LINK : warning LNK4044: unrecognized option '/lm'; ignored
[3145/6042] Building CXX object Modules\Filtering\BinaryMathematicalMorphology\test\CMakeFiles\ITKBinaryMathematicalMorphologyTestDriver.dir\itkBinaryClosingByReconstructionImageFilterTest.cxx.obj
[3146/6042] Building CXX object Modules\Filtering\BinaryMa
        LINK : warning LNK4044: unrecognized option '/lm'; ignored
```
Can you follow up and exclude this option for Visual Studio?

**Comment by badshah400** [comment]
PR #1878 should do it.

**Pull request merged**
