### PR TITLE
STYLE: Replace postfix by prefix increment in `for` loops in ITK/Modules

### PR DESCRIPTION
**Pull request by N-Dekker**
Applied to ITK/Modules, at the GNU bash prompt:

    find . \( -iname *.cxx -or -iname *.hxx -or -iname *.h \) -exec perl -pi -w -e 's/(\s+for \(.*; .+); (\w+)\+\+\)/$1; ++$2)/g;' {} \;

(Excluded ITK/Modules/ThirdParty.)

According to Herb Sutter, Andrei Alexandrescu - C++ Coding Standards:
101 Rules, Guidelines, and Best Practices: "Prefer the canonical form of
++ and --. Prefer calling the prefix forms"

Follow-up to:
pull request https://github.com/InsightSoftwareConsortium/ITK/pull/2493
commit f81578bbb6242032b611d7e3e4dca3b7557fbbe0
"STYLE: Replace postfix by prefix increment in `for` loops in Core/Common"

### CODE REVIEW

**Comment by N-Dekker** [comment]
Nice video by  Fred Overflow (@fredoverflow) on this topic: [Why C++ programmers prefer ++i over i++ (prefix vs. postfix increment operator, for loop, iterators)](https://www.youtube.com/watch?v=bONciSOJ_N4) --> www.youtube.com/watch?v=bONciSOJ_N4

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
MacCI is working again. 😄

**Comment by N-Dekker** [comment]
> MacCI is working again.

I'm glad to hear so @dzenanz  I guess MacCI has been waiting for us to fix those postfix increments  😸

**Comment by dzenanz** [comment]
No, it was fixed by #2492, but this is the first PR created since it was merged. I am glad the fix was simple 😄

**Review by dpshamonin — APPROVED** [review]

**Pull request merged**
