### PR TITLE
BUG: Fix wrong variable names

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix wrong variable names in remote modules required ITK version update
script.

## PR Checklist

- :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- :no_entry_sign: Adds the License notice to new files.
- :no_entry_sign: Adds Python wrapping.
- :no_entry_sign: Adds tests and baseline comparison (quantitative).
- :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
Iff it works, it is good 😄

I assume you tried applying the script and ran into problems?

**Comment by jhlegarreta** [comment]
@dzenanz thanks for the review. That's right. But further testing is always welcome.

**Comment by jhlegarreta** [comment]
Take into account that I also found another issue related to this script and reported it in #1022.

**Comment by jhlegarreta** [comment]
584ce34 rebased on master. Let's see if CI finishes its job and this can be merged.

**Pull request merged**
