### PR TITLE
Fix fem registration missing include

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
> This branch has conflicts that must be resolved

Can you rebase on current master? And format it with clang-format, which is presumably what causes the conflicts.

**Comment by blowekamp** [comment]
Rebased the PR to the last common ancestor of release and master, so the patch can be cleaning merged into both.

The release branch needs to be merged into master to enable the best practice of based patches or the release branch which are to be merged into both branches. It looks like #1186 ( or similar commit ) was never merged into master... I'll work on fixing these things up.

**Comment by hjmjohnson** [comment]
Failing test seems unrelated:

`	1832 - itkStatisticsUniqueLabelMapFilterTest1 (Failed)`

**Comment by blowekamp** [comment]
> Failing test seems unrelated:
> 
> `	1832 - itkStatisticsUniqueLabelMapFilterTest1 (Failed)`

That test has been randomly failing for a VERY long time.

**Pull request merged**
