### PR TITLE
Image to histogram multi thread

### PR DESCRIPTION
**Pull request by hjmjohnson**
http://review.source.kitware.com/#/c/23886/3

Bradley Lowekamp
Uploaded patch set 1.11:41 AM

Bradley Lowekamp
Patch Set 1: I am seeing more that a 10x speed up with 40+ threads.12:16 PM

Dzenan Zukic
12:26 PM
↩
Patch Set 1: Code-Review+2
(1 comment)
I guess this change reduces merge's computational complexity from n to log2(n). With many-core processors, that is significant. But I wouldn't have guessed that total time was dominated by the merge operation. And only that can explain a tenfold speedup.
Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
Line 279:
owner ship -> ownership

Kitware Build Robot
Patch Set 1: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23886-1&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-0112:28 PM

Bradley Lowekamp
Patch Set 1: That observation was for the last execution in the ImageToHistogramImageFilterTest0 where the histogram is for an RGB histogram of size 127x127x127, where the image is the same size. Yes you are correct of the expect threaded performance of the reduction is O(lg(n)) when fully concurrent. However, depending of thread execution, it could be linear with n-1 merges, or like a binary tree with 2n-2 merges.12:40 PM

Bradley Lowekamp
Uploaded patch set 2.12:49 PM

Bradley Lowekamp
Patch Set 2: It looks like the CI needs to be cleaned up from leftover VXL improvements...1:06 PM

Dzenan Zukic
1:06 PM
↩
Patch Set 2: Code-Review+2
(2 comments)
Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
Line 286:
ownership is one word, I think
Modules/Numerics/Statistics/include/itkMaskedImageToHistogramFilter.hxx
Line 114:
Nice reuse!

Dzenan Zukic
Patch Set 2: Also, Matt is in the middle of switching to GitHub. Please don't merge this yet.1:08 PM

Bradley Lowekamp
Uploaded patch set 3.1:16 PM

Bradley Lowekamp
1:16 PM
↩
Patch Set 2:
(1 comment)
thanks!
Modules/Numerics/Statistics/include/itkImageToHistogramFilter.hxx
Line 286:
Done

Dzenan Zukic
Patch Set 3: Code-Review+21:45 PM

Kitware Build Robot
Patch Set 2: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23886-2&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-012:12 PM

Kitware Build Robot
Patch Set 3: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23886-3&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-012:54 PM

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@blowekamp A failing test on linux that seems related to this patch:

2018-11-05T23:35:01.8303956Z The following tests FAILED:
2018-11-05T23:35:01.8304400Z 	1719 - itkStatisticsUniqueLabelMapFilterTest1 (Failed)

**Comment by dzenanz** [comment]
@hjmjohnson I think that `itkStatisticsUniqueLabelMapFilterTest1` has been sporadically failing for months now. Non-deterministic test failures are time-consuming to diagnose. And while the problem is related, it should not stop this patch.

**Comment by blowekamp** [comment]
That test has been failing speratically for MANY years. I think the threading refactoring may have increased the frequency. 

I have a patch on my workstation I should amend to restore the intended std::move operation.

**Comment by hjmjohnson** [comment]
@blowekamp Thanks for looking into this.  I did not mean to close this issue.  Only to comment on it.

**Comment by hjmjohnson** [comment]
Reopen issue.  My bad.  Sorry.

**Comment by thewtex** [comment]
Based on other experiences, we may want to decrease the number of default work units with TBB.

**Comment by dzenanz** [comment]
Or implement the `workUnitToThreadRatio` parameter which could be set per filter. And have the ratio low by default (e.g. 3-4), and high (e.g. 10-30) for filters with uneven per-pixel workload.

**Comment by blowekamp** [comment]
This particular case the image is 127x127 RGB and the histogram is 127^3. This is a particularly bad case where there is more work required for every split done. This ImageToHistogram filter is an interesting case where the cost of image computation (#pixel ), the cost of the histogram (#bins) and the expected cost of merging (#bints*log(#workunits)) can beestimated. The cost of doing a split is not just the data processed, it has the other cost that may need to be considered. Perhaps just setting the work unit ratio for this ( or similar types ) to one is appropriate.

**Comment by dzenanz** [comment]
Of course, the `ratio` could be lowered for cases where splitting incurs a high overhead.

**Pull request merged**
