### PR TITLE
 Itk obj mesh io m number of point pixels default

### PR DESCRIPTION
**Pull request by fbudin69500**
When reading the mesh information, `m_NumberOfPointPixels` is computed based
    on the number of lines starting with the code `vn`. However, this was
    then overriden and set equal to `m_NumberOfPoints`.
    This lead to a crash when these lines were actually read in
    the function `ReadPointData()` because not enough memory was allocated.

### CODE REVIEW

**Comment by thewtex** [comment]
Test output:

```
OBJMeshIO (0x259bf10)
  RTTI typeinfo:   itk::OBJMeshIO
  Reference Count: 1
  Modified Time: 60
  Debug: Off
  Object Name: 
  Observers: 
    none
  AbortGenerateData: Off
  Progress: 0
  FileName: /home/vsts/work/1/s-build/ExternalData/Modules/IO/MeshOBJ/test/Baseline/bunny.obj
  FileType: ASCII
  ByteOrder: OrderNotApplicable
  Point dimension: 3
  Point component type: float
  Cell  component type: long
  Number of point pixel components: 3
  Number of cell  pixel components: 1
  Number of points: 2503
  Number of cells: 4968
  Number of point pixels: 4968
  Number of cell pixels: 0
  Point pixel type: vector
  Cell  pixel type: scalar
  Point pixel component type: float
  Cell  pixel component type: float
Write file /home/vsts/work/1/s-build/Testing/Temporary/bunny.obj failed 

itk::ExceptionObject (0x26561f0)
Location: "unknown" 
File: /home/vsts/work/1/s/Modules/IO/MeshOBJ/src/itkOBJMeshIO.cxx
Line: 597
Description: itk::ERROR: OBJMeshIO(0x259bf10): MNI Mesh required point normals


Failure for itk::Mesh
OBJMeshIO (0x2650630)
  RTTI typeinfo:   itk::OBJMeshIO
  Reference Count: 1
  Modified Time: 22486
  Debug: Off
  Object Name: 
  Observers: 
    none
  AbortGenerateData: Off
  Progress: 0
  FileName: /home/vsts/work/1/s-build/ExternalData/Modules/IO/MeshOBJ/test/Baseline/bunny.obj
  FileType: ASCII
  ByteOrder: OrderNotApplicable
  Point dimension: 3
  Point component type: float
  Cell  component type: long
  Number of point pixel components: 3
  Number of cell  pixel components: 1
  Number of points: 2503
  Number of cells: 4968
  Number of point pixels: 4968
  Number of cell pixels: 0
  Point pixel type: vector
  Cell  pixel type: scalar
  Point pixel component type: float
  Cell  pixel component type: float
Write file /home/vsts/work/1/s-build/Testing/Temporary/bunny.obj failed 

itk::ExceptionObject (0x2a61eb0)
Location: "unknown" 
File: /home/vsts/work/1/s/Modules/IO/MeshOBJ/src/itkOBJMeshIO.cxx
Line: 597
Description: itk::ERROR: OBJMeshIO(0x2650630): MNI Mesh required point normals


Failure for itk::QuadEdgeMesh
```

**Comment by fbudin69500** [comment]
Thanks for uploading the data on girder. This PR correct one problem, but as you can see there is another problem that is still present (see comment on discourse [here](https://discourse.itk.org/t/trianglemeshtobinaryimagefilter-in-python/1604/12?u=fbudin)).

**Comment by maekclena** [comment]
@fbudin69500 having multiple normals per vertex allows sharp edges. In `bunny.obj` for example, each face uses the same normal for all its vertices, making them flat. If you want to limit a vertex to one normal, you can take the average of all normals used with this vertex.

**Comment by fbudin69500** [comment]
@maekclena Do you mean that each vertex has one normal per polygon/triangle they belong to which leads to multiple normals per vertex?

**Comment by maekclena** [comment]
@fbudin69500 yes, at least in `bunny.obj`.

**Comment by dzenanz** [comment]
I just rebased this.

**Comment by dzenanz** [comment]
I just looked into this, and this requires proper support for per-vertex and per-face normals. It will require understanding mesh IO and non-trivial refactoring of this class.

**Comment by dzenanz** [comment]
Updating PR to just exercise reading OBJ with face normals. We get crash avoidance during reading for now, and leave writing normals for another day.

**Comment by dzenanz** [comment]
Only itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest failed, merging.

**Pull request merged**
