### PR TITLE
replace 939

### PR DESCRIPTION
**Pull request by malaterre**
## PR Checklist

- [ ] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] :no_entry_sign: Adds the License notice to new files.
- [ ] :no_entry_sign: Adds Python wrapping.
- [ ] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [ ] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by malaterre** [comment]
If not clear this PR replaces PR 939

@SimonRit

**Comment by issakomi** [comment]
Doesn't have any effect, but that [here](https://github.com/InsightSoftwareConsortium/ITK/blob/ef3e412eb2396786e5bf5a2cce8f4cb891406482/Modules/ThirdParty/GDCM/src/gdcm/Source/DataStructureAndEncodingDefinition/gdcmElement.h#L660) (near that cast) is useless assert

```
      if(array)
      {
        assert(array); // That would be bad
```

**Comment by SimonRit** [comment]
> If not clear this PR replaces PR #939.
> 
> @SimonRit

Thanks. I approve this PR. Can you comment on why this is better than what was in #939 for the alignment warning? It seems to be doing the same thing to me... Any pointer to an explanation?

**Comment by malaterre** [comment]
@SimonRit Technically you are correct, I am indeed using your trick to avoid a compiler warning. However the consumer of the `GetPointer` API should not be responsible for specifiying the alignement of the char * buffer. Since there is no way in c++ (even c++20) [to do so](https://stackoverflow.com/questions/56256431/warning-cast-from-char-to-float-increases-required-alignment-from-1-to). I simply exposed a void* API to the user.

**Comment by thewtex** [comment]
Failing test is unrelated.

**Pull request merged**
