### PR TITLE
ENH: wrapped remaining v4 Registration classes

### PR DESCRIPTION
**Pull request by brad-t-moore**
See #3099 
Added Python testing to existing wrapped classes and added ones
Fixed bug in class naming of itkANTSNeighborhoodCorrelationImageToImageMetricv4 (was erroneously set to "Self")
Moved any wrapping commands for the RegistrationParameterScales classes from parameter .wrap files into central ones
Created itkMetricv4Types.wrap which is used by the RegistrationParameterScales classes wrapping
RegistrationParameterScales classes are in the Metricv4 folder to prevent a cyclic build dependency

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by brad-t-moore** [comment]
I'll rebase this after a cup of coffee in the AM.

**Review by dzenanz — COMMENTED** [review]
Maybe break it up into a few commits, e.g.:
1. bug fix
2. adding testing to existing wrappings
3. move definitions around
4. new additions

**Comment by thewtex** [comment]
@brad-t-moore niiiice!

> Maybe break it up into a few commits

I don't think this is necessary.

**Comment by brad-t-moore** [comment]
I'll try building on my Linux box.  It says a type has the wrong class name.  It might be something filename (case-insensitivity) related.

**Comment by brad-t-moore** [comment]
I get the type warnings but not the errors on my Linux machine- will look into how the CI is configured.

**Comment by brad-t-moore** [comment]
Ack, I think I royally messed up this branch through git.  I had a local second "master" that was created a while back and I think with the merge I did there isn't a good way to squash it without messing up the commit history.  I think I'm going to close this PR and just make a second clean one.

**Comment by brad-t-moore** [comment]
Replaced by PR #3177 to fix git issues.

**Pull request closed without merging**
