### PR TITLE
ENH: Wrap CompositeTransform for float32 parameters

### PR DESCRIPTION
**Pull request by thewtex**
For the use case of a float32 displacement vector field.

### CODE REVIEW

**Comment by thewtex** [comment]
Re: https://discourse.itk.org/t/itk-python-image-of-itk-d-vectors-for-composite-transform/5122

**Review by dzenanz — APPROVED** [review]

**Comment by PranjalSahu** [comment]
Build failing with warning message:
```itkCompositeTransform: warning(4): ITK type not wrapped, or currently not known: itk::MultiTransform< float, 2 >```

**Comment by dzenanz** [comment]
I amended it with addition for `MultiTransform`.

**Review by PranjalSahu — APPROVED** [review]
LGTM

**Pull request merged**
