### PR TITLE
BUG: Fix DICOM loading speed regression

### PR DESCRIPTION
**Pull request by lassoan**
GDCM has changed so that it masks unused bits more frequently.
However, this masking operation was implemented so inefficiently that loading time increased by a factor of 5-10x (on Windows, VS2017).

Fixed by reading/writing data in the data stream in larger chunks.

I know that this should be fixed in GDCM but I've already spent more time with this than I wanted. I hope that @malaterre and others will take this and integrate in GDCM/ITK as appropriate.

It fixes https://github.com/InsightSoftwareConsortium/ITK/issues/1542.

## PR Checklist
- [ ] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] :no_entry_sign: Adds the License notice to new files.
- [ ] :no_entry_sign: Adds Python wrapping.
- [ ] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [ ] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by malaterre** [comment]
@lassoan thanks for the patch ! Can you comment on the speed improvement given by this patch ?

As a side note, I would have picked 1024 instead of 1000.

**Comment by malaterre** [comment]
If this is not clear, I'll import in GDCM. There might be some conflict with a recent work from @blowekamp and PR #1606.

**Comment by lassoan** [comment]
> Can you comment on the speed improvement given by this patch ?

Loading of a JPEG-compressed image used to take about 10 seconds.
After recent GDCM changes, this slowed down to about 1 minute.
With the changes in this pull request, loading takes about 10 seconds again.

> As a side note, I would have picked 1024 instead of 1000.

Most likely it does not matter, but I just wanted to remain somewhat below a 2^n round number (to make sure that a few extra bytes does not make the memory area larger than 2^n).

**Comment by malaterre** [comment]
@lassoan I've chery-picked your commit in GDCM upstream:

* https://github.com/malaterre/GDCM/commit/e7daa53652fbbc146a17db7ad2512957e1b31ac6

thanks !

**Pull request closed without merging**
