### PR TITLE
zlib-ng 2022-05-12 (41d67396)

### PR DESCRIPTION
**Pull request by thewtex**
Code extracted from:

    https://github.com/zlib-ng/zlib-ng.git

at commit 41d67396924ccc7ab1ff9a7e7d434bfb0887b136 (develop).

### CODE REVIEW

**Comment by thewtex** [comment]
The `ghostflow` error is a false positive. We should not be checking third-party for style issues. @mathstuf @bradking

**Comment by bradking** [comment]
The import script should write `.gitattributes` content to disable whitespace checks for the third-party code.  `Modules/ThirdParty/HDF5/UpdateFromUpstream.sh` does this, for example.

**Comment by thewtex** [comment]
> The import script should write .gitattributes content to disable whitespace checks for the third-party code. Modules/ThirdParty/HDF5/UpdateFromUpstream.sh does this, for example.

Did not work here: https://github.com/InsightSoftwareConsortium/ITK/pull/3422/commits/b5f5388c10517f7e5d3b244bf80a0520e97893ad

Neither did: https://github.com/InsightSoftwareConsortium/ITK/pull/3426/commits/85c8ef2f0a9641e107f1ce338f2e28cc017daece

**Comment by bradking** [comment]
You extended the branch rather than rewriting it, so the offending commits were still being checked.

I pushed an update to your branch.

**Review by tbirdso — APPROVED** [review]

**Pull request merged**
