### PR TITLE
ENH: Update codebase for Eigen 3.3.8 release

### PR DESCRIPTION
**Pull request by hjmjohnson**
Fixes several bugs related incompatibilities building on
Intel(R) Xeon(R) Gold 6254 CPU @ 3.10GHz with march=native
flags.

This includes changes manually copied in from upstream/master
with commit 655c3a40428e0e6a5490a3a4d4bddceb45af4a3a on
2020-12-07.

with upstream=	https://gitlab.com/libeigen/eigen.git

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by dzenanz** [comment]
If I remember correctly, there were some custom changes in Pablo's fork.

Build issues:
```text
D:\a\1\s\Modules\ThirdParty\Eigen3\src\itkeigen\Eigen\src/Core/arch/Default/Half.h(626): error C2065: 'M_LOG2E': undeclared identifier
D:\a\1\s\Modules\ThirdParty\Eigen3\src\itkeigen\Eigen\src/Core/arch/Default/BFloat16.h(516): error C2065: 'M_LOG2E': undeclared identifier
Modules/ThirdParty/Eigen3/src/itkeigen/../itkeigen/Eigen/src/Core/AssignEvaluator.h:328:65: warning: unused parameter 'kernel' [-Wunused-parameter]
```

**Comment by phcerdan** [comment]
> if I remember correctly, there were some custom changes in Pablo's fork.

Yeah, the CMake part is overridden for ITK, so at least one commit.

And @hjmjohnson , you will need to go through the UpdateFromUpstream route, not copying the files directly.

**Review by phcerdan — CHANGES_REQUESTED** [review]
Use UpdateFromUpstream, not copying files manually.
There is only one commit, which overrides CMake, that needs to be rebased on top of the upstream eigen.

**Comment by phcerdan** [comment]
I am working on this, will update Eigen today.

**Comment by hjmjohnson** [comment]
@phcerdan Thanks.

FYI The "UpdateFromUpstream.sh" script did not work.  Would you mind adding a few comments to describe the intended process for updating Eigen?    Is the proper mechanism to contact you?

**Comment by phcerdan** [comment]
It didn't work because in this case (as in a few other in ITK as you know)  the `upstream` projects lives here:
```cmake
upstream_git_url="https://gitlab.kitware.com/phcerdan/eigen.git"
upstream_git_branch="for/itk-3.3-find_package"
```
So you have to update that first or create a new branch.

```bash
git clone https://gitlab.kitware.com/phcerdan/eigen.git eigen-src
cd eigen-src
git remote add upstream https://gitlab.com/libeigen/eigen
git fetch upstream
# Checkout the current branch that itk is using
# From upstream_git_branch in  Modules/ThirdParty/Eigen3/UpdateFromUpstream.sh
git checkout for/itk-3.3-find_package
# Create a new branch for your rebase (or push on top the current branch)
git checkout -b for/itk-3.3.8
# Rebase on top of upstream
git rebase upstream/3.3
git push
# And then update `upstream_git_branch`
# Execute UpstreamFromUpstream.sh as usual.
```
> Is the proper mechanism to contact you?

Not sure what you mean here.

PS: I am testing locally and will open a PR soon with the update if all green.

**Comment by dzenanz** [comment]
> Is the proper mechanism to contact you?

Maybe this eigen fork should be moved into InsightSoftwareConsortium organization, so all the maintainers (including Hans) can write to it (update etc).

**Comment by phcerdan** [comment]
That makes sense @dzenanz.

**Comment by phcerdan** [comment]
By the way @hjmjohnson, if you really need a hot-fix for Eigen, you can just use your own Eigen (or recent upstream) providing the CMake variables:
```
ITK_USE_SYSTEM_EIGEN:BOOL=ON
Eigen3_DIR:PATH=/path/your_eigen_build_folder
```

**Pull request closed without merging**
