### PR TITLE
DOC: Updates to the README

### PR DESCRIPTION
**Pull request by thewtex**
- Focus branding on the the simpler and broader name "Insight Toolkit
(ITK)". ITK is well known as "ITK". Its use and applications go beyond
segmentation and registration on medical images. The NLM does not desire
branding of ITK.
- Add Python package installation instructions.

### CODE REVIEW

**Comment by blowekamp** [comment]
OK...

 - Perhaps an acknowledgment of the Insight Software Consortium is in order?
 - There has been Many funding sources for ITK over the years, perhaps some acknowledgment of that is in order?
 - As a developer of SimpleITK, I also feel this may be steering a lot to native ITK Python. There are many elements in the ITK community, SimpleITK has tries to provide little additional to ITK beyond a simplified interface for many languages. Perhaps an additional plug is due too.

**Comment by thewtex** [comment]
>     * Perhaps an acknowledgment of the Insight Software Consortium is in order?

There is an existing reference to the ISC in the README.

>     * There has been Many funding sources for ITK over the years, perhaps some acknowledgment of that is in order?

Yes, a separate Acknowledgements section of the README would be nice, but that is a separate topic. I created an issue here: https://github.com/InsightSoftwareConsortium/ITK/issues/454

>     * As a developer of SimpleITK, I also feel this may be steering a lot to native ITK Python. There are many elements in the ITK community, SimpleITK has tries to provide little additional to ITK beyond a simplified interface for many languages. Perhaps an additional plug is due too.

I do not think SimpleITK or MITK or ITK-SNAP or 3D Slicer or SMILI or Elastix or ANTS or VV or Seg3D or MeVisLab or the Orfeo Toolbox or DREAM.3D or ProjectXYZ should be given a special plug here.

**Comment by blowekamp** [comment]
> I do not think SimpleITK or MITK or ITK-SNAP or 3D Slicer or SMILI or Elastix or ANTS or VV or Seg3D or MeVisLab or the Orfeo Toolbox or DREAM.3D or ProjectXYZ should be given a special plug here.

Yes, it is a complex issue. There are MANY was to use ITK. While popular today, we don't want to convey that ITK is just python. It is a much more diverse toolkit with layers of community and organizational support.

**Comment by bpaniagua** [comment]
> I do not think SimpleITK or MITK or ITK-SNAP or 3D Slicer or SMILI or Elastix or ANTS or VV or Seg3D or MeVisLab or the Orfeo Toolbox or DREAM.3D or ProjectXYZ should be given a special plug here.

:+1:

**Comment by thewtex** [comment]
Circle CI build warnings are unrelated.

**Pull request merged**
