### PR TITLE
STYLE: Update Python files to 3.7 syntax

### PR DESCRIPTION
**Pull request by dzenanz**
Accomplished by using https://github.com/asottile/pyupgrade:

C:\Dev\ITK-git>`for /f %f in ('dir /s /b *.py') do pyupgrade --py37-plus %f`

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by Leengit** [comment]
Thank you.  It looks like this would benefit from a post-pass with `black`:
```dos
for /f %f in ('dir /s /b *.py') do black %f
```
so that `black` wins out where there are disagreements with `pyupgrade`.

**Comment by Leengit** [comment]
Sorry, we probably don't want to apply `black` within `ThirdParty`.

**Comment by dzenanz** [comment]
I noticed that `black` modified a lot of files in third party, but I didn't for `pyupgrade`. If you want to take over, please create a new PR (I don't think you can push to my fork). I will close this one in favor of that.

**Comment by Leengit** [comment]
> If you want to take over, please create a new PR

Can do.

**Comment by dzenanz** [comment]
Closing in favor of #3244.

**Pull request closed without merging**
