### PR TITLE
BUG: Fix 32-bit truncation on VectorImage Accessor

### PR DESCRIPTION
**Pull request by blowekamp**
Initial bug reported in SimpleITK/SimpleITK#2220.

On 64-bit windows system, truncation to 32-bit (unsigned long) was occurring when setting VectorImages with over 4GB buffers.

See #5070 for a WIP test. This test used 8GB memory and needs to ctest memory requirements to ensure there are enough resources.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
This seems like a pretty big bug, IMHO. It may be worth applying to release, and tagging 5.4.2, before all the regaining work for 5.4.1 is completed.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
:100: :eagle: :eye:

**Review by hjmjohnson — CHANGES_REQUESTED** [review]
@blowekamp There are two other places that have similar issues

```bash
git grep "unsigned long offset"                                                                                                
```
```txt
Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
Modules/Core/ImageAdaptors/include/itkNthElementPixelAccessor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
Modules/Core/ImageAdaptors/include/itkVectorImageToImageAdaptor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
Modules/Filtering/ImageIntensity/test/itkHistogramMatchingImageFilterTest.cxx:refPattern(unsigned long offset)
Modules/Filtering/ImageIntensity/test/itkHistogramMatchingImageFilterTest.cxx:srcPattern(unsigned long offset)
Modules/Filtering/Thresholding/test/itkThresholdLabelerImageFilterTest.cxx:  const unsigned long offset = 4;

```

**Comment by hjmjohnson** [comment]
FYI:  I approve the change, just want to ensure all the fixes are put in at once.

**Comment by hjmjohnson** [comment]
@blowekamp Perhaps these  too:

"  int
  FindRegionsInArea(long start, long end, long size, long offset);

int
MirrorPadImageFilter<TInputImage, TOutputImage>::FindRegionsInArea(long start, long end, long size, long offset)
"

**Comment by blowekamp** [comment]
> @blowekamp There are two other places that have similar issues
> 
> ```shell
> git grep "unsigned long offset"                                                                                                
> ```
> 
>  ```
> Modules/Core/Common/include/itkDefaultVectorPixelAccessor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
> Modules/Core/ImageAdaptors/include/itkNthElementPixelAccessor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
> Modules/Core/ImageAdaptors/include/itkVectorImageToImageAdaptor.h:  Set(InternalType & output, const ExternalType & input, const unsigned long offset) const
> Modules/Filtering/ImageIntensity/test/itkHistogramMatchingImageFilterTest.cxx:refPattern(unsigned long offset)
> Modules/Filtering/ImageIntensity/test/itkHistogramMatchingImageFilterTest.cxx:srcPattern(unsigned long offset)
> Modules/Filtering/Thresholding/test/itkThresholdLabelerImageFilterTest.cxx:  const unsigned long offset = 4;
> ```

Good finds. I added the same change to the other classes derived from the adaptor class.

**Comment by blowekamp** [comment]
> @blowekamp Perhaps these too:
> 
> " int FindRegionsInArea(long start, long end, long size, long offset);
> 
> int MirrorPadImageFilter<TInputImage, TOutputImage>::FindRegionsInArea(long start, long end, long size, long offset) "

Just to follow up, with this filter. These values are for the components of a ND index and not 1-D array access. So this would be an issue when one dimension of the image needs more that 32-bits. There is broad incorrect usage of the "long" type in this class and not the appropriate itk::IndexValueType or itk::OffsetValueType used.

**Pull request merged**
