### PR TITLE
Support streaming in Gaussian interpolate image function

### LINKED ISSUE #988: Error when resampling with Gaussian interpolation when employing streaming
Regarding #668, exercising Gaussian interpolation (including #958) still leads to an error in my test case (using ITK @ 8f67778c95) employing streaming:
https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/223961167
```
itk::ExceptionObject (0x7fc848002c90)
Location: "unknown" 
File: /opt/itk/include/ITK-5.1/itkImageConstIteratorWithIndex.hxx
Line: 86
Description: itk::ERROR: Region ImageRegion (0x7fc8c9b11a18)
  Dimension: 3
  Index: [0, 0, 80]
  Size: [8, 8, 18446744073709551596]
 is outside of buffered region ImageRegion (0x1594768)
  Dimension: 3
  Index: [0, 0, 64]
  Size: [217, 202, 60]
```

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #988.

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

### CODE REVIEW

**Comment by dzenanz** [comment]
OK, this needs a pass on Linux compiler compatibility. On it.

**Comment by dzenanz** [comment]
It passes the tests now. Please review.

**Comment by hjmjohnson** [comment]
@dzenanz Needs merge conflict resolution.

**Comment by romangrothausmann** [comment]
@dzenanz What is the reason why a random input image did not trigger this problem while [`ACN_speed.mhd`](https://gitlab.com/romangrothausmann/ITK-CLIs/tree/f701756e0fe4580384efdb849a5e62af34a63f27/tests/data) does (https://github.com/InsightSoftwareConsortium/ITK/issues/988#issuecomment-499163387)?

**Comment by dzenanz** [comment]
Maybe because I supplied .nhdr file, and NRRD does not support streaming even for reading? In retrospect, I should have paid more attention to that.

**Comment by dzenanz** [comment]
An updated code points out the differences. `out4.mha` file contains an additional field in the header: `ElementSize = 1 1 1`. If I copy this to `out1.mha` using a text editor, the files become identical.
```C++
#include <itkImageFileReader.h>
#include <itkResampleImageFilter.h>
#include <itkGaussianInterpolateImageFunction.h>
#include <itkImageFileWriter.h>

using ImageType = itk::Image<int, 3>;
using ReaderType = itk::ImageFileReader<ImageType>;
using FilterType = itk::ResampleImageFilter<ImageType, ImageType>;
using TransformType = itk::IdentityTransform<double, 3>;
using InterpolatorType = itk::GaussianInterpolateImageFunction<ImageType>;
using WriterType = itk::ImageFileWriter<ImageType>;

int main(int argc, char** argv)
{
    ReaderType::Pointer reader = ReaderType::New();
    reader->SetFileName(argv[1]);
    reader->UpdateOutputInformation();
    ImageType::Pointer input = reader->GetOutput();

    typename TransformType::Pointer transform = TransformType::New();
    transform->SetIdentity();
    typename ImageType::SpacingType outputSpacing;
    outputSpacing.Fill(1.0);

    FilterType::Pointer filter = FilterType::New();
    filter->SetInput(reader->GetOutput());
    filter->SetInterpolator(InterpolatorType::New());
    filter->SetSize(input->GetLargestPossibleRegion().GetSize());
    filter->SetOutputOrigin(input->GetOrigin());

    filter->SetTransform(transform);
    filter->SetOutputSpacing(outputSpacing);
    filter->SetOutputDirection(input->GetDirection());
    filter->SetDefaultPixelValue(0);
    filter->ReleaseDataFlagOn();

    WriterType::Pointer writer = WriterType::New();
    writer->SetInput(filter->GetOutput());
    try
    {
        writer->SetFileName("C:/Misc/Tester/out1.mha");
        writer->SetNumberOfStreamDivisions(1);
        writer->Update();

        writer->SetFileName("C:/Misc/Tester/out4.mha");
        writer->SetNumberOfStreamDivisions(4);
        writer->Update();
    }
    catch (itk::ExceptionObject& exc)
    {
        std::cout << exc;
        return EXIT_FAILURE;
    }

    return EXIT_SUCCESS;
}
```

**Comment by romangrothausmann** [comment]
> additional field in the header:

That I do not observe to be the difference for the MD5s (tested with writing to MHDs: MHDs identical, MD5s of RAWs differ), instead `output_SDI.mha` contains only `NaN` from slice 65 onwards, which probably is the reason why `stat` for `output_SDI.mha` prints:
```
Min: -1.52596 Max: 1.42494 Mean: -nan Std: -nan Variance: -nan Sum: -nan
```
see: https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/227298454

**Comment by dzenanz** [comment]
Well, how about you modify the current MWE to demonstrate the problem?

**Comment by romangrothausmann** [comment]
Working on that (https://gitlab.com/romangrothausmann/ITK-CLIs/commits/debugGaussRes), with local testing I do get differing MD5s as soon as I put
```
    reader->ReleaseDataFlagOn();
```
in before `reader->UpdateOutputInformation();`

**Comment by romangrothausmann** [comment]
However, removing `reader->ReleaseDataFlagOn();` in `resample.cxx` (https://github.com/romangrothausmann/ITK-CLIs/commit/378b8394064d4156abeafa00c9ca05048e512e6c) does not make its test for Gauss succeed...
On the ohter hand, adding differing `outputSpacing` to the MWE (https://github.com/romangrothausmann/ITK-CLIs/commit/1540e43009069678c7a1af77af63539a96b214bd) does not lead to differing MD5s on the RAWs.

**Comment by dzenanz** [comment]
The `reader->ReleaseDataFlagOn();` makes only the least piece of the output have correct information, the rest is filled with junk. I think this is yet another, separate bug with streaming.

I will merge this PR, as it is a noticeable improvement (no crashing, works well without ReleaseDataFlagOn).

Can you create a new bug report, or even better a PR proposing a new [test](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Core/ImageFunction/test) which demonstrates the problem with streaming+ReleaseDataFlagOn+GaussianInterpolateImageFunction? The MWE we have in this thread can be easily reworked into the desired regression test. Or perhaps update [itkResampleImageTest7](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageGrid/test/itkResampleImageTest7.cxx) to also test GaussianInterpolateImageFunction and ReleaseDataFlagOn?

**Comment by romangrothausmann** [comment]
> I will merge this PR, as it is a noticeable improvement (no crashing, works well without ReleaseDataFlagOn).

Approved.

> Can you create a new bug report, or even better a PR proposing a new test which demonstrates the problem with streaming+ReleaseDataFlagOn+GaussianInterpolateImageFunction? The MWE we have in this thread can be easily reworked into the desired regression test. Or perhaps update itkResampleImageTest7 to also test GaussianInterpolateImageFunction and ReleaseDataFlagOn?

That, or similar, hope to find the time for continuing debugging next week.

> out4.mha file contains an additional field in the header

What could be the reason for that? Even with https://github.com/romangrothausmann/ITK-CLIs/commit/1540e43009069678c7a1af77af63539a96b214bd the non-streaming output lack the entry `ElementSize`, which should not be the case.

**Comment by blowekamp** [comment]
I have never used the `ReleaseDataFlag` with streaming before as when streaming the buffer is reused for the region processed. Is this a problem with just this combination or a general architecture problem with the data pipeline?

**Comment by romangrothausmann** [comment]
@blowekamp all other interpolators in my [`resampe.cxx`](https://github.com/romangrothausmann/ITK-CLIs/blob/7fe6fab256ec0da28feae5229936bf58b9aa3f96/resample.cxx#L142-L195) seem to work all right with `ReleaseDataFlag`, it is only the Gauss Interpolator that causes trouble.

**Comment by dzenanz** [comment]
I think I tried linear, and it worked correctly.

**Comment by romangrothausmann** [comment]
Found a way to reproduce the problem, just scoping all and running the streaming separately: https://github.com/romangrothausmann/ITK-CLIs/commit/eb81cb5ea63d3ac4edf0a97471ae776b129b0dee
That way each MHD has its `ElementSize` and the RAWs differ (and yield exactly the same output as `resample.cxx`.

**Comment by romangrothausmann** [comment]
Not sure though why the version without scoping behaves differently. Could it be that the filter is not re-executed even though it has `filter->ReleaseDataFlagOn();`? Without that it would be necessary to outdate the filter to have it re-execute for the streaming.

**Pull request merged**
