### PR TITLE
Double convert 3.3.0

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by blowekamp** [comment]
@dzenanz I had to manually restore a couple files from before the Update script was run. Do you have an example of how those files can remain? How could the Update script be modified to do so?

**Comment by dzenanz** [comment]
Restored how? I guess that should be accomplished by commands in the short script here:
https://github.com/InsightSoftwareConsortium/ITK/blob/v5.4.0/Modules/ThirdParty/DoubleConversion/UpdateDoubleConversionFromGoogle.sh#L21

**Comment by dzenanz** [comment]
Mark as ready? And merge?

**Comment by blowekamp** [comment]
I did a `git checkout HEAD~2  src/double-conversion/src/double-conversion-configure.h.in src/double-conversion/CMakeLists.txt` and amended to the merge. I am not clear on the environment that the update script operates in to change it to preserve these files.

**Comment by dzenanz** [comment]
@bradking might have advice.

**Comment by hjmjohnson** [comment]
Updating this package is such a rare occurrence that I think we could merge this PR as is.

**Comment by bradking** [comment]
Also, be sure that this is not merged with GitHub's squash merge feature.  That will erase the corrected history structure.

**Comment by dzenanz** [comment]
OK, so merge commit or manual push to master.

**Comment by bradking** [comment]
Yes, I recommend merging with a dedicated merge commit rather than a direct push fast-forwarding `master`.  Certainly no rebase or squash.

**Pull request merged**
