### PR TITLE
BUG: Add '_d' POSTFIX to Windows Python Debug (#2050)

### PR DESCRIPTION
**Pull request by brad-t-moore**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by brad-t-moore** [comment]
Resolves #2050

**Comment by thewtex** [comment]
`ITK.macOS` has a test failure for  a JPEG 2000 test, which is likely unrelated.

**Review by thewtex — APPROVED** [review]

**Review by dzenanz — COMMENTED** [review]
Change looks good, building...

**Review by N-Dekker — APPROVED** [review]
Thanks!

**Comment by dzenanz** [comment]
This seems to work, namely complaining about missing numpy (I don't have debug version of it).

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
