### PR TITLE
COMP: Explicitly instantiate LBFGSOptimizerBasev4

### PR DESCRIPTION
**Pull request by fabian-philips**
Fixes wrapping of LBFGSOptimizerBasev4 with Python and resulting duplicate symbols. Solution was to remove most of the functionality of the template implementation header into a cxx file and explicitly instantiate with required types.

Discussed here https://discourse.itk.org/t/itk-5-3-0-5-4rc-build-errors-shared-libs-python-wrappings-itkvtkglue-vs-2022-win11/6327

- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by fabian-philips** [comment]
What I did:

1. Move the .hxx code to a new .cxx file (except for the Basev4Helper class-related lines)
2. Copied and adjusted the explicit instantiation snippet from ObjectToObjectOptimizerBaseTemplate
3. Explicitly instantiated types that were not found by the linker (vnl_lbfgs, vnl_lbfgsb)

**Comment by jhlegarreta** [comment]
Re https://github.com/InsightSoftwareConsortium/ITK/pull/4397#issuecomment-1890408521 please, adhere to the [ITK commit message practices](https://docs.itk.org/en/latest/contributing/index.html#commit-messages):
- Add a meaningful, self-contained commit message body.
- Limit the length of the commit message subject to 72 characters.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
@fabian-philips yes, that's it, excellent work! :clap: :pray:

**Comment by jhlegarreta** [comment]
Ah, sorry, I have realized about this once this has been merged: the commit itself was not changed, and only the PR message got changed. So re https://github.com/InsightSoftwareConsortium/ITK/pull/4397#issuecomment-1890450845 @fabian-philips please, use appropriate commit messages in your future contributions. Thank you.

**Pull request merged**
