### PR TITLE
WIP: Tiggering CI on release-4.13

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
@thewtex Any idea why the Azure Pipes didn't get triggered?

**Comment by thewtex** [comment]
@blowekamp I am not sure why the Azure Pipelines builds were not triggered for the other platforms. It is worth trying a rebuild with

```
git commit --amend
git review-push --force
```

**Comment by blowekamp** [comment]
@thewtex Seems to work now. Thanks.


BTW, the review-push script is not in release-4.13.

**Comment by blowekamp** [comment]
It's is best not to commit this code into release.

**Pull request closed without merging**
