### PR TITLE
COMP: Fix linking problems with external HDF5

### LINKED ISSUE #1799: [ITK 5.1] Not building with external HDF5
### Description
Linker error due to missing HDF5 symbols
```
[1462/4340] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIOFactory.cxx.obj Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIO.cxx.obj  /out:bin\ITKIOHDF5-5.1.dll /implib:lib\ITKIOHDF5-5.1.lib /pdb:bin\ITKIOHDF5-5.1.pdb /dll /version:1.0 /nologo  /machine:x64  /nologo  /debug /INCREMENTAL  lib\ITKIOImageBase-5.1.lib  D:\qt2\installed\x64-windows\debug\lib\zlibd.lib  lib\ITKCommon-5.1.lib  lib\itksys-5.1.lib  ws2_32.lib  dbghelp.lib  psapi.lib  lib\ITKVNLInstantiation-5.1.lib  lib\itkvnl_algo-5.1.lib  lib\itkvnl-5.1.lib  lib\itkv3p_netlib-5.1.lib  lib\itknetlib-5.1.lib  lib\itkvcl-5.1.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
FAILED: bin/ITKIOHDF5-5.1.dll lib/ITKIOHDF5-5.1.lib 
cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_dll --intdir=Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe  Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIOFactory.cxx.obj Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIO.cxx.obj  /out:bin\ITKIOHDF5-5.1.dll /implib:lib\ITKIOHDF5-5.1.lib /pdb:bin\ITKIOHDF5-5.1.pdb /dll /version:1.0 /nologo  /machine:x64  /nologo  /debug /INCREMENTAL  lib\ITKIOImageBase-5.1.lib  D:\qt2\installed\x64-windows\debug\lib\zlibd.lib  lib\ITKCommon-5.1.lib  lib\itksys-5.1.lib  ws2_32.lib  dbghelp.lib  psapi.lib  lib\ITKVNLInstantiation-5.1.lib  lib\itkvnl_algo-5.1.lib  lib\itkvnl-5.1.lib  lib\itkv3p_netlib-5.1.lib  lib\itknetlib-5.1.lib  lib\itkvcl-5.1.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
LINK Pass 1: command "C:\PROGRA~2\MIB055~1\2019\COMMUN~1\VC\Tools\MSVC\1425~1.286\bin\Hostx64\x64\link.exe Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIOFactory.cxx.obj Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir\itkHDF5ImageIO.cxx.obj /out:bin\ITKIOHDF5-5.1.dll /implib:lib\ITKIOHDF5-5.1.lib /pdb:bin\ITKIOHDF5-5.1.pdb /dll /version:1.0 /nologo /machine:x64 /nologo /debug /INCREMENTAL lib\ITKIOImageBase-5.1.lib D:\qt2\installed\x64-windows\debug\lib\zlibd.lib lib\ITKCommon-5.1.lib lib\itksys-5.1.lib ws2_32.lib dbghelp.lib psapi.lib lib\ITKVNLInstantiation-5.1.lib lib\itkvnl_algo-5.1.lib lib\itkvnl-5.1.lib lib\itkv3p_netlib-5.1.lib lib\itknetlib-5.1.lib lib\itkvcl-5.1.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir/intermediate.manifest Modules\IO\HDF5\src\CMakeFiles\ITKIOHDF5.dir/manifest.res" failed (exit code 1120) with the following output:
   Creating library lib\ITKIOHDF5-5.1.lib and object lib\ITKIOHDF5-5.1.exp
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol H5open referenced in function "public: virtual bool __cdecl itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UEAA_NPEBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol H5check_version referenced in function "public: virtual bool __cdecl itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UEAA_NPEBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol H5Aexists referenced in function "bool __cdecl itk::`anonymous namespace'::doesAttrExist(class H5::H5Object const &,char const * const)" (?doesAttrExist@?A0x9346111f@itk@@YA_NAEBVH5Object@H5@@QEBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol H5Fis_hdf5 referenced in function "public: virtual bool __cdecl itk::HDF5ImageIO::CanReadFile(char const *)" (?CanReadFile@HDF5ImageIO@itk@@UEAA_NPEBD@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: char const * __cdecl H5::Exception::getCDetailMsg(void)const " (?getCDetailMsg@Exception@H5@@QEBAPEBDXZ) referenced in function __catch$?ReadImageInformation@HDF5ImageIO@itk@@UEAAXXZ$0
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: class H5::IdComponent & __cdecl H5::IdComponent::operator=(class H5::IdComponent const &)" (??4IdComponent@H5@@QEAAAEAV01@AEBV01@@Z) referenced in function "public: class H5::H5Location & __cdecl H5::H5Location::operator=(class H5::H5Location const &)" (??4H5Location@H5@@QEAAAEAV01@AEBV01@@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: __cdecl H5::DataSpace::DataSpace(enum H5S_class_t)" (??0DataSpace@H5@@QEAA@W4H5S_class_t@@@Z) referenced in function "public: virtual void __cdecl itk::HDF5ImageIO::Read(void *)" (?Read@HDF5ImageIO@itk@@UEAAXPEAX@Z)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: __cdecl H5::DataSpace::DataSpace(int,unsigned __int64 const *,unsigned __int64 const *)" (??0DataSpace@H5@@QEAA@HPEB_K0@Z) referenced in function "public: virtual void __cdecl itk::HDF5ImageIO::WriteImageInformation(void)" (?WriteImageInformation@HDF5ImageIO@itk@@UEAAXXZ)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: int __cdecl H5::DataSpace::getSimpleExtentDims(unsigned __int64 *,unsigned __int64 *)const " (?getSimpleExtentDims@DataSpace@H5@@QEBAHPEA_K0@Z) referenced in function "public: virtual void __cdecl itk::HDF5ImageIO::ReadImageInformation(void)" (?ReadImageInformation@HDF5ImageIO@itk@@UEAAXXZ)
itkHDF5ImageIO.cxx.obj : error LNK2019: unresolved external symbol "public: int __cdecl H5::DataSpace::getSimpleExtentNdims(void)const " (?getSimpleExtentNdims@DataSpace@H5@@QEBAHXZ) referenced in function "public: virtual void __cdecl itk::HDF5ImageIO::ReadImageInformation(void)" (?ReadImageInformation@HDF5ImageIO@itk@@UEAAXXZ)

```

### Steps to Reproduce

Clone https://github.com/Neumann-A/vcpkg/tree/update_itk_51
just run (after bootstrapping vcpkg of course)
`./vcpkg.exe install vtk[vtkm,python,qt,paraview,atlmfc] itk[vtk,python]

`

### Versions

5.1

### Environment

vcpkg/windows

### Additional Information

[config-x64-windows-dbg-out.log](https://github.com/InsightSoftwareConsortium/ITK/files/4587757/config-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out.log](https://github.com/InsightSoftwareConsortium/ITK/files/4587758/install-x64-windows-dbg-out.log)

### Additional Information
<removed mentioned in #1696 keep focus here on related issue>

Probably related to:
https://github.com/InsightSoftwareConsortium/ITK/blob/7900a8b6d63ec8201405eff3b46c8d2a4e563c45/CMake/ITKModuleMacros.cmake#L160-L168
and 
https://github.com/InsightSoftwareConsortium/ITK/blob/7900a8b6d63ec8201405eff3b46c8d2a4e563c45/Modules/IO/HDF5/CMakeLists.txt#L2

The following is also a very bad idea if your `_LIBRARIES` are not all targets (due to optimized/debug keywords):
https://github.com/InsightSoftwareConsortium/ITK/blob/7900a8b6d63ec8201405eff3b46c8d2a4e563c45/CMake/ITKModuleMacros.cmake#L166

If it is all targets probably rename it to `_TARGETS` instead

### PR DESCRIPTION
**Pull request by KrisThielemans**
Libraries were set via CMake variables HDF5_C_SHARED_LIBRARY etc,
which were not necessarily set, depending on HDF5 version, hdf5-config.cmake
etc.

This update priorities import targets like hdf5-shared etc. It attempts to cope with different targets used by different versions of HDF5 and CMake's FindHDF5.cmake.

This is based on suggestions by @Neumann-A in #1799 and #1696.

Fixes #1799. 
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x ] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Comment by KrisThielemans** [comment]
I have tried to preserve backwards compatibility by using the same variables and order as the existing code, but there's room for improvement here

- I really don't understand why the original code used both `hdf5_cpp-shared` and `hdf5-shared`. The former should be sufficient
- When no targets exist, I just make a long list of variables. Personally I think only `HDF5_LIBRARIES` should be sufficient.
- The HDF5 config and `FindHDF5.cmake` situation is quite messy. See [this CMake discussion for some info](https://gitlab.kitware.com/cmake/cmake/-/issues/18560#note_881956). I've currently prioritised the `config` targets before the `FindHDF5` variables (they currently don't see dependencies I believe).

Caveat: I really don't understand the following lines https://github.com/InsightSoftwareConsortium/ITK/blob/ee2ab9c973e66616cc2132f9a96fcf7763a6b94d/Modules/ThirdParty/HDF5/CMakeLists.txt#L20-L32
I don't know how they're used, but it's a mystery to me why this seems to search only with `NO_MODULE`. That just seems wrong.

Caveat: I have no good way to test this, as I don't use HDF5 IO with ITK. I only checked if it allowed me to build ITK and the variables came out ok (tested with CMake 3.19.2 and Visual Studio 2019).

**Comment by KrisThielemans** [comment]
`ITK.Linux.Python` job failed [because](https://dev.azure.com/itkrobotlinuxpython/ITK.Linux.Python/_build/results?buildId=3841&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58be928-45a1-58e7-c1ad-04869565b3f4&l=6691)
```
Unable to find executable: /home/vsts/work/1/s-build/Wrapping/Generators/Python/itk/itkTestDriver
```
which doesn't have anything to do with this PR

**Review by dzenanz — COMMENTED** [review]
hdf5 is C library, hdf5_cpp is C++ library. There are others: hdf5_hl etc.

[This code](https://github.com/InsightSoftwareConsortium/ITK/blob/ee2ab9c973e66616cc2132f9a96fcf7763a6b94d/Modules/ThirdParty/HDF5/CMakeLists.txt#L20-L32) is executed in projects which depend (directly or indirectly) on ITKIOHDF5.

I think there are some tests which invoke HDF5 IO functionality, so if they pass all should be good. Please rebase on current master to see whether that resolves the test driver issue.

**Comment by KrisThielemans** [comment]
> hdf5 is C library, hdf5_cpp is C++ library.

ah, I thought that the C++ library depended on the C library, but it doesn't seem to. Sorry.

> Please rebase on current master to see whether that resolves the test driver issue.

done

**Comment by KrisThielemans** [comment]
still the same testdriver problem, e.g. https://dev.azure.com/itkrobotlinux/ITK.Linux/_build/results?buildId=5222&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58be928-45a1-58e7-c1ad-04869565b3f4&l=128567
```
Could not find executable /home/vsts/work/1/s-build/bin/ITKWatershedsTestDriver
```

**Comment by thewtex** [comment]
@KrisThielemans thanks for the contribution :pray: 

A breakdown of the build errors can be found here:

https://open.cdash.org/index.php?project=Insight&date=2021-01-11&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=PR2247

There is an include directory error:

> Modules/ThirdParty/HDF5/src/itkhdf5/H5Cpp.h:3:10: error: '../c++/src/H5Cpp.h' file not found, did you mean 'c++/src/H5Cpp.h'?

**Comment by KrisThielemans** [comment]
thanks @thewtex . I am a bit baffled by this. Possibly @hjmjohnson could help as that file [was created by him](
https://github.com/InsightSoftwareConsortium/ITK/commit/9e0d33cd1ed4a52fc4c55cdaf9e0550690ce4d6f#diff-65879e5d81f79207b490e2eb56d198795dff8106ab6be72617f705d1de5a9c7e).

As far as I can see, I haven't changed anything related to include files (and `ITKHDF5_INCLUDE_DIRS`), but I must be wrong.

Do these tests run with `ITK_USE_SYSTEM_HDF5:BOOL=ON`? Probably not, but I can't figure out if they are or not (sorry).

**Comment by thewtex** [comment]
> Do these tests run with ITK_USE_SYSTEM_HDF5:BOOL=ON?

No, the builds run with mostly default build options `ITK_USE_SYSTEM_HDF5:BOOL=ON`.

**Comment by KrisThielemans** [comment]
I've been trying to understand, but fail... Here' s what I found.
1. if a system HDF5 is used, this include never happens, so it compiles without trouble (which is why I hadn't seen it).
Therefore the rest of the diagnositics is when using ITK's HDF5.
1. `#include "../c++/src/H5Cpp.h"` is trying to find `SOURCE\Modules\ThirdParty\HDF5\src\itkhdf5\c++\src\H5Cpp.h`
2. Checking the `vcxproj`, when using `master`, the following directories are added to the include path for `ITKIOTransformHDF5` (and other HDF5 projects, and not to others)
     - `BUILD\Modules\ThirdParty\HDF5\src\itkhdf5\c++\src`
     - `SOURCE\Modules\ThirdParty\HDF5\src\itkhdf5\c++\src`
     - `BUILD\Modules\ThirdParty\HDF5\src\itkhdf5\src`
     - `SOURCE\Modules\ThirdParty\HDF5\src\itkhdf5\src`
 3. It's the last one that "saves the day"
 4. Those 4 directories are not present on the include path when using this PR, causing the error.
 5. Unfortunately, I have no idea where those directories are added. I first thought it was [here](https://github.com/InsightSoftwareConsortium/ITK/blob/e2c71059e47d5e77c647aab5b799121090fdf4ec/Modules/ThirdParty/HDF5/CMakeLists.txt#L58-L61) but `ITKHDF5_SOURCE_DIR` is  `SOURCE/Modules/ThirdParty/HDF5/` (both when using `master` and this PR).

If anyone could help, that'd be much appreciated.

**Comment by KrisThielemans** [comment]
Ok, the problem was that I tried to make the logic for setting `ITKHDF5_LIBRARIES ` common to both cases. That failed when `ITK_USE_SYSTEM_HDF5=OFF`, as `hdf5-shared` isn't a `TARGET` yet when the `CMakeLists.txt` get processed. Therefore, `ITKHDF5_LIBRARIES` was empty. (And it's `hdf5-shared` that will set the include dependency).

This is quite subtle... I still don't really understand how it all fits together. However, I guess some of this should be documented in the file, such that an overzealous clean-up doesn't create trouble later on.  For now, I've committed it to see what happens with the test-runs.

**Review by thewtex — APPROVED** [review]
@KrisThielemans great work! HDF5's Cmake configuration is a bit complex, but it looks like you have handled the situation well.

**Pull request merged**
