### PR TITLE
ENH: Support for tuples passed as arguments through itkTemplate New()…

### PR DESCRIPTION
**Pull request by fbudin69500**
… function

To set options for an ITK filter in Python, one can directly pass a value
inside the New() function call. However, this was only working if the
corresponding C++ function was expecting only one argument. This commit
allows a user to pass multiple arguments at once as a list.

### CODE REVIEW

**Comment by fbudin69500** [comment]
No PR was created against `master` yet as this PR should ideally only be merged after issue #270 is fixed to make sure that all the tests actually pass.

**Comment by thewtex** [comment]
Rebasing on `master`...

**Comment by hjmjohnson** [comment]
@thewtex All tests are passing.  Is this ready to rebase on master and bring into the master branch?

**Comment by hjmjohnson** [comment]
Removing blocked status since #270 has been addressed.

**Comment by thewtex** [comment]
@hjmjohnson rebased and ready to go! Merging! Thanks @fbudin69500 for the awesomeness and patience :unicorn: !

**Pull request merged**
