### PR TITLE
ENH: Support for non-compliant DICOM in itk-js

### PR DESCRIPTION
**Pull request by jmargeta**
Adds support for non-compliant DICOM headers (but otherwise readable files) in Javascript (itk-js).
This PR aligns the GDCM IO behavior in Javascript with the one in C++ or Python.

A custom build with this works just fine for me.
Are there any other pending reasons for this stricter behavior only in js?

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by dzenanz** [comment]
Using git's blame feature, it is easy to figure out 6322422d82e215e39057ac93ae662c730675743e added that. It was done in PR #423.

**Comment by jmargeta** [comment]
Thanks for the pointer, @dzenanz.

I agree that this was clearly useful when DCMTK is used as the IO for DICOMs:
https://github.com/InsightSoftwareConsortium/ITK/pull/423#issuecomment-455284890

GDCM has already been made the default IO for DICOMs in itk-js here:
https://github.com/InsightSoftwareConsortium/itk-js/pull/316
So maybe the original constraint does not apply anymore?

**Comment by dzenanz** [comment]
> maybe the original constraint does not apply anymore

Maybe, but Matt should decide.

**Comment by thewtex** [comment]
@jmargeta thanks for the patch!

To confirm, you re-built the itk.js Docker images with this branch, ran the test suite, and everything passed?

**Comment by jmargeta** [comment]
@thewtex, yup, almost like that.

To be sure my custom Docker images are used I also changed all the "FROM"s in the itk-base, itk-js, and itk-js-vtk docker images and all the references in the build files to point to our Docker registry.
The difference from this PR is that instead of deleting the ` && !defined(__EMSCRIPTEN__) ` I replaced it with `!defined(__IGNORETHISDEF__)` just after the git checkout step in the itk-base's Dockerfile:
```dockerfile
RUN git clone https://github.com/InsightSoftwareConsortium/ITK.git && \
  cd ITK && \
  git checkout ${ITK_GIT_TAG} && \
  cd ../ && \
  sed -i -e 's/__EMSCRIPTEN__/__IGNORETHISDEF__/' /ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx && \
  sed -i -e '/^option(OPJ_USE_THREAD/c\option(OPJ_USE_THREAD "use threads" OFF)' \
...
```
Based on the DICOMSeriesTest.js I also added a new test with the non-compliant DICOM series (composed of two files).
Running ```npm build``` and then ```npm run test:browser``` passes fine. 

When I now re-run the test suite with the ```npm run test```,  I am getting:
```
  9 tests failed

  runPipelineNodeSyncTest › runPipelineNodeSync uses input and output files in the Emscripten filesystem

  dist/runPipelineEmscripten.js:32

   31:   };                                                   
   32:   var stream = emscriptenModule.open(path, opts.flags);
   33:   var stat = emscriptenModule.stat(path);              

  Error thrown in test:

  TypeError {
    message: 'emscriptenModule.open is not a function',
  }

  readFileSharedArray (dist/runPipelineEmscripten.js:32:33)
  dist/runPipelineEmscripten.js:145:36
  runPipelineEmscripten (dist/runPipelineEmscripten.js:130:13)
  runPipelineNodeSync (dist/runPipelineNodeSync.js:7:16)
  test/runPipelineNodeSyncTest.js:43:39
...
```
This is happening also for the clean build without the proposed changes and looks unrelated to this PR.

I would love to contribute the test and the sample data, but I cannot share the files as is.
Anonymizing the file fixes the headers, unfortunately.

Also a side note, I originally had the test DICOM files inside a ```.raw_dicom``` subfolder and was getting 404s from the test runner. This can be resolved by removing the dot.

**Comment by thewtex** [comment]
> Based on the DICOMSeriesTest.js I also added a new test with the non-compliant DICOM series (composed of two files).
Running npm build and then npm run test:browser passes fine.

Great!

> message: 'emscriptenModule.open is not a function',

> This is happening also for the clean build without the proposed changes and looks unrelated to this PR.

This is suggesting that your build may not be using your custom Docker images. `open` was added recently to the code that gets injected into the Emscripten module when built:

https://github.com/InsightSoftwareConsortium/itk-js/blob/61d3fe9099056eb21665a048b320ce81cd62471e/src/EmscriptenModule/itkJSPost.js#L89-L91

Are the `kitware/itk-js-vtk:latest` images rebuilt locally or was the build script changed to point to your images?

https://github.com/InsightSoftwareConsortium/itk-js/blob/61d3fe9099056eb21665a048b320ce81cd62471e/build.js#L55

https://github.com/InsightSoftwareConsortium/itk-js/blob/61d3fe9099056eb21665a048b320ce81cd62471e/build.js#L263

Also, I have noticed that Node 12 and Node 14 have build errors -- Node 10 may be required.

**Comment by jmargeta** [comment]
Thanks a lot for your response, @thewtex !

Everything should be pointing to our custom image names.
In the build files and in the Dockerfiles, I modified all the Docker image references from `kitware/*` and `insighttoolkit/*` to our container registry names  in the form of `xyx.azurecr.io/*`. 

I rebuilt everything locally (including the images), from scratch, for several times already with the same errors.
It is possible that Docker has been re-using the cached versions without me noticing that or that I've just been doing something silly. Also I was on Node 14 originally, but a quick switch to 10 did not help..

I've just switched to Node v10.23.0 (npm v6.14.8) with nvm + removed all related Docker images (tagged and dangling) local  and from our custom container registry.

Now, I am rebuilding it all from scratch once again, my build sequence now boils down to this:
```sh
git clone  https://github.com/InsightSoftwareConsortium/itk-js.git
cd itk-js
nvm use v10.23.0
npm install
src/Docker/itk-js-base/build.sh
src/Docker/itk-js/build.sh
src/Docker/itk-js-vtk/build.sh
npm run build
npm run test
```
Is this a correct way to locally build and test itk-js from source?

I'll report the results here once it gets done.

**Comment by thewtex** [comment]
> Is this a correct way to locally build and test itk-js from source?

@jmargeta yes, perfect, thanks for testing!

> I'll report the results here once it gets done.

How did it go?

**Comment by jmargeta** [comment]
@thewtex all tests seem to pass just fine now here including the change. 
I just had to rebuilt it all from scratch on another PC which never had a chance to see those Docker images before.

The most likely cause for the failure on the original machine was that an incorrect image was indeed used for my subsequent builds. My partition reserved for Docker images got full (those builds are huge) and the latest images were either not being stored correctly or were evicted too early.

**Comment by thewtex** [comment]
@jmargeta great, thanks for update and contribution!

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
CC @floryst @aylward

**Comment by jmargeta** [comment]
Fantastic, thank you @thewtex !

**Pull request merged**
