### PR TITLE
MetaIO 2024-07-13 (918ad45f)

### PR DESCRIPTION
**Pull request by dzenanz**
Code extracted from:

    https://github.com/Kitware/MetaIO.git

at commit 918ad45f911fb11c4d66965040201b7678c9c8be (master).

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by aylward — APPROVED** [review]
LGTM!

**Review by thewtex — APPROVED** [review]

**Comment by jhlegarreta** [comment]
Valgrind has started reporting leaks related to the classes in MetaIO
https://open.cdash.org/builds/9769472/dynamic_analysis

First report was on 2024-07-12:
https://open.cdash.org/index.php?project=Insight&date=2024-07-12

I will not be able to dig into this.

**Comment by aylward** [comment]
I'm on it!

**Comment by aylward** [comment]
Memory leak addressed in PR https://github.com/Kitware/MetaIO/pull/131

**Comment by dzenanz** [comment]
Follow-up PR: https://github.com/InsightSoftwareConsortium/ITK/pull/4776

**Comment by dzenanz** [comment]
Sorry, I mean that follow-up PR is #4784.

**Comment by jhlegarreta** [comment]
:1st_place_medal: thanks @aylward.

**Comment by jhlegarreta** [comment]
Warnings are gone. Thanks @aylward :100:
https://open.cdash.org/builds/9786403/dynamic_analysis

**Pull request merged**
