### PR TITLE
BUG: Condition FFT wrappings on complex types

### PR DESCRIPTION
**Pull request by tbirdso**
Addresses discussion in #3048 and #2884 surrounding scenario where a real type, i.e. `double`, may be enabled for ITK Python wrappings but its corresponding complex type, i.e. `std::complex<double>`, is not enabled. Adds checks to three FFT class templates to ensure that the classes are not wrapped if either real or complex pixel types are not available.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by tbirdso** [comment]
FYI @dzenanz

**Review by dzenanz — COMMENTED** [review]
Instead of this, we could make `ITK_WRAP_complex_float` a dependent option of `ITK_WRAP_float` in CMake. Analogously for double. Wrapping for complex does not make much sense without the base type. That would prevent needing this here, and in other places. A cleanup of `.wrap` files could be done then.

**Comment by dzenanz** [comment]
Here is an example of how to make a dependent option:
https://github.com/InsightSoftwareConsortium/ITK/blob/v5.3rc02/CMakeLists.txt#L328-L330

**Comment by tbirdso** [comment]
@dzenanz If I understand correctly, this fix addresses the opposite problem from what you're suggesting -- rather than worrying about the scenario where `ITK_WRAP_COMPLEX_DOUBLE=ON` but `ITK_WRAP_DOUBLE=OFF`, this is intended to address the failure where `ITK_WRAP_COMPLEX_DOUBLE=OFF` and `ITK_WRAP_DOUBLE=ON`. I think the latter case, where a user wants double wrappings but no `std::complex` wrappings, is an uncommon but reasonable scenario.

Making complex types dependent on real types is valid but I'm not sure it is required or warranted by this issue.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
:+1:

**Pull request merged**
