### PR TITLE
BUG: Add missing Python string prefix in wrapping warning

### PR DESCRIPTION
**Pull request by SimonRit**
The prefix was accidentally removed during refactoring of the Python wrapping in 53e4fe066fa0955a2a4ee5899b400477ff93f198.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Sneaky bug.

**Comment by N-Dekker** [comment]
> The prefix was accidentally removed during refactoring of the Python wrapping in 53e4fe066fa0955a2a4ee5899b400477ff93f198

Looking at its diff, it seems to me that commit 53e4fe066fa0955a2a4ee5899b400477ff93f198 did _not_ remove the prefix (`f`) from `"as {cl}"`:

```
             message = (
-                "Template %s\n already defined as %s\n is redefined " "as %s"
-            ) % (normFullName, self.__templates__[normFullName], cl)
+                f"Template {normFullName}\n already defined as {itkTemplateBase.__all_templates__[normFullName]}\n is redefined "
+                "as {cl}"
+            )

```

But I agree, it should be added anyway 😺

**Review by hjmjohnson — APPROVED** [review]
GREAT CATCH!

**Pull request merged**
