### PR TITLE
ENH: add RTK as a remote module

### PR DESCRIPTION
**Pull request by SimonRit**
We (mainly @LucasGandel) have been working hard to make RTK a remote module of ITK for the new RTK v2.0.0 release (see SimonRit/RTK@68cb6b2). It would be an achievement to include this remote module file in the ITK repository to ease compilation of RTK for users. I'm looking forward to it!

### CODE REVIEW

**Comment by LucasGandel** [comment]
This is awesome! Thank you Simon for your hard work and Matt for your help.

[Dashboard](https://my.cdash.org/index.php?project=RTK) are green and CI is on. Fully transition to ITKv5 is on the way.

We still haven't uploaded the python packages to PyPi and don't have automatically generated packages (too long to be built on CI) but it should/used to work locally.
We started some work to handle generation of RTK python packages with custom options [here](https://github.com/SimonRit/RTKPythonPackage). I need to have a look at it to see if this is still needed.

**Comment by SimonRit** [comment]
@LucasGandel I already have linux and macos packages (default ITK options, without Cuda). Can you delete your itk-rtk project from PiPy to let me upload them?

**Comment by LucasGandel** [comment]
@SimonRit Done. I deleted the project from https://test.pypi.org/.
I had nothing on the PyPi though.

**Comment by thewtex** [comment]
Please go ahead and publish what is ready -- exciting!

FYI, I am exploring Azure Pipelines for module builds here: https://github.com/InsightSoftwareConsortium/ITKHigherOrderAccurateGradient/pull/12 . This will address timeouts, and simplify both configuration and deployment!

**Comment by LucasGandel** [comment]
Thanks for sharing @thewtex ! Seems very promising!

**Comment by SimonRit** [comment]
Finally done see [message](https://public.kitware.com/pipermail/rtk-users/2019-February/010695.html) on RTK's mailing list. I have had quite some difficulties in generating the packages, is it useful to report? Except for minor modifications on the RTKPythonPackages repository (SimonRit/RTKPythonPackage@fd9e5fc), the problems were
- Compile windows packages in C:\P
- On Windows, help scikit-build find the compiler by setting the env as in a MSVC++ shell.
- Compile MacOS packages in /Users/kitware/Dashboards
- On MacOS, use the same xcode as the cached one. I downgraded to 9.4.1 instead of 10.1

Maybe one should clarify this on the [doc](https://itkpythonpackage.readthedocs.io/en/latest/Build_ITK_Python_packages.html).

That would be awesome to simplify confugation and deployment, I'm looking forward to this. Thanks a lot @thewtex for all your efforts!

**Comment by thewtex** [comment]
> Finally done see [message](https://public.kitware.com/pipermail/rtk-users/2019-February/010695.html) on RTK's mailing list.

Absolutely awesome! :tada: Congratulations @SimonRit @LucasGandel ! :1st_place_medal: 



> * Compile windows packages in C:\P
> 
> * On Windows, help scikit-build find the compiler by setting the env as in a MSVC++ shell.
> 
> * Compile MacOS packages in /Users/kitware/Dashboards
> 
> * On MacOS, use the same xcode as the cached one. I downgraded to 9.4.1 instead of 10.1

All correct. A patch for the doc's that helps a reader would be welcome. These are practical limitations, but we do our best to limit their impact. The `C:\P` is due to Windows line length build limitations, the Windows and macOS package paths are related to the module infrastructure, .... We have RTK Python packages, which is remarkable, and fantastic :raised_hands: :rocket: . The macOS X-code version is related to the TravisCI environment, but migration to Azure Pipelines will alleviate that issue in addition to many more pain points. The future is bright!

On the configuration front, C++ Linux, macOS, and Windows tests along with cross-platform Python package builds is working :tada: :

  https://dev.azure.com/InsightSoftwareConsortium/ITKModules/_build/results?buildId=149

A deployment configuration, which tests the Python packages, deploys to GitHub, and deploys to PyPI on approval is in the works:

  https://dev.azure.com/InsightSoftwareConsortium/ITKModules/_release

**Pull request merged**
