### PR TITLE
STYLE: Catch exceptions by _const_ reference

### PR DESCRIPTION
**Pull request by N-Dekker**
Replaced `catch \((\w+) &` with `catch (const $1 &`, using Visual Studio 2019, Find and Replace, Replace in Files, Use regular expressions.

Following C++ Core Guidelines, April 10, 2022, which says that it is "typically better" to catch by `const` reference than to catch by non-const reference. At https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#e15-throw-by-value-catch-exceptions-from-a-hierarchy-by-reference

Discussed at C++ Core Guidelines issue https://github.com/isocpp/CppCoreGuidelines/issues/518 "Catch exceptions by _const_ reference?", from February 3, 2016.

### CODE REVIEW

**Comment by Leengit** [comment]
Good idea!  I change a few more when I use:
```shell
cd git/ITK
find . -type f | egrep '\.[it]?(cc|hh|[ch](\+\+|pp?|xx)?)$' | fgrep -v ThirdParty | \
    xargs sed -r -i \
        -e 's/catch \((const )?/catch (const /g' \
        -e 's/catch \(const \.\.\.\)/catch (...)/g'
```
Just in case the changes this makes aren't some that you have already considered and rejected ... running that after your commits and then running `git diff --name-only` lists:
Modules/IO/DCMTK/src/itkDCMTKImageIO.cxx
Modules/IO/PhilipsREC/src/itkPhilipsPAR.cxx
Modules/IO/PhilipsREC/src/itkPhilipsRECImageIO.cxx
Modules/Numerics/FEM/include/itkFEMImageMetricLoad.hxx
Modules/Numerics/FEM/test/itkFEMElement2DTest.cxx
Modules/Numerics/FEM/test/itkFEMElement3DTest.cxx
Modules/Numerics/FEM/test/itkFEMElementTest.cxx
Modules/Numerics/FEM/test/itkFEMExceptionTest.cxx
Modules/Numerics/FEM/test/itkFEMGenerateMeshTest.cxx
Modules/Numerics/FEM/test/itkFEMSolverHyperbolicTest.cxx
Modules/Registration/FEM/test/itkFEMRegistrationFilter2DTest.cxx
Modules/Registration/FEM/test/itkFEMRegistrationFilterTest.cxx
Modules/Registration/FEM/test/itkFEMRegistrationFilterTest2.cxx

**Comment by N-Dekker** [comment]
> Good idea! I change a few more when I use:
> 
> ```shell
> cd git/ITK
> find . -type f | egrep '\.[it]?(cc|hh|[ch](\+\+|pp?|xx)?)$' | fgrep -v ThirdParty | \
>     xargs sed -r -i \
>         -e 's/catch \((const )?/catch (const /g' \
>         -e 's/catch \(const \.\.\.\)/catch (...)/g'
> ```

Thanks @Leengit. Please check the [force-push](https://github.com/InsightSoftwareConsortium/ITK/compare/d864f73c6103c5c2a8adf26bb5d457a15b837eb6..65ea9258411b3bb30476926b7dd1957a9c75fe28) that I just did  😃

**Comment by Leengit** [comment]
Text-wise, I see one more possibility (though perhaps it was rejected for other reasons):
https://github.com/InsightSoftwareConsortium/ITK/blob/6e20b32eef66f32436197c1f1a766310eb5939e7/Modules/Numerics/FEM/test/itkFEMSolverHyperbolicTest.cxx#L187

**Review by thewtex — APPROVED** [review]
:+1:

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
> Text-wise, I see one more possibility (though perhaps it was rejected for other reasons):
> 
> https://github.com/InsightSoftwareConsortium/ITK/blob/6e20b32eef66f32436197c1f1a766310eb5939e7/Modules/Numerics/FEM/test/itkFEMSolverHyperbolicTest.cxx#L187

@Leengit Sorry the PR is merged already. Feel free to do a follow-up. But as far as I can see, it's the only case that still wasn't fixed with this PR. With this PR, I only looked for `catch \((\w+) &` and  `catch \((\w+::\w) &`, so I missed the one case with two colons pairs (`::`).

**Comment by N-Dekker** [comment]
For the record, this pull request appears to be a follow-up to pull request #1492 "COMP: Exceptions should be caught by constant reference", commit 0cf2baf077e1e8e86cd552836458e2313d737379  by Hans (@hjmjohnson), merged on 14 December 2019.

**Pull request merged**
