### PR TITLE
DOC: Link groups in Doxygen in module description

### PR DESCRIPTION
**Pull request by jhlegarreta**
Create links to referenced groups when generating the Doxygen documentation from the module description.

Doxygen grouping documentation:
https://www.doxygen.nl/manual/grouping.html

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Preferred to submit separately from PR #3648 so that one or the other can be merged and its effect in the dashboard (warnings, etc.) and Doxygen can be checked prior to merging the other one.

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
I merged PR #3648. I leave it to you to merge this one after you have checked that the 3648 didn't cause issues.

**Review by thewtex — APPROVED** [review]
📖 nice!

**Comment by jhlegarreta** [comment]
Unfortunately this did not work, really sorry: the documentation generation has stripped anything after the "\ref" commands; it is either not being processed correctly of the module/group names/labels are inaccurate.

e.g. 
segmentation_description_changes

resulting in
segmentation_description

Not sure where to look at for now. Suggestions are welcome.

**Pull request merged**
