### PR TITLE
DOC: Add HDF5 GitHub upstream in post-commit hook

### PR DESCRIPTION
**Pull request by thewtex**
Notify contributors of the upstream contribution repository.

### CODE REVIEW

**Review by hjmjohnson — APPROVED** [review]
Excellent!

**Review by dzenanz — APPROVED** [review]

**Comment by hjmjohnson** [comment]
@thewtex Is this where upstream info for NIFTI should go as well?

**Comment by hjmjohnson** [comment]
@mseng10   Please review all the Thirdparty upstreams that use GIT and ensure that a mapping exists in the post-commit hook identifying where the upstream is.

**Review by jhlegarreta — APPROVED** [review]

**Comment by thewtex** [comment]
Superceded by https://github.com/InsightSoftwareConsortium/ITK/pull/2330

**Pull request closed without merging**
