### PR TITLE
Update VNL to 2021-07-19 (22f874db)

### LINKED ISSUE #2651: Missing limits include
### Description

ITK build fails for a missing include.

### Steps to Reproduce

1. Try to compile ITK 5.2.0

### Expected behavior

Get the code built

### Actual behavior

Build fails for a missing include

### Reproducibility

100%

### Versions

ITK 5.2.0

### Environment

Arch Linux
GCC 11.1
CMake 3.21.0

### Additional Information

Adding
#include <limits>
to Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangePhotometricInterpretation.h
fix the issue.

### PR DESCRIPTION
**Pull request by dzenanz**
Code extracted from:

    https://github.com/vxl/vxl.git

at commit 22f874db61407f087795521884a0c407274b789d (master).

Closes #2651.

### CODE REVIEW

**Comment by thewtex** [comment]
Awesome @dzenanz !

Was this branched from `release`? We should integrate into `release` for the patch release, and branching / merging to `release` first will work well with Git.

**Comment by dzenanz** [comment]
This is only a minor update. Bigger update was merged recently. But that one had the WriteCompilerDetectionHeader feature removed. I don't think it is a good candidate for backporting.

**Review by jhlegarreta — APPROVED** [review]
Not sure what is the best way to proceed concerning Matt's comment to branch from `release`/do not see reasons against. I'm fine either way.

**Comment by dzenanz** [comment]
If we really want to update VNL in a patch release, we should start from release branch and run update script with a commit just before removal of WriteCompilerDetectionHeader (that would be [cc84ffb](https://github.com/vxl/vxl/commit/cc84ffb342a6208d5bdf3d463b7d166a3092e702)). But I suppose we can live with 5.2's then-current VNL - we don't have to update it for 5.2.1.

**Pull request merged**
