### PR TITLE
ENH: Add registration of TIFF ImageJ tags

### PR DESCRIPTION
**Pull request by blowekamp**
These tag are commonly generate warning messages, by adding them to the FieldInfo no warning is generated.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
The site for registration private TIFF tags seems to be not one line. I found this in the archives:
https://web.archive.org/web/20240420004104/https://www.awaresystems.be/imaging/tiff/tifftags/private.html

**Comment by jcfr** [comment]
Thanks, for reference. in the context of Slicer, the "unknown" tags we would like to ignore are `65280` and `65281`:

```
$ tiffinfo ~/Downloads/sample/Scan_0101__rec00001890.tif 
TIFFReadDirectory: Warning, Unknown field with tag 65280 (0xff00) encountered.
TIFFReadDirectory: Warning, Unknown field with tag 65281 (0xff01) encountered.
TIFF Directory at offset 0x3a7950 (3832144)
  Subfile Type: (0 = 0x0)
  Image Width: 1348 Image Length: 1420
  Resolution: 2822, 2822 pixels/inch
  Bits/Sample: 16
  Compression Scheme: None
  Photometric Interpretation: min-is-black
  Samples/Pixel: 1
  Rows/Strip: 3
  Planar Configuration: single image plane
  Tag 65280: -100
  Tag 65281: 13400
```

That said, since it is challenging to finding reference for the definition of those, how about extending this patch adding the following:

```cpp
  // For example of occurrences of 65280 and 65281 unknown tags. See https://github.com/SlicerMorph/SlicerMorph/issues/320
  { static_cast<ttag_t>(65280), -1, -1, TIFF_UNDEFINED, FIELD_CUSTOM, true, true, "Tag 65280" },
  { static_cast<ttag_t>(65281), -1, -1, TIFF_UNDEFINED, FIELD_CUSTOM, true, true, "Tag 65281" },
```

Until the support for officially ignoring unknown tags is integrated in upstream libtiff, this may be a reasonable path forward ?

Related issues and pull requests:
* https://github.com/SlicerMorph/SlicerMorph/issues/320
* https://github.com/Slicer/Slicer/pull/8016

**Comment by lassoan** [comment]
Thank you for working on this @blowekamp. Now that the fix in libtiff is merged upstream, I'm wondering if we should use this fix. I've already backported it to ITK's libtiff (https://github.com/InsightSoftwareConsortium/ITK/pull/4920) and it all seems very simple.

**Comment by blowekamp** [comment]
What are the TIFF tags that are giving you the warnings?

I don't think there is much benefit for using this change for just reading TIFF TAGS as they were already being loaded correctly into ITK's meta-data dictionary.

**Comment by jcfr** [comment]
> What are the TIFF tags that are giving you the warnings?

Those are listed above in my recent comment.

> backport libtiff fix

I instead suggest we move forward with the backport of @lassoan aiming to avoid reporting warnings related to unknown tags.

**Comment by lassoan** [comment]
Thanks a lot @jcfr and @blowekamp for all the discussions and prototyping efforts!

**Pull request closed without merging**
