### PR TITLE
ENH: use the new CMake mechanism to specify MSVC's static or DLL CRT

### LINKED ISSUE #2872: Windows runtime linking flags (/MD or /MT) are not downstreamed to internal DCMTK build
Hello ITK team!

### Description

When DCMTK is built through the external project on Windows, the runtime linking flags (/MD, /MT, /MDd, /MTd) don't seem to be downstreamed into the DCMTK config by cmake. 
The configuration collides when one try to build an application, as by default ITK config set dynamic linking while DCMTK set static,  (ITK and DCMTK do both build seamlessly though).

### Steps to Reproduce

1. Build ITK with ITKDCMTK, ITKIODCMTK and ITKIOTransformDCMTK 
2. Compare the CMAKE_CXX_FLAGS_*** from ITK and ITKDCMTK_ExtProject cmake caches

ITK cache:
```
# This is the CMakeCache file.
# For build in directory: c:/Libraries/Builds/ITK_5.2.1

[...]

//Flags used by the CXX compiler during all build types.
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//Flags used by the CXX compiler during DEBUG builds.
CMAKE_CXX_FLAGS_DEBUG:STRING=/MDd /Zi /Ob0 /Od /RTC1

//Flags used by the CXX compiler during MINSIZEREL builds.
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MD /O1 /Ob1 /DNDEBUG

//Flags used by the CXX compiler during RELEASE builds.
CMAKE_CXX_FLAGS_RELEASE:STRING=/MD /O2 /Ob2 /DNDEBUG

//Flags used by the CXX compiler during RELWITHDEBINFO builds.
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MD /Zi /O2 /Ob1 /DNDEBUG
```

ITKDCMTK_ExtProject cache:
```
# This is the CMakeCache file.
# For build in directory: c:/Libraries/Builds/ITK_5.2.1/Modules/ThirdParty/DCMTK/ITKDCMTK_ExtProject-build

[...]

//msvc compiler flags
CMAKE_CXX_FLAGS:STRING=/DWIN32 /D_WINDOWS /W3 /GR /EHsc

//msvc compiler flags
CMAKE_CXX_FLAGS_DEBUG:STRING=/MTd /Zi /Ob0 /Od /RTC1

//msvc compiler flags
CMAKE_CXX_FLAGS_MINSIZEREL:STRING=/MT /O1 /Ob1 /DNDEBUG

//msvc compiler flags
CMAKE_CXX_FLAGS_RELEASE:STRING=/MT /O2 /Ob2 /DNDEBUG

//msvc compiler flags
CMAKE_CXX_FLAGS_RELWITHDEBINFO:STRING=/MT /Zi /O2 /Ob1 /DNDEBUG
```

### Expected behavior
ITK config overwriting DCMTK config

### Actual behavior
No ITK config overwriting

### Reproducibility
100%

### Versions
5.2.1 

### Environment

OS: Windows 10
CMake: 3.21.4
Compiler: MSVC 2019 14.29.30133

### Additional Information
N/A

### PR DESCRIPTION
**Pull request by dzenanz**
Related to #2872.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Comment by dzenanz** [comment]
@MrTzschr, @liupeiqiHN and @tim-evain your opinion is welcome.

I have not tested to confirm that this fixes #2872. Tim, can you test and report?

**Review by jhlegarreta — COMMENTED** [review]
Have not tried.

Does this happen on other OS?

**Comment by tim-evain** [comment]
@dzenanz 
New variable `ITK_MSVC_STATIC_RUNTIME_LIBRARY` does correctly switch ITK config, but has no impact on underlying DCMTK configuration regarding #2872 (i.e. when off, DCMTK is still built with static CRT)

**Comment by dzenanz** [comment]
This needs an addition of passing this flag to external projects, such as DCMTK and Expat, but probably others, too.

**Comment by hjmjohnson** [comment]
@dzenanz  Is this still a draft?

**Comment by dzenanz** [comment]
Yes. While this commit on its own is fine, some logical connected changes are needed to make this resolved, as I [commented earlier](https://github.com/InsightSoftwareConsortium/ITK/pull/2887#issuecomment-977169074).

**Comment by dzenanz** [comment]
@tim-evain I just updated this. Can you test now?

**Comment by tim-evain** [comment]
@dzenanz DCMTK is still built against static CRT when `ITK_MSVC_STATIC_RUNTIME_LIBRARY` is OFF. 
I do see `CMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreadedDLL` in the CMakeCache of the external project build, but the compiler flags still have `/MT(d)`. I'm not sure how that interacts with the property setting made by `CMAKE_MSVC_RUNTIME_LIBRARY` but I guess compiler flags overwrite that setting?

**Comment by dzenanz** [comment]
[Policy 91](https://cmake.org/cmake/help/latest/policy/CMP0091.html) needs to be set to `NEW` for the `CMAKE_MSVC_RUNTIME_LIBRARY` to have an effect. The policy could be set manually, or by requiring minimum CMake version of 3.15 or higher. Otherwise compiler flags govern which CRT will be linked.

I guess DCMTK sets those flag somewhere, as it want to link to static CRT. And since it has [CMP0091 implicitly as OLD](https://github.com/InsightSoftwareConsortium/DCMTK/blob/9354a6457b70748db9c062e81115394341f612c0/CMakeLists.txt#L2-L5), passed setting has no effect.

**Comment by dzenanz** [comment]
Even the [latest DCMTK](https://github.com/DCMTK/dcmtk/blob/a5a6fc38accce2c738ba2c2690ee1e8aad1dfb39/CMakeLists.txt#L2) tops out at CMake 3.13.2.

**Review by hjmjohnson — APPROVED** [review]
I am not a windows expert, but all these changes appear reasonable.

**Review by thewtex — APPROVED** [review]

**Pull request merged**
