### PR TITLE
ENH: Update a few remote modules to their latest commit versions

### PR DESCRIPTION
**Pull request by jhlegarreta**
Update a few remote modules to their latest commit versions.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Let's see if this helps bringing the [Expected Nightly Remotes in CDash](http://testing.cdash.org/index.php?project=Insight#!#Expected_Nightly_Remote_Modules) to the green.

**Comment by gdevenyi** [comment]
Shouldn't these be done separately?

**Comment by jhlegarreta** [comment]
@gdevenyi There is no fixed rule. See the following commits as an example: https://github.com/InsightSoftwareConsortium/ITK/commit/fbfabd8cbdf331b5ca203034b86a0266ef572905, https://github.com/InsightSoftwareConsortium/ITK/commit/4792824e3dbb163ab2d9ee1ab07502b73f01c67d

**Comment by jhlegarreta** [comment]
Also, and although I may have missed some in this PR, updating each separately brings an overhead in terms of PRs that may not pay off. IMHO.

**Comment by jhlegarreta** [comment]
@gdevenyi This should facilitate maintaining the remote modules up-to-date in ITK: https://github.com/InsightSoftwareConsortium/ITK/pull/632

**Pull request merged**
