### PR TITLE
BUG: Limits, spacing, and direction in ComputeJacobianWithRespectToPosition

### PR DESCRIPTION
**Pull request by josempozo**
In the previous version, the limits, spacing, and direction of the displacement field were incorrectly managed. This pull amends all of them, providing the correct behaviour.

The test itkDisplacementFieldTransformTest has been modified to include anisotropic spacing and non-trivial grid direction. The test is not passed by the previous version.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Looks good on a glance.

**Comment by josempozo** [comment]
The automatic checks seems to result in failing builds for linux and macOs. But I cannot see which is the error. Actually they also say that all test are passed.

Is there anything that I should correct for this?

**Comment by dzenanz** [comment]
We need to look up build results on the dashboard, here is the link to yesterday: [https://open.cdash.org/index.php?project=Insight&date=2022-02-08](https://open.cdash.org/index.php?project=Insight&date=2022-02-08). You need to search for `PR3179` there. Here are the direct links to build warnings:
https://open.cdash.org/viewBuildError.php?type=1&buildid=7729530
https://open.cdash.org/viewBuildError.php?type=1&buildid=7729304
https://open.cdash.org/viewBuildError.php?type=1&buildid=7729305
https://open.cdash.org/viewBuildError.php?type=1&buildid=7729424
https://open.cdash.org/viewBuildError.php?type=1&buildid=7729572

**Comment by josempozo** [comment]
> We need to look up build results on the dashboard, here is the link to yesterday: https://open.cdash.org/index.php?project=Insight&date=2022-02-08. You need to search for `PR3179` there. Here are the direct links to build warnings: https://open.cdash.org/viewBuildError.php?type=1&buildid=7729530 https://open.cdash.org/viewBuildError.php?type=1&buildid=7729304 https://open.cdash.org/viewBuildError.php?type=1&buildid=7729305 https://open.cdash.org/viewBuildError.php?type=1&buildid=7729424 https://open.cdash.org/viewBuildError.php?type=1&buildid=7729572

Thanks for the links. I think that I have solved the appearing warning now.

**Review by thewtex — APPROVED** [review]
@josempozo thank you for the contribution!

**Pull request merged**
