### PR TITLE
DOC: Use Doxygen syntax to create automatic links to members

### PR DESCRIPTION
**Pull request by jhlegarreta**
Use Doxygen syntax to create automatic links to members.

According to the relevant Doxygen documentation:
https://doxygen.nl/manual/autolink.html

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Similar to #3650, can be merged after that one and prior to #3648 and #3649, as this one is less extensive and hopefully less problematic than the latter two.

**Comment by jhlegarreta** [comment]
\azp ITK.macOS

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Jon, merge when appropriate.

**Review by thewtex — APPROVED** [review]
Cool! 😎

**Comment by jhlegarreta** [comment]
These are now linked, exactly as expected from the Doxygen documentation ! Hurray ! We now have a working example for cross-class member documentation linking in ITK :tada: :fireworks:.

**Pull request merged**
