### PR TITLE
STYLE: Fix several spelling errors

### PR DESCRIPTION
**Pull request by Leengit**
```bash
cd ITK
find . -type f | fgrep -v ThirdParty | egrep '\.[hc](xx|pp)?$' | \
  xargs sed -i -r \
    -e 's/(o|O)uput/\1utput/g' \
    -e 's/(u|U)sefull/\1seful/g' \
    -e 's/(a|A)sign/\1ssign/g' \
    -e 's/(s|S)waping/\1wapping/g' \
    -e 's/(m|M)easurment/\1easurement/g' \
    -e 's/(r|R)essource/\1esource/g' \
    -e 's/(l|L)enght/\1ength/g' \
    -e 's/the all the/all the/g' \
    -e 's/[nN]-[dD]imensional/n-dimensional/g' \
    -e 's/([^A-Za-z])a n-dimensional/\1an n-dimensional/g' \
    -e 's/([^A-Za-z])a itk/\1an itk/g' \
    -e 's/([^A-Za-z])a an([^A-Za-z])/\1an\2/g'
```

Also, change "a" -> "an" where appropriate.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Maybe you could add `lenght` to the list? Instances:
https://github.com/InsightSoftwareConsortium/ITK/blob/828453d1bf61c487310d2d8c9570093e08798a40/Modules/Numerics/Statistics/test/itkListSampleTest.cxx#L409
https://github.com/InsightSoftwareConsortium/ITK/blob/da13473cb02267f0086468236b5612c4caf28e46/Modules/Core/Common/include/itkNumericTraitsVariableLengthVectorPixel.h#L31

**Review by N-Dekker — APPROVED** [review]

**Comment by Leengit** [comment]
Thank you @dzenanz and @N-Dekker for the follow up suggestions.  They are in there now, except that I changed strings to `n-dimensional` rather than `N-dimensional`.

**Review by N-Dekker — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]
It turns out lenght was quite popular 😄

**Comment by N-Dekker** [comment]
@Leengit This PR is ready now, right? I guess so, because it isn't in draft status. On the other hand I can imagine that you may want to keep the PR open until each and every typo is fixed 😸

**Comment by Leengit** [comment]
Please merge.

**Review by hjmjohnson — APPROVED** [review]

**Comment by Leengit** [comment]
I just rebased against the newly current master; no other changes.

**Pull request merged**
