### PR TITLE
Revert "Merge pull request #1039 from samuelgerber/MultithreadPointSe…

### PR DESCRIPTION
**Pull request by hjmjohnson**
…tToPointSetMetricv4"

This reverts commit 687c49176ba97fbbe805fc468bd96ec36b46ffc0, reversing
changes made to 9ef036a9cbc2a9f42059f4574fdcf4f0fc83bf88.

itkTimeVaryingBSplineVelocityFieldPointSetRegistrationTest test became unstable on
many platforms due to the changes in this patch set.  A stable refactoring is needed
before this is included in the main branch.

### CODE REVIEW

**Comment by dzenanz** [comment]
Sam is trying to hunt down the bug, let's give him a day or two before merging this.

**Comment by hjmjohnson** [comment]
I'm concerned that this is slowing down progress on other PR's since it is causing red dashboards.

I'm OK with waiting 1 or 2 more days, but I'd like to push other PR's through even if this test fails.

**Comment by hjmjohnson** [comment]
@samuelgerber Have you made any progress on resolving the test failures?  If you think it will be many more days, I suggest we revert the original patch, then re-apply the original patch with the bug fix at a later time.

**Comment by dzenanz** [comment]
He is going on some trip tomorrow, if he doesn't resolve the issue by then we will merge this revert.

**Comment by samuelgerber** [comment]
I think I found it. Testing right now.

**Comment by hjmjohnson** [comment]
Yippie!  Fingers crossed.

**Comment by samuelgerber** [comment]
I hope I submitted a fix. I can't get it to crash anymore on my linux box ( at least for the time it has been running).

**Comment by samuelgerber** [comment]
Fixed that, if nothing else brakes maybe good to go now.

**Comment by hjmjohnson** [comment]
The tests is still failing.  As @samuelgerber will be on vacation starting tomorrow, I propose that we revert the original patch set to get green dashboards until this can be tracked down further.

**Pull request merged**
