### PR TITLE
Get vnl matrix reference

### PR DESCRIPTION
**Pull request by SimonRit**
This PR adds a test to PR #601 as discussed on [discourse](https://discourse.itk.org/t/numpy-vnl-bridge-unexpected-behavior/1659).

### CODE REVIEW

**Comment by fbudin69500** [comment]
Thanks @SimonRit . In general, it is easier to just push on the branch that you are trying to modify directly (i.e. you would have had to add my repo as a remote on your machine). Since you have created a new PR, I closed the old one. And since it is a PR that changes Python code, I am going to create another PR against the `Python-build` branch to start a Python build on the CI machines.

**Comment by SimonRit** [comment]
Ok thanks. I did add your repo as a remote but I did not I could push to it. Or should I have created a PR on your branch?

**Comment by fbudin69500** [comment]
Normally, you just have to push to my branch, and it should work. I don't know if I should have had to give you some permissions, but when I did it for other people's PRs it worked without having to request any additional permission. Next time we can try :)

**Comment by blowekamp** [comment]
@fbudin69500 I believe to push to a PR's fork you need to the a maintainer of the upstream repo:
https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Pull request merged**
