### PR TITLE
ENH: Enable LZW compression

### LINKED ISSUE #3277: LZW compression in TIFFimageIO.
### Description

Based on a quick online search, it appears that the patent on LZW has expired (but don't quote me on the this). So [lzw patent](https://github.com/InsightSoftwareConsortium/ITK/blob/1d68414c4ec026c0086122569301a9576839873a/Modules/IO/TIFF/src/itkTIFFImageIO.cxx#L696) is perhaps not an issue for tiff images anymore. However, if using it is still not possible, what is the point of exposing LZW compression? Why not just remove the option from TiffImageIO? 

### Expected coding style

Remove LZW comrpression option from TiffImageIO.

### PR DESCRIPTION
**Pull request by HaaPut**
Enable LZW compression in TIFF images now that its patent has expired.
fixes #3277

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Comment by HaaPut** [comment]
It looks like macOS python piipeline failed due to unrelated network issues. Is there a way to rerun the pipeline?

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
@HaaPut thank you!

**Pull request merged**
