### PR TITLE
ENH: fix Windows Bitmap (BMP) channel order ABGR -> BGRA

### LINKED ISSUE #2596: BMP files with alpha channel are read with incorrect channel order
When a 32-bit ARGB BMP file is loaded using ITK, the colors are all mixed up.

### Description

BMP files with transparency are stored with ARGB channel order. It seems that ITK assumes RGBA order.

### Steps to Reproduce

Load this image using ITK: https://1drv.ms/u/s!Arm_AFxB9yqHxcpbEw34sbS-h1pjkA?e=cf39o8

```python
img = sitk.ReadImage('15-14-49.bmp')
myshow(img)  # incorrect
```

```python
nda = sitk.GetArrayFromImage(img)
img2=sitk.GetImageFromArray(nda[:,:,[1,2,3,0]])
myshow(img2)  # correct
```

image

### Expected behavior

Colors should appear correctly in an application, regardless of what file format is loaded from (png, jpg, bmp, ...)

### Actual behavior

Colors are not correct if BMP format is used (if transparency is stored with the image).

### Reproducibility

100%

### Versions

v5.2.0

### Environment

all (Windows and Linux tested)

### Additional Information

See original user report at https://discourse.slicer.org/t/grey-level-image-looking-blue-or-other-color/18095/3

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #2596.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Comment by dzenanz** [comment]
Uh, I forgot to update regression tests. Will get to it, maybe tomorrow.

**Comment by dzenanz** [comment]
The first force-push updates the baseline image, the second rebased on master.

**Comment by dzenanz** [comment]
The latest force-push fixes ghostflow errors by adding newlines. This should be ready now.

**Review by thewtex — APPROVED** [review]

**Comment by lassoan** [comment]
This is great, thank you!

**Pull request merged**
