### PR TITLE
ENH: Add BUILD_SHARED_LIBS to macOS build CI configuration

### PR DESCRIPTION
**Pull request by thewtex**
See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:

Start ITK commit messages with a standard prefix (and a space):

 * BUG: fix for runtime crash or incorrect result
 * COMP: compiler error or warning fix
 * DOC: documentation change
 * ENH: new functionality
 * PERF: performance improvement
 * STYLE: no logic impact (indentation, comments)
 * WIP: Work In Progress not ready for merge

Provide a short, meaningful message that describes the change you made.

When the PR is based on a single commit, the commit message is usually left as the PR message.

A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

[@mentions](https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams) of the person or team responsible for reviewing proposed changes.

Thanks for contributing to ITK!

### CODE REVIEW

**Comment by mathstuf** [comment]
Do: check

**Comment by mathstuf** [comment]
Ah, this is ignored because it targets the `python-builds` branch. @bradking

**Comment by bradking** [comment]
@thewtex didn't you ask for `python-builds` to be a nightly follower of `master`?  There should be no PRs targeting it directly.

**Comment by thewtex** [comment]
`python-builds` is currently used to trigger Python builds. But, this configuration is a WIP and may changed.

**Comment by thewtex** [comment]
We prefer static builds on macOS.

**Pull request closed without merging**
