### PR TITLE
COMP: apply upstream fix to eigen warning suppressions

### PR DESCRIPTION
**Pull request by seanm**
From upstream:
https://gitlab.com/libeigen/eigen/-/merge_requests/819

### CODE REVIEW

**Comment by seanm** [comment]
@phcerdan @dzenanz

**Review by hjmjohnson — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
:green_heart:

**Comment by thewtex** [comment]
@seanm For formatting of our ChangeLog, please begin commit messages with a capital letter, i.e. *apply* -> *Apply*

**Comment by phcerdan** [comment]
This is great @seanm. Not sure if it is better to cherry-pick your commit upstream in [our eigen fork](https://gitlab.kitware.com/phcerdan/eigen/-/tree/for/itk-3.4), instead of merging it directly here.

**Comment by seanm** [comment]
@phcerdan oh, true, I forget about that other repo!  If you know how to do the cerry-pick magic, could you please?

**Comment by phcerdan** [comment]
Sure, let's continue at PR #3133

**Pull request closed without merging**
