### PR TITLE
WIP: Manual TEST -- Update to include changes from upstream MetaIO

### PR DESCRIPTION
**Pull request by hjmjohnson**
This was a manual merging of the upstream content.

The Update script failed to update the upstream
content correctly.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@dzenanz MetaIO needs to be updated to be in sync with the upstream master version of MetaIO.

There are 3 outstanding PRs that all seem to be sub-optimal.  
#2151 New PR from upstream including 2138 and several other C++11 cleanups to MetaIO.
#2143 Initial PR from upstream that includes 2138
#2138 Initial minor change directly to ITK requested to be upstreamed

**Comment by dzenanz** [comment]
The update script seems to be working correctly for @blowekamp, so I suggest we let him update.

**Comment by blowekamp** [comment]
PR #2143 was updated.

**Comment by hjmjohnson** [comment]
abandoned in favor of #2143

**Pull request closed without merging**
