### PR TITLE
ENH: Bump CastXML binaries to 0.3.6

### PR DESCRIPTION
**Pull request by thewtex**
And address omp.h include error with ITKElastix build.

### CODE REVIEW

**Review by hjmjohnson — APPROVED** [review]
Looks reasonable.

**Comment by hjmjohnson** [comment]
@thewtex Mac build failed.

**Comment by dzenanz** [comment]
Mac build error: https://open.cdash.org/viewBuildError.php?buildid=6892436
Linux test failure: https://open.cdash.org/test/291413943

**Comment by thewtex** [comment]
Split the required patch into #2130

**Pull request closed without merging**
