### PR TITLE
Reserved identifier

### PR DESCRIPTION
**Pull request by seanm**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
@hjmjohnson more double underscore fixes...

**Review by hjmjohnson — APPROVED** [review]

**Comment by seanm** [comment]
Not sure why I'm seeing 4 commits in this PR though... checking my git notes...

**Review by dzenanz — APPROVED** [review]
Aren't only leading underscores reserved?

**Comment by seanm** [comment]
> Aren't only leading underscores reserved?

No. See for example https://clang.llvm.org/extra/clang-tidy/checks/bugprone-reserved-identifier.html

**Comment by dzenanz** [comment]
Oh, they are. From [cppreference](https://en.cppreference.com/w/cpp/language/identifiers):
* the identifiers with a double underscore anywhere are reserved;
* the identifiers that begin with an underscore followed by an uppercase letter are reserved;
* the identifiers that begin with an underscore are reserved in the global namespace.

**Comment by dzenanz** [comment]
> The C standard additionally reserves names beginning with a double underscore

This is what I remembered about double underscores.

**Comment by dzenanz** [comment]
I guess that rename wasn't thorough: `Modules/Core/Common/include/itkMultiThreaderBase.h:245:1: error: unknown type name 'CLANG_SUPPRESS_Wc__14_extensions'`

**Comment by seanm** [comment]
Doh! Fixed.

**Review by dzenanz — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]

**Comment by seanm** [comment]
So almost all are fixed... there are just a few left:

https://open.cdash.org/viewBuildError.php?type=1&buildid=7630658

all in ThirdParty though...

@hjmjohnson do you think you could fix the vxl ones?  I recall you work on that project...

The HDF5 ones are already fixed upstream.

I could fix the `lbfgs.h` one, but there's no `UpdateFromUpstream.sh`... where does ITK inherit this code from?  From a fast search, [this](https://github.com/chokkan/liblbfgs) is maybe the source?

**Pull request merged**
