### PR TITLE
Update vnl 11 17 19

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
This patch should address warning in a newly configure nightly CentOS Valgrind build:
https://open.cdash.org/buildSummary.php?buildid=6212361

It looks like there are some recent changes related to implicit conversion of type:
https://github.com/vxl/vxl/commit/ccdcf37b27def61f3901d1473ca4c46db7517535

@hjmjohnson Are these changes ready for ITK?

**Comment by hjmjohnson** [comment]
> This patch should address warning in a newly configure nightly CentOS Valgrind build:
> https://open.cdash.org/buildSummary.php?buildid=6212361
> 
> It looks like there are some recent changes related to implicit conversion of type:
> [vxl/vxl@ccdcf37](https://github.com/vxl/vxl/commit/ccdcf37b27def61f3901d1473ca4c46db7517535)
> 
> @hjmjohnson Are these changes ready for ITK?


Brad,  VNL is ready, but ITK will need some work to convert the implicit type conversions to explicit type conversions.  At the moment the code continues to work, but many warnings are produced.

https://open.cdash.org/viewBuildError.php?type=1&buildid=6212572

When updating VXL to avoid implicit conversions, there were several places where the implicit conversions that were occurring were unnecessary if the types were more carefully matched or values taken from the original object rather than a converted version of the original.

**Comment by blowekamp** [comment]
The warning should be addressed. However, the deprecated warning message gave the wrong suggestion, but has been fixed in upstream VXL now. So well let this test complete, then update VNL again.

**Comment by dzenanz** [comment]
This has cut down the number of warnings to just a few. Good work!

**Comment by blowekamp** [comment]
I update VNL, but I got an error locally...

**Comment by blowekamp** [comment]
Everything looks OK on the dashboard as far as I can tell. Please review.

**Comment by dzenanz** [comment]
ghostflow complains about `commit 7b6a506 adds bad whitespace including CR/LF line endings:`
```text
core/vnl/vnl_vector.h:457: trailing whitespace.
+  
v3p/netlib/libf2c/comptry.bat:1: trailing whitespace.
+%1 %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/comptry.bat:2: trailing whitespace.
+if errorlevel 1 goto nolonglong⏎
v3p/netlib/libf2c/comptry.bat:3: trailing whitespace.
+exit 0⏎
v3p/netlib/libf2c/comptry.bat:4: trailing whitespace.
+:nolonglong⏎
v3p/netlib/libf2c/comptry.bat:5: trailing whitespace.
+%1 -DNO_LONG_LONG %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/scomptry.bat:1: trailing whitespace.
+%1 -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎
v3p/netlib/libf2c/scomptry.bat:2: trailing whitespace.
+if errorlevel 1 goto nolonglong⏎
v3p/netlib/libf2c/scomptry.bat:3: trailing whitespace.
+exit 0⏎
v3p/netlib/libf2c/scomptry.bat:4: trailing whitespace.
+:nolonglong⏎
v3p/netlib/libf2c/scomptry.bat:5: trailing whitespace.
+%1 -DNO_LONG_LONG -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎
```

**Comment by blowekamp** [comment]
> ghostflow complains about `commit 7b6a506 adds bad whitespace including CR/LF line endings:`
> 
> ```
> core/vnl/vnl_vector.h:457: trailing whitespace.
> +  
> v3p/netlib/libf2c/comptry.bat:1: trailing whitespace.
> +%1 %2 %3 %4 %5 %6 %7 %8 %9⏎
> v3p/netlib/libf2c/comptry.bat:2: trailing whitespace.
> +if errorlevel 1 goto nolonglong⏎
> v3p/netlib/libf2c/comptry.bat:3: trailing whitespace.
> +exit 0⏎
> v3p/netlib/libf2c/comptry.bat:4: trailing whitespace.
> +:nolonglong⏎
> v3p/netlib/libf2c/comptry.bat:5: trailing whitespace.
> +%1 -DNO_LONG_LONG %2 %3 %4 %5 %6 %7 %8 %9⏎
> v3p/netlib/libf2c/scomptry.bat:1: trailing whitespace.
> +%1 -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎
> v3p/netlib/libf2c/scomptry.bat:2: trailing whitespace.
> +if errorlevel 1 goto nolonglong⏎
> v3p/netlib/libf2c/scomptry.bat:3: trailing whitespace.
> +exit 0⏎
> v3p/netlib/libf2c/scomptry.bat:4: trailing whitespace.
> +:nolonglong⏎
> v3p/netlib/libf2c/scomptry.bat:5: trailing whitespace.
> +%1 -DNO_LONG_LONG -DWRITE_ARITH_H -DNO_FPINIT %2 %3 %4 %5 %6 %7 %8 %9⏎
> ```

That is clearly from the VXL project. @hjmjohnson may know more about the quality process there and how/why this got through and if it's OK for that third party library.

**Comment by hjmjohnson** [comment]
@blowekamp VXL is certainly less rigorous in its code style.  My primary goal of helping to maintain VXL is to work towards removing ITK's dependance on it :).

Patches to VXL are always welcome.

**Pull request merged**
