### PR TITLE
Use unsigned int for indexing into number of image dimensions

### PR DESCRIPTION
**Pull request by blowekamp**
Replace non-portable "long" type with "int".

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by N-Dekker** [comment]
I very much agree, the use of `long` is indeed troublesome when supporting both Linux and Windows. In this case (number of dimensions), `unsigned int` should be _long_ enough 😸

**Comment by N-Dekker** [comment]
@blowekamp I think I might approve your pull request, once it is "Ready for review"  😸

**Review by N-Dekker — APPROVED** [review]

**Comment by N-Dekker** [comment]
> ready for review 😄

@dzenanz approved  😄 😄

**Review by thewtex — APPROVED** [review]
:100:

**Pull request merged**
