### PR TITLE
STYLE: Remove ` == true` from Boolean expressions

### PR DESCRIPTION
**Pull request by N-Dekker**
Following C++ Core Guidelines, February 15, 2024, "Don’t add redundant `==` or `!=` to conditions",
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es87-dont-add-redundant--or--to-conditions

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Did you use some tool to find instances of this?

**Comment by thewtex** [comment]
Windows failure:

```
The following tests FAILED:
	779 - itkConvolutionImageFilterStreamingValidTest (Failed)
```

test flake?

**Comment by N-Dekker** [comment]
> Did you use some tool to find instances of this?

Well, I did it step by step, "heuristically", starting with a global search of just `m_UseImageSpacing == true`, then using regular expressions, `(  if \(\w+) == true\)`, `(  if \([^ ]+) == true\)`, normal search `== true)`, and `== true ||`, etc. Until I felt most relevant cases were addressed.

Looking back, I could have done just a brute force find `== true` and replace with (nothing). There are only a few  `== true` cases left now. Not sure if I should also address them.

**Comment by N-Dekker** [comment]
Also not addressed:

https://github.com/InsightSoftwareConsortium/ITK/blob/e3189492ce6858035b68a2b89e4a4d2f1d4041ad/Modules/Filtering/DistanceMap/test/itkSignedDanielssonDistanceMapImageFilterTest11.cxx#L124

**Comment by N-Dekker** [comment]
This one is not addressed, but maybe it should, what do you think?

https://github.com/InsightSoftwareConsortium/ITK/blob/e3189492ce6858035b68a2b89e4a4d2f1d4041ad/Modules/Core/Common/test/itkMetaProgrammingLibraryTest.cxx#L30

**Comment by dzenanz** [comment]
Yes, you could also update that.

**Comment by N-Dekker** [comment]
FYI While I think this pull request is very much in line with C++ Core Guidelines item "Don’t add redundant `==` or `!=` to conditions", I believe it would be helpful if the guideline would explicitly mention such `b == true` cases. So I also submitted a pull request to the C++ Core Guidelines 😃 :  

- https://github.com/isocpp/CppCoreGuidelines/pull/2185

**Pull request merged**
