### PR TITLE
[COMP] Fix unmangled type symbols on HDF5

### PR DESCRIPTION
**Pull request by fbordignon**
Hello, I was having trouble with an external python lib calling the itk_hdf5 function as shared below. The ?? sometimes indicates a callback but to be sure I searched all instances of H5VL_group_close and only H5G__close_cb was calling it currently unmangled. I will test this soon and report back.

<details>

```
#0  0x00007febfdaa8b49 in itk_H5CX_get_vol_wrap_ctx () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#1  0x00007febfdd23a44 in itk_H5VL_set_vol_wrapper () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#2  0x00007febfdd1870b in itk_H5VL_group_close () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#3  0x00007febfdb4b11d in ?? () from /home/gabriel/g/bin/../lib/GeoSlicer-5.1/libitkhdf5-shared-5.3.so.1
#4  0x00007fead7b7d480 in H5I_dec_ref () from /home/gabriel/g/lib/Python/lib/python3.9/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#5  0x00007fead7b7d544 in H5I_dec_app_ref () from /home/gabriel/g/lib/Python/lib/python3.9/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
#6  0x00007fead7b79fd1 in H5Idec_ref () from /home/gabriel/g/lib/Python/lib/python3.9/site-packages/h5py/../h5py.libs/libhdf5-346dbfc8.so.200.1.0
```
</details>

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
I now see that you didn't format commit message according to [guidelines](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#commit-messages). Please add `COMP: ` prefix.

**Comment by fbordignon** [comment]
Sorry, I've edited online with github. I always forget to use the guidelines when doing so. Just force pushed a fix. Thanks

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
Thanks Fernando. I just wonder why the problem occurred, and why the name mangling would be necessary for `H5G__close_cb`! You see, it looks like `H5G__close_cb` is a `static` C function inside a C source file of hdf5:

```
static herr_t
H5G__close_cb(H5VL_object_t *grp_vol_obj, void **request)
```
In https://github.com/HDFGroup/hdf5/blob/509fe962d42b3f02d356d2668b04712df06daf7f/src/H5Gint.c#L211-L212  

In general, a `static` C function is an internal function, for implementation only. (It has "static linkage".) So it should not be part of the HDF5 library interface, and I would not expect it to have any naming conflict. So then, why would it need to be mangled?

---
PS The commit message still looks a bit unusual: https://github.com/InsightSoftwareConsortium/ITK/pull/3882/commits/2b595db72c98419acc994da6fa00ff17be3d845d "Hello, I was having trouble with..." is a nice begin of an issue (bug report) at GitHub, but it is rather unusual in a commit message. In general a commit message should just _shortly_ tell what the commit does, and why. But to me the main question is: why would `H5G__close_cb` need to be mangled?

**Comment by fbordignon** [comment]
@N-Dekker thanks for pointing that out. You are right. I thought it was a quick fix but it did not solve the problem at first. The issue ended up being related to this [extern](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5private.h#L1816):
`extern H5_debug_t H5_debug_g;`
It somehow renamed H5_debug_g to H5_debug_t and ended up being unmangled on the final .so on linux.
Same issue with the other 3 I've commited:
```
00000000006618c0 B H5_debug_g
0000000000661a20 B H5E_stack_g
0000000000662160 B H5I_type_info_array_g
```

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
@fbordignon Glad to hear you fixed the problem!

Some detail:
You wrote:
> The issue ended up being related to this [extern](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5private.h#L1816):
`extern H5_debug_t H5_debug_g;`
> It somehow renamed H5_debug_g to H5_debug_t

Just for your information, that isn't a rename! It declares a global (`extern`) variable `H5_debug_g` of type `H5_debug_t`. Both the variable and its type should be mangled, to avoid naming conflicts. Which is what you actually did  😃

**Comment by fbordignon** [comment]
@N-Dekker that makes a lot more sense now 🤣 
Thank you!

**Comment by N-Dekker** [comment]
> Please, advise on a better commit message and/or PR title. 

Please check https://github.com/InsightSoftwareConsortium/ITK/blob/57624fda9a9a7aa4771481655e5fdd82e780f362/CONTRIBUTING.md#commit-messages  😃 

Moreover (I think the guidelines don't say so explicitly), I would suggest the subject line of the commit message to be very _specific_, so that it can be distinguished easily when looking through the commit history of ITK. For example (well below the maximum of 72 characters):

    COMP: Mangle HDF5 H5_debug symbols, H5E_t and H5I_type_info_t

For the body of the commit message, it would be sufficient to just mention the error that it fixes. Possibly also mention the platform. Did you get an error message, or just a stack trace?

    Fixes the following error on Ubuntu/Linux when doing...:
    ....

**Review by dzenanz — APPROVED** [review]

**Review by N-Dekker — APPROVED** [review]
Approved, thanks @fbordignon!  👍 

One more question, just out of interest... did you run `nm`, as suggested at https://github.com/InsightSoftwareConsortium/ITK/blob/0827484a4369d273eedee3e07657ef452acb1110/Modules/ThirdParty/HDF5/src/itkhdf5/src/itk_hdf5_mangle.h#L10-L18 ?

**Comment by fbordignon** [comment]
@N-Dekker I've tried, but `nm` with `-g` flag outputs "no symbols". I've used the `-D` flag and it showed the unmangled symbols mentioned above.

**Pull request merged**
