### PR TITLE
BUG: Error converting from rotation axis and rotation angle to quaternion

### PR DESCRIPTION
**Pull request by huangjxbq**
BUG: 由旋转轴和旋转角度转化为四元数错误

### CODE REVIEW

**Comment by thewtex** [comment]
> 由旋转轴和旋转角度转化为四元数错误

Please use English so the rest of the community can follow.

Please add a unit test that identifies the issue and verifies that it is fixed.

**Comment by dzenanz** [comment]
You can force-push to your master branch to translate the commit message into English.

**Comment by jcfr** [comment]
For future reference, Google translation of `由旋转轴和旋转角度转化为四元数错误` led to `Error converting from rotation axis and rotation angle to quaternion` 

> add a unit test that identifies the issue and verifies that it is fixed.

That would indeed be very helpful.

@hyunjaeKang let us know if you need some guidance.

**Comment by hjmjohnson** [comment]
@kian-weimer Can you please convert this PR to english, and submit a new PR?  Reference the original PR #1904

**Comment by hjmjohnson** [comment]
Don't know if this is correct.  There is not enough information in the PR.

**Comment by hjmjohnson** [comment]
Replaced by #3984

**Pull request closed without merging**
