### PR TITLE
COMP: Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` for Windows wrapping

### PR DESCRIPTION
**Pull request by jhlegarreta**
- COMP: Set `DOWNLOAD_EXTRACT_TIMESTAMP` to `TRUE` for Windows wrapping
- DOC: Document the wrapping modules' extraction/archived timestamp flags

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The `if(WIN32)` case was left behind in #3709. Sorry.

**Review by thewtex — APPROVED** [review]
@jhlegarreta thank you!!

**Comment by blowekamp** [comment]
@jhlegarreta Sorry for the late comment. There is no harm in the change, justing the old behavior. The superbuild for SWIG windows just downloads and extracts an executable. So it does not build SWIG/PCRE or use automake for file based time modifications times. So the old time exaction behavior is technically not needed.

Also looking at the latest SWIG release, it now has native CMake support. How the SWIG superbuild is performed make change in the near future. Last I used a the SWIG CMAKE, it was going to need some minor improvements to get the build robustly working.

**Comment by jhlegarreta** [comment]
Not sure if I follow @blowekamp. The Wwindows build was complaining about the policy not being set for the SWIG project:
https://github.com/InsightSoftwareConsortium/ITK/pull/3763/commits/b50e4f4d8e61bcd4f5908ef76403213ffd5d8ec6

So even if it only extracts the executable, and thus the extraction time does not have any impact, the warning was there, and I prefer that the builds configure cleanly. If you think the flag value should be set to `FALSE` for Windows, please go ahead. Let me know if I misunderstood.

**Comment by blowekamp** [comment]
@jhlegarreta I missed the detail that the CMP policy was not set for this external project.

**Comment by jhlegarreta** [comment]
> @jhlegarreta I missed the detail that the CMP policy was not set for this external project.

No problem. Then things look OK and no changes are needed, right?

**Comment by blowekamp** [comment]
No changes are needed.

**Pull request merged**
