### PR TITLE
Deprecate `...CoordRepType` and replace them with `...CoordinateType`

### PR DESCRIPTION
**Pull request by N-Dekker**
Triggered by a comment from Hans (@hjmjohnson) at https://github.com/InsightSoftwareConsortium/ITK/pull/4999#pullrequestreview-2472588270

- Follow-up to pull request #4997

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Good job working on this so far. Is there any chance you can update the remote modules, at least the more commonly used ones, which are tested nightly? E.g. [Montage](https://github.com/InsightSoftwareConsortium/ITKMontage) now has a lot of [warnings](https://open.cdash.org/viewBuildError.php?type=1&buildid=10063093).

**Comment by dzenanz** [comment]
Also, in order to build it against ITK 5.x, do we need to put some ifdefs there? This probably applies to other user code - ITK5/6 ifdef, or turn on legacy. Should we document this in the [migration guide](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/docs/migration_guides/itk_6_migration_guide.md)?

**Comment by N-Dekker** [comment]
Thanks @dzenanz

First of all, none of these changes should trigger a compile error on any user code, _except_ when `FUTURE_LEGACY_REMOVE` is ON.  Moreover, none of the changes should produce a warning on any user code, as long as the user enabled legacy support (`LEGACY_REMOVE` is OFF). (But only after PR #4999 was merged)

Was Montage built with or without legacy support? If it was built with legacy support (`LEGACY_REMOVE` is OFF), the warnings should no longer appear after PR #4999.

Indeed, a note should be added to the migration guide. Thanks for reminding me  😃 I can make a PR to do so, right after this one (#5006) is merged.

**Comment by dzenanz** [comment]
Yes, legacy was turned off. You can see the full configuration here:
https://open.cdash.org/builds/10063093/notes

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
> Should we document this in the [migration guide](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/docs/migration_guides/itk_6_migration_guide.md)?

@dzenanz Proposed note:

```
For the sake of code readibility, a new `CoordinateType` alias is added for
each nested `CoordRepType` alias. The old `CoordRepType` aliases will still be
available with ITK 6.0, but it is recommended to use `CoordinateType` instead.
The `CoordRepType` aliases will be removed when `ITK_FUTURE_LEGACY_REMOVE` is
enabled. Similarly, `InputCoordinateType`, `OutputCoordinateType`, and
`ImagePointCoordinateType` also replace the corresponding `CoordRepType`
aliases.

```

(I'm not yet able to make it a pull request, because my clang-format isn't yet properly installed/configured.)

**Comment by dzenanz** [comment]
From this commit: 0b1fabd319697a61e10602804f4eb02e455ac6a1, get Windows binary from [this link](https://data.kitware.com/api/v1/file/hashsum/sha512/0e6d7176927e52acf081f47ff7cda1cd8d093931c80889f3765a3dca673633f8c1326b9977c5bf79f6d32e98632cb83d91e871aca18081477f70a715059454cf/download).

**Pull request merged**
