### PR TITLE
STYLE: Use local include syntax to include ITK files

### PR DESCRIPTION
**Pull request by jhlegarreta**
Use local include syntax to include ITK files.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
`ITK.macOS.Python` failure is unrelated.

**Review by hjmjohnson — APPROVED** [review]
Failing test itkPyBufferMemoryLeakTest seems unrelated to this change.

**Comment by hjmjohnson** [comment]
@jhlegarreta There are merge conflicts that need to be addressed.

**Comment by jhlegarreta** [comment]
> @jhlegarreta There are merge conflicts that need to be addressed.

Done in 24f2892.

**Pull request merged**
