### PR TITLE
COMP: Add missing const to dircos_comp::operator()

### PR DESCRIPTION
**Pull request by BillyONeal**
This enables compilation with Visual Studio 2019 Update 2 nightly builds.

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm not sure how to submit upstream to GDCM, as that's a SourceForge project, but I sent a message to someone who's committed there recently and hopefully they'll send instructions to fix or just fix it themselves.

**Comment by dzenanz** [comment]
That would be @malaterre.

**Comment by malaterre** [comment]
Thanks !

Applied upstream:

* https://sourceforge.net/p/gdcm/gdcm/ci/b9232933da42016fc882e590764d34b8673b3111/

**Comment by BillyONeal** [comment]
@malaterre Thanks!

**Comment by dzenanz** [comment]
@malaterre Can you update GDCM in ITK? Just run [Modules/ThirdParty/GDCM/UpdateFromUpstream.sh](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/GDCM/UpdateFromUpstream.sh). I tried that, but there are some merge conflicts which are more a question of what should be done (e.g. required version of CMake) than how to do it.

**Pull request closed without merging**
