### PR TITLE
BUG: Register ComposeScaleSkewVersor3DTransform transform

### PR DESCRIPTION
**Pull request by blowekamp**
This is required to read and write the transform.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
This PR should be merged into the release branch too.

**Review by aylward — APPROVED** [review]
LGTM!

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Homebrew's CMake [download location](https://ghcr.io/v2/homebrew/core/cmake/manifests/3.18.4) gives 404: `{"errors":[{"code":"UNAUTHORIZED","message":"authentication required"}]}`. I have seen a similar error on some CI before. Is this now broken or merely intermittent?

**Comment by dzenanz** [comment]
#2484 has the same Mac build issue. @seanm and anyone else routinely using Macs: Do we know why this broke? And how to best fix it?

**Comment by seanm** [comment]
Did it break on my bots?  If so, I keep a log of when I do any updates on them... What broke when and where?

**Comment by dzenanz** [comment]
MacOS CI is now failing for PRs here on GitHub. Here is a copy of the [log](https://dev.azure.com/itkrobotmacos/ITK.macOS/_build/results?buildId=5767&view=logs&j=a5e52b91-c83f-5429-4a68-c246fc63a4f7&t=5add3200-7efa-59c0-0a45-43bce0c77c69&l=42):
```text
Starting: Build and test
==============================================================================
Task         : Bash
Description  : Run a Bash script on macOS, Linux, or Windows
Version      : 3.182.0
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
==============================================================================
Generating script.
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /Users/runner/work/_temp/8d845d24-e341-4ad0-a9dd-d2397d5c9f47.sh
+ curl -O https://raw.githubusercontent.com/Homebrew/homebrew-core/de946dd0c0a91ecf6c78c843a4580bd7116c6bf0/Formula/cmake.rb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1917  100  1917    0     0  50447      0 --:--:-- --:--:-- --:--:-- 50447
+ brew unlink cmake
Unlinking /usr/local/Cellar/cmake/3.20.1... 36 symlinks removed.
+ brew install ./cmake.rb
Warning: Calling `cellar` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256` with a `cellar:` argument instead.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Warning: Calling `sha256 "digest" => :tag` in a bottle block is deprecated! Use `brew style --fix` on the formula to update the style or use `sha256 tag: "digest"` instead.
Error: Failed to load cask: ./cmake.rb
Cask 'cmake' is unreadable: wrong constant name #<Class:0x00007ff101304ec8>
Warning: Treating ./cmake.rb as a formula.
==> Downloading https://ghcr.io/v2/homebrew/core/cmake/manifests/3.18.4
curl: (22) The requested URL returned error: 404 
Error: Failed to download resource "cmake_bottle_manifest"
Download failed: https://ghcr.io/v2/homebrew/core/cmake/manifests/3.18.4
+ c++ --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
+ cmake --version
/Users/runner/work/_temp/8d845d24-e341-4ad0-a9dd-d2397d5c9f47.sh: line 8: cmake: command not found
+ ctest -S /Users/runner/work/1/ITK-dashboard/dashboard.cmake -VV -j 4
/Users/runner/work/_temp/8d845d24-e341-4ad0-a9dd-d2397d5c9f47.sh: line 10: ctest: command not found
##[error]Bash exited with code '127'.
Finishing: Build and test
```

**Comment by seanm** [comment]
`cmake: command not found` -> I guess github borked something.

**Comment by dzenanz** [comment]
I created #2492 to track Mac CI issue.

**Comment by blowekamp** [comment]
Can we merge?

**Comment by dzenanz** [comment]
We can.

**Pull request merged**
