### PR TITLE
ENH: Update remote modules

### PR DESCRIPTION
**Pull request by jhlegarreta**
Update remote modules.

Used the `/Utilities/Maintenance/UpdateRemoteModules.sh` script to update
the modules.

Manually remove the double quotes for the commit hash before update for
the the `RTK` and `TubeTK` modules to allow the script to work as
expected.

Take advantage of the commit to do minor manual editions on the `RTK` and
`TubeTK` remote files concerning the style.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Should help in cleaning the warnings/failures, e.g. for the `Cuberille`remote:
https://open.cdash.org/viewBuildError.php?type=1&buildid=6673523

from the dashboard.

**Comment by jhlegarreta** [comment]
The macOS Python wrapping CI seems to have failed due to some network interruption:
```
##[error]We stopped hearing from agent Hosted Agent. Verify the agent machine is running and has a healthy network connection. Anything that terminates an agent process, starves it for CPU, or blocks its network access can cause this error. For more information, see: https://go.microsoft.com/fwlink/?linkid=846610
```

I'd dare to say that it is safe to merge, since in any case, AFAIK, remotes are not tested by CI even when the related git tag is changed.

**Comment by dzenanz** [comment]
Go ahead and merge. But I thought that a remote is tested (turned on) if its remote specification file is changed.

**Comment by jhlegarreta** [comment]
> Go ahead and merge.

OK. Will merge. Thanks Dženan.

> But I thought that a remote is tested (turned on) if its remote specification file is changed.

Now that you say it, I recall this from an earlier set up (maybe prior to the switch to Azure Pipelines or maybe just reporting to CDash), but having a look at the raw log, the remotes are not turned on, and I did not find them on either in the CDash build.

**Comment by jhlegarreta** [comment]
@thewtex Azure Pipelines CIs are [signalling failures](https://dev.azure.com/itkrobotlinuxpython/ITK.Linux.Python/_build/results?buildId=3052&view=logs&j=0da5d1d9-276d-5173-c4c4-9d4d4ed14fdb&t=f58be928-45a1-58e7-c1ad-04869565b3f4&l=10647) in all Python builds on `master` after having merged this PR. Looks like there are connection issues:

```
FAILED: Wrapping/Generators/SwigInterface/swig-prefix/src/swig-stamp/swig-download 
-- Downloading...
   dst='/home/vsts/work/1/s-build/Wrapping/Generators/SwigInterface/swig-prefix/src/archive.tar'
   timeout='none'
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
-- Retrying...
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
-- Retry after 5 seconds (attempt #2) ...
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
-- Retry after 5 seconds (attempt #3) ...
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download'
CMake Error at swig-stamp/download-swig.cmake:159 (message):
  Each download failed!

    error: downloading 'https://data.kitware.com/api/v1/file/hashsum/sha512/595ef01cb83adfa960ceed9c325a9429192549e8d1e9aa3ab35a4301512a61d82e2e89a8c7939c2a5a0811254ea1832a443bd387e11459eb2b0bafc563ad1308/download' failed
         status_code: 7
         status_string: "Couldn't connect to server"
```

Not sure what triggered this, looks unrelated to the change itself but turned up right after my merge.

**Comment by dzenanz** [comment]
This was an email from our sys-admin earlier this morning:

> We had a brief network outage this morning after an unexpected issue during what should have been a fairly routine reboot of our redundant firewall. This affected access to our public-facing sites, among other things. Things should be mostly back to normal, although we are still seeing some issues with DNS affecting some systems, including some dashboards and perhaps some desktop machines. We are looking into those issues now.

**Comment by jhlegarreta** [comment]
Thanks @dzenanz ! :+1:

**Pull request merged**
