### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@dzenanz Please see https://github.com/NIFTI-Imaging/nifti_clib/pull/135. would this be an upstream fix?

**Comment by dzenanz** [comment]
Yes, your fix upstream seems much more complete. If you make a PR to update niftilib, I will rebase on top of that and remove the duplicated fix.

**Review by hjmjohnson — APPROVED** [review]
Upstream merge of nifti may require manual merge in the future, but that is OK.

**Comment by dzenanz** [comment]
If the change to be merged is already present, I think it is automatically and unproblematically solved. Even to the point where you have a merge with no changes, which can be confusing 😄

**Pull request merged**
