### PR TITLE
COMP: Use pre-built swig for Linux/x86_64

### PR DESCRIPTION
**Pull request by thewtex**
Prevent complexities when cross-compiling for ARM and avoid the need to build from source in wrapping and remote module builds.

Build portability notes:

- Built with the dockcross/manylinux2014-x64 toolchain
- PRCE built static: ./pcre-8.44/configure --prefix=${PWD}/PCRE --disable-shared make make install
- SWIG built with static libstdc++ and against the static pcre export CXXFLAGS=-static-libstdc++ export PCRE_CONFIG=/work/pcre/PCRE/bin/pcre-config ./configure --prefix=/work/swiglinux-4.0.2 --with-prce-prefix=/work/pcre/PCRE make make install

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Code looks good on a glance.

**Comment by dzenanz** [comment]
As far as I can tell, this prevents x64 executables from being used on arm64. And arm64 compilation continues, as well as for other, unrecognized platforms.

**Review by hjmjohnson — APPROVED** [review]
Could other pre-built versions be used for the core dashboard system platforms?

**Comment by thewtex** [comment]
> To be clear, do we plan to continue building SWIG from source for Linux ARM builds?

The goal here is to use this for cross-compiled Linux ARM builds.

> Could other pre-built versions be used for the core dashboard system platforms?

Yes, issue here: https://github.com/InsightSoftwareConsortium/ITK/issues/3955

**Pull request merged**
