### PR TITLE
DOC: Miscellaneous `ITKIOTransformMINC` doc improvements

### PR DESCRIPTION
**Pull request by jhlegarreta**
- DOC: Remove unnecessary `ITKIOTransformMINC` `README` files
- DOC: Improve `ITKIOTransformMINC` class documentation

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
The `itk-module.cmake` description is not shown in the Doxygen documentation; happens as well to other modules, e.g. `ITKIOPhilipsREC`, maybe because they are not enabled by default.

**Comment by blowekamp** [comment]
> The `itk-module.cmake` description is not shown in the Doxygen documentation; happens as well to other modules, e.g. `ITKIOPhilipsREC`, maybe because they are not enabled by default.

Yes, that is my understanding of it. I believe this is the configuration use:
https://open.cdash.org/build/9040972/notes#note0

There is also the [ITKDoxygen](https://github.com/InsightSoftwareConsortium/ITKDoxygen/tree/master) repo where a PR could be make to change the configuration for that separate build.

**Comment by jhlegarreta** [comment]
> There is also the ITKDoxygen repo where a PR could be make to change the configuration for that separate build.

OK. IMO, all modules should be enabled for the Doxygen build.

**Comment by blowekamp** [comment]
> OK. IMO, all modules should be enabled for the Doxygen build.

Yes, that would be nice. I think some issue include that some modules have additional dependencies, and other issues that can cause the full Doxygen build to stop working. That is if there is a small issue in any one of the modules then it all fails.

**Review by thewtex — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
