### PR TITLE
ENH: Update to use CircleCI 2.0

### PR DESCRIPTION
**Pull request by blowekamp**
Change-Id: Ic3880bb5ba0da9572299a4fa66688e5fd36ffab1

### CODE REVIEW

**Comment by blowekamp** [comment]
@thewtex I am trying out the "resource_class" field in CircleCI 2.0. But we are still getting the following message:

> Configurable resource class is not enabled in your project. Please contact your CSM person or our support team to whitelist your project.

Any ideas?

**Comment by thewtex** [comment]
@blowekamp thanks for the update!

I will check with CircleCI support.

**Comment by thewtex** [comment]
@blowekamp please re-try the build.

**Comment by blowekamp** [comment]
Disabled CircleCI for blowekamp/ITK, enable "Build forked pull requests" for InsightSoftwareConsortium/ITK. Now we are getting the following error message:

> The machine executor doesn't support configurable resource class.

Progress....

**Comment by thewtex** [comment]
Getting there.

A few ideas:

- `resource_class` may mean distcc is no longer required
- to use distcc with CircleCI 2.0, the CircleCI Workflow will likely need to be configured
- `ctest -VV` will give information and possibly avoid timeout
- output timeout is configurable with CircleCI 2.0 and can be extended

**Comment by blowekamp** [comment]
Thank you for the suggestions. 

Yes, the goal is to use no longer use distcc and just use one "container".  The  circleci.cmake file in the dashboard branch was always adding distcc as a launcher, which required distcc configuration and problems.  I have patched it [ on my repo ](https://github.com/blowekamp/ITK/commit/3e22095d313bb2eff2f3c63a2213ea1caa54e6ad) only use distcc when configured.  This is used with the most current try.

I'm going to extent the no [output timeout](https://circleci.com/docs/2.0/configuration-reference/#run) for the run command. However, I have concerns that the timeout was due to running out of memory during linking or smoother resource limitation with parallelization.

progress...

**Comment by blowekamp** [comment]
running `nproc` via ssh on the container yielded 32, and ninja was doing it's best to used all 32 cores. The timeout was likely due to termination of the processes by a job manager. I have manually added a `-j 5` to the build command.

**Comment by blowekamp** [comment]
The last build was successful. Just tweaking the JUnit reporting.

With the "large" resource of 4 cores and 8 GB of memory we are able to build and test ITK in ~45 min, compares to 1h37m with 3 containers and distcc. 

This looks like a good place to start with the CircleCI 2.0 testing, so can merge and make use of additional features such as a custom docker image, or cache latter. 

What do you think?

**Comment by thewtex** [comment]
Fantastic! Yes, this is great.

**Comment by blowekamp** [comment]
#32 Must be merge first to the dashboard branch, before this.

**Comment by thewtex** [comment]
Merged as:

  http://review.source.kitware.com/#/c/22592/

**Pull request closed without merging**
