### PR TITLE
STYLE: Prefer C++11 zero initializer to ZeroValue

### PR DESCRIPTION
**Pull request by hjmjohnson**
Prefer to use standard C++ language initializers to the itk::NumericValues<>::ZeroValue() initializers.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:+1:

**Review by N-Dekker — APPROVED** [review]
Wonderful, thanks Hans! Did you use a regular expression to find and replace all those cases? If so, can you possibly still share the regular expression, either in the commit message or as a PR comment?

BTW, I would slightly reword the subject line, to mention `{}` explicitly, for example:

    STYLE: Prefer C++11 `{}` initializer to NumericTraits::ZeroValue() call

But that's just a matter of style  😸 Approved anyway! 👍

**Comment by blowekamp** [comment]
Will the `{}` initializer work for non-scalar pixel types too? Does this add new requirements for pixel types? As I recall some multi-component types itk::Size or itk::Index were defined as aggregate types. Will the `{}` initialization still zero the components?

**Comment by N-Dekker** [comment]
> Will the `{}` initializer work for non-scalar pixel types too? Does this add new requirements for pixel types? As I recall some multi-component types itk::Size or itk::Index were defined as aggregate types. Will the `{}` initialization still zero the components?

Hi @blowekamp Yes, `itk::Size<N>` and `itk::Index<N>` are properly zero-initialized by `{}`.

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
@blowekamp To elaborate on your question, with the following user-defined types (below here), the data members of instances of Aggregate and DefaultedConstructor are properly zero-initialized by the form `T var{}`.  Only `EmptyConstructor::m_Data3` is not initialized by `EmptyConstructor var{}`. 

```
struct Aggregate
{
    int m_Data1;
};

class DefaultedConstructor
{
public:
  DefaultedConstructor() = default;
  int m_Data2;
};

class EmptyConstructor
{
public:
  EmptyConstructor() {}
  int m_Data3;
};

```

    Aggregate aggregate{};  // m_Data1 is zero-initialized.
    DefaultedConstructor defaultedConstructor{};  // m_Data2 is zero-initialized.
    EmptyConstructor emptyConstructor{};  // m_Data2 is uninitialized!


See https://godbolt.org/z/xodK1T5Ys

**Pull request merged**
