### PR TITLE
BUG: Address race condition

### PR DESCRIPTION
**Pull request by blowekamp**
Addresses issue #4711.

When RelabelConnectedRegion is called by ThreadedConnectivity, both outputLabel and requeredLabel are the same value. Don't re-write the same value.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
@blowekamp cool, thanks!  Do you need me to try with TSan or did you already?

**Comment by blowekamp** [comment]
> @blowekamp cool, thanks! Do you need me to try with TSan or did you already?

Yes, please test to confirm. I have not configured TSan yet.

**Review by hjmjohnson — APPROVED** [review]
This looks like a good modification.  Thanks!

**Comment by seanm** [comment]
>Yes, please test to confirm.

I'm afraid all 3 tests still fail under TSan.

>I have not configured TSan yet.

Which platform/compiler do you use?  TSan is quite easy to use with clang on unix-like OS (and with gcc AFAIK).

**Comment by blowekamp** [comment]
Well that is disappointing. 

I am on OSX 12 ARM. Do you have any documentation for using this tool?

**Comment by seanm** [comment]
Very easy then, just add `-fsanitize=thread` to `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`.

For details: https://clang.llvm.org/docs/ThreadSanitizer.html

**Comment by blowekamp** [comment]
> Very easy then, just add `-fsanitize=thread` to `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS`.
> 
> For details: https://clang.llvm.org/docs/ThreadSanitizer.html

Yes, that was easy. The SLIC tests now pass local with the thread sanitizer flag enabled now.

**Comment by seanm** [comment]
> Yes, that was easy. The SLIC tests now pass local with the thread sanitizer flag enabled now.

Sweet! Thanks. The change looks reasonable looking to me, but I don't know this code at all.

**Review by hjmjohnson — APPROVED** [review]
Thanks @blowekamp

**Comment by dzenanz** [comment]
The change is small, but non-trivial. I can't dive now into the code to understand what it does, and to verify the change is OK.

**Review by hjmjohnson — APPROVED** [review]

**Comment by blowekamp** [comment]
@thewtex Looks like this PR was directly merged into release-5.4. Not sure what need to occur now, to get the release and release-5.4 branches is order.

**Comment by dzenanz** [comment]
Merge `release-5.4` to `release`, then merge `release` into `master`?

**Comment by thewtex** [comment]
> @thewtex Looks like this PR was directly merged into release-5.4. Not sure what need to occur now, to get the release and release-5.4 branches is order.

I went ahead and updated `release` and `master` -- happy to do so with an @ ping. Docs are also available here: https://docs.itk.org/en/latest/contributing/index.html#merge-a-topic

**Comment by thewtex** [comment]
> Thanks for the doc links. It's not clear to me what currently is the difference between the release and the release-x.x branches, and how to determine is a "patch" should got to just release or to both.

`release` is not version specific, which `release-X.X` is.

They always go into both.

**Comment by seanm** [comment]
> I went ahead and updated `release` and `master`

Meaning this should be reflected in today's cdash, right?

SLICFixture.Blank2DImage is still failing under TSan on my bot: https://open.cdash.org/tests/1617156531

Was it passing locally for you @blowekamp ?

Perhaps you fixed one race, but not all of them?

**Comment by thewtex** [comment]
> Meaning this should be reflected in today's cdash, right?

Yes

**Comment by blowekamp** [comment]
@seanm  I am seeing SLICFixture.Blank2DImage consistently failing and [itkSLICImageFilterTest3](https://open.cdash.org/test/1630633524) failing on the dashboard. I have not been able to reproduce these locally. I just added `-fsanitize=thread` to C/CXX FLAGS. Are there other flags that could aid in reproducibility?

**Pull request merged**
