### PR TITLE
STYLE: Remove `std::` prefix from types that work without it

### LINKED ISSUE #3248: STYLE: `size_t` vs. `std::size_t`
### Description
We use both `size_t` and `std::size_t`.  Which is the preferred style?

### Actual coding style
As of cef0b6511c27b486cd3469493fa6fcc774f97f53, the count of occurrences with and without the prefix `std::` are as follows.  
```
     22 int8_t
     41 int16_t
    123 int32_t
     88 int64_t
      6 intmax_t
      4 intptr_t
      2 int_fast8_t
      2 int_fast16_t
      2 int_fast32_t
      2 int_fast64_t
      2 int_least8_t
      2 int_least16_t
      2 int_least32_t
      2 int_least64_t
     21 int_t
     17 ptrdiff_t
   1333 size_t
    156 uint8_t
     84 uint16_t
    495 uint32_t
     49 uint64_t
      6 uintmax_t
      2 uintptr_t
      2 uint_fast8_t
      2 uint_fast16_t
      2 uint_fast32_t
      2 uint_fast64_t
      2 uint_least8_t
      2 uint_least16_t
      2 uint_least32_t
      2 uint_least64_t

      3 std::int8_t
      2 std::int16_t
      1 std::int32_t
      3 std::int64_t
      1 std::intmax_t
      1 std::intptr_t
      1 std::int_fast8_t
      1 std::int_fast16_t
      1 std::int_fast32_t
      1 std::int_fast64_t
      1 std::int_least8_t
      1 std::int_least16_t
      1 std::int_least32_t
      1 std::int_least64_t
     11 std::nullptr_t
     19 std::ptrdiff_t
    144 std::size_t
      4 std::uint8_t
      3 std::uint16_t
      3 std::uint32_t
      1 std::uint64_t
     26 std::uintmax_t
      1 std::uintptr_t
      1 std::uint_fast8_t
      1 std::uint_fast16_t
      1 std::uint_fast32_t
      1 std::uint_fast64_t
      1 std::uint_least8_t
      1 std::uint_least16_t
      1 std::uint_least32_t
      1 std::uint_least64_t
```
This list was generated from
```shell
cd git/ITK
find * -type f | egrep '\.[hc](xx|pp)?$' | fgrep -v ThirdParty |
  xargs egrep -o '(std::)?(size|ptrdiff|nullptr|max_align|u?int(_fast|_least|max|ptr)?[0-9]*|float[0-9]*)_t' |
  cut -d : -f 2- | sort -V | uniq -c
```

### PR DESCRIPTION
**Pull request by Leengit**
This is accomplished with
```sh
cd git/ITK
find * -type f |
  egrep '\.(c|cc|cxx|cpp|h|hh|hxx|hpp)$' |
  fgrep -v ThirdParty |
  fgrep -v itkIntTypes.h |
  xargs sed -i -r -e \
    's/std::((size|ptrdiff|max_align|u?int(_fast|_least|max|ptr)?[0-9]*)_t)/\1/g'
```
Closes #3248.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Comment by N-Dekker** [comment]
@Leengit C++ doesn't specify whether or not the ` std` integer types from `<cstdint>` are also defined in the global namespace. Is the idea for ITK code to always use the aliases from the `itk` namespace, defined by "itkIntTypes.h"?

**Comment by Leengit** [comment]
> Is the idea for ITK code to always use the aliases from the `itk` namespace, defined by "itkIntTypes.h"?

Wherever they come from doesn't matter to me.  Folks have been using the short form predominantly, it works, and I am bringing the minority of cases into the fold.

**Comment by N-Dekker** [comment]
> Wherever they come from doesn't matter to me. Folks have been using the short form predominantly, it works, and I am bringing the minority of cases into the fold.

The majority isn't always right! It does help if we could specify why and when the ` std::` may be dropped. Because we won't remove all ` std::` in the entire code base, right?

There is no "max_align..." alias in "itkIntTypes.h", should it still be added?

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
> integer types from <cstdint> are also defined in the global namespace

I understood this is true from https://en.cppreference.com/w/cpp/types/integer.

**Comment by Leengit** [comment]
> The majority isn't always right!

What do you propose?

**Comment by N-Dekker** [comment]
@dzenanz 
> > integer types from `<cstdint>` are also defined in the global namespace
> 
> I understood this is true from https://en.cppreference.com/w/cpp/types/integer.

[The latest draft of the C++ Standard](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2021/n4901.pdf) section [headers] says:
> Except as noted in Clause 16 through Clause 32 and Annex D, the contents of each header _cname_ is the
same as that of the corresponding header _name_.h as specified in the C standard library (Clause 2). In the
C++ standard library, however, the declarations (except for names which are defined as macros in C) are
within namespace scope (6.4.5) of the namespace `std`. It is unspecified whether these names (including any
overloads added in Clause 17 through Clause 32 and Annex D) are first declared within the global namespace
scope and are then injected into namespace std by explicit _using-declarations_ (9.9).

HTH, Nieks

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
