### PR TITLE
ENH: Add python wrapping for std::pair and other int containers

### PR DESCRIPTION
**Pull request by phcerdan**

### CODE REVIEW

**Comment by phcerdan** [comment]
The IsotropicWavelets module outputs `std::pair<unsigned int, unsigned int>` 

The rest was for completion of missing common int and unsigned int.

**Comment by thewtex** [comment]
@phcerdan could you also please create a PR against the `python-builds` branch? This is the current (hopefully temporary) mechanism we use to trigger Python builds. When the patch is ready to be merged, this PR will be merged, and the `python-builds` PR will be closed.

**Comment by thewtex** [comment]
@phcerdan you are tooo fast! :zap: I see the PR was created here: https://github.com/InsightSoftwareConsortium/ITK/pull/396

**Comment by phcerdan** [comment]
Maybe I am doing something different in my github workflow? The ghostflow-check tends to fail in my PR's...

I am using [hub pull-request](https://hub.github.com/hub-pull-request.1.html)

**Comment by phcerdan** [comment]
@thewtex the python build seems fine #396. I cannot merge with the ghostflow failing though.

**Comment by thewtex** [comment]
@phcerdan please make a pull request against the `python-builds` branch via the GitHub browser interface to trigger Python builds.

**Comment by phcerdan** [comment]
done at #396. I just re-triggered the build changing the base branch. It seems that Linux python is building

**Pull request merged**
