### PR TITLE
Update gdcm 2020 02 12

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist

- [x] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [x] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
@thewtex @bradking kwrobot-v1  is repeatedly posting the same same error message.

**Comment by bradking** [comment]
@blowekamp that likely means that kwrobot has constructed a *huge* error message about problems with the PR.  It is probably whitespace complaints about the snapshot commit.  Try updating the `Modules/ThirdParty/GDCM/UpdateFromUpstream.sh` script to add a `.gitattributes` file to the GDCM tree's top level containing `* -whitespace`.  That should prevent the bot from caring about whitespace in the third-party code.

In the script, update the `extract_source` function to be:

```bash
extract_source () {
    git_archive
    pushd "${extractdir}/${name}-reduced"
    echo "* -whitespace" > .gitattributes
    popd
}
```

Make that the first commit on your branch.  Then run the script to create the updated content and merge again.

**Comment by blowekamp** [comment]
@bradking Done. Thank you very much for that help!

**Comment by dzenanz** [comment]
Maybe also incorporate changes proposed in #1608?

**Comment by blowekamp** [comment]
I'm inclined to just merge this as it's all green and ready to go now.

**Comment by dzenanz** [comment]
Sure, and add the other improvement in a new PR.

**Pull request merged**
