### PR TITLE
DOC: Updated GDCMImageIO

### PR DESCRIPTION
**Pull request by issakomi**
Fixed issue with GDCMImageIO doxygen (s. screenshot), updated one comment.

**No code changes.**

Before:
Screenshot at 2020-10-10 01-53-44

After:
Screenshot at 2020-10-11 00-12-15

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
I don't know what the problem was, especially if this PR fixes it.

**Comment by jhlegarreta** [comment]
@issakomi thanks for doing this :100: . Maybe changing the commit message prefix and the PR prefix to `DOC:` would be preferred, as this is a documentation issue. Would you mind doing that and push forcing, please? Once that is done, and hence the `WIP` removed, and hopefully all dashboard checks passing, this will be ready to be merged. Thanks.

**Comment by issakomi** [comment]
Sure, i shall do it. Does someone have an idea what to do that with the statement below?

```
  /** Macro to access Rescale Slope and Rescale Intercept. Which are
   * needed to rescale properly image when needed. User then need to
   * Always check those value when access value from the DICOM header */
  itkGetConstMacro(RescaleSlope, double);
  itkGetConstMacro(RescaleIntercept, double);
```

It doesn't provide any useful information, IMHO, but, in fact, some info could be not bad, because there are examples with re-using of reader's gdcmIO for writer and re-scale values can easily cause problem, there were already issues and posts about it. I can also let it be as it is or reduce to just "Macro to get Rescale Slope and Rescale Intercept."  Please let me know.

**Comment by blowekamp** [comment]
> I don't know what the problem was, especially if this PR fixes it.

Hrmm... This got me thinking we have this "grouping" script: https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Doxygen/itkgroup.pl

It may be wise to run this script to determine it this auto grouping is a cause of the issue.

**Comment by dzenanz** [comment]
As rescale slope and intercept are automatically applied, the docstring for them could be changed/shortened.

**Comment by issakomi** [comment]
> As rescale slope and intercept are automatically applied, the docstring for them could be changed/shortened.

I think so too, a user can only read the value, not really access (change) it in itkGDCMImageIO.

**Comment by jhlegarreta** [comment]
Thanks for doing this @issakomi ! This is ready to be merged I'd say.

> It may be wise to run this script to determine it this auto grouping is a cause of the issue.

@blowekamp may be that can be investigated locally/separately, and @dzenanz can merge this?

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
> It may be wise to run this script

@blowekamp I have never used it. Can you run it?

> and @dzenanz can merge this?

With the approval, either the PR author or maintainers can merge.

**Comment by blowekamp** [comment]
> > It may be wise to run this script
> 
> @blowekamp I have never used it. Can you run it?

Identifying a potential cause of the odd/erroneous Doxygen behavior was my contribution to this PR.

**Comment by issakomi** [comment]
Unfortunately, as already expected, the PR didn't fix main issue with broken documentation of the class. There are still many fixed typos and is was renamed appropriately (just "Updated" instead "Fixed"), so i think there is no need to revert. Locally build documentation for this class was OK, further investigation are required. :(

**Comment by issakomi** [comment]
@dzenanz 

The problem with documentation is not limited to GDCM IO, i have clicked random class just now and already the first one has similar issue

Screenshot at 2020-10-14 14-53-31

**Comment by dzenanz** [comment]
Maybe turn this into an issue so we don't forget about it?

**Comment by issakomi** [comment]
@dzenanz 

OK, thanks, i shall open the issue

**Comment by dzenanz** [comment]
_Each night I merge some PRs, I get the email below. Maybe the warnings in there are related to broken docs?_

A submission to CDash for the project Insight has warnings. You have been identified as one of the authors who have checked in changes that are part of this submission or you are listed in the default contact list.

Details on the submission can be found at https://open.cdash.org/build/6817866.

Project: Insight
Site: blaster.kitware
Build Name: Linux-Ubuntu-GCC-Doxygen
Build Time: 2020-10-14 05:30:02
Type: Nightly
Total Warnings: 20

*Warnings* (first 5 included)
home/kitware/DashboardITK-build/Utilities/Doxygen/Modules/ITKCommon.dox line 28 (https://open.cdash.org/viewBuildError.php?type=1&buildid=6817866
Preprocessing /home/kitware/Dashboard/.../ITK-build/Utilities/Doxygen/Modules/ITKCommon.dox:28: warning: end of file with unbalanced grouping commands
s/Tests/ITK-build/Utilities/Doxygen/Modules/ITKBiasCorrection.dox...
Parsing file /.../ITK-build/Utilities/Doxygen/Modules/ITKBiasCorrection.dox...
Preprocessing /.../ITK-build/Utilities/Doxygen/Modules/ITKBinaryMathematicalMorphology.dox...
Parsing file
        Utilities/Doxygen/Modules/ITKIOMeta.dox line 20 (https://open.cdash.org/viewBuildError.php?type=1&buildid=6817866
Parsing file /.../ITK-buil/.../ITK-build/Utilities/Doxygen/Modules/ITKIOMeta.dox:20: warning: end of file with unbalanced grouping commands
d/Utilities/Doxygen/Modules/ITKIOHDF5.dox...
Preprocessing /.../ITK-build/Utilities/Doxygen/Modules/ITKIOImageBase.dox...
Parsing file /.../ITK-build/Utilities/Doxygen/Modules/ITKIOImageBase.dox...
Preprocessing /.../ITK-build/Utilities/Doxygen/Modules/IT
        Utilities/Doxygen/Modules/SmoothingRecursiveYvvGaussianFITK-build/Utilities/Doxygen/Modules/Thickness3D.dox line 171 (https://open.cdash.org/viewBuildError.php?type=1&buildid=6817866
Parsing file /.../ITK-build/Utilities/Doxygen/Modules/SmoothingRecursiveYvvGaussianF/.../ITK-build/Utilities/Doxygen/Modules/Thickness3D.dox:171: warning: reached end of file while inside a '```' block!
The command that should end the block seems to be missing!

ilter.dox...
Preprocessing /.../ITK-build/Utilities/Doxygen/Modules/SphinxExamples.dox...
Parsing file /.../ITK-build/Utilities/Doxygen/Modules/SphinxExamples.dox...
Preprocessing /.../ITK-build/
        Modules/Core/Common/include/itkTriangleCellTITK/Modules/Core/Common/include/itkVariableLengthVector.h line 1471 (https://open.cdash.org/viewBuildError.php?type=1&buildid=6817866
Preprocessing /.../ITK/Modules/Core/Common/include/itkTriangleCellT/.../ITK/Modules/Core/Common/include/itkVariableLengthVector.h:1471: warning: end of file with unbalanced grouping commands
opology.h...
Parsing file /.../ITK/Modules/Core/Common/include/itkTriangleCellTopology.h...
Preprocessing /.../ITK/Modules/Core/Common/include/itkTriangleHelper.h...
Parsing file /.../ITK/Modules/Core/Common/include/itkTriangleHelper.h...
Preprocessing /.
        home/kITK/Modules/Core/QuadEdgeMesh/include/itkQuadEdge.h line 452 (https://open.cdash.org/viewBuildError.php?type=1&buildid=6817866
Parsing file /home/k/.../ITK/Modules/Core/QuadEdgeMesh/include/itkQuadEdge.h:452: warning: end of file with unbalanced grouping commands
itware/Dashboards/Tests/ITK/Modules/IO/GIPL/include/itkGiplImageIOFactory.h...
Preprocessing /.../ITK/Modules/IO/JPEG/include/itkJPEGImageIO.h...
Parsing file /.../ITK/Modules/IO/JPEG/include/itkJPEGImageIO.h...
Preprocessing /.../ITK/Modules/IO/JPEG/incl

-CDash on open.cdash.org

**Comment by jhlegarreta** [comment]
Yep, I had noticed the warnings being consistently reported in `CDash`. I tried to have a look at where it comes from and potential fixes but unfortunately did not succeed in finding the source of the warnings.

**Pull request merged**
