### PR TITLE
BUG: Handle CellData in Decimation Filter

### PR DESCRIPTION
**Pull request by DVigneault**
Currently, cell data is not properly handled in the
itk::SquaredEdgeLengthDecimation filter.  This patch adds entries to
the cell data array as faces are added in the Zip filter, and then
deletes unreferenced entries in a new member function added to
itk::Mesh.

## PR Checklist

- :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] Adds the License notice to new files.
- :no_entry_sign: Adds Python wrapping.
- [X] Adds tests and baseline comparison (quantitative).
- :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by DVigneault** [comment]
Here's an example of a high-poly input mesh (left) and a low-poly decimated mesh (right), where the cell faces are colored according to their corresponding cell data entries using VTK.

Decimation

**Comment by DVigneault** [comment]
Not sure what accounts for the `ITK.Windows` failure--looking at the output, it appears that none of the test executables could be found and so no tests were run.

**Comment by DVigneault** [comment]
@dzenanz I changed the signature of the test from `(int, char**)` to `(int, char*[])`, which seems to have fixed the failure on `ITK.Windows`.  Unfortunately, there is now a failure on `ITK.macOS`, though this seems to be unrelated (something to do with the `vnl_symmetric_eigensystem`).  Here are the failing lines from Azure Pipelines:

````
109: Start Testing test_symmetric_eigensystem:
...
109:  Test 009: Specialised version is faster                         --> **FAILED**
````

````
Start Testing test_symmetric_eigensystem:
...
Test 009: Specialised version is faster                         --> **FAILED**
````

**Comment by dzenanz** [comment]
That's a known flaky test.

**Comment by dzenanz** [comment]
It looks like this introduces some problem with TBB multi threader:
https://open.cdash.org/testDetails.php?test=837479003&build=6285497
We could wait another nightly test cycle to be sure.

**Pull request merged**
