### PR TITLE
Update png

### PR DESCRIPTION
**Pull request by blowekamp**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
What was the previously bundled version?

**Comment by blowekamp** [comment]
> What was the previously bundled version?

The change in more minor now with updating to a more recent version.

**Review by dzenanz — APPROVED** [review]

**Comment by blowekamp** [comment]
> What was the previously bundled version?

The previous update was from 'libpng16' which is the release branch for 1.6, but it was 1.6.43.git meaning it was not tagged. This update is to and official tag/release: "1.6.44"

**Pull request merged**
