### PR TITLE
BUG: Resolve ITK `make` build error with Python Wrappings. 

### LINKED ISSUE #2908: ITK Build Failure when doing Python Wrapping using Make
### Description

Build failure when building ITK with cmake using Make. It fails at around 41% progress with the following message.
```
[ 41%] Building CXX object Modules/Segmentation/Watersheds/src/CMakeFiles/ITKWatersheds.dir/itkWatershedMiniPipelineProgressCommand.cxx.o
make[2]: *** [Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonSwig.dir/build.make:461: Wrapping/Typedefs/itkFixedArray.i] Error 1
make[2]: *** Deleting file 'Wrapping/Typedefs/itkFixedArray.i'
make[1]: *** [CMakeFiles/Makefile2:32930: Wrapping/Modules/ITKCommon/CMakeFiles/ITKCommonSwig.dir/all] Error 2
```
I have tested both single thread and multi thread build with make (eg. make -j8). It fails for both cases.

It is building fine when using Ninja. 

Also I have narrowed down the change to commit: [ENH: Generate stub-files to support type hints](https://github.com/InsightSoftwareConsortium/ITK/commit/faa3ab0a7e36ad82ad9c817e282bea48e2ac380c)

### Steps to Reproduce
1. Configure cmake to use Make. 
2. Select Python wrapping
3. Build

### Expected behavior

Build should succeed.

### Actual behavior

```none
```

### Environment

Tested on both Linux system and Mac system. It failed on both.

### PR DESCRIPTION
**Pull request by kian-weimer**
Resolved a few small bugs causing `make` builds to fail when python wrapping is enabled. 

The following was changed:
1. The itk-stubs directory is generated via cmake during build configuration before igenerator.py is ran.
2. The .pyi output files in the igenerator custom command were corrected. 
3. The typehint generation code was reformatted to prevent duplicate definitions from being saved to several files. 

This should fix #2908. 

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by kian-weimer** [comment]
@PranjalSahu Would you mind building again with this fix to see if it resolves your issue? Thanks!

**Comment by dzenanz** [comment]
Pranjal is out of office this week, so I suppose this will need to wait for next week.

**Review by dzenanz — COMMENTED** [review]
LGTM

**Comment by PranjalSahu** [comment]
I am to build it successfully on MacBook.

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
