### PR TITLE
No longer disable MSVC warning C4231, order #pragma warnings

### PR DESCRIPTION
**Pull request by N-Dekker**

### CODE REVIEW

**Comment by N-Dekker** [comment]
FYI, An attempt to disable 4231 actually triggers another one, when using MSVC compiler option `/Wall`:

> warning C4619: #pragma warning: there is no warning number '4231'

See https://rextester.com/FGKL98315

**Comment by N-Dekker** [comment]
@hjmjohnson Hi Hans, I'm afraid I just found another VNL/vxl/vcl issue, using MSVC option `/Wall`:

> vcl_compiler.h(202): warning C4574: 'VNL_CONFIG_LEGACY_METHODS' is defined to be '0': did you mean to use '#if VNL_CONFIG_LEGACY_METHODS'?

Here: https://github.com/InsightSoftwareConsortium/ITK/blob/v5.0.0/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h.in#L202

    #ifdef VNL_CONFIG_LEGACY_METHODS
    #include "vcl_legacy_aliases.h"
    #endif

In my "vnl_config.h" (in the build directory): `#define VNL_CONFIG_LEGACY_METHODS 0`

You see, even now that `VNL_CONFIG_LEGACY_METHODS` is zero, "vcl_legacy_aliases.h" will be included! Could you fix that?

**Comment by N-Dekker** [comment]
I think this pull request is ready for merge! (Although it suggests some changes to VNL as well.)

**Comment by dzenanz** [comment]
I could merge it, but I prefer @hjmjohnson to do it, since it should be accompanied by some VNL updates.

**Comment by hjmjohnson** [comment]
https://github.com/vxl/vxl/pull/658

**Pull request merged**
