### PR TITLE
Use cxx 17 features directly

### PR DESCRIPTION
**Pull request by hjmjohnson**
Remove specialized ITK functionality that is now part of the CXX-17 standard language.  

## PR Checklist
- []  API changes that are backward compatible if cxx17 language features are used directly
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed) Compiler messages provide instructions for how to update codebase.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
@thewtex FYI: Clang-format is tormenting me again.  Is there something I am doing wrong?

**Comment by thewtex** [comment]
@hjmjohnson maybe rebase on `master`

**Comment by hjmjohnson** [comment]
> @hjmjohnson maybe rebase on `master`

```
% git fetch upstream                                                                                                                                                                             
% git rebase upstream/master                                                                                                                                                                     
Current branch use-cxx-17-features-directly is up to date.
% git push
Everything up-to-date
```

**Comment by thewtex** [comment]
@hjmjohnson follow-up in #4712

**Review by thewtex — APPROVED** [review]
:rocket:

**Pull request merged**
