### PR TITLE
DOC: Move detailed description to the top of class documentation page

### LINKED ISSUE #3666: Change doxygen layout
I think it would be better if detailed class description is at the top of the page, and not buried after heaps of public definitions inside a class, many of the pretty standard and therefore not overly interesting.

Relevant doxygen docs: https://www.doxygen.nl/manual/customize.html#layout

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #3666. Build in progress on `blaster`.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Updated API documentation (or API not changed)

### CODE REVIEW

**Review by blowekamp — APPROVED** [review]
Love it!

**Comment by dzenanz** [comment]
Below is a screenshot of how it looks like with this change. It might have some historic value in the far future. More importantly, if this PR is not merged today, I assume that the docs will be regenerated overnight using the `master` branch, so this screenshot can be used as a reference "new" style.
Screenshot 2023-10-05 15 27 26

**Review by N-Dekker — APPROVED** [review]

**Review by jhlegarreta — COMMENTED** [review]
Thanks for doing this @dzenanz.

Looks more helpful this way.

A few comments:
- I again would like to see a commit message body, even if it reproduces the commit message subject (the PR message on GitHub in this case does not explain the change).
- I had to go to the ITKDoxygen repository and had to look there whether the previous version could be found. Hopefully Brad had this set up nicely, and we can see the difference (https://insightsoftwareconsortium.github.io/ITKDoxygen/classitk_1_1ImageBase.html). Bottom line: we should not make the changes in a PR be the immediate production version before we have seen changes in a pre-production build (GHA, Azure or whatever) (although in this case the change looked simple, and involving no risks). I can open an issue to keep track of this.

**Comment by dzenanz** [comment]
Point 1 addressed with force-push.

To test this, I hijacked the usual documentation build process, as no one had a documentation build setup ready. I though that the normal documentation would be built overnight, but I was wrong. The machine which build documentation does a `git fetch`, but it does not automatically check out `master`. I did that now, and kicked off a fresh doc build. It should finish in about an hour, and we will be back to the usual process.

**Comment by blowekamp** [comment]
You may find this repo and docker images useful:
https://github.com/InsightSoftwareConsortium/ITKDoxygen

**Review by jhlegarreta — APPROVED** [review]
Thanks for the commit message body addition Dženan.

**Comment by dzenanz** [comment]
For posterity, here is also the old style (before merging this PR):
Screenshot 2023-10-06 09 40 28

**Pull request merged**
