### PR TITLE
COMP: Set vxl minimum to 3.0.0

### PR DESCRIPTION
**Pull request by hjmjohnson**
find_package(VXL 3.0.0 REQUIRED)
3.0.0 is the first version of VXL that supports
the requirement of front() and back() members
in the vnl_vector and vnl_vector_fixed.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)

### CODE REVIEW

**Comment by hjmjohnson** [comment]
The eldorado.kitware build will need to have VXL system version updated.

eldorado.kitware | Ubuntu-g++-4.8.2-Release-System-VXL | d9e464 | 0 | 0 | 1 | 1 | 2499 | 0 | 133 | 10s | 17 hours ago
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

VXL now needs to be at least 3.0.0 to include the 'front()' and 'back()' vector operations.

**Comment by hjmjohnson** [comment]
@seanm threw down the gaunlet! :) So I attacked some of the "ASAN" errors on the dashboard.

This one was a nasty little bugger to find.  Thank goodness for CLion's support of Sanatizer tool with the debugger.

**Comment by hjmjohnson** [comment]
Failures on 


RogueResearch15 | Mac10.13-AppleClang-dbg-x86_64-ASanUBSan | d9e464 | 0 | 0 | 0 | 0 | 0 | 2 | 2784 | 28m 40s | 20 hours ago
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
RogueResearch16 | Mac10.14-AppleClang-dbg-ASanUBSan | d9e464 | 0 | 0 | 0 | 0 | 0 | 2 | 2784 | 18m 48s | 20 hours ago



Should be addressed by this and the VNL patch sets.

**Comment by thewtex** [comment]
> The eldorado.kitware build will need to have VXL system version updated.

@hjmjohnson `eldorado.kitware` now has VXL `master`.

**Comment by hjmjohnson** [comment]
@dzenanz  How does one ignore "ghostflow" warnings in ThirdParty code?

**Comment by dzenanz** [comment]
I don't know. @bradking should know?

**Comment by hjmjohnson** [comment]
@bradking I think that a .gitattributes file needs to be constructed for the VXL directory.

I don't know how to "disable" checks in the .gitattributes files.

**Review by dzenanz — APPROVED** [review]

**Comment by hjmjohnson** [comment]
@dzenanz I've tried many things to get the ghostflow to pass with the VNL code.

I think that the failure can be safely ignored here as we don't really care about the VNL formatting of those patch sets.

I'm going to merge as is and not spend any more effort trying to make it perfect.

**Comment by dzenanz** [comment]
Do you see what is ghostflow complaining about? I can't get the error message.

**Comment by hjmjohnson** [comment]
all complaints about whitespace that are not relevant.

> Do you see what is ghostflow complaining about? I can't get the error message.
```
Errors:

commit df92e58 adds bad whitespace:

config/cmake/Modules/FindOpenJPEG2.cmake:75: new blank line at EOF.
config/cmake/Modules/NewCMake/FindDC1394.cmake:29: new blank line at EOF.
config/cmake/Modules/NewCMake/FindGEOTIFF.cmake:33: new blank line at EOF.
config/cmake/Modules/NewCMake/FindSIMVoleon.cmake:75: new blank line at EOF.
config/cmake/Modules/NewCMake/FindWin32SDK.cmake:55: new blank line at EOF.
config/cmake/Modules/readme.txt:20: new blank line at EOF.
v3p/netlib/README.md:61: trailing whitespace.
+    
v3p/netlib/lapack/double/dlaev2.h:10: new blank line at EOF.
v3p/netlib/lapack/double/dspr.h:10: new blank line at EOF.
v3p/netlib/lapack/double/dsptrf.h:9: new blank line at EOF.
v3p/netlib/lapack/double/dsptrs.h:12: new blank line at EOF.
v3p/netlib/libf2c/Notice:23: new blank line at EOF.
v3p/netlib/mathews/adaquad.f:130: new blank line at EOF.
v3p/netlib/mathews/simpson.f:58: new blank line at EOF.
v3p/netlib/mathews/trapezod.f:40: new blank line at EOF.
v3p/netlib/napack/cg.f:491: new blank line at EOF.
v3p/netlib/opt/lbfgs.f:1053: new blank line at EOF.
v3p/netlib/opt/lbfgsb.f:1488: space before tab in indent.
+     	 call bmv(m,sy,wt,col,p,v,info)
v3p/netlib/opt/lbfgsb.f:1490: space before tab in indent.
+     	 f2 = f2 - ddot(col2,v,1,p,1)
v3p/netlib/opt/lbfgsb.f:1592: space before tab in indent.
+      	 pointr = head
v3p/netlib/opt/lbfgsb.f:1607: space before tab in indent.
+       	 call daxpy(col2,-dibp,wbp,1,p,1)
v3p/netlib/opt/lbfgsb.f:1610: space before tab in indent.
+      	 f1 = f1 + dibp*wmc
v3p/netlib/opt/lbfgsb.f:1611: space before tab in indent.
+      	 f2 = f2 + 2.0d0*dibp*wmp - dibp2*wmw
v3p/netlib/opt/lbfgsb.f:1620: space before tab in indent.
+      	 f1 = zero
v3p/netlib/opt/lbfgsb.f:1621: space before tab in indent.
+      	 f2 = zero
v3p/netlib/opt/lbfgsb.f:1713: space before tab in indent.
+     	 call bmv(m,sy,wt,col,wa(2*m+1),wa(1),info)
v3p/netlib/opt/lbfgsb.f:1719: space before tab in indent.
+     	 do 34 j = 1, col
v3p/netlib/opt/lbfgsb.f:1720: space before tab in indent.
+       	    a1 = wa(j)
v3p/netlib/opt/lbfgsb.f:1947: space before tab in indent.
+ 	       call dcopy(m-jy,wn1(js+1,js+1),1,wn1(js,js),1)
v3p/netlib/opt/lbfgsb.f:1948: space before tab in indent.
+ 	       call dcopy(m-1,wn1(m+2,jy+1),1,wn1(m+1,jy),1)
v3p/netlib/opt/lbfgsb.f:2011: space before tab in indent.
+      	 do 40 jy = 1, iy
v3p/netlib/opt/lbfgsb.f:2066: space before tab in indent.
+      	 do 65 jy = 1, iy
v3p/netlib/opt/lbfgsb.f:2069: space before tab in indent.
+ 	    wn(jy,iy) = wn1(iy,jy)/theta
v3p/netlib/opt/lbfgsb.f:2070: space before tab in indent.
+ 	    wn(js,is) = wn1(is1,js1)*theta
v3p/netlib/opt/lbfgsb.f:2072: space before tab in indent.
+      	 do 66 jy = 1, iy - 1
v3p/netlib/opt/lbfgsb.f:2073: space before tab in indent.
+ 	    wn(jy,is) = -wn1(is1,jy)
v3p/netlib/opt/lbfgsb.f:2075: space before tab in indent.
+      	 do 67 jy = iy, col
v3p/netlib/opt/lbfgsb.f:2076: space before tab in indent.
+ 	    wn(jy,is) = wn1(is1,jy)
v3p/netlib/opt/lbfgsb.f:2078: space before tab in indent.
+ 	 wn(iy,iy) = wn(iy,iy) + sy(iy,iy)
v3p/netlib/opt/lbfgsb.f:2162: space before tab in indent.
+      	 wt(1,j) = theta*ss(1,j)
v3p/netlib/opt/lbfgsb.f:2922: space before tab in indent.
+       	   else
v3p/netlib/opt/lbfgsb.f:3105: space before tab in indent.
+     	 temp1 = zero
v3p/netlib/opt/lbfgsb.f:3153: space before tab in indent.
+   	    if (dk .lt. zero .and. nbd(k) .le. 2) then
v3p/netlib/opt/lbfgsb.f:3159: space before tab in indent.
+ 	       endif
v3p/netlib/opt/lbfgsb.f:3160: space before tab in indent.
+   	    else if (dk .gt. zero .and. nbd(k) .ge. 2) then
v3p/netlib/opt/lbfgsb.f:3166: space before tab in indent.
+ 	       endif
v3p/netlib/opt/lbfgsb.f:3176: space before tab in indent.
+      	 dk = d(ibd)
v3p/netlib/opt/lbfgsb.f:3177: space before tab in indent.
+      	 k = ind(ibd)
v3p/netlib/opt/lbfgsb.f:3178: space before tab in indent.
+      	 if (dk .gt. zero) then
v3p/netlib/opt/lbfgsb.f:3181: space before tab in indent.
+     	 else if (dk .lt. zero) then
v3p/netlib/opt/lbfgsb.f:3184: space before tab in indent.
+     	 endif
v3p/netlib/tests/lbfgs-example.f:62: new blank line at EOF.
commit df92e58 is not allowed; missing newline at the end of file in config/cmake/doxygen/doxy-notes.txt.

commit df92e58 is not allowed; missing newline at the end of file in config/cmake/doxygen/doxy_header.html.

Please rewrite commits to fix the errors listed above (adding fixup commits will not resolve the errors) and force-push the branch again to update the merge request.
```

**Comment by dzenanz** [comment]
Go ahead and merge.

**Pull request merged**
