### PR TITLE
Eigen fix bug 1644

### PR DESCRIPTION
**Pull request by vfonov**
ENH: included fix for bug 1644 from upstream eigen repository

See  http://eigen.tuxfamily.org/bz/show_bug.cgi?id=1644

### CODE REVIEW

**Comment by vfonov** [comment]
ping @seanm

**Comment by dzenanz** [comment]
The failing test is unrelated. Let's give @phcerdan some more time to do a more comprehensive update of Eigen (including this fix) before merging this PR.

**Comment by seanm** [comment]
Any approx ETA?  We're trying to get our dashboards green, and the eigen -Wcast-qual warnings are some of the only ones left:

https://open.cdash.org/viewBuildError.php?type=1&buildid=6142838

**Comment by dzenanz** [comment]
We could merge today if you are eager, and then @phcerdan could obliterate these changes with a more comprehensive update. Otherwise we could give him time until Monday.

**Comment by seanm** [comment]
I'm eager, but if we're talking days, I'm not that impatient. :)

**Comment by phcerdan** [comment]
sure, let's update internal itk eigen to the top of 3.3 branch: https://bitbucket.org/eigen/eigen/commits/branch/3.3, commit [1553e26d9ce84](https://bitbucket.org/eigen/eigen/commits/1553e26d9ce848a947e25225fec6fb2c58c2b921)

**Pull request closed without merging**
