### PR TITLE
COMP: Get ITK_USE_FLOAT_SPACE_PRECISION=ON to compile again

### PR DESCRIPTION
**Pull request by thewtex**

### CODE REVIEW

**Comment by dzenanz** [comment]
This runs into the same issue as #4805.

**Comment by thewtex** [comment]
> This runs into the same issue as #4805.

I cherry-picked the requisite patch.

**Review by dzenanz — APPROVED** [review]

**Review by seanm — APPROVED** [review]

**Comment by dzenanz** [comment]
After merging here, I manually merged this to `release` and `master`.

**Pull request merged**
