### PR TITLE
BUG: fix python module definition in VtkGlue wrap

### PR DESCRIPTION
**Pull request by lexming**
Compilation of VtkGlue with wrapping for Python fails due to a `module()` call with extra escape characters in the argument list.

Fixes issue https://github.com/InsightSoftwareConsortium/ITK/issues/2026

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
It looks like the problem was introduced by 98fc085a9d96bb43f60160a147e1156cf30a26b3.

**Comment by dzenanz** [comment]
I am testing this locally, but it will take a while.

**Review by thewtex — APPROVED** [review]

**Comment by thewtex** [comment]
@lexming 

@dzenanz please merged after your testing completes.

**Comment by dzenanz** [comment]
This gets past compile stage:
```text
Linking CXX shared module ../../../lib/_ITKVtkGluePython.so
/usr/bin/ld: /usr/local/lib/libvtkCommonCore-8.1.a(vtkDataArray.cxx.o): relocation R_X86_64_PC32 against symbol `_ZTVN3tbb10interface98internal9flag_taskE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/build.make:744: recipe for target 'lib/_ITKVtkGluePython.so' failed
make[3]: *** [lib/_ITKVtkGluePython.so] Error 1
CMakeFiles/Makefile2:57223: recipe for target 'Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/all' failed
make[2]: *** [Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/all] Error 2
CMakeFiles/Makefile2:57230: recipe for target 'Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/rule' failed
make[1]: *** [Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGluePython.dir/rule] Error 2
Makefile:10759: recipe for target 'ITKVtkGluePython' failed
make: *** [ITKVtkGluePython] Error 2
```
The link issue is probably unrelated. Even if it is related, this patch is still an improvement.

**Comment by lexming** [comment]
Thanks for the quick action. @dzenanz the link issue might be solved by recompiling with `-fPIC`

**Comment by dzenanz** [comment]
When I get around to it, I will just start with a fresh VTK build using the latest version (9.0 or 9.1 by then).

**Pull request merged**
