### PR TITLE
ENH: use master branch of GoogleTest until a stable version is released

### PR DESCRIPTION
**Pull request by dzenanz**
## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by N-Dekker** [comment]
Thanks, @dzenanz  It would be especially interesting to me it this would allow me to quickly enjoy my own recent GoogleTest pull requests, https://github.com/google/googletest/pull/3184 and https://github.com/google/googletest/pull/3191 as soon as they get merged, by the Googlers... if they get accepted, of course!  😄

**Comment by dzenanz** [comment]
The reason for the update is to get rid of CMake deprecation warning:
```text
CMake Deprecation Warning at Modules/ThirdParty/GoogleTest/src/itkgoogletest/CMakeLists.txt:4 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at Modules/ThirdParty/GoogleTest/src/itkgoogletest/googletest/CMakeLists.txt:56 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
```
I thought the update would be smooth, but all CIs are failing. If your PR(s) get merged, please feel free to amend this PR. If I get around to fixing this PR first, you can update GTest again. Running the script is easy.

**Comment by N-Dekker** [comment]
> If your PR(s) get merged, please feel free to amend this PR.

One of my two GoogleTest PRs, https://github.com/google/googletest/pull/3191 has just been rejected last week, unfortunately. Hopefully there is still a chance for https://github.com/google/googletest/pull/3184

**Comment by dzenanz** [comment]
This is ready for review now.

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
@dzenanz 
> If your PR(s) get merged, please feel free to amend this PR.

Update: My pull request https://github.com/google/googletest/pull/3184 has just been merged onto the master branch of GoogleTest: https://github.com/google/googletest/commit/bcfcf75ef62af29f15fbb98be25fbfb87f45036e  🎉 

I hope that it's still in time for the final release of ITK 5.2   😄

**Comment by dzenanz** [comment]
I later reverted this PR because it breaks GCC 4.8.5 builds. I think we concluded we should drop GCC 4.x with ITK 5.3.

**Comment by N-Dekker** [comment]
> I later reverted this PR because it breaks GCC 4.8.5 builds. I think we concluded we should drop GCC 4.x with ITK 5.3.

OK, thanks @dzenanz  I look forward to say goodbye to GCC 4.8.5  😸

**Pull request merged**
