### PR TITLE
COMP: Forward CMAKE_APPLE_SILICON_PROCESSOR

### PR DESCRIPTION
**Pull request by issakomi**
Forward [CMAKE_APPLE_SILICON_PROCESSOR](https://cmake.org/cmake/help/latest/variable/CMAKE_APPLE_SILICON_PROCESSOR.html) variable to external cmake configuration commands (Eigen3 and FFTW).
This fixes configuration for _x86_64_ on Apple Silicon, if _CMAKE_APPLE_SILICON_PROCESSOR_ variable was set by user (value should be _x86_64_ or _arm64_).

Theoretically, for cross-compile setups, specially on other architectures, more variables should be forwarded, IMHO, but Eigen3 is header library, this is required only to pass correct architecture to "try compile" cmake's tests, AFAIK. And internal FFTW build is marked as non-production experimental build, so probably it is OK. Note: i **didn't** test FFTW build on Apple Silicon, but i think it is straightforward.

Let me know if you think _CMAKE_OSX_ARCHITECTURES_ or other variables should be added too, so temporary set WIP.

S. comments to https://github.com/InsightSoftwareConsortium/ITK/pull/2391

CC @seanm 

**Edit**:
have tried "internal" FFTW builds (both variants, _float_ and _double_) with _CMAKE_APPLE_SILICON_PROCESSOR_ **x86_64** on Apple Silicon, they are OK.

This variable exists in Cmake >= 3.19.2, BTW.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
Thanks, @issakomi !

**Review by hjmjohnson — APPROVED** [review]

**Comment by seanm** [comment]
Not sure I get the point of the existence of `CMAKE_APPLE_SILICON_PROCESSOR`, but it exists, so passing it down the line seems fine.

**Comment by issakomi** [comment]
> Not sure I get the point of the existence of CMAKE_APPLE_SILICON_PROCESSOR, but it exists, so passing it down the line seems fine.


Here https://cmake.org/cmake/help/v3.19/release/3.19.html is some information

Apple Silicon is now supported (since CMake 3.19.2):

 * The CMAKE_HOST_SYSTEM_PROCESSOR is selected using uname -m. Since this may vary based on CMake’s own architecture and that of the invoking process tree, the CMAKE_APPLE_SILICON_PROCESSOR variable or CMAKE_APPLE_SILICON_PROCESSOR environment variable may be set to specify a host architecture explicitly.

 * If CMAKE_OSX_ARCHITECTURES is not set, CMake adds explicit flags to tell the compiler to build for the CMAKE_HOST_SYSTEM_PROCESSOR so the toolchain does not have to guess based on the process tree’s architecture.

**Comment by issakomi** [comment]
@seanm 

```
#include <cstdlib>
int main(int, char**)
{
	system("uname -a");
	return 0;
}
```

mi@mis-Mac-mini ~ % clang++ --target="x86_64-apple-macos10.14" test1.cpp
mi@mis-Mac-mini ~ % ./a.out 
Darwin mis-Mac-mini.fritz.box 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 **x86_64**


mi@mis-Mac-mini ~ % clang++  test1.cpp
mi@mis-Mac-mini ~ % ./a.out 
Darwin mis-Mac-mini.fritz.box 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 **arm64**

**Pull request merged**
