### PR TITLE
COMP: Increased min cmake from 3.10.2 to 3.16.3

### PR DESCRIPTION
**Pull request by seanm**
Part of the motivation here is HDF's increasing of their minumum.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
@thewtex @dzenanz is there more to it than this?

**Review by dzenanz — APPROVED** [review]
Looks about right.

**Comment by dzenanz** [comment]
It [looks like](https://open.cdash.org/build/7274066/configure) we need to update our CircleCI configuration, or even remove it?

**Comment by thewtex** [comment]
The CircleCI version is here:

https://github.com/InsightSoftwareConsortium/ITK/blob/842b89d4a96f98e3c59a1012f3043f08de19c459/.circleci/config.yml#L51

**Comment by N-Dekker** [comment]
> Part of the motivation here is HDF's increasing of their minumum.

@seanm CMake 3.16.3 is fine by me, but which HDF version do you refer to?
 https://github.com/HDFGroup/hdf5/blob/50d0888f491821435f6884c0c4c516f69ff67927/CMakeLists.txt#L1 (at their develop branch today) says:

    cmake_minimum_required (VERSION 3.12)

**Comment by dzenanz** [comment]
Another thing we can remove with a bump to CMake version:
https://github.com/InsightSoftwareConsortium/ITK/blob/dd6f608141b26862f9050307a9c10910c5537ad1/CMake/ITKSetPython3Vars.cmake#L15-L48

**Comment by dzenanz** [comment]
@N-Dekker I think he was referring to this: https://github.com/InsightSoftwareConsortium/ITK/pull/2294#issuecomment-777739447

**Comment by seanm** [comment]
Yup, but it was @dzenanz that chose/suggested the version of cmake. it is indeed higher than what HDF5 needs.

**Comment by thewtex** [comment]
Is this PR intended to be against `release` instead of `master` to support the HDF5 update in https://github.com/InsightSoftwareConsortium/ITK/pull/2294 ?

**Comment by seanm** [comment]
> Is this PR intended to be against `release` instead of `master` to support the HDF5 update in #2294 ?

No, the HDF5 update will be for master only.

**Comment by thewtex** [comment]
@seanm can the cmake version in .circleci/config.yml please be updated to get this in?

**Comment by seanm** [comment]
> @seanm can the cmake version in .circleci/config.yml please be updated to get this in?

Oh that's in ITK's git?  I thought it was something someone needed to tweak on some buildbot... checking now...

**Comment by thewtex** [comment]
@seanm thanks!

**Review by dzenanz — APPROVED** [review]
Good even as-is, but would be better if this conditionality upon CMake version were removed:
https://github.com/InsightSoftwareConsortium/ITK/blob/dd6f608141b26862f9050307a9c10910c5537ad1/CMake/ITKSetPython3Vars.cmake#L15-L48

**Comment by seanm** [comment]
I'll grep for `CMAKE_VERSION` and see what I can remove...

**Review by dzenanz — APPROVED** [review]
Awesome!

**Pull request merged**
