### PR TITLE
BUG: fix error on IBM POWER9 ppcle64 arch, v2

### PR DESCRIPTION
**Pull request by Mon-ius**
See details on :

- https://github.com/InsightSoftwareConsortium/ITK/pull/1963#pullrequestreview-476814283

- https://github.com/InsightSoftwareConsortium/ITK/issues/1960

### CODE REVIEW

**Comment by Mon-ius** [comment]
Yeah, it passed all build test.

**Comment by dzenanz** [comment]
Can you apply clang-format to the code? The linter is complaining.

**Comment by Mon-ius** [comment]
After modified the file, I did following things:

- `git add  Modules/IO/BMP/test/itkBMPImageIOTestExtension.cxx`
- `git-clang-format`
- `git commit -m "BUG: fix error on IBM POWER9 ppcle64 arch, v2, format"`
- `git push`

But still, have the clang-format error.

**Comment by dzenanz** [comment]
These were the changes that were needed:
https://github.com/InsightSoftwareConsortium/ITK/compare/853480737d9e1e5393cfbc544c10b74871aa1773..1bfbed412616efd7f9c8ac06f01943cab271b08f

**Comment by dzenanz** [comment]
Closing in favor of #1968.

**Pull request closed without merging**
