### PR TITLE
COMP: libjpeg-turbo: Add object libraries as source files

### PR DESCRIPTION
**Pull request by blowekamp**
Addresses #5021.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Code looks good. I am about to try this locally.

**Comment by dzenanz** [comment]
Unfortunately, this does not work:
```log
Build started at 12:20...
1>------ Build started: Project: ZERO_CHECK, Configuration: Debug x64 ------
2>------ Skipped Build: Project: RUN_TESTS, Configuration: Debug x64 ------
2>Project not selected to build for this solution configuration 
3>------ Skipped Build: Project: NightlyMemoryCheck, Configuration: Debug x64 ------
3>Project not selected to build for this solution configuration 
4>------ Skipped Build: Project: Nightly, Configuration: Debug x64 ------
4>Project not selected to build for this solution configuration 
5>------ Build started: Project: FpfhTestDriver, Configuration: Debug x64 ------
6>------ Build started: Project: FpfhHeaderTestClean, Configuration: Debug x64 ------
7>------ Skipped Build: Project: Experimental, Configuration: Debug x64 ------
7>Project not selected to build for this solution configuration 
8>------ Skipped Build: Project: Continuous, Configuration: Debug x64 ------
8>Project not selected to build for this solution configuration 
9>------ Skipped Build: Project: ITKHeaderTests, Configuration: Debug x64 ------
9>Project not selected to build for this solution configuration 
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_d_main_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_d_coef_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_d_post_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_inverse_dct referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_upsampler referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_color_deconverter referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_1pass_quantizer referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_2pass_quantizer referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_merged_upsampler referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_d_main_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_d_post_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_upsampler referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_color_deconverter referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_d_diff_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_d_diff_controller referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j12init_lossless_decompressor referenced in function master_selection
5>itkjpeg-6.0.lib(jdmaster.obj) : error LNK2019: unresolved external symbol itk_j16init_lossless_decompressor referenced in function master_selection
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_c_main_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_c_prep_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_c_coef_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_color_converter referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_downsampler referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_forward_dct referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_c_main_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_c_prep_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_color_converter referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_downsampler referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_c_diff_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_c_diff_controller referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j12init_lossless_compressor referenced in function itk_jinit_compress_master
5>itkjpeg-6.0.lib(jcinit.obj) : error LNK2019: unresolved external symbol itk_j16init_lossless_compressor referenced in function itk_jinit_compress_master
5>C:\Misc\ITK-patches2-vs22\bin\Debug\FpfhTestDriver.exe : fatal error LNK1120: 31 unresolved externals
5>Done building project "FpfhTestDriver.vcxproj" -- FAILED.
10>------ Skipped Build: Project: INSTALL, Configuration: Debug x64 ------
10>Project not selected to build for this solution configuration 
========== Build: 2 succeeded, 1 failed, 4 up-to-date, 7 skipped ==========
========== Build completed at 12:20 and took 01.027 seconds ==========
```

**Review by thewtex — APPROVED** [review]
:100:

**Comment by dzenanz** [comment]
pixi builds seem to be timing out. Merging.

**Pull request merged**
