### PR TITLE
Fix lbfbs2 optimizer reuse

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
Thanks for the quick review and merge.

I'm not 100% happy with this. It was the quick fix to get working code, but it does introduce an additional per evaluation allocation of the parameters. It's not clear to be if the itk::OptimizerParameter class support being used as a "reference" array, which is what is needed to remove the additional malloc/copy.

**Comment by dzenanz** [comment]
@hjmjohnson it might be better to leave merging to PR authors who can merge themselves, e.g. Brad, me, Matt and Jon.

Most of the time it is fine, but sometimes we might be considering a squash, or waiting for some other PR to be merged to amend the PR in question. For example, #237 could have benefited from the middle commit being integrated upstream, and the other two commits squashed together. I didn't put a WIP there because it was OK in the original form too.

Merging for other authors is quite welcome!

**Comment by blowekamp** [comment]
I glad that it was merged. I am just looking for any suggestions how to handle the parameter arrays so as to avoid a memory allocation and copy.

**Comment by hjmjohnson** [comment]
@dzenanz I respectfully disagree with your assertion.  I'll try really hard to be on the 10am meeting today to discuss more in person, but a terse response is:

If not a WIP, and approved without concerning comments, and passes all dashboard tests, then add to master branch immediately.

Any other steps cause unnecessary burden all around.  If you want a hold, or merge by original author, then that should be easy to make it WIP, reject in the review, or just state in the comments the person who should be the merger.

======
FOR MY PATCHES:  Please merge as soon as you can after it passes all the safeguard checks (no WIP, dashboard pass, no concerning comments).  I don't want to log back in just to click the merge button, if you are there, please just do it.

That's my 2-cents, I'm open to change my views.

**Pull request merged**
