### PR TITLE
ENH: Add MetaDataObject Python wrapping with Matrix

### PR DESCRIPTION
**Pull request by PranjalSahu**
Needed to convert image to xarray. Dict method on image fails without these wrappings.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by PranjalSahu** [comment]
We should test it with more nifti files. 
With these changes it is able to convert the image sample in issue https://github.com/InsightSoftwareConsortium/ITK/issues/3520.
But there might be more keys for which we need to add support.

**Review by dzenanz — APPROVED** [review]

**Review by thewtex — APPROVED** [review]
:1st_place_medal:

**Comment by N-Dekker** [comment]
Sorry, I thought I was asked to review 6 minutes ago!

**Review by N-Dekker — COMMENTED** [review]
The wrapping looks fine, of course, although I did not try it out yet. Regarding the test, I would have liked to see something more like an Arrange, Act, and Assert ("AAA") style unit test. At least, I would have liked to see an `assert`. Maybe something to consider for the next test? Possibly using Python `unittest`, or `pytest`? Just a suggestion.

**Comment by PranjalSahu** [comment]
I was going to add one test with that sample nifit image but then I saw that xarray test is conditional due to package not present so I I skipped it for now.

**Comment by N-Dekker** [comment]
Also in general, I'd rather see less `print` statements in unit tests. Specifically when a test is passing successfully, it's often unnecessary to print internal details to the output. But anyway, thank you for your contribution! My two cents.

**Pull request merged**
