### PR TITLE
COMP: cherrypick HDF5 commit that added C++11 override keywords

### PR DESCRIPTION
**Pull request by seanm**
Backported 7501f96ab9605e11c58bc0c9e6412e4db30ba7db from upstream HDF5 to add C++11 override keyword where appropriate.

Fixes compiler warnings.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
@dzenanz @thewtex should fix some of the last warnings from my bots...

**Review by dzenanz — APPROVED** [review]
This makes us diverge from upstream more. Fine with me if you promise to do a proper update of HDF5 after 5.2.0 is out 😄

**Review by thewtex — APPROVED** [review]
@seanm thanks!

**Comment by thewtex** [comment]
Warnings:

https://open.cdash.org/viewBuildError.php?type=1&buildid=7089934

**Comment by seanm** [comment]
Phew, that one is in upstream, I just botched the (manual) merge.  Fixed now.

**Review by thewtex — APPROVED** [review]
:green_heart:

**Comment by jhlegarreta** [comment]
@seanm thanks for doing this :100: .

Just in case, you missed some, the `Rogue` builds are still complaining about some destructors not being marked with the `override` keyword e.g.
https://open.cdash.org/viewBuildError.php?type=1&buildid=7103987

e.g.
https://github.com/InsightSoftwareConsortium/ITK/pull/2392/files#diff-54e6f4714d9929b2e0e37566f30f2bc4a9de266f68f6f10a255113ff3de86d44L125

Looks like the [upstream](https://github.com/HDFGroup/hdf5/blob/develop/c++/src/H5DataSpace.h#L130) is also missing them.

`RogueResearch17` reports as well some other methods missing the keyword, e.g.
```
[CTest: warning matched] /Users/builder/external/ITK/Modules/ThirdParty/HDF5/src/itkhdf5src/H5PropList.h:104:30:
warning: 'fromClass' overrides a member function but is not marked 'override' [-Wsuggest-override]
        virtual H5std_string fromClass () const { return("PropList"); }
```
https://open.cdash.org/viewBuildError.php?type=1&buildid=7103543

Thanks for the effort Sean.

**Comment by seanm** [comment]
Yup, I have a PR pending upstream...

**Pull request merged**
