### PR TITLE
COMP: remove Eigen3 shadow warnings with GCC 4.8.5

### LINKED ISSUE #1254: Eigen warnings with GCC 4.8.5
I have a bunch of shadow warnings when compiling with GCC 4.8.5, see
[RTK dashoard](https://my.cdash.org/buildSummary.php?buildid=1702853). I am willing to fix them but I'm not sure what's the best procedure. Since they are coming from a third party software, Eigen3, should I add a rule in CMake/CTestCustom.cmake.in to ignore them or try to correct the Eigen3 code?

### PR DESCRIPTION
**Pull request by SimonRit**
Fixes #1254

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by phcerdan** [comment]
This is great @SimonRit, thanks. 
We have an Eigen fork/branch for itk in [here](https://gitlab.kitware.com/phcerdan/eigen/tree/for/itk). This patch should be integrated there first, and then call the UpdateFromUpstream script to merge into ITK, instead of directly merging here.

Eigen is a third party library, I don't think it scales well to diverge from upstream to omit warnings on a 5 years old compiler, however:
a) we can propose these changes into upstream, [here](https://bitbucket.org/eigen/eigen/src/default/). 
b) we can ignore this, and the user add the compiler flag `-Wno-shadow` to discard the spurious warnings for this particular compiler.

I will let ITK main maintainers to decide about it. I can integrate this patch in the for/itk branch of our Eigen fork, however I don't feel comfortable proposing this into upstream Eigen, I have the feeling that we would only solve it for a subset of Eigen, and only for old compilers. But of course, if @SimonRit is keen, you just have to flick a mail to Eigen mantainer, and shortly after you would be able to open merge requests there.

**Comment by SimonRit** [comment]
Sure, I understand your point. There is another option
c) Add a line in CMake/CTestCustom.cmake.in to ignore these warnings during ctest.

**Comment by phcerdan** [comment]
> c) Add a line in CMake/CTestCustom.cmake.in to ignore these warnings during ctest.

I would prefer that one too if it is only added when using gcc4.8 or older.

**Comment by thewtex** [comment]
Thanks for pushing this forward @SimonRit @phcerdan :clap: . I see a number of Eigen warnings locally beyond GCC 8 (not sure if it is these, though), and it would be excellent to clean up the noise :droplet: .

This patch seems like a very reasonable fix -- I think it would be worthwhile submitting a PR to upstream to see if they would accept it.

**Comment by dzenanz** [comment]
Does a recent update of Eigen interact with this PR?

**Comment by hjmjohnson** [comment]
No.  I was hopeful that the recent update would fix the problem, but alas it did not.

I had this problem before and after the recent update.


I can replicate on both mac and linux with pretty new CPU's, so I'm thinking it's a problem with Eigen conditional compilation code.

**Comment by hjmjohnson** [comment]
@phcerdan Is this PR still relevant after the recent Eigen work?

**Comment by phcerdan** [comment]
I don't have that GCC to reproduce it. The warnings are not there with a modern compiler.

**Comment by N-Dekker** [comment]
Slightly related: A fix that I proposed for another warning from an Eigen header file was merged into the Eigen master branch two weeks ago, by Rasmus Munk Larsen (@rmlarsen):

_Fix half_impl::float_to_half_rtne(float) warning: '<<' causes overflow_
https://gitlab.com/libeigen/eigen/-/merge_requests/202
https://gitlab.com/libeigen/eigen/-/commit/5328c9be4356cc3d7ab2e359acb1e9ebeeeea631

The warning did appear when building an ITK based application.

**Pull request merged**
