### PR TITLE
ENH: Added interface files for wrapped Python classes and methods.

### PR DESCRIPTION
**Pull request by kian-weimer**
Wrapped Python classes and methods, have introspection enabled typehints to allow auto-completion in IDE's.
    
Logic was added to the igenerator.py file to produce stubs for wrapped ITK classes in Python.
    
A large number of available ITK classes are currently supported by this feature, with more being worked on.
    
The itk-stubs directory is created with a __init__.pyi file that provides all the interface stubs to tools that can utilize stub files. The included interface files provide information needed for IDE's like Pycharm. Once built there should be no extra setup needed to get the hinting functionality.  The hints for type selection factories use Template and Proxy names  appended to them to differentiate them from the actual ITK classes. The  interfaces may provide hints for types that are not valid in some cases.  The interfaces suggest potentially correct input options.  For example methods may only accept a double or character depending on the object type, but the hints will suggest both leaving it up to the user to determine which type is valid.
    
NOTE: Stub files must use relative imports for .pyi files in order to expose the imported symbols.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5

### CODE REVIEW

**Comment by kian-weimer** [comment]
This is a continuation of PR #2480.

**Comment by kian-weimer** [comment]
The functionality is getting close to complete, I'm now in the process of testing, finding edge cases, and adding fixes for them. 
If anyone would like to test this out, feedback would be appreciated. 
The stub files should build automatically once `ITK_WRAP_PYTHON` is enabled. The stubs have only been verified to fully work with CLion so far.

**Comment by kian-weimer** [comment]
@dzenanz @thewtex @hjmjohnson 
To help bring people up to speed with the code changes, here is a power point that describes the current state of this PR.

Please let me know if you have any feedback. 

[ITK Python Typehinting.pdf](https://github.com/InsightSoftwareConsortium/ITK/files/7500062/ITK.Python.Typehinting.pdf)
[ITK Python Typehinting.pptx](https://github.com/InsightSoftwareConsortium/ITK/files/7500065/ITK.Python.Typehinting.pptx)

**Comment by hjmjohnson** [comment]
@kian-weimer  I think this is really close!  I have been using this within pycham, and it makes coding SOOO MUCH more pleasant!   Really great work.

@thewtex @dzenanz I think this is ready for review.  I'd love to hear you thoughts and if the interface stubs work in your favorite code editor.

**Comment by hjmjohnson** [comment]
Arrg.  Two silly little errors required force push.

**Review by dzenanz — APPROVED** [review]
LGTM on a glance. I use PyCharm and Visual Studio for Python code, so I should be able to try it.

**Review by hjmjohnson — APPROVED** [review]
@kian. Great work.

**Comment by phcerdan** [comment]
Are these `.pyi` files distributed via `pip`? It would be great to have an `itk-stubs` package for this.

Linking VTK conversation about this topic: https://discourse.vtk.org/t/python-ide-autocompletion-for-upcoming-vtk-9-1/6708/10

**Pull request merged**
