### PR TITLE
ENH: Deprecate some vector specializations

### PR DESCRIPTION
**Pull request by maekclena**
Addresses #725.

Deprecates the following classes:
- `VectorAnisotropicDiffusionFunction`
- `VectorCastImageFilter`
- `VectorCentralDifferenceImageFunction`
- ~~`VectorConfidenceConnectedImageFilter`~~
- ~~`VectorConnectedComponentImageFilter`~~
- `VectorCurvatureAnisotropicDiffusionImageFilter`
- `VectorCurvatureNDAnisotropicDiffusionFunction`
- `VectorExpandImageFilter`
- `VectorGradientAnisotropicDiffusionImageFilter`
- `VectorGradientMagnitudeImageFilter`
- `VectorGradientNDAnisotropicDiffusionFunction`
- ~~`VectorMeanImageFunction`~~
- `VectorNearestNeighborInterpolateImageFunction`
- `VectorResampleImageFilter`
- `VectorThresholdSegmentationLevelSetFunction`
- `VectorThresholdSegmentationLevelSetImageFilter`

Some classes remain because replacing them by their generic counterparts causes compilation errors (I still replaced as many references as possible):
- `VectorImageToImageMetricTraitsv4`
- `VectorLinearInterpolateImageFunction`
- `VectorInterpolateImageFunction`
- `VectorNeighborhoodInnerProduct`
- `VectorImageNeighborhoodAccessorFunctor`
- `VectorRescaleIntensityImageFilter`
- `VectorNeighborhoodOperatorImageFilter`

### CODE REVIEW

**Comment by blowekamp** [comment]
From memory, and cross checking with SimpleITK, I think the following vector filters do something different than the regular one:
- VectorConfidenceConnectedImageFilter
- VectorConnectedComponentImageFilter

**Comment by blowekamp** [comment]
Glad to see many for these specialization go away! Thanks for the work.

**Comment by dzenanz** [comment]
When you get CI green, it is probably best to squash all the changes into one commit.

**Comment by blowekamp** [comment]
This is the list of filter I have concerns about the regular version not properly supporting vector images:
- VectorCurvatureAnisotropicDiffusionImageFilter
- VectorGradientAnisotropicDiffusionImageFilter
- VectorThresholdSegmentationLevelSetImageFilter
- VectorGradientAnisotropicDiffusionImageFilter
- VectorGradientMagnitudeImageFilter

The criteria for depreciation is that the "regular" ( non-Vector ) version should produce the equivalent results, so that it is nearly a drop in replacement.

Off the top of my head, I know the following should be deprecated:
- VectorCastImageFilter
- VectorCentralDifferenceImageFunction
- VectorExpandImageFilter
- VectorNearestNeighborInterpolateImageFunction
- VectorResampleImageFilter

I would like to add a "-1" review, because I'm uncertain the correct criteria was used.

**Comment by maekclena** [comment]
After reverting the classes mentioned above, their dependencies and the ones failing the example tests I am down to only 2 classes deprecated. At this point it's not even worth merging so I suggest closing this PR and noting somewhere that a lot more work needs to be done to deprecate vector specializations.

**Pull request closed without merging**
