### PR TITLE
ENH: expose HDF5_BUILD_HL_LIB

### PR DESCRIPTION
**Pull request by dzenanz**
Comment out adding of HDF5 tests, as they are not bundled with ITK.

### CODE REVIEW

**Review by Leengit — APPROVED** [review]
Looks good.  It continues to get us past the HDF5 compile-time errors for Seg3D on my local system.

**Comment by dzenanz** [comment]
I could not locally reproduce Windows CI build failure. I have rebased and pushed again, let's see if we run into the same issue again.

**Comment by hjmjohnson** [comment]
@dzenanz The PR message and the content of the patch set do not seem related.  Did the wrong branch get force-pushed?

**Comment by dzenanz** [comment]
I was rebasing and force-pushing this branch, I forgot I had this PR open.

**Pull request closed without merging**
