### PR TITLE
Update HDF from 1.12.1 to 1.12.3 (2nd attempt)

### PR DESCRIPTION
**Pull request by seanm**

### CODE REVIEW

**Comment by thewtex** [comment]
Note: once CI is green, the symbols will also need to be per itk_hdf5_mangle.h.in.

**Comment by seanm** [comment]
> Note: once CI is green, the symbols will also need to be per itk_hdf5_mangle.h.in.

Hopefully next week I'll have time to try this again, on top of 5.4 branch.

**Comment by hjmjohnson** [comment]
Superceeded by #4940

**Comment by blowekamp** [comment]
> Superceeded by #4940

What in particular to you want to ensure is in this PR? That other PR, was not building correctly, and this PR makes an effort to remove changes from the HDF5 code base.

**Comment by hjmjohnson** [comment]
I just wanted to ensure that this PR references the other one as context since they both seem to be addressing the same update desire.

**Pull request closed without merging**
