### PR TITLE
STYLE: Apply "black -l 88" to format Python

### PR DESCRIPTION
**Pull request by Leengit**
Apply "black -l 88" (edited from "black -l 120") to format Python in `*.py` and `*.py.in` files.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Added test (or behavior not changed)
- [X] Updated API documentation (or API not changed)
- [X] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [X] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by hjmjohnson — CHANGES_REQUESTED** [review]
I am concerned about the "-I 120" flag being used.  I think it would be much better to simply run black without any line length flags.  

Maintaining consistent coding style is a lot easier if no specialized, non-default options are used.

**Comment by Leengit** [comment]
> I am concerned about the "-I 120" flag being used. I think it would be much better to simply run black without any line length flags.
> 
> Maintaining consistent coding style is a lot easier if no specialized, non-default options are used.

I got 120 from https://github.com/InsightSoftwareConsortium/ITK/blob/384fc45b0cb08e7651ba5cbd8d8ae38f6ff92559/.clang-format#L75 where it is used / enforced for ITK C++ code.

**Comment by Leengit** [comment]
With the second commit, I added a repository top-level configuration file `pyproject.toml` that specifies a default line-length of 120 for `black`.  I also rebased to the current `master` branch.

**Comment by Leengit** [comment]
I just rebased to the current master branch to get the fixes to the errors that we are seeing here.

**Review by dzenanz — APPROVED** [review]

**Comment by thewtex** [comment]
Please rebase on `'master`.

**Comment by Leengit** [comment]
Rebased to current master.

**Comment by Leengit** [comment]
@hjmjohnson This PR still shows "requesting changes" from you -- did the addition of the `pyproject.toml` address your comment?

**Comment by gdevenyi** [comment]
New in git for such style changes, an ignore facility for git blame

https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame

Can we get this added in this PR and I'll open an issue.

**Comment by Leengit** [comment]
@gdevenyi I've added the bulk-changes commit to `.git-blame-ignore-revs`.  Thank you for the suggestion.

**Comment by dzenanz** [comment]
We should probably add some of the historic bulk changes to that list too, but that can we done in a follow-up PR.

**Review by hjmjohnson — APPROVED** [review]
Approving with reservations.  I have mixed feelings about this.  I personally like 120 line lengths, but the neuro-imaging python standard is rapidly becoming 88 due to the prevalence of the default for `black`.    The config file will also need to be propagated to all sub-projects in the same way that clang format was propagated.  All the remote modules should also have the config file added.

**Comment by thewtex** [comment]
I have the same persective of Hans. 120 line length does look nicer, but it 88 is the community standard, and it will take effort to enforce remote modules the same way.

scipy is also consider black with the default 88 support:

  https://github.com/scipy/scipy/pull/14330

**Comment by Leengit** [comment]
I have redone it all, but with 88 instead of 120 for the line length, and have done a force push.

**Review by dzenanz — APPROVED** [review]

**Comment by Leengit** [comment]
I just rebased to the current master branch.

**Review by tbirdso — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]
I enthusiastically approve of this PR!

**Comment by Leengit** [comment]
Some part of this process, perhaps the rebasing, changed the hash of the commit to be added to `.git-blame-ignore-revs`.  Because this could keep happening, I will submit a follow-up PR with the correct commit hash once this PR has been fully merged.

**Review by thewtex — APPROVED** [review]
Thanks @Leengit !

**Pull request merged**
