### PR TITLE
ENH: wrapped remaining v4 Registration classes

### PR DESCRIPTION
**Pull request by brad-t-moore**
See #3099
Added Python testing to existing wrapped classes and added ones
Moved any wrapping commands for the RegistrationParameterScales classes from parameter .wrap files into central ones
Created itkMetricv4Types.wrap which is used by the RegistrationParameterScales classes wrapping
RegistrationParameterScales classes are in the Metricv4 folder to prevent a cyclic build dependency

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
Looks good on a glance.

**Comment by brad-t-moore** [comment]
I think the warning that threw this off is `2022-02-09T02:23:50.5840494Z itkTimeVaryingVelocityFieldImageRegistrationMethodv4: warning(4): ITK type not wrapped, or currently not known: itk::DataObjectDecorator< itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform< double, 2 > >`

No tests failed though.

**Comment by brad-t-moore** [comment]
I think I need to add `itk::GaussianSmoothingOnUpdateTimeVaryingVelocityFieldTransform` like the other transforms in `RegistrationMethodv4.wrap

**Comment by brad-t-moore** [comment]
Here's hoping this works.  Interesting that these SWIG "warnings" are essentially errors but Visual Studio doesn't report them as such.

**Pull request merged**
