### PR TITLE
BUG: fix exception handling in itk::PoolMultiThreader

### LINKED ISSUE #2776: Exception not caught with PoolMultiThreader if not in main task
### Description

An exception is launched but not caught by PoolMultiThreader when the exception is not launched by the main task.

### Steps to Reproduce

I have written the following minimal example to reproduce the issue:

```cpp
#include <itkImageSource.h>

namespace itk
{
template <typename TOutputImage>
class ITK_TEMPLATE_EXPORT DummyImageSource
  : public ImageSource<TOutputImage>
{
public:
  ITK_DISALLOW_COPY_AND_MOVE(DummyImageSource);

  /** Standard class type aliases. */
  using Self = DummyImageSource;
  using Superclass = ImageSource<TOutputImage>;
  using Pointer = SmartPointer<Self>;
  using ConstPointer = SmartPointer<const Self>;

  /** Convenient type alias. */
  using OutputImageRegionType = typename TOutputImage::RegionType;

  /** Method for creation through the object factory. */
  itkNewMacro(Self);

  /** Run-time type information (and related methods). */
  itkTypeMacro(DummyImageSource, ImageSource);

protected:
  DummyImageSource() = default;
  ~DummyImageSource() override = default;
  void GenerateOutputInformation() override
  {
  TOutputImage * output = nullptr;
  output = this->GetOutput(0);
  typename TOutputImage::RegionType largestPossibleRegion;
  largestPossibleRegion.SetSize({4,4,4});
  output->SetLargestPossibleRegion(largestPossibleRegion);
  }

  void
  DynamicThreadedGenerateData(const OutputImageRegionType & outputRegionForThread) override
  {
    if(outputRegionForThread.GetIndex() != typename TOutputImage::IndexType())
    {
      std::cout << "Exception launched" << std::endl;
      itkGenericExceptionMacro(<< "Error");
    }
  }
};
} // end namespace itk

int
main(int argc, char * argv[])
{
  using OutputPixelType = float;
  constexpr unsigned int Dimension = 3;

  using OutputImageType = itk::Image<OutputPixelType, Dimension>;

  typename itk::DummyImageSource<OutputImageType>::Pointer dummySrc;
  dummySrc = itk::DummyImageSource<OutputImageType>::New();
  try
  {
    dummySrc->Update();
  }
  catch (itk::ExceptionObject & err)
  {
    std::cerr << "Problem!!!" << std::endl;
    return EXIT_FAILURE;
  }
  std::cout << "No problem" << std::endl;
  return EXIT_SUCCESS;
}
```
### Expected behavior

The following should be displayed
```
Exception launched
Exception launched
Exception launched
Problem!!!
```
which occurs with the environment variable ITK_GLOBAL_DEFAULT_THREADER=PLATFORM

### Actual behavior

```
Exception launched
Exception launched
Exception launched
No problem
```

### Reproducibility

100%

### Versions

eec9fe6705

### Environment

Linux

### PR DESCRIPTION
**Pull request by SimonRit**
Exception thrown in most threads were not caught. Fixes #2776.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by SimonRit** [comment]
Should I add a test based on #2776? Any pointer to a test demonstrating correct exception handling?

**Comment by dzenanz** [comment]
Yes, adding a test based on repro in #2776 is desirable. It can be an additional commit.

**Review by dzenanz — APPROVED** [review]

**Comment by SimonRit** [comment]
> Yes, adding a test based on repro in #2776 is desirable. It can be an additional commit.

Done in f07aad09314df57d1b636e6cca8a13161c1b7c9a

**Review by dzenanz — APPROVED** [review]
Awesome!

**Pull request merged**
