### PR TITLE
ENH: Provide rating scale for ITK Remote modules

### PR DESCRIPTION
**Pull request by hjmjohnson**
SEE https://discourse.itk.org/t/remote-module-grading-ranking-system-needed/2750

Resolves issue #1655

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed)
- [X] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

### CODE REVIEW

**Comment by hjmjohnson** [comment]
> Thanks again for the effort Hans.
> 
> A general comment: I would assume that when a module complies with level `N`, it automatically complies with all lower levels `[N-1,0]`.
> 
> As for a full review/approval, I will defer the decision to others as I am not fully convinced that this is the solution to the current situation. Unfortunately, I have no better proposals or time to develop the aspects I brought in the discourse thread. I am sorry 😔.

@jhlegarreta Thanks!  You are correct that the selection defines the minimum.

**Comment by jhlegarreta** [comment]
@hjmjohnson I may have not made clear my point :thinking: : if a module complies with e.g. level 4, then I would assume that checking `[X] All requirements below` at level 4 would imply that either **all** checkboxes of levels 0, 1, 2, and 3 should be checked or left empty (whatever it is decided to be best). Hence, I am not sure about the rationale behind checking `[X] All requirements below` at e.g. level 4 and checking only **some** of the checkboxes in lower levels.

**Comment by lassoan** [comment]
Instead of "All requirements below", it would be more clear to say "All requirements for Level 1-3 fulfilled" (otherwise Level 0 would be contradictory).

I would not repeat the grading checklist in each cmake file, I would just keep the MODULE_COMPLIANCE_LEVEL value and a comment that explains why the software is at the current level (what are the main limitations that would need to be fixed to get to the next level). This way the checklist could be maintained more easily (it would not be replicated in each of the 44 modules) and would better match reality: that the checklist is a guideline only (there is no way it can reflect the current state of all modules all the time).

**Comment by hjmjohnson** [comment]
> Instead of "All requirements below", it would be more clear to say "All requirements for Level 1-3 fulfilled" (otherwise Level 0 would be contradictory).
> 
> I would not repeat the grading checklist in each cmake file, I would just keep the MODULE_COMPLIANCE_LEVEL value and a comment that explains why the software is at the current level (what are the main limitations that would need to be fixed to get to the next level). This way the checklist could be maintained more easily (it would not be replicated in each of the 44 modules) and would better match reality: that the checklist is a guideline only (there is no way it can reflect the current state of all modules all the time).

@lassoan I agree 100% with your first comment and will implement that in the next few days. 

Regarding having the checklist in each file, as each module will have a different status, and meet different criteria on the checklist, I think it is important to act as a per-module report-card/roadmap of what needs to be done to elevate the module to the next grading level.

**Comment by hjmjohnson** [comment]
Thanks, everyone for your feedback. I think we have a good, low burden solution that is better than the previous one.

**Pull request merged**
