### PR TITLE
BUG: Restore Doxygen on enabled Remote modules

### PR DESCRIPTION
**Pull request by blowekamp**
This was temporarily disabled in commit 8f67778c for "debugging"
purposes.

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [x] Added test (or behavior not changed)
- [x] Updated API documentation (or API not changed)
- [x] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [x] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [x] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by thewtex** [comment]
Has this been tested?

**Comment by blowekamp** [comment]
I had to make this change to generate Doxygen for the SimpleITKFilters to get that documentation into SimpleITK. 

The classes in any of the remote modules are not in the ITK doxygen. Some were configured on the nightly build of the ITK Doxygen. There are likely more doxygen warning errors in some remote module.

**Comment by blowekamp** [comment]
The remote modules should be disabled from the Doxygen build. Then added back as the they are  are fixed.

In the current state NO ONE can build or test the Doxygen in remote modules. I guess that is OK.

**Comment by thewtex** [comment]
> In the current state NO ONE can build or test the Doxygen in remote modules.

This is an incorrect statement.

**Comment by blowekamp** [comment]
> This is an incorrect statement.

A constructive reply would include HOW one currently build Doxygen for a remote module.

I'll amend my statement to improve accuracy: In the current state *no one* can build or test the Doxygen in remote modules as part of the ITK build.

**Comment by thewtex** [comment]
> In the current state NO ONE can build or test the Doxygen in remote modules. I guess that is OK.

No, this is an example of a non-constructive reply.

> A constructive reply would include HOW one currently build Doxygen for a remote module.

This has to be determined, and it will take investigation, but the method should not break the Doxygen build altogether.

**Pull request closed without merging**
