### PR TITLE
ENH: use double-conversion's CMake targets

### LINKED ISSUE #579: Use find_package and target_link_libraries to include system double conversion and properly include double-conversion
### Description
double-conversion exports configs and targets. Those should be used to correctly include/link against double-conversion. 

### Expected coding style
in ITK\Modules\Core\Common\src\itkNumberToString.cxx 
`#include "double-conversion/double-conversion.h"`
(actually would expect `#include <double-conversion/double-conversion.h>` for system headers
 but that is against ITK coding style)

 In ITK\Modules\ThirdParty\DoubleConversion\CMakeLists.txt
```
if(ITK_USE_SYSTEM_DOUBLECONVERSION)
  find_package(double-conversion CONFIG REQUIRED)
else()
```
and a target_link_libraries call where the target which requires double-conversion is linked against target double-conversion::double-conversion (Properly in  ITK\Modules\Core\Common\src\CMakeLists.txt @ line 138)

### Actual coding style
in ITK\Modules\Core\Common\src\itkNumberToString.cxx 
`#include "double-conversion.h"`

 In ITK\Modules\ThirdParty\DoubleConversion\CMakeLists.txt
```
if(ITK_USE_SYSTEM_DOUBLECONVERSION)
  find_library(double-conversion_LIBRARIES double-conversion)
  find_path(double-conversion_INCLUDE_DIRS double-conversion.h
    PATH_SUFFIXES double-conversion
    )

  if (double-conversion_LIBRARIES AND double-conversion_INCLUDE_DIRS)
    set(ITKDoubleConversion_SYSTEM_INCLUDE_DIRS
      ${double-conversion_INCLUDE_DIRS})
    set(ITKDoubleConversion_LIBRARIES
      "${double-conversion_LIBRARIES}")
  else()
    message(ERROR "double-conversion system library not found")
  endif()
else()
```

### PR DESCRIPTION
**Pull request by dzenanz**
This will support multiple system versions of double-conversion.
Suggested by Alexander Neumann. Closes #579. Aimed to be back-ported to 4.13.x release to address #912.

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

### CODE REVIEW

**Comment by dzenanz** [comment]
double-conversion is a library with no dependencies, and it is only privately used in ITK's modules (except remote module Montage, and I am looking into that right now). So we don't have to list it as a public dependency in package configuration file.

**Comment by dzenanz** [comment]
... and Montage also privately depends on double-conversion, so I will change the module specification to reflect that.

**Comment by hjmjohnson** [comment]
@dzenanz Can this be merged?

**Comment by dzenanz** [comment]
I am waiting for @TheChymera's confirmation that it fixes the issue it is supposed to address.

**Comment by TheChymera** [comment]
@dzenanz afaict it [does not](https://github.com/InsightSoftwareConsortium/ITK/issues/912#issuecomment-497835463).

**Pull request merged**
