### PR TITLE
COMP: Fix SW Guide examples LaTeX block line start warnings

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix SW Guide examples LaTeX block line start warnings.

Fixes:
```
Examples/Segmentation/GeodesicActiveContourImageFilter.cxx:534: warning:
Line after start of LaTeX block should be a newline -- instead got /*
```
and
```
Examples/Segmentation/GeodesicActiveContourShapePriorLevelSetImageFilter.cxx:987:
warning: Line after start of LaTeX block should be a newline -- instead
got /*

```
and
```
Examples/Segmentation/IsolatedConnectedImageFilter.cxx:241: warning: Line
after start of LaTeX block should be a newline -- instead got /*
```
and
```
Examples/Segmentation/VectorConfidenceConnected.cxx:268: warning: Line
after start of LaTeX block should be a newline -- instead got /*
```

raised at:
https://open.cdash.org/viewBuildError.php?type=1&buildid=6680104

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
- The clang formatting pre-commit hook had failed locally on my end, and the label-triggered action also seems to have failed. The latter seems like an access issue; not sure whether I should do something on my ITK fork.
- `ITK.Linux.Python` failures are unrelated.

So unless someone wants to apply the clang formatting locally and push that, this is ready to be merged.

**Comment by dzenanz** [comment]
> Maybe the #include "itkMacro.h" statement is missing?

This might be it.

**Comment by thewtex** [comment]
> The latter seems like an access issue; not sure whether I should do something on my ITK fork.

To use that action, the branch / PR has to be made from `InsightSoftwareConsortium/ITK`.

**Comment by thewtex** [comment]
> unless someone wants to apply the clang formatting locally and push that

I'll do this.

> Maybe the #include "itkMacro.h" statement is missing?

And add this.

**Comment by jhlegarreta** [comment]
> To use that action, the branch / PR has to be made from InsightSoftwareConsortium/ITK.

Thanks for the explanation Matt.

> green_heart thanks @jhlegarreta !

As always, it's a pleasure to be part of this ! :+1:

**Comment by jhlegarreta** [comment]
Not sure why Circle CI complains:
 ```
CMake Error at /home/circleci/ITK-dashboard/itk_common.cmake:506 (message):
  Build did not complete without warnings, errors, or failures.
Call Stack (most recent call first):
  /home/circleci/ITK-dashboard/circleci.cmake:84 (include)
```
maybe it was unable to submit results to the dashboard; the tests it run did not fail: `100% tests passed, 0 tests failed out of 2751`.

In any case, the Azure Pipelines builds passed :tada: :fireworks: , so in my opinion this can be safely merged.

**Pull request merged**
