### PR TITLE
DOC: Transfer the wiki HU page to Markdown documentation

### PR DESCRIPTION
**Pull request by jhlegarreta**
Transfer the wiki HU page to Markdown documentation: https://itk.org/Wiki/ITK_Hounsfield_Units

Rename the document and title to honor the contents.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by thewtex — APPROVED** [review]
:1st_place_medal:

**Comment by thewtex** [comment]
Perhaps should go in the FAQ?

**Comment by jhlegarreta** [comment]
> Perhaps should go in the FAQ?

OK. Will integrate in there once the FAQ gets merged. Making it a draft for now.

**Comment by jhlegarreta** [comment]
> OK. Will integrate in there once the FAQ gets merged. Making it a draft for now.

Done in 3760101.

**Pull request merged**
