### PR TITLE
COMP: Fix missing initialization braces warning

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix missing initialization braces warning.

Fixes:
```
[CTest: warning matched]
/Users/builder/externalModules/Core/Common/test/itkPointSetToImageFilterTest1.cxx:76:40:
warning: suggest braces around initialization of subobject [-Wmissing-braces]
  BinaryImageType::PointType origin{ { -125, -125 } };
                                       ^~~~~~~~~~
                                       {         }
[CTest: warning suppressed] 1 warning generated.
```

Raised for example in:
https://open.cdash.org/viewBuildError.php?type=1&onlydeltap&buildid=7794978

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Review by N-Dekker — APPROVED** [review]
Wow, two pairs of braces still not enough? Apparently so! 😮 [comment edited] ... approved.

**Comment by seanm** [comment]
Again, I'd love to turn this warning off, if only I could figure out how...  I've put `-Wno-missing-braces` which you can see here:

https://open.cdash.org/build/7797155/notes

But it's clearly not in the right place, or being overridden, or something.  I've never been able to figure it out. :(

**Review by thewtex — APPROVED** [review]

**Comment by N-Dekker** [comment]
FYI, The warning appears with clang 5.0.2, but it no longer appears with clang 6.0.0, at least according to godbolt.org:

```
struct PointType
{
    PointType(const std::array<double, 2>&);
};

PointType origin{ { -125, -125 } };

```
https://godbolt.org/z/73vPd9Ke9

**Comment by seanm** [comment]
Which is why I'd like to disable it on that older bot (which runs the newest Xcode that macOS can).

**Pull request merged**
