### PR TITLE
BUG: Avoid itkConfig double import trap

### PR DESCRIPTION
**Pull request by hjmjohnson**
This potential failure mode can be summed up in the following general
guideline: “Never add a package directory, or any directory inside a
package, directly to the Python path”.

The reason that adding nested directories to the Python sys.path is
problematic is that every module in that directory is now potentially
accessible under two different names: as a top level module (since the
directory is on sys.path) and as a submodule of the package (if the
higher level directory containing the package itself is also on
sys.path).

We must import the itkConfig module from python path, not local reference
in order to maintain the desired behavior that the module acts
as a singleton for the module values (i.e. once the
itkConfig module is loaded, we assume it is never loaded again,
thus changed values like itkConfig.LazyLoading persist across
diffent modules).

`import .conf.itkConfig` is a different context than
`import itkConfig`, even if they are the same file. The
LazyLoading and other values may be different in the two contexts.

In order to maintain backward compatibility AND avoid the
double import trap by “Never add a package directory, or any directory
inside a package, directly to the Python path”, the itkConfig.py file
must exist outside of the itk package directory (it *must* be a stand-alone
single file module).

http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]
LGTM, but @thewtex should review.

**Review by thewtex — APPROVED** [review]
:+1: thanks for the follow-up, Hans!

**Comment by dzenanz** [comment]
With 3ac149f83078e788f2fc868d9eaa9ae6fc2ec7f7 I get the following output on `import itk`:

```text
WARNING: Internal configuration path is invalid: M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
WARNING: Invalid: swig_lib: location of the swig-generated shared libraries
WARNING: Internal configuration path is invalid: M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
WARNING: Invalid: swig_py: location of the xxxPython.py swig-generated python interfaces
WARNING: Internal configuration path is invalid: M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
WARNING: Invalid: config_py: location of xxxConfig.py CMake-generated library descriptions
WARNING: Invalid configuration directory requested: M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files (x86)\microsoft visual studio\2019\professional\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "M:\Dev\ITK-git\Modules\Core\Common\wrapping\test\itkPythonMultiProcessingTest.py", line 6, in <module>
    import itk
  File "M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 105, in <module>
    _initialize_module()
  File "M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 54, in _initialize_module
    from .support import itkBase as _itkBase
  File "M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 312, in <module>
    _initialize(itk_base_global_module_data)
  File "M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 287, in _initialize
    f"WARNING: Invalid configuration directory requested: {candidate_config_path}"
RuntimeError: WARNING: Invalid configuration directory requested: M:\Dev\ITK-vs19\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
```
`ITKCommonConfig.py` and friends are in `M:\Dev\ITK-vs19\Wrapping\Generators\Python\itk\Configuration`. Do you think a clean build would help?

**Comment by hjmjohnson** [comment]
Clean build is definitely my first attempt.    There have been many files moved.

**Pull request merged**
