### PR TITLE
STYLE: Remove tab.

### PR DESCRIPTION
**Pull request by jhlegarreta**
Remove tab that slipped in commit b8a1416.

## PR Checklist
- [ ] [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] Adds the License notice to new files.
- [ ] Adds Python wrapping.
- [ ] Adds tests and baseline comparison (quantitative).
- [ ] [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@maekclena please review. Thanks.

**Comment by maekclena** [comment]
That tab is intentional as that's how the output of `git ls-remote` is formatted. I admit it looks a bit out of place so an alternative could be to replace it with the special notation `[[:space:]]`.

**Comment by jhlegarreta** [comment]
👍 Thanks for the review @maekclena !! To avoid further confusion with the tab, I switched to the `[[:space:]]` solution you suggested.

**Comment by jhlegarreta** [comment]
Checked locally that the fix is working: commit hashes in remote modules' `cmake` files are updated as expected

Merging.

**Pull request merged**
