### PR TITLE
ENH: Refactor UpdateDoubleConversionFromGoogle.sh

### LINKED ISSUE #3193: Refactor UpdateDoubleConversionFromGoogle.sh
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/DoubleConversion/UpdateDoubleConversionFromGoogle.sh needs to be updated to use https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/Maintenance/update-third-party.bash, similar to e.g. https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/ThirdParty/ZLIB/UpdateFromUpstream.sh.

### LINKED ISSUE #3204: Upgrade Google double-conversion library as "REQUIRED" (at least to version 3.1.6)
With pull request #3160  commit https://github.com/InsightSoftwareConsortium/ITK/commit/701c8c25ea998cc5defdd3457241c518a7b8b65b ("COMP: Add minimum version for double-conversion" by @RafaelPalomar), ITK requires _at least_ version 3.1.6 of the double-conversion library: https://github.com/InsightSoftwareConsortium/ITK/blob/701c8c25ea998cc5defdd3457241c518a7b8b65b/Modules/ThirdParty/DoubleConversion/CMakeLists.txt#L10

At least, when `ITK_USE_SYSTEM_DOUBLECONVERSION` is enabled.

Would it be possible to also upgrade the "embedded" (non-system) version of that library, at https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/DoubleConversion/src ? As I suggested at https://github.com/InsightSoftwareConsortium/ITK/pull/3160#issuecomment-1036156664

Related issue: #3193 "Refactor UpdateDoubleConversionFromGoogle.sh" by @dzenanz

### PR DESCRIPTION
**Pull request by dzenanz**
Closes #3193. Closes #3204.

### CODE REVIEW

**Comment by dzenanz** [comment]
Trying to run this, everything seems fine until:
```log
...
Unpacking objects: 100% (26/26), 74.22 KiB | 1.81 MiB/s, done.
From C:/Misc/ITK-patches/work/extract
 + e7cc73eea0...5f9b33bbc0 upstream-DoubleConversion -> upstream-DoubleConversion  (forced update)
++ git merge --log -s ours --no-commit --allow-unrelated-histories upstream-DoubleConversion
Automatic merge went well; stopped before committing as requested
++ git read-tree -u --prefix=Modules/ThirdParty/DoubleConversion/src/ upstream-DoubleConversion
error: Entry 'Modules/ThirdParty/DoubleConversion/src/double-conversion/SConscript' overlaps with 'Modules/ThirdParty/DoubleConversion/src/double-conversion/SConscript'.  Cannot bind.
+ rm -rf /c/Misc/ITK-patches/work

Dzenan@Ryzenator MINGW64 /c/Misc/ITK-patches/Modules/ThirdParty/DoubleConversion (master|MERGING)
```
We probably need a one-time action to keep continuity with the old `double-conversion` tree. I don't know how to accomplish that. @bradking can you help?

**Comment by bradking** [comment]
It looks like #2214 updated the doubleconversion code directly without merging the upstream vendor branch.  It will take me some time to unravel this.

**Comment by bradking** [comment]
@dzenanz I updated your branch to record history of the prior imports in a way that both converts to the new-style script and recovers from the above-mentioned direct import.  Please fetch and reset your checkout to match my version of the branch.  After that you should be able to run the script again locally to update.  Then you can push again to fast-forward the PR branch to include the new update commits.

**Comment by dzenanz** [comment]
@bradking Thank you!

**Review by bradking — APPROVED** [review]

**Review by hjmjohnson — APPROVED** [review]

**Comment by N-Dekker** [comment]
Thanks very much @dzenanz, @bradking, @hjmjohnson! FYI, an ITK pull request that I submitted yesterday (PR #3542) already makes use of a new double-conversion library feature (`StringToDoubleConverter::StringTo<T>`), which has just become available to ITK with the new UpdateDoubleConversionFromGoogle  😃

**Pull request merged**
