### PR TITLE
ENH: Restore integer support for laplacian sharpening

### PR DESCRIPTION
**Pull request by blowekamp**
Revert to using the a laplacian neighborhood operator over the recursive laplacian filter which requires real pixel types for input and output.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by blowekamp** [comment]
@ntustison This PR restores support for integer pixel types while removing the scaling when the UseSpacing flag is false. This uses the original neighborhood operator filter.

SimpleITK did instantiate this filter with integer pixel types.

**Review by dzenanz — COMMENTED** [review]
LGTM on a glance.

**Comment by ntustison** [comment]
Thanks @blowekamp .  I think I mentioned in the original PR that I had no preference other than this and the Laplacian filter be uniform in their possible input types.

**Comment by blowekamp** [comment]
This is the falling test on OSX:
https://open.cdash.org/test/1112051341

It appears unrelated. @dzenanz Can you please retriever just the AZP ITK.macOS build

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
