### PR TITLE
ENH: Set ITK_TEST_OUTPUT_DIR with module path

### PR DESCRIPTION
**Pull request by blowekamp**
Change the default output path for modules testing data to include the
module name as a directory.

This prevents the same file name in defferent modules clobbering one
another causing intermediate testing failures.

## PR Checklist
- [ ] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ ] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
Does this work as intended? Or to rephrase the question: how thoroughly has this been tested? It has potential to cause minor disruption in some remote modules.

**Comment by blowekamp** [comment]
> how thoroughly has this been tested?

It has not been thoroughly tested. It seemed to work locally. And using the CI to test what happens across systems on clean build seemed like the next step.

>  It has potential to cause minor disruption in some remote modules.

Yes indeed. Alternatively, a new CMake variable could be introduced, and every thing changed to used it.. but that is more work that I care to tackle especially with the remote modules.

**Comment by jhlegarreta** [comment]
If remote modules do provide an appropriate value for the `itk-module` variable, this seems a fair solution to me.

**Comment by dzenanz** [comment]
> remote modules provide ... itk-module

I don't think this is an issue. I think there are some assumptions where the test temp dir is. Updating that should not be hard.

**Comment by blowekamp** [comment]
Looks like all the tests in the CI passed :)

**Comment by dzenanz** [comment]
Probably best to check how it works for externally built remote modules (pick 2-3 to test). I expect that remotes built as part of ITK will behave the same as regular modules.

**Comment by thewtex** [comment]
Seems fine to generally help with filename clobbering issues. I tend to use the consolidated testing output directory with `rm -rf ITK-build/Testing/Temporary` to clean up build trees that are used repeatedly over time and inflate disk usage. This would make it more difficult, but maybe we could also isolate more easily areas that require cleanup.

**Comment by blowekamp** [comment]
> I tend to use the consolidated testing output directory with `rm -rf ITK-build/Testing/Temporary` to clean up build trees that are used repeatedly over time and inflate disk usage.

That will still work as the new test output directory for modules will be like `ITK-build/Testing/Temporary/ITKCommon` and not under the modules build path.

**Comment by jhlegarreta** [comment]
If as @dzenanz said rather than the module name issue this is likely to impact the output dir expected by the remotes, once that has been checked, I'd be for the change.

**Comment by dzenanz** [comment]
Brad, are we still targeting this for 5.3?

**Review by hjmjohnson — APPROVED** [review]
I think this is ready for merging now.

**Pull request merged**
