### PR TITLE
ENH: Rename ResampleInPlaceImage to TransformGeometryImageFilter

### PR DESCRIPTION
**Pull request by blowekamp**
Community discussion and voting converged TransformGeometryImageFilter
is a more accurate name for the operation.

Renamed per the discussion: https://discourse.itk.org/t/simpleitk-euler3d-transform-adjust-image-origin-and-direction/3966/25

### CODE REVIEW

**Review by hjmjohnson — APPROVED** [review]
This is great!  You also had identified bugs in pipeline processing.  Will you be addressing those issues as well?

**Review by zivy — APPROVED** [review]

**Comment by blowekamp** [comment]
@hjmjohnson Yes, I am working on those now. I am prioritizing API changes to get them merged before the RC. Internal corrections and pipeline fixes are coming.

**Comment by hjmjohnson** [comment]
> @hjmjohnson Yes, I am working on those now. I am prioritizing API changes to get them merged before the RC. Internal corrections and pipeline fixes are coming.

You are awesome!  Thank you.

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
I guess merge as soon as the CI comes back green?

**Review by dzenanz — APPROVED** [review]

**Pull request merged**
