### PR TITLE
WIP: Trying building Doxygen on CircleCI for ITK

### PR DESCRIPTION
**Pull request by blowekamp**

### CODE REVIEW

**Comment by blowekamp** [comment]
@thewtex 
Any idea why CircleCI is not build pull requests on Github? I wanted to see of ITK Doxygen could be build with in the time window allowed.

**Comment by thewtex** [comment]
@blowekamp We have *Build forked pull requests* enabled in the *InsightSoftwareConsortium/ITK* CircleCI settings, which should enable this behavior. But, I have observed other projects not building their pull requests over the last few days, with no changes on my end ...

**Comment by blowekamp** [comment]
@thewtex It looks like the build time for Doxygen on CircleCI should be doable. Should we persue building Doxygen on CircleCI further?

Currently, the CircleCI builds a failing due to compiler warnings. The docs job needs some work to doable testing. Yaml anchors need to be used to reduce dupolication etc...

**Comment by thewtex** [comment]
@blowekamp If you would like to pursue it, then go for it.

**Comment by blowekamp** [comment]
I can pursue getting this CircleCI script functioning, but it will need coordination on either getting itk.org updated with the results or figuring out how to push it to GitHub.io on demand.

**Comment by thewtex** [comment]
I will look into using the results on itk.org if it works.

**Comment by hjmjohnson** [comment]
@blowekamp  can you rebase this onto of the master branch?

**Comment by blowekamp** [comment]
There is not longer interest in building Doxygen on CircleCI.

**Pull request closed without merging**
