### PR TITLE
ENH: Update SWIG python documentation

### PR DESCRIPTION
**Pull request by hjmjohnson**
Update SWIG to allow new documentation improvements for python introspections.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
LGTM, but Matt should double-check.

**Comment by hjmjohnson** [comment]
@dzenanz Would you mind running a windows python build with these changes?

**Comment by dzenanz** [comment]
Incremental or clean build?

**Comment by dzenanz** [comment]
I am starting an incremental build.

**Comment by dzenanz** [comment]
It builds, but all the Python tests fail. Typical example:

```text
2960: Test command: C:\Dev\ITK-19DLL\bin\RelWithDebInfo\itkTestDriver.exe "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/RelWithDebInfo" "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/RelWithDebInfo/itk/conf" "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/itk/RelWithDebInfo" "--add-before-libpath" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/itk/RelWithDebInfo" "--add-before-libpath" "C:/Dev/ITK-19DLL/bin/RelWithDebInfo" "C:/Program Files/Python37/python.exe" "C:/Dev/ITK-git/Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py"
2960: Test timeout computed to be: 1500
2960: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
2960: WARNING: Invalid: swig_lib: location of the swig-generated shared libraries
2960: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
2960: WARNING: Invalid: swig_py: location of the xxxPython.py swig-generated python interfaces
2960: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
2960: WARNING: Invalid: config_py: location of xxxConfig.py CMake-generated library descriptions
2960: Traceback (most recent call last):
2960:   File "C:/Dev/ITK-git/Modules/Bridge/NumPy/wrapping/test/itkPyVectorContainerTest.py", line 22, in <module>
2960:     import itk
2960:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 107, in <module>
2960:     _initialize_module()
2960:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 37, in _initialize_module
2960:     from .support.itkBase import ITKModuleInfo, ITKTemplateFeatures
2960:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 395, in <module>
2960:     _initialize(itk_base_global_module_data)
2960:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 377, in _initialize
2960:     raise RuntimeError(error_message)
2960: RuntimeError: WARNING: Invalid configuration directory requested: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
2960: itkTestDriver: Process exited with return value: 1
114/124 Test #2960: itkPyVectorContainerTest ...........................................***Failed    1.11 sec
```
Path `C:/Dev/ITK-19DLL/Wrapping/Generators/Python/RelWithDebInfo` does not exist. Most Python-related files are in `C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk`. `itkBase.py` is in `C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo`. But this is probably due to other changes, or maybe unclean build. I will start a new clean build.

**Review by thewtex — APPROVED** [review]
Nice! LGTM!

**Comment by dzenanz** [comment]
Clean build did not change the outcome. With yesterday's master (1401fdbe4f341849e6f5ad2b5b94a2a2d565f66d), Python runtime failures persist:
```text
        Start 2812: PythonFindEmptyClasses

2812: Test command: C:\Dev\ITK-19DLL\bin\RelWithDebInfo\itkTestDriver.exe "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/RelWithDebInfo" "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/RelWithDebInfo/itk/conf" "--add-before-env" "PYTHONPATH" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/itk/RelWithDebInfo" "--add-before-libpath" "C:/Dev/ITK-19DLL/Wrapping/Generators/Python/itk/RelWithDebInfo" "--add-before-libpath" "C:/Dev/ITK-19DLL/bin/RelWithDebInfo" "C:/Program Files/Python37/python.exe" "C:/Dev/ITK-git/Wrapping/Generators/Python/Tests/findEmptyClasses.py"
2812: Test timeout computed to be: 1500
2812: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
2812: WARNING: Invalid: swig_lib: location of the swig-generated shared libraries
2812: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\RelWithDebInfo
2812: WARNING: Invalid: swig_py: location of the xxxPython.py swig-generated python interfaces
2812: WARNING: Internal configuration path is invalid: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
2812: WARNING: Invalid: config_py: location of xxxConfig.py CMake-generated library descriptions
2812: Traceback (most recent call last):
2812:   File "C:/Dev/ITK-git/Wrapping/Generators/Python/Tests/findEmptyClasses.py", line 19, in <module>
2812:     import itk
2812:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 123, in <module>
2812:     _initialize_module()
2812:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\__init__.py", line 37, in _initialize_module
2812:     from .support.itkBase import ITKModuleInfo, ITKTemplateFeatures
2812:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 395, in <module>
2812:     _initialize(itk_base_global_module_data)
2812:   File "C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\support\itkBase.py", line 377, in _initialize
2812:     raise RuntimeError(error_message)
2812: RuntimeError: WARNING: Invalid configuration directory requested: C:\Dev\ITK-19DLL\Wrapping\Generators\Python\RelWithDebInfo\itk\Configuration
2812: itkTestDriver: Process exited with return value: 1
 13/124 Test #2812: PythonFindEmptyClasses .............................................***Failed    1.18 sec
```

**Comment by hjmjohnson** [comment]
I think it has to do with using multi-config generators.  I am building a linux "Ninja Multi-Config" to see if I can replicate the problem.

I don't think it will be hard to fix, just hard to find all the locations where the paths need to be set.

**Pull request merged**
