### PR TITLE
COMP: Include <limits> to stop std::numeric_limits compilation errors.

### PR DESCRIPTION
**Pull request by melrobin**
## PR Checklist
- [ X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [ X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKSphinxExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

Some recent changes have broken compilation of ITK.  This pull request adds some needed header files for the build.

### CODE REVIEW

**Review by dzenanz — COMMENTED** [review]
These are changes to third party libraries. They should be made in https://github.com/vxl/vxl and https://sourceforge.net/projects/gdcm/. @malaterre and @hjmjohnson are maintainers of GDCM and VNL.

What compilers and versions produce compile errors?

**Comment by melrobin** [comment]
OK, I'll try to figure out how to get these changes to the right place.  The build failed for me using gcc 11.1.1

**Comment by dzenanz** [comment]
You can just make a PR to VXL in a similar way to ITK. I am not sure about process for GDCM.

**Comment by malaterre** [comment]
@melrobin  For GDCM, please submit as PR directly at: https://github.com/malaterre/GDCM

Thanks

**Comment by seanm** [comment]
GDCM has this fix already.

**Pull request closed without merging**
