### PR TITLE
ENH: Use Numpy bridge with array of dimension 1

### PR DESCRIPTION
**Pull request by arobert01**
Allow the use of the function GetImageFromArray with arrays of dimension
1.

The previous assert prevented the use of the Numpy bridge for the
dimension 1 even if this dimension was wrapped.

This change is motivated by the [pull request](https://github.com/SimonRit/RTK/pull/344) of @LucasGandel to extend itkPyBuffer available types for [RTK](https://github.com/SimonRit/RTK) python wrapping.  

## PR Checklist
- [x] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [x] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [ ] Added test (or behavior not changed)
- [ ] Updated API documentation (or API not changed)
- [ ] Added [license](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Utilities/KWStyle/ITKHeader.h) to new files (if any)
- [ ] Added Python wrapping to new files (if any) as described in [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) Section 9.5
- [ ] Added [ITK examples](https://github.com/InsightSoftwareConsortium/ITKExamples) for all new major features (if any)

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by SimonRit** [comment]
Do you think this patch could be included in the 5.1.1 release? @thewtex @dzenanz

**Comment by dzenanz** [comment]
@SimonRit I don't see why not. Make a PR to `release` branch if you want that.

**Comment by thewtex** [comment]
I went ahead and backported to `release`.

**Comment by SimonRit** [comment]
Thanks @thewtex!

**Pull request merged**
