### PR TITLE
STYLE: Fix ITK coding style inconsistency linter error

### PR DESCRIPTION
**Pull request by jhlegarreta**
Fix ITK coding style inconsistency linter error.

Fixes:
```
Error: Code is inconsistent with ITK Coding Style.
Add the *action:ApplyClangFormat* PR label to correct.

Changes required:

Files:
Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx

Changes:
diff --git a/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
           b/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
index 813d8b00..af2ea2b8 100644
--- a/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
+++ b/Modules/Nonunit/IntegratedTest/test/itkBioRadImageIOTest.cxx
@@ -63,6 +63,5 @@ itkBioRadImageIOTest(int argc, char * argv[])
   ITK_TRY_EXPECT_NO_EXCEPTION(writer->Update());

-
   return EXIT_SUCCESS;
 }
```

raised, for example, at:
https://github.com/InsightSoftwareConsortium/ITK/actions/runs/5802502099/job/15728990457#step:4:6

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
This is so unfortunate. Sorry, my bad. Does not look like there is a good way of preventing this from happening. @thewtex Shall we rewrite the history and go back two commits?
https://github.com/InsightSoftwareConsortium/ITK/actions/workflows/clang-format-linter.yml

**Comment by dzenanz** [comment]
If needed, reverting a commit is fine.

**Comment by jhlegarreta** [comment]
> If needed, reverting a commit is fine.

Given that reverting does not re-write history, it would still leave 2 commits whose style makes the style check to fail.

**Comment by dzenanz** [comment]
Will that problem go away once tip of `master` is stylistically correct?

**Comment by jhlegarreta** [comment]
> Will that problem go away once tip of master is stylistically correct?

No, we can always check out a given commit.

**Review by thewtex — APPROVED** [review]
Thanks for the update @jhlegarreta !

No worries about slight bugs / style issues in previous commits. We keep moving forward and improving. Any significant and valuable codebase will have opportunities for improvement :-).

**Comment by jhlegarreta** [comment]
Thanks Matt.

**Pull request merged**
