### PR TITLE
Update VXL library to the latest upstream master

### PR DESCRIPTION
**Pull request by vfonov**
Updating VXL to incorporate changes from vxl/vxl#729
@seanm 

## PR Checklist

- [ ] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] :no_entry_sign: Adds the License notice to new files.
- [ ] :no_entry_sign: Adds Python wrapping.
- [ ] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [ ] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by seanm** [comment]
Great, thanks!

**Comment by thewtex** [comment]
Failing test output:

```
-----------------------------------------------------------------------------
Start Testing test_symmetric_eigensystem:
-----------------------------------------------------------------------------
V'*D*V - S = -1.42109e-14 -8.88178e-16 -2.4869e-14 1.77636e-15 -1.68754e-14 -1.42109e-14 
0 -8.88178e-15 1.33227e-15 -8.43769e-15 6.21725e-15 1.13798e-15 
-2.4869e-14 1.77636e-15 -3.55271e-15 -1.11022e-14 -8.52096e-15 -7.10543e-15 
1.77636e-15 -8.43769e-15 -1.28786e-14 8.88178e-15 -1.04361e-14 -3.9968e-15 
-1.59872e-14 6.21725e-15 -8.52096e-15 -1.04361e-14 4.88498e-15 -1.15463e-14 
-1.06581e-14 6.93889e-16 -7.10543e-15 -3.9968e-15 -1.15463e-14 2.13163e-14 

residual = 6.50281e-14
 Test 001: recompose residual                                    -->  should be 0, is 6.50281e-14,   PASSED
Eigenvalues: 0.170864 2.16934 3.79272 15.435 24.6083 78.2994 
V'*D*V - C = 0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 0 0 0 
0 0 0 1.11022e-16 0 -4.44089e-16 
0 0 0 0 0 0 
0 0 0 -4.44089e-16 0 1.11022e-16 

residual = 6.47366e-16
 Test 002: recompose residual                                    -->  should be 0, is 6.47366e-16,   PASSED
Eigenvalues: -2 -1 0 0 0 2 
Testing random system:
evals: 3.49113 13.6528 30.1636 47.9597 54.3172 190.044
 Test 003: Eigenvalue increases                                  -->   PASSED
 Test 004: Eigenvalue increases                                  -->   PASSED
 Test 005: Eigenvalue increases                                  -->   PASSED
 Test 006: Eigenvalue increases                                  -->   PASSED
 Test 007: Eigenvalue increases                                  -->   PASSED
Eigenvals: 1 1 1
 Test 008: Correct eigenvalues for I                             -->   PASSED
Fixed Time: 56   netlib time: 54
 Test 009: Specialised version is faster                         --> **FAILED**
max_dsq: 4.77266e-27  mean_dsq: 2.40789e-29
 Test 010: Specialised version gives similar results             -->   PASSED
 Test 011: Numerically difficult values are ok v1                -->  should be 4199, is 4199, difference 1.81899e-12,   PASSED
 Test 012: Numerically difficult values are ok v2                -->  should be 4199, is 4199, difference 1.81899e-12,   PASSED
 Test 013: Numerically difficult values are ok v3                -->  should be 4801, is 4801, difference 4.54747e-12,   PASSED
-----------------------------------------------------------------------------
test_symmetric_eigensystem Test Summary: 12 tests succeeded, 1 test failed		*****
-----------------------------------------------------------------------------

```

**Comment by hjmjohnson** [comment]
I just looked at that.  It is a terribly written test for timing that is very unstable.  The timing of the algorithm being tested is corrupted by other variables.

Should timing tests like this be included in vxl?  It seems too fragile.

**Comment by thewtex** [comment]
> Should timing tests like this be included in vxl? It seems too fragile.

We have had similar issues with VXL timing tests in the pass -- +1 for excluding or removing them or adding a generous tolerance.

**Comment by hjmjohnson** [comment]
See #1480 for updated version.

**Pull request closed without merging**
