### PR TITLE
DOC: Fix Doxygen warnings

### PR DESCRIPTION
**Pull request by jhlegarreta**
- DOC: Fix argument names in method Doxygen documentation
- DOC: Fix unexpected token in class documentation]
- DOC: Fix Doxygen automatic link to member function 
- DOC: Fix `itk::MRASlabIdentifier` class documentation list syntax
- DOC: Fix links to ITK Sphinx examples in class documentation
- DOC: Remove Sphinx link to non-existing example
- DOC: Provide a name for the `FitSplineIntoPointSet` Sphinx example
- DOC: Improve Sphinx example displayed names

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
@hjmjohnson Any way to bypass the line length so that the link to the example in
https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h#L51

can be correctly parsed?

The warning

```
Modules/Filtering/ImageStatistics/include/itkStatisticsImageFilter.h:51:
warning: Found unknown command '\sphinxexample'
```

is being reported in https://open.cdash.org/viewBuildError.php?type=1&buildid=8167118

There might be other cases that are going unnoticed (probably because the `Review` module might not be set in the build), e.g.:
https://github.com/InsightSoftwareConsortium/ITK/blob/23da3dfa79152648f3d38050ee147df47f41ce0a/Modules/Nonunit/Review/include/itkScalarChanAndVeseSparseLevelSetImageFilter.h

Thanks.

**Comment by dzenanz** [comment]
```cpp
// clang-format off
...
// clang-format on
```
should work. I don't know where to squeeze it in, maybe some trail and error is required.

**Review by dzenanz — APPROVED** [review]
🏅 Amazing. This has been bugging me for a long time, I never had the luxury to devote time to it.

**Comment by jhlegarreta** [comment]
> medal_sports Amazing. This has been bugging me for a long time, I never had the luxury to devote time to it.

Thanks @dzenanz. Unfortunately, this will not address all warnings; my investigation to solve the "unbalanced grouping
commands" has been unsuccessful so far, but I'll have another look as time permits:
https://sourceforge.net/p/doxygen/mailman/doxygen-users/thread/CAPUXxNEK00EJruPwV__AL3W_bmoMWXuGoKBysXC4XEUeLM_9Ag%40mail.gmail.com/#msg37710320

I'll open a separate PR if I finally figure out the problem and the solution.

I'll see later today if the `clang-format` on/off makes the trick for the last commit in this PR, and will report back/amend the commit.

**Comment by jhlegarreta** [comment]
> I'll see later today if the clang-format on/off makes the trick for the last commit in this PR, and will report back/amend the commit.

After some more investigation I found that `clang-format` also breaks into multiple lines other Sphinx examples and these are not raising warnings/are displayed correctly in the generated documentation, including the `ScalarChandAndVeseSparseLevelSetImageFilter` that I pointed:
https://itk.org/Doxygen/html/classitk_1_1ScalarChanAndVeseSparseLevelSetImageFilter.html

So my bet is that it were the commas that prevented the command from being appropriately parsed. So avoided he commas the displayed name; I did not submit a PR to rename the actual example. I think it is fine, but let me know if it should be renamed for the sake of consistency.

**Review by dzenanz — APPROVED** [review]

**Review by dzenanz — APPROVED** [review]

**Comment by jhlegarreta** [comment]
The PR is ready to be merged :green_circle:.

As a follow up to:

> Thanks @dzenanz. This will clean a good number of warnings, but, unfortunately, it will not address all warnings; my investigation to solve the "unbalanced grouping commands" has been unsuccessful so far. I'll try to have another look as time permits:
https://sourceforge.net/p/doxygen/mailman/doxygen-users/thread/CAPUXxNEK00EJruPwV__AL3W_bmoMWXuGoKBysXC4XEUeLM_9Ag%40mail.gmail.com/#msg37710320

Still unsure where this comes from:
https://github.com/doxygen/doxygen/blob/ade61047308990ec679d1d59f0019a825e87451d/src/docgroup.cpp#L142

A few things I've looked into:
- Maybe the groups are not being closed properly in the `CMake` file `defgroup`s somewhere in here:
https://github.com/InsightSoftwareConsortium/ITK/blob/b870edf59bb0347116d245a445a2df8f5c6a8e56/CMake/ITKModuleDoxygen.cmake
https://github.com/InsightSoftwareConsortium/ITK/blob/d12f14e105500362a30264e683a4045eed21ba14/CMake/ITKGroups.cmake
Or else it's maybe a closing `*/` in here?
https://github.com/InsightSoftwareConsortium/ITK/blob/b870edf59bb0347116d245a445a2df8f5c6a8e56/Utilities/Doxygen/itkgroup.pl
e.g.
https://github.com/InsightSoftwareConsortium/ITK/blob/b870edf59bb0347116d245a445a2df8f5c6a8e56/Utilities/Doxygen/itkgroup.pl#L74

- Having a look at the first two warnings, which happen for [`itk::AutoPointer`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkAutoPointer.h#L41) and [`itk::BackwardDifferenceOperator`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkBackwardDifferenceOperator.h#L40) 
I don't see any hint in the group/module bar in Doxygen:
itkAutoPointer_doxygen
itkBackwardDifferenceOperator_doxygen

However, when comparing to [`itk::Array`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Core/Common/include/itkArray.h#L43) which does not seem to trigger a warning
itkArray_doxygen

It looks like the first two have each a `defgroup` (`ITKSystemObjects` for `itk::AutoPointer` and `Operators` for `itk::BackwardDifferenceOperator`) which is itself inside another group (`ITKSystemObjects` in `SystemObjects` and `Operators` in `DataProcessing`, respectively):
https://github.com/InsightSoftwareConsortium/ITK/blob/bcac6f9db2cb134d3d3c60a21041cde136feb1d9/Documentation/Doxygen/Modules.dox#L510

Another randomly picked class which is also raising the warning, `itk::NeighborhoodOperatorImageFilter`, also contains the described nested group pattern (`ImageFilters` being in `Filters`).

Maybe those nested groups are not being closed correctly when parsed by the above scripts. I know, more questions than certainties so far.

**Pull request merged**
