### PR TITLE
ENH: Declare `front()` and `back()` of Index, Offset, and Size constexpr

### PR DESCRIPTION
**Pull request by N-Dekker**
Follow-up to pull request https://github.com/InsightSoftwareConsortium/ITK/pull/3236 commit 47bce264791a53853020a3911dd94d060cfbd655
"ENH: Declare begin(), end() of FixedArray, Index, Offset, Size constexpr"

### CODE REVIEW

**Review by dzenanz — APPROVED** [review]

**Comment by N-Dekker** [comment]
@thewtex Would this PR still be feasible for v5.4.0? It just adds `constexpr` keywords to `front()` and `back()` member functions.

**Comment by blowekamp** [comment]
> @thewtex Would this PR still be feasible for v5.4.0? It just adds `constexpr` keywords to `front()` and `back()` member functions.

Out of my curiosity, is this for a particular issue? Has it given any measurable performance benefit?

**Comment by N-Dekker** [comment]
> Out of my curiosity, is this for a particular issue? Has it given any measurable performance benefit?

This PR would pave the way to adding constexpr to `itk::Index` iteration, by `itk::IndexRange`. Which would allow creating the OffsetToIndexTable of BSplineInterpolationWeightFunction at compile-time, instead of at run-time. I haven't yet been able to benchmark, but it may certainly benefit its performance.

Note that `itk::Index<N>` is similar to `std::array<itk::IndexValueType, N>`, whose `front()` and `back()` are also marked "constexpr": https://en.cppreference.com/w/cpp/container/array/back

**Review by thewtex — APPROVED** [review]
@N-Dekker this is awesome!

I think we should save it for ITK 6 to avoid any unforeseen issues.

**Comment by N-Dekker** [comment]
> I think we should save it for ITK 6 to avoid any unforeseen issues.

@thewtex  OK, thanks. Marked "draft" to avoid that this PR might accidentally be merged before the release of ITK 5.4!

**Comment by N-Dekker** [comment]
I think this pull request may also be merged now, as v5.4.0 has been tagged (https://github.com/InsightSoftwareConsortium/ITK/pull/4603#issuecomment-2120498131)

**Pull request merged**
