### PR TITLE
Remove hash map

### PR DESCRIPTION
**Pull request by dzenanz**
Watershed filter produces different/wrong result. If someone wants to dig in it would be great. If not, I will probably come back to this in a few weeks.

### CODE REVIEW

**Comment by dzenanz** [comment]
We should still do this, preferably before 5.0 final.

**Comment by maekclena** [comment]
I've been looking into this issue, here's what I found.

The only change responsible is [`edge_table_t`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.h#L259) which maps a label to its height.

In [`WatershedSegmenter`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Segmentation/Watersheds/include/itkWatershedSegmenter.hxx#L1027), these hash maps are dumped into lists. Because of differences in iterator implementation between `std::map` and `itksys::hash_map`, the order of insertion is different. The lists are sorted later but the [comparator](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Segmentation/Watersheds/include/itkWatershedSegmentTable.h#L69) only uses the height, leaving labels with the same height in the order they came in.

Because [`SegmentTreeGenerator`](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Segmentation/Watersheds/include/itkWatershedSegmentTreeGenerator.hxx) consumes the lists in order, the merge trees end up being very different, especially at lower flood levels.

The tests' output is actually somewhat misleading because it looks like a tiny difference. From my tests on segmenting `cthead1.png` with `WatershedImageFilter` the difference between `std::map` and `itksys::hash_map` can go up to 28% around 8% flood level. Above 66% the difference falls to 0.

**Comment by thewtex** [comment]
Thanks for the investigation @maekclena ! 

So, should we:

- Use `std::map` with new baselines and not that expected output may change in ITK 5.
- Use `std::unordered_map`, and add a sort somewhere to get consistent results (?)
- ....

The morphological watersheds are so much better in practice than the original watershed implementation, I not think we should be too concerned about getting the same results in with the original watersheds in ITK 5.

**Comment by blowekamp** [comment]
Please keep in mind the performance difference of operations between hash based maps and ordered maps. The hashes can be ver efficient for access O(1), while the ordered maps are O(lg n).

I'd prefer this change to be done in two steps:
1. Update to the equivalent C++11 class
2. See if the different map type fixes the watershed issue, and monitor/check performance as it is already a slower filter.

**Comment by dzenanz** [comment]
I rebased the PR.

**Comment by dzenanz** [comment]
I tried turning `edge_table_t` and `edge_table_hash_t` into `map` (instead of `unordered_map`), but the test still fails.

**Comment by thewtex** [comment]
Can the baseline image be updated for *itkIsolatedWatershedImageFilterTest*?

**Comment by dzenanz** [comment]
We could do that, but I am afraid that this filter was unintentionally relying on undocumented ordering of elements in `itksys::hash_map`. If I remember correctly, `itksys::hash_map` had 100 elements by default, and if less than 100 elements were entered into it those elements would retain their order. `std::undordered_map` behaves nothing like that, thus causing subtle changes.

**Comment by thewtex** [comment]
> std::undordered_map behaves nothing like that, thus causing subtle changes.

Why not `std::map`?

**Comment by dzenanz** [comment]
Neither does `std::map`. In commit [42fefe5](https://github.com/InsightSoftwareConsortium/ITK/pull/187/commits/42fefe5fddab689e7ef7d9f58bdc3e29c9376661) I tried using `std::map` everywhere, the test still fails.

**Comment by thewtex** [comment]
> Neither does std::map. In commit 42fefe5 I tried using std::map everywhere, the test still fails.

Yes -- why not update the baseline? If they are slightly different results, it should not be a show-stopper.

**Comment by thewtex** [comment]
Note that KWSys / itksys removes `hash_map` in later versions -- we need to get rid of it to keep updating KWSys and keep ITK maintainable.

**Comment by dzenanz** [comment]
OK, I kept `std::unordered_map` and updated the test baseline. Once the automated testing is in, this will be ready for review.

**Comment by thewtex** [comment]
@dzenanz please also add a note in the Migration Guide.

**Pull request merged**
