### PR TITLE
Update to GDCM 3.0.3+

### PR DESCRIPTION
**Pull request by malaterre**
## PR Checklist

- [ ] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [ ] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [ ] :no_entry_sign: Adds the License notice to new files.
- [ ] :no_entry_sign: Adds Python wrapping.
- [ ] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [ ] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [ ] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [ ] :no_entry_sign: Adds Documentation.

Refer to the [ITK Software Guide](https://itk.org/ItkSoftwareGuide.pdf) for
further development details if necessary.

### CODE REVIEW

**Comment by malaterre** [comment]
Update to latest GDCM 3.0.x current release branch. In particular this will add proper support for raw/YBR_FULL_422. As discussed with @blowekamp @issakomi

**Comment by dzenanz** [comment]
Of course, minor technical corrections should be made to resolve [ghost-flow errors](https://github.com/InsightSoftwareConsortium/ITK/pull/1301/checks?check_run_id=250727744).

**Comment by hjmjohnson** [comment]
> Of course, minor technical corrections should be made to resolve [ghost-flow errors](https://github.com/InsightSoftwareConsortium/ITK/pull/1301/checks?check_run_id=250727744).

@dzenanz These merge conflicts can be really tricky to resolve as part of the merge.  Do you know how to make the simple requested changes part of the merge, or should it be done as a separate patch?

**Comment by dzenanz** [comment]
The best thing is to make these changes in GDCM, and the redo the update process. That's what I did in #1285.

**Comment by malaterre** [comment]
> The best thing is to make these changes in GDCM, and the redo the update process. That's what I did in #1285.

The ghostflow-check-master is acting weirdly. I could not get something like 59f0677ca6a2a70fad1549e4d1c31ed501ebca7f to work, instead I had to use a different syntax 7770cb412a44c627821b0e66c355d7108dc4920f to pass.

**Pull request merged**
