### PR TITLE
STYLE: Remove ITKv3 Registration examples

### PR DESCRIPTION
**Pull request by hjmjohnson**
Remove redundancy for ITKv3 examples with respect to ITKv4.

As ITKv5 does not support ITKv3 registration any longer, completely remove the examples.

## PR Checklist
- No [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- No [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- No Adds the License notice to new files.
- No Adds Python wrapping.
- No Adds tests and baseline comparison (quantitative).
- No [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [x] Removes outdated ITKv3 Registration Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- No Adds Documentation.

### CODE REVIEW

**Comment by hjmjohnson** [comment]
Based on comments in #809 we wanted to keep ITKv3 registration frameworks there for testing.  After a considerable effort to minimize the duplication between ITKv3 and ITKv4 examples, I identified that the ITKv3 registration code was NOT USED FOR TESTING, and had been turned off and inaccessible since early in the ITKv5 conversion (as evidenced by lack of support for new spatial objects, and many C++11 warning oversights, or refactoring skips).

In the end I think that removing the directory is the best option, but the intermediate path to getting there will provide granular restore points if it becomes necessary to restore these outdated examples.  I'd rather not squash them (which would be cleaner), but less granular for restore points.

**Comment by blowekamp** [comment]
I got most of them working here #814

- likely c++11 warnings
- many of the RegistrationITKv3 examples are duplicated in the RegistrationITKv4 directory.
- many of the RegistrationITKv4 examples still use the old registration frame work

not sure what the path forward is here.

**Comment by blowekamp** [comment]
Nice work cleaning up the duplicates! I'm totally for merging that ASAP.

As for removing the reminder, I'm not on that page yet.

**Comment by hjmjohnson** [comment]
@blowekamp Give me an hour or two.  I think I have a good solution. When "BUILD_EXAMPLES" is turned on, the non-duplicated code will be built and tested (i.e. improve code coverage, and exercise old code in a way that was at one point our best practices suggestions).

I'm working through a linking issues now.

**Comment by hjmjohnson** [comment]
@blowekamp @dzenanz @thewtex  This took a bit longer than expected to move the code around.  I'd love to have this merged in soon so that the content in the Examples directory is only demonstrating modern best practices, and so that the long-dormant untested code starts to be tested again (at least when Examples are built).

**Comment by blowekamp** [comment]
Looks great!

Could we enable the examples and the legacy testing, just to test how the CI does with these examples?

**Comment by dzenanz** [comment]
I will add examples and ITKFEMRegistration to this [build](https://open.cdash.org/buildSummary.php?buildid=5894171).

**Pull request merged**
