### PR TITLE
ENH: GDCMImageIO SINGLEBIT image type

### LINKED ISSUE #1969: Bug: GDCMImageIO issue loading single-bit binary dcm mask.
### Description

Hello. I am running into an error processing a medical image segmentation DICOM file from The Cancer Imaging Archive. When I call itk.imread() on the datapoint, the `GDCMImageIo` library is throwing an `Unhandled PixelFormat: SamplesPerPixel     :1` error.

The python SimpleITK library throws the same error. 

### Steps to Reproduce

```
1. itk.imread(seg_file)
```

### Expected behavior

Dicom mask file is loaded into an image.

### Actual behavior

**Log from crash**
```
>>> segpath
'/nvdata/NSCLC-Radiogenomics-Fresh/NSCLC Radiogenomics/R01-041/09-07-1992-CT THORAX WO DYE-33339/1000.000000-3D Slicer segmentation result-38898/1-1.dcm'
>>> itkseg = itk.imread(segpath)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gagan/anaconda3/envs/monai/lib/python3.8/site-packages/itkExtras.py", line 645, in imread
    reader = TemplateReaderType.New(**kwargs)
  File "/home/gagan/anaconda3/envs/monai/lib/python3.8/site-packages/itkTemplate.py", line 469, in New
    return self._NewImageReader(itk.ImageFileReader, False, 'FileName', *args, **kwargs)
  File "/home/gagan/anaconda3/envs/monai/lib/python3.8/site-packages/itkTemplate.py", line 555, in _NewImageReader
    imageIO.ReadImageInformation()
RuntimeError: /work/ITK-source/ITK/Modules/IO/GDCM/src/itkGDCMImageIO.cxx:465:
itk::ERROR: itk::ERROR: GDCMImageIO(0x5633c7065c20): Unhandled PixelFormat: SamplesPerPixel    :1
BitsAllocated      :1
BitsStored         :1
HighBit            :0
PixelRepresentation:0
ScalarType found   :SINGLEBIT
```

### Reproducibility

I am using CT scan image data from this [NSCLC Radiogenomics](https://wiki.cancerimagingarchive.net/display/Public/NSCLC+Radiogenomics) TCIA dataset. The error happens every time I try to a patients 3d chest ct segmentation .dcm file.

### Environment

Debian Buster, Cmake == 3.16.3, itk == 5.1.1, python == 3.8.3

### Additional Information

I want to use the GDCM SingleBit pixelformat in the [GDCM docs](http://gdcm.sourceforge.net/html/classgdcm_1_1PixelFormat.html#aee3a522ae0a207c1d0f86b23055e850f), but I am not sure how to pass it in through itk.

### PR DESCRIPTION
**Pull request by issakomi**
SINGLEBIT image type for GDCMImageIO. Closes #1969.

### CODE REVIEW

**Comment by issakomi** [comment]
Test [file](https://drive.google.com/file/d/1lPxbexwJlUEoa0maOdVJxkndACCh6sZX/view?usp=sharing) (original from TCIA)

Simple test:

```
#include "itkImage.h"
#include "itkImageFileReader.h"
#include "itkImageFileWriter.h"
 
int main(int, char * argv[])
{
  using ImageType  = itk::Image<unsigned char, 3>;
  using ReaderType = itk::ImageFileReader<ImageType>;
  using WriterType = itk::ImageFileWriter<ImageType>;
  ReaderType::Pointer reader = ReaderType::New();
  WriterType::Pointer writer = WriterType::New();
  try
  {
    reader->SetFileName(argv[1]);
    reader->Update();
    writer->SetFileName("from_singlebit.mha");
    writer->SetInput(reader->GetOutput());
    writer->Update();
  }
  catch (const itk::ExceptionObject & ex)
  {
    std::cout << ex << std::endl;
    return 1;
  }
  return 0;
}
```

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Do you want to add a regression test yourself? Reusing the [read/write test](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/IO/GDCM/test/itkGDCMImageReadWriteTest.cxx) should be easy if you follow the [pattern](https://github.com/InsightSoftwareConsortium/ITK/blob/7a6f90ce62c4769f858415af0b000e1d5ba8952d/Modules/IO/GDCM/test/CMakeLists.txt#L169-L217).

**Comment by issakomi** [comment]
Thank you! Test program were probably easy, but unfortunately i don't know how it works with files, seems to be complicated, upload, links, etc. Is the file in above post OK, it is ~480 KB? I shall try to generate smaller one, there is an extension in Slicer, AFAIK, not 100% sure, if it will not work i could create somehow a file, i hope.

**Comment by dzenanz** [comment]
480KB is not bad, but a smaller one would be preferable. The simplest way is to [use web interface to upload](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md#upload-via-the-web-interface) data, then use the web interface to [download the hash file](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md#download-the-content-link). Then reference it in [test code](https://github.com/InsightSoftwareConsortium/ITK/blob/7a6f90ce62c4769f858415af0b000e1d5ba8952d/Modules/IO/GDCM/test/CMakeLists.txt#L169-L217) just like the other input files.

**Comment by issakomi** [comment]
Found smaller [file](https://drive.google.com/file/d/1gDpuuWyLUwZ_cyG1pk6LhgVIzLP_wZYQ/view?usp=sharing) ~ 60KB, original from TCIA, QIN-HEADNECK collection.

**Comment by issakomi** [comment]
I have tried. Added
```
itk_add_test(NAME itkGDCM_ComplianceTestRGB_singlebit
  COMMAND ITKIOGDCMTestDriver
    --compare DATA{Baseline/single-bit.mha}
      ${ITK_TEST_OUTPUT_DIR}/single-bit.mha
    itkGDCMImageReadWriteTest
      DATA{Input/single-bit.dcm}
      ${ITK_TEST_OUTPUT_DIR}/single-bit.mha
      scalar)
```

it produced compressed MHA file of float type: `ElementType = MET_FLOAT`, not sure it is good for binary mask. Also not sure do i need new function like `function(AddComplianceTest fileName)`

**Comment by issakomi** [comment]
I have to know about that _float_ before i shall upload mha file.

**Comment by dzenanz** [comment]
Since it is a binary mask, it should compress really well and be small. It does not matter that it is float. I think it is OK to upload.

**Comment by issakomi** [comment]
OK, i have uploaded mha file and added sha512 files. The test seems to work
```
      Start 24: itkGDCM_ComplianceTestRGB_singlebit
24/32 Test #24: itkGDCM_ComplianceTestRGB_singlebit ................   Passed    0.04 sec

```

Another questions, i see also _md5_ files for input and baseline, do i need to generate and add md5 file too?

**Comment by dzenanz** [comment]
You could, but this is usually done at the time of release by a script.

**Review by dzenanz — COMMENTED** [review]
Can you amend the PR with the test+data?

**Comment by issakomi** [comment]
Oh, something went wrong, commits should be merged, but they are not, probably i have done something wrong.

**Comment by issakomi** [comment]
Somehow it is not correct. I am getting strange messages from git. I'll close the PR and re-create.

**Comment by issakomi** [comment]
S. https://github.com/InsightSoftwareConsortium/ITK/pull/2010

**Pull request closed without merging**
