### PR TITLE
COMP: Update maintenance script to compile with Visual Studio 2022

### PR DESCRIPTION
**Pull request by dzenanz**

### CODE REVIEW

**Comment by dzenanz** [comment]
I was trying to apply it to Ultrasound remote module, but it did not catch [this change](https://github.com/KitwareMedical/ITKUltrasound/pull/225) which I made manually.

Also, I thought that PRs in Utilities directory should not trigger CI builds?

**Comment by N-Dekker** [comment]
> Update maintenance script to compile with Visual Studio 2022

Is it VS2022 specific, or is it C++17 specific? I mean, in VS2022 you can still enable C++14, wouldn't that allow compiling the file?

**Comment by dzenanz** [comment]
You are right. It is more C++17 related, than Visual Studio. I was to lazy to look up when that experimental stuff stopped being valid. What would be a better commit message?

**Review by N-Dekker — APPROVED** [review]
Thanks @dzenanz ! 👍

**Review by hjmjohnson — APPROVED** [review]

**Pull request merged**
