### PR TITLE
DOC: Consolidate `LaplacianSharpeningImageFilter` `UseImageSpacing` doc

### PR DESCRIPTION
**Pull request by jhlegarreta**
Consolidate `itk::LaplacianSharpeningImageFilter` `UseImageSpacing` ivar documentation: group together the `itkBooleanMacro` macro and the `Set/Get` methods, and document them at a single place.

## PR Checklist
- [X] No [API changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes) were made (or the changes have been approved)
- [X] No [major design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes) were made (or the changes have been approved)
- [X] Updated API documentation (or API not changed)

### CODE REVIEW

**Comment by jhlegarreta** [comment]
Not sure why a diff exists for the `GenerateInputRequestedRegion` documentation:
https://github.com/InsightSoftwareConsortium/ITK/blob/master/Modules/Filtering/ImageFeature/include/itkLaplacianImageFilter.h#L104

I haven't touched it.

**Review by dzenanz — APPROVED** [review]

**Comment by dzenanz** [comment]
Clang-format made the change during pre-commit hook?

**Comment by jhlegarreta** [comment]
> Clang-format made the change during pre-commit hook?

Not sure how the change got to the commit @dzenanz. 75bf848 removes it in any case.

**Pull request merged**
