### PR TITLE
PERF: less strict heuristic for valid points check

### PR DESCRIPTION
**Pull request by stnava**
The previous check was overly strict.   For example, one may be using a small mask (e.g. hippocampus) to focus registration within a much larger image.   The registration result can be valid in this case despite a relatively small number of points used.  Another alternative to this request would be to remove this check entirely.

See the [CONTRIBUTING](CONTRIBUTING.md) guide. Specifically:

Start ITK commit messages with a standard prefix (and a space):

 * BUG: fix for runtime crash or incorrect result
 * COMP: compiler error or warning fix
 * DOC: documentation change
 * ENH: new functionality
 * PERF: performance improvement
 * STYLE: no logic impact (indentation, comments)
 * WIP: Work In Progress not ready for merge

Provide a short, meaningful message that describes the change you made.

When the PR is based on a single commit, the commit message is usually left as the PR message.

A [reference to a related issue or pull request](https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests) in your repository. You can automatically [close a related issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/)

[@mentions](https://help.github.com/articles/basic-writing-and-formatting-syntax/#mentioning-people-and-teams) of the person or team responsible for reviewing proposed changes.

Thanks for contributing to ITK!

### CODE REVIEW

**Comment by blowekamp** [comment]
I believe the ideal solution may be to have a "minimum overlap" parameter, in all the metrics.

It is quite a common error for the initial registration to have no overlay. It is also not uncommon for an optimization to go awry resulting in little to no overlap.

**Comment by stnava** [comment]
practically speaking, i think we are erring on the wrong side here - rejecting too many valid registration setups as invalid.  we've had several complaints about this and users have ultimately gone on to modify their own ITK copy.

**Comment by thewtex** [comment]
Pushed to Gerrit here:

  http://review.source.kitware.com/#/c/23580/

**Comment by thewtex** [comment]
This has been merged.

**Pull request closed without merging**
