### PR TITLE
ENH: Synchronize factories across modules in Python

### PR DESCRIPTION
**Pull request by hjmjohnson**
Replaces individual synchronization mechanisms across modules for each global
variables used in ITK by a central mechanism in which all these variables
are registered and which gives a single entry point to synchronize
all global variables.

Global variables are registered in a map, with a key that is their name and
a value that is a pair of their pointer and a pointer to a synchronization
function. The synchronization function will be called to synchronize
these global variables across the different modules. Different global
variables may have different synchronization functions: Some variables
will just override the previous value in all modules whereas some
others will need to actually synchronize their values.

Change-Id: Ib6ebc9b3f9acd93ce8319f00579f6bf4982ca6b8

### CODE REVIEW

**Comment by hjmjohnson** [comment]
http://review.source.kitware.com/#/c/23362/

Francois Budin
Uploaded patch set 1.Apr 26, 2018

Matt McCormick
Patch Set 1: request build: pythonApr 26, 2018

Francois Budin
Patch Set 1: FYI, I really don't know if the Python part is going to work in the current state. It is really a WIP. We'll see I guess.Apr 26, 2018

Kitware Build Robot
Patch Set 1: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23362-1&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Apr 26, 2018

Kitware Build Robot
Patch Set 1: Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23362-1&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Apr 26, 2018

Francois Budin
Uploaded patch set 2.May 31 9:45 PM

Francois Budin
Patch Set 2: request build: pythonMay 31 9:46 PM

Francois Budin
Patch Set 2: This still need a little bit of polishing, but the idea is here. It should work.May 31 9:46 PM

Francois Budin
Patch Set 2: Also, there are a couple global variables that do not use the new pattern yet, but this will come in the next patch version.May 31 9:47 PM

Kitware Build Robot
Patch Set 2: Verified-1 Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23362-2&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Jun 1 1:53 AM

Kitware Build Robot
Patch Set 2: Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23362-2&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Jun 1 2:12 AM

Francois Budin
Patch Set 2: request build: pythonJun 1 7:42 AM

Bradley Lowekamp
Patch Set 2: Is there a test in Python to check that this is working correctly?Jun 1 7:46 AM

Francois Budin
Patch Set 2: @Brad: There is one test that verifies that the synchronization works for the TimeStamp (https://github.com/InsightSoftwareConsortium/ITK/blob/master/Wrapping/Generators/Python/Tests/ModifiedTime.py) and that test passes locally on my machine. I have cleaned the dashboard directories this morning because I think that some (all?) of the errors reported on CDash are because of dirty build trees, but we'll know better after the last build report comes back. Also, as I said in my previous comment, this PR needs a little bit more love, to add the few extra global variables that have not been converted yet, and to clean up the code and variable names.Jun 1 8:14 AM

Kitware Build Robot
Patch Set 2: Build Failed: CDash filtered results: https://open.cdash.org/index.php?&project=Insight&filtercount=3&field1=buildname/string&compare1=63&value1=23362-2&field2=buildstarttime/date&compare2=83&value2=2015-03-01&field3=buildstarttime/date&compare3=84&value3=2029-01-01Jun 1 9:57 AM

Matt McCormick
Patch Set 2: Code-Review+2

**Comment by hjmjohnson** [comment]
@fbudin69500 This was previously approved, but not merged.

**Comment by fbudin69500** [comment]
This is still work in progress. This is an important improvement for ITK but I haven't found the time to quite finish the PR. It is on my to-do list though.

**Comment by hjmjohnson** [comment]
Accidentally deleted the branch in my account.

**Comment by fbudin69500** [comment]
I updated this PR on this branch: https://github.com/fbudin69500/ITK/tree/global_variable_global_synchronization

**Pull request merged**
