### PR TITLE
Bugfixes in DCMTK

### LINKED ISSUE #1125: itkDCMTKImageIO.h RGB Converter
### Description
In Line 320 ~ 337 in itkDCMTKImageIO.cxx the buffer of the DICOM Image is copied to the itkImage buffer. For the RGB(A) Pixels a reorder of the RGB(A) Pixel (itkDCMTKImageIO.h Line 123 ~134) is made, which is useless, because in Line 337 (itkDCMTKImageIO.cxx) the old buffer is again copied over the new sorted buffer.

### Steps to Reproduce
See above

### Versions

ITK 5.0.0

### Environment

OS: Windows
Platform Toolset: MSVS 2017 Visual Studio 2017 (v141)
Windows SDK Version: 10.0.15063.0

### PR DESCRIPTION
**Pull request by maekclena**
The first commit fixes #1125 and removes an outdated comment.
The second commit adds a metadata read for spacing (according to already existing comments in the code) to fix failing test `itkDCMTKImageIOMultiFrameImageTest`.

## PR Checklist

- [X] :no_entry_sign: [Makes breaking changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#breaking-changes)
- [X] :no_entry_sign: [Makes design changes](https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#design-changes)
- [X] :no_entry_sign: Adds the License notice to new files.
- [X] :no_entry_sign: Adds Python wrapping.
- [X] :no_entry_sign: Adds tests and baseline comparison (quantitative).
- [X] :no_entry_sign: [Adds test data](https://github.com/InsightSoftwareConsortium/ITK/blob/master/Documentation/UploadBinaryData.md).
- [X] :no_entry_sign: Adds Examples to [ITKExamples](https://github.com/InsightSoftwareConsortium/ITKExamples)
- [X] :no_entry_sign: Adds Documentation.

### CODE REVIEW

**Comment by dzenanz** [comment]
I remember some discussions about this, e.g. #112 and #315. Were you aware of it @maekclena?

**Comment by maekclena** [comment]
No, I did not know. It seems like the fallback behavior was mistakenly removed in #243.

**Comment by hjmjohnson** [comment]
> No, I did not know. It seems like the fallback behavior was mistakenly removed in #243.

I don't think it was mistakenly removed.  My recollection is that it was purposefully removed because using SliceThinkness was determined to be the wrong approach.  If 0018, 0088 is not present, then the correct behavior is to explicitly compute the distance between slices as described in 

https://github.com/InsightSoftwareConsortium/ITK/pull/112#pullrequestreview-179175160
and
https://github.com/InsightSoftwareConsortium/ITK/pull/112#issuecomment-442451420

@malaterre is an expert in DICOM conformance.

**Comment by dzenanz** [comment]
Please split this into two PRs. First commit is non-contentious, and can be merged immediately. That will allow reviews for the second commit independently.

**Comment by malaterre** [comment]
> > No, I did not know. It seems like the fallback behavior was mistakenly removed in #243.
> 
> I don't think it was mistakenly removed. My recollection is that it was purposefully removed because using SliceThinkness was determined to be the wrong approach. If 0018, 0088 is not present, then the correct behavior is to explicitly compute the distance between slices as described in
> 
> [#112 (review)](https://github.com/InsightSoftwareConsortium/ITK/pull/112#pullrequestreview-179175160)
> and
> [#112 (comment)](https://github.com/InsightSoftwareConsortium/ITK/pull/112#issuecomment-442451420)
> 
> @malaterre is an expert in DICOM conformance.

1. 0018,0088 is Spacing Between Slices and should represent the actual Z-spacing when present,
2. Never (ever!) confuse Spacing Between Slices and Slice Thickness those are totally independent attributes
3. During the course of ITK dev, it was found that Spacing Between Slices may be missing (eg. CT Image Storage), or incorrect. Computing the actual Z-spacing from the IOP & IPP make sure to report any missing slices or inconsistency. Which is the reason why it is acceptable to loop over all frames to (re)compute the Slice Interval.

Ref:
* https://stackoverflow.com/a/15116116/136285

**Pull request merged**
