### PR TITLE
ENH: various DICOM compliance tests

### PR DESCRIPTION
**Pull request by dzenanz**
In Debug mode, _RLE-RGB.dcm_ and _RLE-YBR_FULL.dcm_ trigger:
```text
Warning: In C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmBitmap.cxx, line 179, function gdcm::Bitmap::SetPlanarConfiguration
Cant have Planar Configuration in JPEG/JPEG-LS/JPEG 2000. Discarding
```
Also, _JPEG2000-YBR_RCT.dcm_ triggers an assert in `C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmJPEG2000Codec.cxx`, at line 788. Everything works fine in Release mode.

### CODE REVIEW

**Comment by dzenanz** [comment]
This is a follow-up to #1306, #1309 and #1310. Test data produced by Mihail Isakov.

**Comment by blowekamp** [comment]
Great! Glad you were able to find this data, last I looked it wasn't there.

Looks like there are couple issues to track down before this can be merged and we can declare ITK has support for all these DICOM formats.

**Comment by dzenanz** [comment]
On Tue, Oct 29, 2019 at 6:11 AM @issakomi wrote:
> BTW, i have some doubts about RLE images, they were done with GDCM clone, but i've found comments that GDCM can only produce Planar Configuration 0, but the written Planar Configuration is 1. All viewers are opening RLE images correct, but i am not sure now. FYI. May be better were original images from manufacturers, but they were not so small.

@malaterre or @issakomi: can compliant input files be created? Maybe using DCMTK, if not GDCM?

**Comment by issakomi** [comment]
I am not sure about planar configuration, RLE can have planar configuration 1, of course. s [Table 8.2.2-1](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.2.html#table_8.2.2-1). The question is - is ithe value correct or not. It was produced with GDCM clone, i have mentioned there is a comment that GDCM can only produce 0, but written is 1. Not sure. Better discard the RLE images and take original from manufacturer. I shall look now for smallest i can find and share a link.

**Comment by issakomi** [comment]
[GE RLE YBR_FULL](https://drive.google.com/file/d/1bQrZmA4nlaeRlR-_7iorcYZiE3mSzFFA/view?usp=sharing). Will trigger this confusing JPEG warning too, AFAIK.

**Comment by issakomi** [comment]
[Acuson RLE YBR_FULL](https://drive.google.com/file/d/1Ko_OfjSzqbLjZMs8pKfbGsUqedFtIMBn/view?usp=sharing)

**Comment by issakomi** [comment]
Both images above have planar configuration 1 and will trigger this warning.

**Comment by dzenanz** [comment]
I am looking into using DCMTK to create the problematic files from raw file.

**Comment by issakomi** [comment]
Here is another one from [Acuson](https://drive.google.com/file/d/1QmCZRyq9r2c5TDI0Vu69iUlguWWIpyXc/view?usp=sharing), ~ 50 KB.
All of them have planar configuration 1.

**Comment by blowekamp** [comment]
Can we focus this PR on the ones that currently work. Add the other more difficult was in additional  PRs.?

**Comment by issakomi** [comment]
All images work, for original RLE images the warning is wrong, there is nothing to warn about. For generated i am in doubt myself now. Some comments are not not clear for me. JPEG2000 work all in release mode, and have very offen asserts in debug, not only color, but all.

Sorry for being in again, you have asked - and i can not ignore, but it is really better i will be out of GDCM stuff. Thank you.

**Comment by dzenanz** [comment]
I removed two of the problematic files and re-created the third one using `dcmcrle.exe raw-RGB.dcm RLE-RGB.dcm`.

**Comment by issakomi** [comment]
Here GDCM forces planar configuration **1** for RLE - [gdcmImageChangeTransferSyntax.cxx#L142](https://github.com/InsightSoftwareConsortium/ITK/blob/5213de5a568d6646c62aae84f394320fc07215df/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangeTransferSyntax.cxx#L142). It was correct to delete them, IMHO.

**Comment by issakomi** [comment]
Here is [raw-YBR_FULL.dcm](https://drive.google.com/file/d/1vp32rDt76FSUjDeGHwSPxHtaht2kBzYn/view?usp=sharing) from this tiny collection. May be you can create RLE-YBR_FULL with DCMTK, not sure how (check photo-metric value). RLE-RGB doesn't make sense and is never used by manufacturers, compression is too bad. raw-YBR_FULL doesn't make sense too, it is little lossy without compression at all, just for testing, FYI.

**Comment by dzenanz** [comment]
The latest force-push incorporates `raw-YBR_FULL.dcm`.

**Comment by issakomi** [comment]
JPEG2000 [YBR_ICT](https://drive.google.com/file/d/13-9bm1iX750jsfX3Fm7pG3Fw-qTqFyc0/view?usp=sharing) (D.Clinue), very small ~ 58 KB

**Comment by issakomi** [comment]
JPEG2000 [YBR_RCT](https://drive.google.com/file/d/14bTk1ult2ZOznDYDIhNxDzV6ObMNGlL4/view?usp=sharing) (D. Clunie) ~150 KB

**Comment by issakomi** [comment]
Better replace JPEG2000-YBR_RCT.dcm with D. Clunie's images, IMHO, they are small.

**Comment by dzenanz** [comment]
Those last two files could be added as a new PR, as they have different content from the rest of the test files in this patch. CI passes, and I think this is ready for reviewing and merging.

**Comment by malaterre** [comment]
> In Debug mode, _RLE-RGB.dcm_ and _RLE-YBR_FULL.dcm_ trigger:
> 
> ```
> Warning: In C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmBitmap.cxx, line 179, function gdcm::Bitmap::SetPlanarConfiguration
> Cant have Planar Configuration in JPEG/JPEG-LS/JPEG 2000. Discarding
> ```

The warning is correct (a bit pedantic, but correct). How did you generate those files ? Was it with gdcm command line tool ? In any case a good reference file used for unit testing should not declare an invalid state for Planar Configuration.

> Also, _JPEG2000-YBR_RCT.dcm_ triggers an assert in `C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmJPEG2000Codec.cxx`, at line 788. Everything works fine in Release mode.

That's odd. I am pretty sure I did fix this issue with YBR_ICT a couple of days ago. I see this is merged in ITK master:

* https://github.com/malaterre/ITK/blob/master/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmJPEG2000Codec.cxx#L787

**Comment by malaterre** [comment]
@dzenanz FYI, If you need my review, please give me a little more than 18hours (night time in Europe).

**Comment by dzenanz** [comment]
> @dzenanz FYI, If you need my review, please give me a little more than 18hours (night time in Europe).

Sorry, two other people commented on the PR so I got carried away with itchy merge-finger.

If/when the assert triggered by JPEG2000-YBR_RCT gets fixed/removed, I could re-add that test file.
[JPEG2000-YBR_RCT.zip](https://github.com/InsightSoftwareConsortium/ITK/files/3789506/JPEG2000-YBR_RCT.zip)

**Comment by dzenanz** [comment]
> the whole point was to test YBR_RCT here. If so, the J2K codestream needs to be re-generated.

Correct. Can you create a standards-compliant version of it?

**Comment by issakomi** [comment]
> > In Debug mode, RLE-RGB.dcm and RLE-YBR_FULL.dcm trigger:
> > 
> > Warning: In C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmBitmap.cxx, line 179, function gdcm::Bitmap::SetPlanarConfiguration
> > Cant have Planar Configuration in JPEG/JPEG-LS/JPEG 2000. Discarding
> 
> The warning is correct (a bit pedantic, but correct). How did you generate those files ? Was it with gdcm command line tool ? In any case a good reference file used for unit testing should not declare an invalid state for Planar Configuration.

RLE files i have done myself with GDCM, i didn't done something special with. Planar configuration 1 comes from here - [gdcmImageChangeTransferSyntax.cxx#L142](https://github.com/InsightSoftwareConsortium/ITK/blob/5213de5a568d6646c62aae84f394320fc07215df/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangeTransferSyntax.cxx#L142). I am not sure now, may be they are bad. If they are bad -  it is a bug in GDCM. The warning about Jpeg related to RLE is wrong per definition at least thru confusion with wording about JPEGs. And RLE can have planar 1, s. [Table 8.2.2-1](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.2.html#table_8.2.2-1), i have tons of original RLE from manufacturers, all with planar 1.

**Comment by malaterre** [comment]
> > > In Debug mode, RLE-RGB.dcm and RLE-YBR_FULL.dcm trigger:
> > > Warning: In C:\Dev\ITK-git\Modules\ThirdParty\GDCM\src\gdcm\Source\MediaStorageAndFileFormat\gdcmBitmap.cxx, line 179, function gdcm::Bitmap::SetPlanarConfiguration
> > > Cant have Planar Configuration in JPEG/JPEG-LS/JPEG 2000. Discarding
> > 
> > 
> > The warning is correct (a bit pedantic, but correct). How did you generate those files ? Was it with gdcm command line tool ? In any case a good reference file used for unit testing should not declare an invalid state for Planar Configuration.
> 
> RLE files i have done myself with GDCM, i didn't done something special with. Planar configuration 1 comes from here - [gdcmImageChangeTransferSyntax.cxx#L142](https://github.com/InsightSoftwareConsortium/ITK/blob/5213de5a568d6646c62aae84f394320fc07215df/Modules/ThirdParty/GDCM/src/gdcm/Source/MediaStorageAndFileFormat/gdcmImageChangeTransferSyntax.cxx#L142). I am not sure now, may be they are bad. If they are bad - it is a bug in GDCM. The warning about Jpeg related to RLE is wrong per definition at least thru confusion with wording about JPEGs. And RLE can have planar 1, s. [Table 8.2.2-1](http://dicom.nema.org/medical/dicom/current/output/chtml/part05/sect_8.2.2.html#table_8.2.2-1), i have tons of original RLE from manufacturers, all with planar 1.

My bad. This has been updated then changed back in the DICOM standard. See the intermediate wording in DCMTK bug tracker:

* https://support.dcmtk.org/redmine/issues/819

[...]
The use of separate segments implies that the Planar Configuration (0028,0006) will always be 1 for RLE compressed images.
[...]

Which can still be seen in an older version of the standard:

* http://dicom.nema.org/medical/dicom/2018b/output/chtml/part05/sect_G.2.html

CP-1843 has clarified the situation:

* ftp://medical.nema.org/medical/dicom/final/cp1843_ft_planarconfigurationforjpeglswithwsi.pdf

So the warning in GDCM is indeed a remaining dust from an old version of the DICOM standard (pre 2018b). I'll fix that ASAP.

**Comment by issakomi** [comment]
Thank you very much.

**Comment by malaterre** [comment]
For later reference this is gdcm commit d1a4ae35a618b76a136edcf4f8a2037054f7bd4b

**Pull request merged**
